### ISSUE TITLE
Automatically prepend to path

### ISSUE THREAD

**Issue by benjamin-kirkbride** [bigskysoftware/htmx#1011]
Is there a way to prepend a path using HTMX in all child invocations (probably not using all the right terminology, I apologize)?

For instance, if I know that I'm going to be making a ton of calls to an API located at `https://prod.example.com/service/api/v1/` such as `https://prod.example.com/service/api/v1/users`, `https://prod.example.com/service/api/v1/products`, etc, is there a way to abstract that? Perhaps by creating a template/variable for the `https://prod.example.com/service/api/v1/` portion such that I can just do something like:

``` html
<button hx-post="$api/clicked" hx-swap="outerHTML">
```

Perhaps this is something that would be best handled by templating + a build step. Still, curious if this has come up and if there is something that I'm missing.

**Comment by JonasR** [comment]
I don't know if there is another way to do this, but you could probably use the workaround based on`htmx:configRequest` outlined on Stackoverflow [here](https://stackoverflow.com/questions/69456875/how-to-configure-base-url-for-all-requests-using-htmx)?

**Comment by 1cg** [comment]
Yep, `htmx:configRequest` is the right way to do this.  Thank you @JonasR !
