### ISSUE TITLE
HTMX saves modified DOM in saveHistory

### ISSUE THREAD

**Issue by hirasso** [bigskysoftware/htmx#1015]
Hi there! I have a site with `hx-boost` enabled. I also want to use [Alpinejs](https://alpinejs.dev/) for a few things. This, for example, would render a list with the three colors in it (see [documetation](https://alpinejs.dev/directives/for)):

```html
<ul x-data="{ colors: ['Red', 'Orange', 'Yellow'] }">
  <template x-for="color in colors">
    <li x-text="color"></li>
  </template>
</ul>
```
It works just as expected if I first visit the page that contains this snippet. But when I navigate away and then back to the page using the browser's back-button, this happens: The previously rendered list is already there, but is again evaluated, leading to errors. Basically what is happening is, HTMX saves the state of the DOM *after* it was altered by other scripts, which leads to side-effects like this. 

Are there any known approaches to solving these kind of problems?

**Comment by hirasso** [comment]
As a hacky workaround, I can do this to clean-up the component before htmx takes it's snapshot:

```html
<ul x-data="{ colors: ['Red', 'Orange', 'Yellow'], innerHTML: null, init: () => innerHTML = $el.innerHTML, destroy: () => $el.innerHTML = innerHTML }" 
  x-on:htmx:before-history-save.window.camel="destroy()"
  style="position: fixed;">
  <template x-for="color in colors">
    <li x-text="color"></li>
  </template>
</ul>
```
This saves the `innerHTML` of the component before it renders the first time and resets it before HTMX takes it's snapshot. But probably there is a cleaner solution?

**Comment by 1cg** [comment]
What you have is, unfortunately, the recommended solution.

In htmx 2.0, I'm going to think harder about how to deal with HTML that's been mutated by javascript and the history cache.  It's a hard problem.

**Comment by hirasso** [comment]
Yes, it's a hard problem, indeed. I can actually imagine that it won't be possible to cleanly solve it for every last use case. But some official documentation on how to deal with DOM-altering third-party JS would already be very helpful, IMHO.

**Comment by frktimo** [comment]
Here's my take on @hirasso's workaround (thanks!). It stores pristine snapshots of Alpine components' HTML in data attributes (I'm not proud of it but look how easy it is! :smile:) and restores them after HTMX has restored its snapshot of the whole DOM.

```js
window.saveHtmxHistorySnapshot = (el) => {
  el.dataset.htmxHistorySnapshot = el.outerHTML;
};

addEventListener('htmx:historyRestore', () => {
  const els = document.querySelectorAll("[data-htmx-history-snapshot]");

  for (const el of els) {
    const snapshot = document.createElement("template");
    snapshot.innerHTML = el.dataset.htmxHistorySnapshot;
    const snapshotEl = snapshot.content.firstChild;

    el.replaceWith(snapshotEl);

    htmx.process(snapshotEl);
  }
});
```

Usage:
```html
<div x-data x-init="saveHtmxHistorySnapshot($el)">
  ...
</div>
```

Note that this hack is not specific to Alpine.js, and I use it to work around the same kind of issues with highlight.js.

**Comment by billythedummy** [comment]
Do these workarounds actually work? I've tried both suggestions with a Custom Element i'm building and what i'm observing is that the hx- attributes stop working if you press back sometimes. I'll try to create a minimal repro if i have time.  

It also seems like the saved localStorage entry still contains the mutated HTML instead of the reset HTML despite having reset innerHTML on beforeHistorySave.

**Comment by scrhartley** [comment]
Here's the version of the Alpine.js solution by @hirasso that I use:
```html
<ul x-data="{ colors: ['Red', 'Orange', 'Yellow'] }"
    x-init="$data.innerHTML = $el.innerHTML"
    x-on:htmx:before-history-save.window="$el.innerHTML = $data.innerHTML">
  <template x-for="color in colors">
    <li x-text="color"></li>
  </template>
</ul>
```
Note 1: `.camel` on the event attribute isn't necessary since htmx also fires a kebab case version of the event
Note 2: when I tried to use his version, it didn't work since it was missing using `this.` for access to properties in `x-data`
Note 3: `$data.` in the event attribute isn't actually necessary, since it's initialized at that point, but... symmetry

Different version:
```html
<ul x-data="{ colors: ['Red', 'Orange', 'Yellow'] }"
    x-on:htmx:before-history-save.window="htmx.findAll($el, ':scope > :not(template)').forEach(node => htmx.remove(node))">
  <template x-for="color in colors">
    <li x-text="color"></li>
  </template>
</ul>
```
Or: `x-on:htmx:before-history-save.window="$el.replaceChildren($el.firstElementChild)"`

Here's a fixed version of the original:
```html
<ul x-data="{ 
    colors: ['Red', 'Orange', 'Yellow'],
    init: () => this.innerHTML = $el.innerHTML,
    reset: () => $el.innerHTML = this.innerHTML
}" x-on:htmx:before-history-save.window="reset()">
  <template x-for="color in colors">
    <li x-text="color"></li>
  </template>
</ul>
```

**Edit:**
Perhaps you could do something like this:
```html
x-on:htmx:before-history-save.document.once="Alpine.destroyTree($el)"
```

**Comment by danielnieto** [comment]
> What you have is, unfortunately, the recommended solution.
> 
> 
> 
> In htmx 2.0, I'm going to think harder about how to deal with HTML that's been mutated by javascript and the history cache.  It's a hard problem.

What a fix implemented in Htmx 2?

**Comment by croxton** [comment]
For anyone finding this, I wrote a general purpose extension `hx-history-preserve` that preserves the dom state of an element and its children for history snapshot restores. It works well with Alpine or any library that mutates the dom.

https://gist.github.com/croxton/e2c33bd22591f9a5bd8c9d23a56c9edc

**Comment by Biszu** [comment]
> What you have is, unfortunately, the recommended solution.
> 
> In htmx 2.0, I'm going to think harder about how to deal with HTML that's been mutated by javascript and the history cache. It's a hard problem.

@1cg 
Has anything changed in 2.0, or it is still the recommended solution?

**Comment by scrhartley** [comment]
> > What you have is, unfortunately, the recommended solution.
> > In htmx 2.0, I'm going to think harder about how to deal with HTML that's been mutated by javascript and the history cache. It's a hard problem.
> 
> [@1cg](https://github.com/1cg) Has anything changed in 2.0, or it is still the recommended solution?

Perhaps try this in the head of your page:
```html
<script>
    document.addEventListener('htmx:beforeHistorySave', evt => {
        window.Alpine && window.Alpine.destroyTree(evt.detail.historyElt)
    })
</script>
```

**Comment by 1cg** [comment]
@MichaelWest22 I assume the 4.x alpine compatibility extension handles this?

**Comment by MichaelWest22** [comment]
yeah this is handled well in the htmx 4 use case by either the core htmx4 only which does not save any history cache anymore which means history actions are just full page updates which means you lose all your client state but at least nothing is invalid.  The new alpine compat extension also helps if you install it as partial page updates from htmx should work seamlessly with alpine.  And then there is a history cache extension which if installed along with the alpine compat extension will use many of the workarounds in this thread and it will destroy all alpine modifications on history save and captures the internal state of alpine data into the snapshot data as well.  This means that on back navigation it is able to restore the old page state and alpine internal state and re-apply it properly.  It also captures all input values and scroll states and restores these as well.
