### ISSUE TITLE
Handling Errors, Timeouts and Exceptions

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#102]
Can you add error, timeout and exception and error handling options?

**Comment by chg20** [comment]
We fire events on all of these, what do you have in mind?

My default answer here is going to be hyperscript after the 0.1 release, but not everyone wants to write code in a language I came up with :)

**Comment by sirinath** [comment]
E.g.

```html
<button hx-post="/clicked" hx-swap="outerHTML" hx-tries="3" hx-timeout="60s">
    Click Me
</button>
```

```html
<button hx-get="/data" hx-swap="show" hx-timeout="timeout" hx-retry-fail="timedout" hx-error="error" hx-tries="3" hx-timeout="60s">
    <div class="show"></div>
    <div class="timeout" hidden>There was a timout. Retryig. </div>
    <div class="timeout-1" hidden>Attemt 1.</div>
    <div class="timeout-2" hidden>Attemt 2.</div>
    <div class="timeout-3" hidden>Attemt 3.</div>
    <div class="timedout" hidden>There was a timout. Could not retrive data. </div>
    <div class="error" hidden>There was an error geting data.</div>
    <div class="error-404" hidden>Resource could not be found.</div>
</button>
```

**Comment by chg20** [comment]
That looks like an extension to me, not something I'd include in the core library.

**Comment by sirinath** [comment]
Ability to handle exceptions and events without having to fall back JavaScript is a boon for this library as it it the idiomatic way to use it, but having said that the actual way to do it can be different from the example I gave.

**Comment by bencroker** [comment]
Since hyperscript seems to be becoming the defacto way of handling htmx events, I agree that this kind of functionality doesn't need to belong in core.

**Comment by 1cg** [comment]
closing as agreed to not include in core (but I encourage an extension to explore it!)
