### ISSUE TITLE
Can hx-trigger prevent the default behavior?

### ISSUE THREAD

**Issue by deanebarker** [bigskysoftware/htmx#1029]
In my textarea, I have this:

```
hx-trigger="keydown[ctrlKey && keyCode==13]"
```

This works to trigger on CTRL-Enter. However, it doesn't prevent the default behavior of adding a carriage return.

Can that be prevented?

**Comment by 1cg** [comment]
htmx only prevents the default behavior in cases of links and forms, to prevent HTTP requests

for other purely client-side stuff you'll need to use scripting of some sort

sorry about that!

**Comment by YamiOdymel** [comment]
I have a similar situation, using a chip input for recipients within a `<form>`. This would be useful if it had `.prevent`, like Alpine.js does.


<img width="759" height="360" alt="Image" src="https://github.com/user-attachments/assets/6bb08f39-e466-480e-a02b-a4d51b505977" />

https://alpinejs.dev/essentials/events#preventing-default
