### ISSUE TITLE
HX-Trigger Response Header - documentation clarification on how to trigger multiple events?

### ISSUE THREAD

**Issue by gpshonik** [bigskysoftware/htmx#1030]
If I'm understanding the [docs](https://htmx.org/headers/hx-trigger/) correctly, it should be possible to trigger multiple events via the HX-Trigger HTTP response header: 

```You can trigger a single event or as many uniquely named events as you would like.```

Unfortunately I can't seem to find the magic sauce to actually trigger multiple events. I have tried to pass the HX-Trigger header value events as a comma-separated list ("foo,bar") as one would on the hx-trigger attribute but that does seem to work. 

There's a simple workaround for this scenario but I would still like to know if triggering multiple events from the response header is indeed possible.

Thanks!

**Comment by David-Guillot** [comment]
Hi @gpshonik ,

The docs says something about a JSON-formatted way to invoke events with details ; have you tried that? It seems that you need to use that syntax in order to invoke multiple events.

**Comment by gpshonik** [comment]
Ah, thank you - see it now, right at the bottom of the page! Sorry about that. This worked perfectly in the header

```{"Foo":"","Bar":"","Baz":""}```

and triggered all 3 events.

**Comment by JulianS-Uni** [comment]
Hi, I am using htmx with django and I am trying to invoke multiple events with the HX-Trigger Header. I let my server respond with a status code of 204 but also tried 200 if this matters.
```python
response = HttpResponse(status=204)
response['HX-Trigger'] = {"update_account_buttons":"", "update_messages":""}
return response
```
I also tried:
```python
response['HX-Trigger'] = 'update_account_buttons', 'update_messages'
```

but none of those events triggers. Both trigger fine if I just put one of them into the Header like:
```python
response['HX-Trigger'] = "update_account_buttons"
```

Chrome Network shows the HX-Trigger like so for the first variant: 
```
{'update_account_buttons': 'buttons', 'update_messages': 'messages'}
```

And like this for the second:
```
('update_account_buttons', 'update_messages')
```

I am going out of ideas on how to make this work. Can anyone confrim how the header should look after beeing send?
I have feeling this might be a django problem.

**Comment by matheuscas** [comment]
@JulianS-Uni Have being able to trigger more than 2 events? The below code doesn't fire all events, only the first and the last one: 
```
        if request.htmx:
            event = {
                "updateSwitcher": {"month": current_month, "year": current_year},
                "updateBalance": {"month": current_month, "year": current_year},
                "updatePaidBalance": {"month": current_month, "year": current_year}
            }
            response.headers["HX-Trigger"] = json.dumps(event)
```
And I have similar event listeners for each custom event, like below: 

```
<script>
    me("body").on("updateBalance", (evt) => {
        const url = `{% url 'accounts:get_account_total_balance' account_pk %}?month=${evt.detail.month}&year=${evt.detail.year}`
        htmx.ajax(
            "GET",
            url,
            {target: "#account-total-balance", swap: "outerHTML"})
    })
</script>
```
I'm Using Django and SurrealJS

**Comment by matheuscas** [comment]
Update (and sorry for comment in a closed issue):

It looks like to be a race condition. The 3 events are triggered, but not all of them make the request. I had to add a timeout to make them work together.

**Comment by Telroshan** [comment]
@matheuscas 
As you're using `htmx.ajax` with no `source` parameter set, only `target`, htmx will currently use the `body` as the source (see #2770 that should fix this situation and make htmx use your `target` element as the source).
As your 3 requests will be done "from" the `body`, and if you haven't defined [`hx-sync`](https://htmx.org/attributes/hx-sync/) on it, the default sync strategy will apply, where a new request drops any in-flight request currently happening, which could explain your issue
Until that linked PR is merged & a new version is released, you'll likely want to eithe
- set `source` to the same element as `target` in your `htmx.ajax` calls
- or, use `hx-sync` on the `body` (or your `source` elements if you still end up using the same source for multiple different requests)

Hope this helps!
