### ISSUE TITLE
documentation request on CORS

### ISSUE THREAD

**Issue by bbbart** [bigskysoftware/htmx#1032]
I was having an issue with an HTMX event not being triggered, even while everything seemed to be in order:
 - the event listener was defined and attached properly
 - the XHR response had a proper HX-Trigger header

After a long time of nail biting and debugging, @benpate put me on the right track: it happened to be a CORS issue (backend and frontend are on different domains).

Exposing the header HX-Trigger with CORS from my backend made everything work properly at once.

I'm just putting this issue here as a reminder for someone (perhaps myself) to find a spot in the HTMX documentation where this can be written down to prevent more unnecessary nail biting in the future. :-)

**Comment by benpate** [comment]
For the record, during the debugging process, I played the role of an excellent "rubber duck."  @bbart found and fixed the bug :)

Notes to our future selves:

* [This section](https://htmx.org/docs/#cors) might mention other headers like `HX-Trigger`
* Sections for `hx-get`, `hx-post`, etc. could also include a "troubleshooting" section that mentions CORS  (and links back to the definitive section in the docs.

**Comment by bbbart** [comment]
oh....

```
When using htmx in a cross origin context, remember to configure your web server to set Access-Control headers in order for htmx headers to be visible on the client side.

   Access-Control-Allow-Headers (for request headers)
   Access-Control-Expose-Headers (for response headers)
```

it already mentions it pretty clearly! I reckon there's nothing more to do here (except for me to read the existing docs more thoroughly).

(also, count the B's in my name ;-))

**Comment by benpate** [comment]
Yeah, I saw that too.  But that's already in the CORS section.  Not much help if you're not already searching for CORS-related problems.  It wouldn't hurt to link to this with a note in each of the AJAX articles, along with expanding a couple more examples here.  

Debugging is a pain.  And, sorry about your username.  Fixed :)
