### ISSUE TITLE
Flicker on form submission

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#104]
There's a noticable flicker when a form is submitted and replaced in htmx 0.0.4. Here's my test source code written in Twig:

```twig
<form hx-get="/profile">
    <div>
        <label for="first-name">First Name</label>
        <input type="text" name="firstName" value="{{ firstName ?? 'First' }}">
    </div>
    <div>
        <label for="last-name">Last Name</label>
        <input type="text" name="lastName" value="{{ lastName ?? 'Last' }}">
    </div>
    <div>
        <input type="submit" value="Save Profile">
    </div>
</form>
```

The values of `firstName` and `lastName` are set to the submitted input field values, defaulting to `First` and `Last` respectively. Here is the resulting flicker, which happens only after the values have been changed..

![ScreenFlow](https://user-images.githubusercontent.com/57572400/85132079-5d36b300-b238-11ea-9729-539a89bff17f.gif)

**Comment by chg20** [comment]
Can you check the console and see if there are multiple requests being issued?  I don't see why it should flicker back to its original val... OHHHHHHHHHH, ITS THE VALUE ATTRIBUTE ON SETTLE.

lol 

OK, I know the fix.

**Comment by bencroker** [comment]
Great, thanks!

**Comment by chg20** [comment]
OK, fix up:

https://github.com/bigskysoftware/htmx/commit/276082f2c23c171b86b86213e2c74a829a28cb3b

can you test against the version in src and see if this helps?

**Comment by bencroker** [comment]
That works beautifully, thanks!
