### ISSUE TITLE
htmx is broken in `dev` branche since "selector implementation for processNode"

### ISSUE THREAD

**Issue by twidi** [bigskysoftware/htmx#107]
Since the commit b07ed32dc4fe7338c7ddabb4858a88f23ed30b0b (`selector implementation for processNode`), htmx is broken in the `dev` branch.

The code to init htmx is `processNode(body, true)`

But this `true` means `ignoreChildren`

So in `processNode`, the `forEach(findElementsToProcess(elt), function(child) { processNode(child, true) });` line is not called so nothing is done

It works on `master` because you made the commit 6d2b52ff143bf47173ac6d5a5d2d2ca9947a837a (`0.0.6 release`) that was not applied back to the `dev` branch.

**Comment by chg20** [comment]
Sorry about that, the 0.0.5 release was broken (for the reasons you mention) despite my tests passing.

I have merged back to dev.
