### ISSUE TITLE
Infinite scroll only works when the whole page scrolls

### ISSUE THREAD

**Issue by marcpiechura** [bigskysoftware/htmx#1072]
Hey, 

it looks like that the `revealed` trigger does not work if only a sub area of the page scrolls. 
It's easy reproducible with the example page, see attached video. 
I've set:
- \<html> 
  - `overflow-y: hidden;`
- \<div id="demo-canvas">
  - `overflow-y: auto;`
  - `height: 350px;` 

Thanks, 
Marc

https://user-images.githubusercontent.com/6583600/194042702-df435432-1b09-43ff-8515-b55e229074ec.mp4

**Comment by David-Guillot** [comment]
Hi @marcpiechura ,

`hx-trigger` [docs](https://htmx.org/attributes/hx-trigger/) says:
> `revealed` - triggered when an element is scrolled into the viewport (also useful for lazy-loading). If you are using `overflow` in css like `overflow-y: scroll` you should use `intersect once` instead of `revealed`.

Have you tried that?

Maybe the docs could be more explicit about the limitations of `revealed`, which seems to be a shorthand for some specific `intersect` configuration.

**Comment by marcpiechura** [comment]
@David-Guillot 
Thanks a lot! 
I think the `hx-trigger` docs are fine, but I only looked at the [Infinite Scroll example](https://htmx.org/examples/infinite-scroll/) and that's why I haven't tried `intersect once`. I'll make a PR to add the note to the example page too.
