### ISSUE TITLE
Infinite scrolling stopped working in 1.8.1

### ISSUE THREAD

**Issue by krysros** [bigskysoftware/htmx#1075]
See: [Htmx Pattern: Infinite scroll](https://htmx.org/examples/infinite-scroll/)

**Comment by mpclarkson** [comment]
Same problem here...

**Comment by 1cg** [comment]
Fixed with version 1.8.2

Sorry about that!

**Comment by krysros** [comment]
@1cg This issue should be re-open for 1.8.3.

**Comment by 1cg** [comment]
gosh DARN it, a merge nuked the fix... 

I have published 1.8.4 w/ the fixe reapplied

**Comment by krysros** [comment]
Thank you!
