### ISSUE TITLE
HTTP status code events

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#110]
Can we have an HTTP status code events say `httpStatusCode`. For `401` it will be `httpStatusCode.htmx.official.error.sc4xx.sc401` and for `304` it will be `httpStatusCode.htmx.official.sc3xx.sc304` and for `509` it will be `httpStatusCode.htmx.unofficial.error.sc5xx.sc509`. `òfficial` and `unofficial` can be omitted if there is an overhead to implement and/or call.

It can have the following namespaces:
- official
- sc1xx
- sc100 - sc103
- sc2xx
- sc200 - sc2008, sc226
- sc3xx
- sc300 - sc308
- error
- sc4xx
- sc400 - sc418, sc421 - sc429, sc431, sc451
- sc5xx
- unofficial
- sc1xx - sc5xx
- sc100 - sc599 (not listed above)

This information can also be present in the `detail`. 

`responseError.htmx` can also have the errors information in the `detail`. `responseError.htmx` could be deprecated and removed if a more generic response function is introduced.

10 most used response codes: 200, 201, 204, 304, 400, 401. 403, 404, 409, 500

Ref:

- https://restfulapi.net/http-status-codes/
- https://www.restapitutorial.com/httpstatuscodes.html
- https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by chg20** [comment]
Cool idea, I really like the 4xx concept.

This could dovetail well with the proposed event naming change here:

https://github.com/bigskysoftware/htmx/issues/109

**Comment by sirinath** [comment]
If the namespace is complicated to implement and has a significant run time overhead drop it but we need a generic function to get HTTP status codes.

**Comment by bencroker** [comment]
This can already be achieved as follows:

```js
htmx.on('htmx:responseError', function(event) { 
    console.log(event.detail.xhr.status); 
});
```

Is there any reason for adding new events that target specific error codes?

**Comment by qrhfz** [comment]
@bencroker What is the version specific version on response success?

**Comment by bencroker** [comment]
> @bencroker What is the event for response success?

There are a few, check the event reference at https://htmx.org/reference/#events
