### ISSUE TITLE
No form parameters on GET requests?

### ISSUE THREAD

**Issue by adamstep** [bigskysoftware/htmx#111]
In Intercooler, GET requests would serialize the surrounding form data as query parameters. However, it looks like htmx only includes form data for non-GET requests. This makes it harder to implement a table-filtering behavior:

```html
<form id="filters">
  <div hx-get="/list" hx-target="#table">
    <!-- filter controls -->
  </div>
</form>
<div id="table">
  <!-- items -->
</div>
```
The code above makes requests to `/list` without any query params. I tried adding `hx-include` like this:
```html
<form id="filters">
  <div hx-get="/list" hx-target="#table" hx-include="#filters">
    <!-- filter controls -->
  </div>
</form>
<div id="table">
  <!-- items -->
</div>
```
This does include the form data in the GET request, but it includes the old state, not the latest state that triggered the request.

I also tried adding the attributes to the form:
```html
<form hx-get="/list" hx-target="#table" hx-trigger="change">
    <!-- filter controls -->
</form>
<div id="table">
  <!-- items -->
</div>
```
Changes in the form fields did not result in any requests.

So 2 questions:
- Is it intended that GET requests don't include the surrounding form? Are you open to changing that?
- Is it intended that `<form>` elements cannot be triggered on a `change`?

**Comment by chg20** [comment]
The new semantics are:  

* a `GET` does not include the closest form
* a `GET` on a form should include the parameters
* all non-`GET` requests do

So the second form, with the `hx-get` on the form should be the correct approach.  Not triggering on `change` sounds like a bug.

**Comment by adamstep** [comment]
Got it. After I simplified my form implementation, `hx-change="trigger"` on the form did work as expected. So I think the bug is in one of the form widgets I used.

**Comment by chg20** [comment]
I should mention that the reason for this change is we now automatically include GET query parameters when we push the request, so forms behave much more naturally with an `hx-push-url` attribute.  I didn't want random links inside the form to include all the form values if they issued a `GET`, however.
