### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by C1rdec** [bigskysoftware/htmx#1117]
I know that IE 11 is no more supported by Microsoft but many legacy system or still using IE11. 
- Example : Winform WebView

We were using inter-cooler and we decided to migrate to htmx and I was pleased to see that htmx was compatible with IE11.

But since **1.7.0** there's 2 breaking change for IE11....

We manage to make it work with 2 small changes:

1. Use a function [here](https://github.com/bigskysoftware/htmx/blob/50e2f77d3e184f65a2fbc1aeee24a612914cc63c/src/htmx.js#L3004)
2. [GetRootNode](https://github.com/bigskysoftware/htmx/blob/50e2f77d3e184f65a2fbc1aeee24a612914cc63c/src/htmx.js#L372)

**Comment by 1cg** [comment]
Can you check the latest release?  I got most tests running again with IE.

**Comment by C1rdec** [comment]
Will do
