### ISSUE TITLE
How avoid loss the caret position on a form?

### ISSUE THREAD

**Issue by mamcx** [bigskysoftware/htmx#112]
I have a complex form that need validations and recalculations (is for an invoice) that trigger when the price or the qty change (a reduced sample):

```html
<form id="app" name="SearchForm" method="POST">
    <content id='content'>		
		<input class="input flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border border-grey-light px-3 relative h-10 pr-10" type="number" id="price" name="price" value="53093.0" required   hx-post=""
        hx-trigger="keyup changed delay:500ms" 
        hx-swap="outerHTML"
        hx-target="#content"
        hx-select="#content"/>

		<input class="input flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border border-grey-light px-3 relative h-10 pr-10" type="number" id="qty" name="qty" value="22230" required  autofocus hx-post=""
        hx-trigger="keyup changed delay:500ms" 
        hx-swap="outerHTML"
        hx-target="#content"
        hx-select="#content"/>

        <section>
          <div class="border-t flex font-bold mx-5 pb-2 text-neutral-700">
            <span>Total</span>
            <span class="ml-auto">$1,390,461,231.16</span>
          </div>
        </section>	    

    </content>
</form>
```

This work, but the caret move to the start of the input (because all the form is swap).  This cause a UX problem for the users. I was expecting to capture which control cause the swap with:

```js
htmx.on("afterSettle.htmx", function(xhr, elt, target) {
  console.log("afterSettle.htmx", xhr, elt, target);  
});
```
But this not reference anywhere I can see the input that cause the swap so i can manually move the caret. How solve this?

**Comment by chg20** [comment]
Are you using the latest version of htmx?

Does the input have an id on it?  We try to preserve the select state if that's the case.

**Comment by mamcx** [comment]
I have what is reference at https://htmx.org/docs/#installing. The input have the ID, but the caret position move after the swap.

**Comment by sirinath** [comment]
@chg20 I believe @mamcx is referring to the carat position within the selection.

**Comment by chg20** [comment]
Here is the code in question:

```javascript
                                    var activeElt = document.activeElement;
                                    var selectionInfo = {
                                        elt: activeElt,
                                        start: activeElt.selectionStart,
                                        end: activeElt.selectionEnd,
                                    };

                                    var settleInfo = makeSettleInfo(target);
                                    selectAndSwap(swapSpec.swapStyle, target, elt, resp, settleInfo);

                                    if (!bodyContains(selectionInfo.elt) && selectionInfo.elt.id) {
                                        var newActiveElt = document.getElementById(selectionInfo.elt.id);
                                        if (selectionInfo.start && newActiveElt.setSelectionRange) {
                                            newActiveElt.setSelectionRange(selectionInfo.start, selectionInfo.end);
                                        }
                                        newActiveElt.focus();
                                    }
```

Any ideas?

**Comment by sirinath** [comment]
Can the library manage this without exposing the complexity to the user?

**Comment by chg20** [comment]
I believe so.  This was my first attempt at preserving focus and the selection, but I'm sure it can be improved.

Actually, wait a sec, @mamcx can you include IDs on the inputs?  That might be the missing key here.

**Comment by sirinath** [comment]
Maybe this can also be dealt with in the same code: https://github.com/bigskysoftware/htmx/issues/108

**Comment by mamcx** [comment]
> Actually, wait a sec, @mamcx can you include IDs on the inputs? That might be the missing key here.

?

The ids are in the inputs in the sample I post (but maybe is the css classes of tailwind that obscure them!):


```html
<input  type="number" id="price" name="price" value="53093.0" required   hx-post=""
        hx-trigger="keyup changed delay:500ms" 
        hx-swap="outerHTML"
        hx-target="#content"
        hx-select="#content"/>
```

**Comment by mamcx** [comment]
Ultra weird: If I change the input from "number" to "text" it not happens anymore (?).

**Comment by 1cg** [comment]
I wonder if `number` inputs don't have a `selectionStart` property...

Anyway, it works on text inputs, so I am going to call this good

**Comment by saward** [comment]
I'd like to add to this that it seems that sometimes an input trigger swapping out the page and input (type="number") will lead to htmx no longer triggering for any inputs.  There's no errors or messages in the console when this happens -- it just doesn't seem to trigger events any more for input changes.

If the input's type is "text", then I don't see either the cursor position issue, or the issue with requests no longer occurring.

**Comment by saward** [comment]
Possible theory: when max attribute is set on a number field, and that value is exceeded, then htmx breaks.  Quick test suggests this is the case.

**Comment by saward** [comment]
Sorry for the spam, but just wanted to post this update.  I've realised now what's probably happening is that the browser sees that forms fail validation requirements on the number field, so refuses to send the request.  Nothing shows up because that's happening via a htmx request, so the browser doesn't jump me to the offending field.  So I suspect this additional issue I'm having is not an issue with htmx at all.
