### ISSUE TITLE
Submit button child elements do not send the name or value of the parent attributes in the request

### ISSUE THREAD

**Issue by tropotek** [bigskysoftware/htmx#1128]
When using a standard submit button:
```
<button type="submit" id="edit-save" name="edit-save" value="save">Save</button>
```
The form will submit with name and value in the request.
However when the button has child elements like a span for example:
```
<button type="submit" id="edit-save" name="edit-save" value="save"><span>Save</span></button>
```
The request is missing the parent buttons name and value if you click on the span element.

**Comment by 1cg** [comment]
Fixed with https://github.com/bigskysoftware/htmx/commit/666c6aa8e57ad986741adf85b6714d1d40c3d7e8
