### ISSUE TITLE
hx-post on simple button does not send name or value

### ISSUE THREAD

**Issue by pyc-mo** [bigskysoftware/htmx#1132]
Hello,

The examples in the documentation figure hx-post without any paramers.
According to the documentation "_By default, an element that causes a request will include its value if it has one._ "

It does not seem to work with a simple button:

```
<button name="btn" value="delete" hx-post="/reset">
	Enable Your Account
</button>
```

Does not post anything (request body is empty).

HTMX version used : 1.8.4

**Comment by NBA707** [comment]
It looks like it works for html  input, checkbox, textarea but not button or div tags, you could do something like:

  <input type="hidden" name="enableAccount" value="delete"/>

    <button name="btn" hx-post="/testhtmx" hx-include="[name='enableAccount']">
        Enable Your Account
    </button>

Then it does the payload with enableAccount with value delete.

**Comment by flibustenet** [comment]
You can maybe use `hx-vals`, but i believe you're right, the value of the button should be posted according to the documentation.

**Comment by spookylukey** [comment]
For me this is also not working with:

```html
<input type="submit" hx-trigger="click" name="delete" value="Delete" >
```
I would expected `delete=Delete` to be submitted in this case.

htmx 1.8.4

**Comment by julianwachholz** [comment]
I too have run into this issue but it doesn't happen all the time. From my perspective it looks like this scenario does work **if**:
- The button is of type="submit"
- and has both `value` and `name` attributes

This is how it would also work without any javascript. It works on most browsers except Safari on iOS.

My use case has multiple different submit buttons on a single form where the action depends on the button clicked. E.g.:

```html
<form method="post" action="">
  <button type="submit" name="action" value="increase">Increase Counter</button>
  <button type="submit" name="action" value="decrease">Decrease Counter</button>
</form>
```

**Comment by samueleaton** [comment]
@julianwachholz not quite the same, although using a form (or an anchor tag) seems to be the main workaround. 

Form submissions import *all inputs with values* (which includes buttons). This issue is for when you aren't using a form element. 

I have an open PR i submitted a couple weeks ago that fixes this.

**Comment by 1cg** [comment]
If my understanding is correct, with normal forms the button/submit input value is only included when that button is clicked on.  We attempt to mimic this behavior with the code here:

https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1773

https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1819

There is an open PR that I need to review to improve things so we handle HTML element internal to a button as well:

https://github.com/bigskysoftware/htmx/pull/1168

@spookylukey are you clicking on the button?  If so, which browser/OS?  @julianwachholz 😑 truely, the new IE

**Comment by 1cg** [comment]
I have integrated https://github.com/bigskysoftware/htmx/commit/666c6aa8e57ad986741adf85b6714d1d40c3d7e8, and button values should be included in form submissions *if* they are the cause of the form submission

**Comment by neilmcguigan** [comment]
`<button hx-vars="foo:bar" name="foo" value="bar"></button> `works, but sadly, `hx-vars` is deprecated
