### ISSUE TITLE
Add class to target on swap/after swap

### ISSUE THREAD

**Issue by blazmrak** [bigskysoftware/htmx#1135]
My case is mainly for animation of navigation. I have something like the following:

```pug
.parent
  .left-nav(hx-target='.parent' hx-swap='outerHTML') <
  .right-nav(hx-target='.parent' hx-swap='outerHTML') >
```

```sass
.parent
  transition: transform 200ms
  &.htmx-swapping
    transform: translateX(1000px)
  &.htmx-swapping
    transform: translateX(-1000px)
```

What I think I would need would be to somehow attach the class to parent depending on which button was clicked. And also attach it to the content that it will be swapped with, so I would have this kind of css:

```sass
.parent
  transition: transform 200ms
  &.htmx-swapping
    &.left
      transform: translateX(1000px)
    &.right
      transform: translateX(-1000px)
  &.htmx-swapping
    &.left
      transform: translateX(-1000px)
    &.right
      transform: translateX(1000px)
```

Is there a way to achieve this or would a new extension have to be made?

**Comment by 1cg** [comment]
sounds like something for an extension to me...

**Comment by 5amch3n** [comment]
> sounds like something for an extension to me...

There's no need for an extension or plugin or something like that. Just set hx-swap to 'none', and on the server side send an Hx-Trigger like this
```
c.Response().Header.Set("Hx-Trigger", "something_just_happened")
```
, and on the client side(the browser) use a little HyperScript magic like this
```
_="on something_just_happened from body toggle .some_class on me"
```
