### ISSUE TITLE
Uncaught SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by lazna** [bigskysoftware/htmx#1139]
Just discovery HTMX, download .js file, create HTML index file but it do nothing. Got %subj% in F12 developer tools.

```
<html>
<head>
<meta charset="utf-8">
<title>
HTMX - elementary example
</title>
<script type="text/javascript" src="js/htmx.min.js">
</script>
<link rel="icon" type="image/x-icon" href="/HTMX/favicon.ico">
</head>
<body>

<button hx-post="cgi-bin/answer.cmd" hx-trigger="click" hx-target="#answer-div">
    Retrieve answer!
</button>

<div id="answer-div">
    DIR output list here
</div>

</body>
</html>
```

**Comment by David-Guillot** [comment]
Hi @lazna ,

We need some more details to be able to help you:
- When does this error happen? On page load or on button click?
- Do you see any XHR request being sent in Developer Tools when clicking the button?
- If an XHR request occurs, what does its response look like?

Also: you would probably find help more easily on htmx Discord 😉

**Comment by lazna** [comment]
- Error is displayed on pageload
- Using MS Edge, on F12 click Network tab and clicking, but nothing happens here. (verified previously by wireshark too - no packets from browser to server

**Comment by David-Guillot** [comment]
Just in case: have you tried removing the new line before `</script>`?

From 
```html
<script type="text/javascript" src="js/htmx.min.js">
</script>
```
to
```html
<script type="text/javascript" src="js/htmx.min.js"></script>
```

?

**Comment by lazna** [comment]
tried now, but not help.

**Comment by David-Guillot** [comment]
And have you checked that `htmx.min.js` is successfully loaded? Are there other scripts loaded by this page? Have you tried non-minified version?

**Comment by lazna** [comment]
Have no idea how to check if js file is loaded. have zero experisce with javascript, thas why I want to use HTMX. 

I have it on public address, does it help to you if i (privatelly) send you link? It may save your time...

**Comment by lazna** [comment]
same with non-minified version

**Comment by David-Guillot** [comment]
> Have no idea how to check if js file is loaded.
Just look at the network tab of your browsers developer tools. Maybe loading the JS file gets a 404 or another HTTP response code. If your server decides to return an HTML error page, the browser will throw this error.

**Comment by lazna** [comment]
https://www.imgpaste.net/image/KuFjP4

**Comment by David-Guillot** [comment]
Okay so clearly the server has something wrong here: obviously it doesn't serve htmx (which is only 40kB, not 343kB), but it serves an HTML error page with no error code.

**Comment by lazna** [comment]
You are propably right, but what am I doing wrong? Perform right-click on file here https://unpkg.com/browse/htmx.org@1.8.4/dist/ and choose 'save link as'. No trying to redownload (latest MS Edge and latest Firefox) files several times, but still got same (wrong) size and strange (html rather than javascript) content. It probabaly saving something else, but WHY THE HELL files are not ditributed in zip file, as usual ?!?!?!? It shoud prevent such accident :-/ How/where could I download files properly?

**Comment by lucxoff** [comment]
Hey, 
For help with that link, just go to [https://unpkg.com/htmx.org@1.8.4/dist/htmx.min.js](https://unpkg.com/htmx.org@1.8.4/dist/htmx.min.js) and right click on it to save it. 

Then, moove the new file to the folder that you have write in the script src. 

Also, try to add this javascript code after initialize the script for see every log from htmx.

**Comment by 1cg** [comment]
You can download releases from github:

https://github.com/bigskysoftware/htmx/releases/tag/v1.8.4
