### ISSUE TITLE
Control over Requests to Server

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#114]
In order not to overwhelm the server can there be parameters specified to control requests to the server by child elements (this can be also implemented at the page level to make it simpler supporting child elements is too complicated):
- number of parallels requests
- the delay between requests in a thread (this will be very small)
  - delay as an absolute number
  - delay as an uniformly distributed random number within a range (prevent all requests from firing nearly the same time)
- alternate parameters after error code (to stop overwhelming the server)
- ability to get parameters periodically from the server as a REST call (to stop overwhelming the server)

The `trigger` might need to be changed where the request is ques when triggered not actually making the request. If there is no delay and unlimited parallel request any request which is queued will be immediate.

**Comment by benpate** [comment]
AngularJS had a really useful concept of "interceptors" that (like aspects) could run before and after an XHR request.  

Sirinath, your ticket makes me think that it would be useful to have general-purpose before/after hooks around XHR requests for lots of reasons, including the ones you list above.  

Another example along these lines might be adding JWT authentication to the HTTP headers instead of using cookies.

**Comment by 1cg** [comment]
htmx has events for before and after hooks:

https://htmx.org/events/

As of right now, my long term vision is that hyperscript will fill this need.  But I won't get back to hyperscript until the Fall unfortunately.  :/

**Comment by 1cg** [comment]
Good example of using the events to add an auth token:

https://htmx.org/events/#htmx:configRequest

**Comment by benpate** [comment]
Awesome info.  Thanks!  

Here is where I swear I tried to read all the documentation first, before posting to GitHub.

**Comment by bencroker** [comment]
Can this issue be closed since the `htmx:beforeRequest` and `htmx:afterRequest` events already exist?

**Comment by bencroker** [comment]
Requesting input from @1cg.

**Comment by 1cg** [comment]
yes, events are the way to handle this

if there is a need for declarative implementations, that should be first does as an extension to get firmed up and then we can consider moving it into core
