### ISSUE TITLE
If call to server fails give a fallback

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#115]
In https://github.com/bigskysoftware/htmx/issues/103 I requested JS/JSX/data as a source of the content. This can also come under: https://github.com/bigskysoftware/htmx/issues/102

Can we have this option as a fall back:

```html
<div hx-post="/clicked"
       hx-js-alt="javascript:clicked()"
       hx-trigger="click"
       hx-target="#parent-div"
       hx-swap="outerHTML">
    Click Me!
</div>
```

even:

```html
<div hx-post="/clicked"
       hx-post-alt="/clickedAlt"
       hx-trigger="click"
       hx-target="#parent-div"
       hx-swap="outerHTML">
    Click Me!
</div>
```

If the 1st fails then try the rest.

To be more flexible it can be like:

```html
<div hx-action='{"POST":"/clicked", "POST":"/clickedAlt", "javascript":"javascript:clicked()"}'
       hx-trigger="click"
       hx-target="#parent-div"
       hx-swap="outerHTML">
    Click Me!
</div>
```

**Comment by 1cg** [comment]
This is a bit too elaborate for my tastes.  I'd like to see it implemented as an extension first before we consider it more deeply.
