### ISSUE TITLE
Web Types file is not packaged

### ISSUE THREAD

**Issue by piotrtomiak** [bigskysoftware/htmx#1161]
Web Types file is present in the repository and is referenced in the `package.json`, but it's not present in the built module. Could you please fix the build, so that the file is included. Unfortunately I am not familiar with the build setup, so can't provide PR for this.

**Comment by 1cg** [comment]
Will be fixed in the next release (I hope this friday):

https://github.com/bigskysoftware/htmx/commit/43d36af56026746d37d7f3ee95f5e86805d531c1

**Comment by piotrtomiak** [comment]
@1cg - looking at the commit you've referenced, I don't see how it would help with the missing `editors/jetbrains/htmx.web-types.json` file from the output.

**Comment by 1cg** [comment]
Hi

**Comment by 1cg** [comment]
Hi @piotrtomiak oh, do I need to include it in the NPM distribution?  Something like this:

```json
  "files": [
    "LICENSE",
    "README.md",
    "dist/htmx.d.ts",
    "dist/*.js",
    "dist/ext/*.js",
    "dist/*.js.gz",
  "editors/jetbrains/htmx.web-types.json"
  ],
  "main": "dist/htmx.min.js",
  "types": "dist/htmx.d.ts",
  "unpkg": "dist/htmx.min.js",
  "web-types": "editors/jetbrains/htmx.web-types.json",
```
Sorry, not super familiar w/ this tech...

**Comment by 1cg** [comment]
this look right?

https://github.com/bigskysoftware/htmx/commit/307e3eb227823c8094927aec5f1c7359d211faa6

**Comment by piotrtomiak** [comment]
@1cg Hey! Thanks for the change. I guess it should work now :)
