### ISSUE TITLE
Thymeleaf with HTMX and jquery - Problem when previous browser button is pressed

### ISSUE THREAD

**Issue by brunospy007** [bigskysoftware/htmx#1178]
All jquery libraries such as data tables and rich text editor duplicate elements when I press the browser's back button, has anyone experienced this, or know how to solve it?

**Comment by David-Guillot** [comment]
Hi @brunospy007 ,

To me your question seems like a duplicate of #1169 and #1107. Let me know if I'm wrong 😉 

@1cg could you pin one of these questions to the top of Issues?

**Comment by brunospy007** [comment]
@David-Guillot , my problem is the same as #1107 , applying the same solution and using hx-history-elt the problem was solved.
