### ISSUE TITLE
Support multiple data sources, events triggers, etc. - for hx-XYZ add alias hx="XYZ: ..."

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#118]
Is it possible to have an option to have something like `<div hx="GET:/resource1 trigger:getResoure1 indicator:#IDX1 indicator-style:istyle1, GET:/resource2 trigger:getResoure2 indicator:#IDX2 indicator-style:istyle2"></div>` where `hx-get="..."` becomes `hx="GET: ..."` and similarly for other attributes. Equivalant of `<div hx-get="/news" hx-trigger="load, click delay:1s"></div>` will be `<div hx="GET:/news trigger:load, GET:/news trigger:click delay:1s"></div>`

There can be a Hyperscript version also which is: `<div _="on getResoure1 GET resource1 end, on getResoure2 GET resource2 end"></div>`. `<div hx-get="/example">Get Some HTML</div>` will become `<div _="GET /example">Get Some HTML</div>`

**Comment by bencroker** [comment]
Is there a reason for wanting to add this alternative syntax? In my opinion it doesn't help the readability of the code nor provide any obvious benefits.

**Comment by sirinath** [comment]
You can retrieve data from multiple sources based on events and also apply different styling base on the source of data. E.g.: `<div hx="GET:/resource1 trigger:getResoure1 indicator:#IDX1 indicator-style:istyle1, GET:/resource2 trigger:getResoure2 indicator:#IDX2 indicator-style:istyle2"></div>`

**Comment by bencroker** [comment]
Hmm this seems like it might be better handled by [hyperscript](https://hyperscript.org/), don't you think?

**Comment by sirinath** [comment]
You can have a hyperscript version also, something like `<div _="on getResoure1 GET resource1 end, on getResoure2 GET resource2 end"></div>. <div hx-get="/example">Get Some HTML</div>` which might not yet be supported. Having the alternate syntax will give feature parity with it.

**Comment by bencroker** [comment]
My understanding is that the intention is not to have feature parity between the projects, but that hyperscript should supplement (or fill any gaps in) what htmx does. Anyway, let's wait and see what @chg20 thinks about all of this ;)

**Comment by sirinath** [comment]
More than feature parity if you do not have something like `<div hx="GET:/resource1 trigger:getResoure1 indicator:#IDX1 indicator-style:istyle1, GET:/resource2 trigger:getResoure2 indicator:#IDX2 indicator-style:istyle2"></div>` you cannot have request, triggers, etc. matched against each other. Also, you can support multiple sets of requests and associated attributes for each element. If you have separate attributes it is hard to support multiple requests and data sources.

Essentially this request is to support multiple data sources for each element than to support this particular syntax.

**Comment by bencroker** [comment]
Yeah I see that now, I guess the title of the issue threw me off initially.

**Comment by chg20** [comment]
I would want to see this in an extension before I folded it into the core.

Multiple events and URLs on the same element seems like a heck of a jump from where we currently are, especially since you can wrap a div around another div quite easily and add a new event/trigger/etc. there with identical results.
