### ISSUE TITLE
getStartTag Function Shouldn't Use Regex

### ISSUE THREAD

**Issue by samueleaton** [bigskysoftware/htmx#1180]
The [`getStartTag` function](https://github.com/bigskysoftware/htmx/blob/a3c414dcee94fd0351d5cbf622773fc982232204/src/htmx.js#L224), which is used for generating the html fragment from the server, uses a regex to identify the start tag. 

The main issue with this is HTML comments, and the secondary issue is that regex are slower than a highly domain specific, optimized parser.

Consider the following server response:
```html
<!-- <p>my commented paragraph</p> -->
<div>my div</div>
```
the `getStartTag` function thinks that the `p` tag is the first element.

**Comment by 1cg** [comment]
it's a good point, but this is in there to deal with some gronkyness around table-specific elements that won't parse as a top level element when we can't use templates

this code will go away in htmx 2.0 since we are dropping IE support and can remove this code entirely
