### ISSUE TITLE
Trigger JS Events, Update Styles, Send Data Payloads Encoded in Header Simultaneously with HTML based on headers and status codes - Introduce hx-status-handle & hx-status-style and hx-header-handle & hx-header-style

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#119]
Can we have something like:
- `<div hx-get="/example" hx-data-header-"x-hx-data" hx-status-handle="4xx:handle(details)" hx-status-style="4xx:errorStyle" hx-header-handle="x-element-style:handleStyle(details) hx-header-style="x-element-style">Get Some HTML</div>` and/or
-  `<div hx="GET:/example data-header:x-hx-data status-handle:4xx:handle(details) status-style:4xx:errorStyle header-handle:x-element-style:handleStyle(details) header-style:x-element-style">Get Some HTML</div>` and/or 
- `<div hx-get="/example data-header:x-hx-data status-handle:4xx:handle(details) status-style:4xx:errorStyle header-handle:x-element-style:handleStyle(details) header-style:x-element-style">Get Some HTML</div>`.

Description:
- `hx-status-handle` - trigger JS is the status code match
- `hx-status-style` - apply style when code is retuned
- `hx-header-handle` - trigger JS if the header match
- `hx-header-style` - apply style if header match. If a style is unspecified get the style from the value.
- `hx-data-header` - points to header with data payload. Maybe default can be `x-hx-data`.

Essentially this gives the ability to use status and headers to trigger UI actions and specify styling while also sending data.

Also, they can perhaps tired to evens like on load: `<div hx="load status-handle:4xx:handle(details) status-style:4xx:errorStyle header-handle:x-element-style:handleStyle(details) header-style:x-element-style">Get Some HTML</div>`

**Comment by chg20** [comment]
This looks like something that should be first implemented as an extension to see how it turns out.
