### ISSUE TITLE
extensions documentation

### ISSUE THREAD

**Issue by mhadam** [bigskysoftware/htmx#1193]
I found the term "included extensions" confusing cause my first impression was that I just had to add `htmx.js` to a page and set `hx-ext`. Perhaps it should be more explicitly stated that extensions actually require being loaded from additional script files.

Maybe "available/official/standard extensions" (vs. custom)?

**Comment by 1cg** [comment]
Open source hero @Renerick has updated the docs:

https://github.com/bigskysoftware/htmx/commit/f44b04f1a1afbd79c589e97130dad677c2ccd0cd

I will pluck that change into master so it goes out now.

Thank you!

**Comment by 1cg** [comment]
https://github.com/bigskysoftware/htmx/commit/a708395d46a6c4eced8423aa6802efd3b8036809
