### ISSUE TITLE
Request for `hx-include-vals` attribute

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#120]
In my use-cases, I find myself using the [include-vals extension](https://htmx.org/extensions/include-vals/) a LOT, to the point where I would love to just have a `hx-include-vals` attribute, rather than have to add the extension each time. It would mean being able to rewrite this:

```html
<div hx-ext="include-vals">
    <div hx-get="/test" include-vals="included:true, computed: computeValue()">
      Will Include Additional Values
    </div>
</div> 

<script src="https://unpkg.com/htmx.org/dist/ext/include-vals.js"></script>
```

As this:

```html
<div hx-get="/test" hx-include-vals="included:true, computed: computeValue()">
    Will Include Additional Values
</div> 
```

Does anyone else regularly use the `include-vals` extension and see the benefit in making this an attribute?

**Comment by chg20** [comment]
See the mentioned issue above.  In intercooler, the `ic-include` attribute could be JSON, but I didn't like how that meant you couldn't include both computed and input values, so I like a separate attribute with the syntax you lay out.

Maybe `hx-vals` ?

**Comment by bencroker** [comment]
Yeah I think your choice for the syntax is great! We could allow both a string, which is evaluated to JSON as it is now, and JSON, but I'm not sure there's much benefit to offering the choice.

Since `hx-include` and `hx-params` are already taken, `hx-vals` seems like a reasonable name, although I can already see my future self typing `hx-vars` by accident!

**Comment by chg20** [comment]
I like `hx-vars`  that makes clearer that it is a variable coming from javascript.

It should also recurse up the parent hierarchy and include all `hx-vars` declared above it, so you can include stuff easily on parent tags (e.g. the body).

**Comment by chg20** [comment]
In the recursion, the closest declaration should win, so children can override parents if need be.

And yeah, it should definitely be an eval rather than JSON, for flexibility.

**Comment by bencroker** [comment]
> I like `hx-vars` that makes clearer that it is a variable coming from javascript.

My future self thanks you!

**Comment by chg20** [comment]
Fixed w/ https://github.com/bigskysoftware/htmx/commit/70d770a1b598689bcfbca211395ddd66e202be41
