### ISSUE TITLE
target input type text should set the value attribute!!!

### ISSUE THREAD

**Issue by fardeadok** [bigskysoftware/htmx#1200]
this is an old problem and it has not been solved. Can make it so that you can specify which attributes are the target?

today I lost a WHOLE DAY trying to figure out why the text field doesn't change after the response hx-get="/myhandler"

**Comment by fardeadok** [comment]
textarea is the same
htmx is useless

**Comment by fardeadok** [comment]
<dic contenteditable ...
DONOT GENERATE EVENTS!!!  hx-post="myhandler"  hx-trigger="change  or keyup or changed  DO NOT WORK!
idiot

**Comment by fardeadok** [comment]
<div contenteditable> </div>  dont generate events for hx-trigger="change or changed or keyup"!!!

**Comment by 1cg** [comment]
the default swap strategy is `innerHTML` as the docs make clear

inputs are not allowed to have inner HTML, so it makes more sense to target the outerHTML and replace the whole thing

on the other hand, you probably don't want randomly-returning hypermedia responses jamming text over whatever happens to be in the input when they come in.  I'd need to see exactly what you are doing to have a sensible recommendation on an alternative.

if you'd like live help, please jump on the htmx discord:

https://htmx.org/discord

there are a lot of good folks there who can probably help you out.
