### ISSUE TITLE
Possibility to pass some parameters as path variables instead of in query string

### ISSUE THREAD

**Issue by jyrimatti** [bigskysoftware/htmx#1202]
Hi,

I believe it's more or less an API design issue whether an endpoint accepts parameters in the query string or as path variables. Often both are used. I couldn't find a way to make htmx pass parameters in the path. Is there a way, did I just not find it?

This can be achieved with an extension like this:
```
htmx.defineExtension('path-params', {
    onEvent: function(name, evt) {
        if (name === "htmx:configRequest") {
            evt.detail.path = evt.detail.path.replace(/{{([A-Za-z0-9_]+)}}/g, function (_, param) {
                let val = evt.detail.parameters[param];
                delete evt.detail.parameters[param]; // don't pass in query string since already in path
                return val;
          })
        }
    }
});
```

which would produce a URL `api/2023-01-14.json` from `<a href="api/{{date}}.json" hx-ext="path-params" hx-include="[name='date']">` assuming a field `date` exists. Something similar has been discussed at least in (https://stackoverflow.com/questions/68052027/in-htmx-how-do-i-request-a-specific-url-for-each-option-within-a-select-form-el).

The suggested escape syntax `{{paramName}}` could be something else as well, but at least this form is widely used and forms an invalid URI path.

An extension solves the issue, but since I don't think path parameters differ from query string parameters semantically, should this functionality be bundled in htmx and enabled by default without any extensions or additional attributes?

**Comment by 1cg** [comment]
This isn't something I would want to integrate into htmx itself, but you can implement it yourself via the `htmx:configRequest` event:

https://htmx.org/events/#htmx:configRequest

You can look at the `detail.path` for a regex matching your suggestion and replace it with a value in the `detail.parameters` object, then delete it from the parameters object.

**Comment by jyrimatti** [comment]
Hi,

it's a pity, but I understand. If using out-of-own-control APIs becomes a bigger use case in the future, maybe this will be reconsidered.
For now I'll keep using the custom extension. It's quite trivial after all, thanks to the great extension possibilities 👍

**Comment by lanmaster53** [comment]
> Hi,
> 
> I believe it's more or less an API design issue whether an endpoint accepts parameters in the query string or as path variables. Often both are used. I couldn't find a way to make htmx pass parameters in the path. Is there a way, did I just not find it?
> 
> This can be achieved with an extension like this:
> 
> ```
> htmx.defineExtension('path-params', {
>     onEvent: function(name, evt) {
>         if (name === "htmx:configRequest") {
>             evt.detail.path = evt.detail.path.replace(/{{([A-Za-z0-9_]+)}}/g, function (_, param) {
>                 let val = evt.detail.parameters[param];
>                 delete evt.detail.parameters[param]; // don't pass in query string since already in path
>                 return val;
>           })
>         }
>     }
> });
> ```
> 
> which would produce a URL `api/2023-01-14.json` from `<a href="api/{{date}}.json" hx-ext="path-params" hx-include="[name='date']">` assuming a field `date` exists. Something similar has been discussed at least in (https://stackoverflow.com/questions/68052027/in-htmx-how-do-i-request-a-specific-url-for-each-option-within-a-select-form-el).
> 
> The suggested escape syntax `{{paramName}}` could be something else as well, but at least this form is widely used and forms an invalid URI path.
> 
> An extension solves the issue, but since I don't think path parameters differ from query string parameters semantically, should this functionality be bundled in htmx and enabled by default without any extensions or additional attributes?

I ran into issues using double braces in server-side templates, so I changed it to single braces and it works great. Definitely a useful extension. Thank you!
