### ISSUE TITLE
Make `hx-push-url` more flexible

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#121]
Currently, [hx-push-url](https://htmx.org/attributes/hx-push-url/) accepts `true` or `false` values only. Would it be possible to make `hx-push-url` accept a custom string as well?

For example, send a request to `/account` and set the URL to `/account/home`.

```html
<div hx-get="/account" hx-push-url="/account/home">
  Go to My Account
</div>
```

**Comment by chg20** [comment]
Great idea, pretty easy to implement.  You want to give it a crack?

**Comment by bencroker** [comment]
Sure thing!
