### ISSUE TITLE
When boosting enabled, page focusing on hx-target

### ISSUE THREAD

**Issue by abrorbekuz** [bigskysoftware/htmx#1212]
When i tried hx-target with hx-boost, my page suddenly scrolled on its own.
like href="#some_content"

after that i used hx-push-url to push to url, and everything has solved
hope it can be help to others, even a l. b.

**Comment by moxplod** [comment]
This is happening to me today too. Tried this on my body tag

`<body hx-boost="true" hx-target="#main">`

Everything is working great except I have a scroll happening to #main

**Comment by moxplod** [comment]
Found a fix. By adding: hx-swap="innerHTML show:window:top" 
It did what I was looking to do and it stopped scrolling to the target. 

But this seems like a bug, as he default behavior says it should not scroll. But it definitely is without specifying this swap attribute.

**Comment by neuged** [comment]
Per [this related comment/thread](https://github.com/bigskysoftware/htmx/issues/407#issuecomment-1562366865) you can use the modifier `show:unset` like in `hx-swap="outerHTML show:unset"` to not scroll on hx-boost.

**Comment by tanczosm** [comment]
hx-boost when you use hx-swap="innerHTML scroll:window:top" sets show (swapSpec.show) without a showTarget, so without a target it will fall back to hx-target. This feels like a bug.

So scroll:window:top will set the scrollTop to 0 and cause the window to scroll to a spot, then the hx-boost enabled show will then scroll to the target using whatever scroll method you define in htmx.config.scrollBehavior

htmx.js ~line 2646:
```js
            if (swapSpec.show) {  <-- will be set when hx-boost is turned on
                var target = null;
                if (swapSpec.showTarget) {  <-- will NOT be set
                    var targetStr = swapSpec.showTarget;
                    if (swapSpec.showTarget === "window") {
                        targetStr = "body";
                    }
                    target = querySelectorExt(first, targetStr);
                }

                if (swapSpec.show === "top" && (first || target)) {  <-- Since show is "top" on hx-boost, first is the hx-target element, and target is still null the target will fall back to hx-target instead of the top of the page
                    target = target || first;
                    target.scrollIntoView({block:'start', behavior: htmx.config.scrollBehavior});
                }
```

Be aware that because any container can have a scrollbar it's possible that you don't actually want to scroll:window:top but may want to scroll to the top of a particular container.

**Comment by abrorbekuz** [comment]
oh shit )

that problem, took all of us huh 😂

**Comment by rudyrdx** [comment]
> hx-boost when you use `hx-swap="innerHTML scroll:window:top"` sets show (swapSpec.show) without a showTarget, so without a target it will fall back to hx-target. If you don't set `scroll:window:top` at all then show will still be set, but without a showTarget so it will still scroll to hx-target. This feels like a bug.
> 
> So `scroll:window:top` will set the window.scrollTop to 0 and cause the window to scroll to the top, then the hx-boost enabled show will then scroll to the target using whatever scroll method you define in htmx.config.scrollBehavior
> 
> htmx.js ~line 2646:
> 
> ```js
>             if (swapSpec.show) {  <-- will be set when hx-boost is turned on
>                 var target = null;
>                 if (swapSpec.showTarget) {  <-- will NOT be set
>                     var targetStr = swapSpec.showTarget;
>                     if (swapSpec.showTarget === "window") {
>                         targetStr = "body";
>                     }
>                     target = querySelectorExt(first, targetStr);
>                 }
> 
>                 if (swapSpec.show === "top" && (first || target)) {  <-- Since show is "top" on hx-boost, first is the hx-target element, and target is still null the target will fall back to hx-target instead of the top of the page
>                     target = target || first;
>                     target.scrollIntoView({block:'start', behavior: htmx.config.scrollBehavior});
>                 }
> ```
> 
> Be aware that because any container can have a scrollbar it's possible that you don't actually want to `scroll:window:top` but may want to scroll to the top of a particular container.
> 
> So my fix, because I want the scroll to go to the top of the page, is to set BOTH scroll and show in hx-swap explicitly to get the correct behavior. `hx-swap="innerHTML scroll:window:top show:window:top"`
> 
> OR you can explicitly just avoid any "scroll to this element" behavior with `show:unset`
> 
> `hx-swap="innerHTML scroll:window:top show:unset"`
> 
> If you don't want any scrolling at all, then: `hx-swap="innerHTML show:unset"`
> 
> Now I did lie a little because my scrollbar is actually on a dom element called main, so I'm actually using: `hx-swap="innerHTML scroll:main:top show:main:top"`

Came accross this, I solved mine by removing this ```e.scrollIntoView({ block: "start", behavior: "auto" })``` from the htmx.min.js untill i just felt bad and tried your solution 😜

**Comment by filipencopav** [comment]
If anyone else encounters this and wants a simple, clean, official solution, then add this tag into your head:
```html
<meta name="htmx-config" content='{"scrollIntoViewOnBoost":"outerHTML"}'>
```

**Comment by abrorbekuz** [comment]
Thx everyone I think every one got the idea but the is fixed now in the default codebase
Im gonna closing the ticket
