### ISSUE TITLE
Changing attributes with javascript doesnt change behavior

### ISSUE THREAD

**Issue by vargaking** [bigskysoftware/htmx#1213]
Let's say I have a button like this:
`<div class="btn" hx-get='/test' id="button">`

But after the site loaded I want to change it with JS:
`document.getElementById("button").setAttribute("hx-get", "/test2");`

However, when I click the button, it still makes the request to `/test`. Is there any way to make this work?

**Comment by David-Guillot** [comment]
Hi @vargaking ,

I think you're looking for [htmx.process()](https://htmx.org/api/#process), what so you think?

**Comment by vargaking** [comment]
> Hi @vargaking ,
> 
> I think you're looking for [htmx.process()](https://htmx.org/api/#process), what so you think?

Calling htmx.process(document.body) should solve this? or i have to call it on the specific elements?

**Comment by vargaking** [comment]
meanwhile I tried both calling it on document.body and on the element specifically, neither of them is working

**Comment by vargaking** [comment]
Okay, looks like I successfully solved this issue by upgrading htmx from 1.5.0 to 1.8.5 :)
