### ISSUE TITLE
from:body silent failure

### ISSUE THREAD

**Issue by zakarybk** [bigskysoftware/htmx#1215]
Hi,

I want to make a suggestion. When there's a 'from:body' flag without a corresponding tag, then a warning should be printed to console.

For example
`<div hx-trigger="load, loginUpdate, from:body">`

Which should actually be
`<div hx-trigger="load, loginUpdate from:body">`

This syntax error caused me a lot of headache and it would be amazing if there was a warning printed to console for this.

I did a quick search for from:body in the codebase and didn't really find anything useful. I'm happy to give this a go with a PR if someone can give me a few pointers.

Thanks

**Comment by 1cg** [comment]
I'm sorry that's a nasty one.  

Unfortunately `from:body` *is* a valid event name, so there isn't a good way to catch that without also risking disallowing valid events... 😑
