### ISSUE TITLE
500 internal server error while accessing hx-requests in Django project

### ISSUE THREAD

**Issue by ajayk781** [bigskysoftware/htmx#1218]
Hi all, I am working on a Django project to create a dynamic form using HTMX using a YouTube video.. As I am clicking "Add" button to add a form, no form gets added.. and as I inspect the browser console, I get the following error:

GET http://127.0.0.1:8000/businesscase/htmx/project-form/ 500 (Internal Server Error)
lr @ htmx.org@1.8.5:1
(anonymous) @ htmx.org@1.8.5:1
i @ htmx.org@1.8.5:1

Response Status Error Code 500 from /businesscase/htmx/project-form/
St @ htmx.org@1.8.5:1
ee @ htmx.org@1.8.5:1
Q @ htmx.org@1.8.5:1
fr @ htmx.org@1.8.5:1
o.onload @ htmx.org@1.8.5:1
load (async)
lr @ htmx.org@1.8.5:1
(anonymous) @ htmx.org@1.8.5:1
i @ htmx.org@1.8.5:1

![image](https://user-images.githubusercontent.com/118190943/214853709-0475d806-26ee-41bc-b364-a71ed7115217.png)

I am fairly new to programming, tried to search a lot in Google to get rid of this error, but unfortunately all I received was to refresh browser, clear cache etc which I did but the problem persists..

I'd really appreciate of any quick solution here.. many thanks..

**Comment by mfisco** [comment]
It looks like the issue you're having is due to an error in your Django code (either a template, form, or view) since the response code is 500. 


Would you be able to share the traceback from your development server and, if possible, the associated form/view/template code?

**Comment by 1cg** [comment]
Agreed, this appears to be a server side error, I would consult the logs for your django server and see what's going on there.
