### ISSUE TITLE
History cache not cleared after historyCacheSize has been set to 0 and cache was not empty

### ISSUE THREAD

**Issue by aomader** [bigskysoftware/htmx#1221]
If the history cache is not empty and the `historyCacheSize` is set to 0, the history cache is not cleared, but still used. This leads to very subtle bugs.

https://github.com/bigskysoftware/htmx/blob/7ea35d03c6226aaf278b47d80170132bad9384f0/src/htmx.js#L1945-L1956

**Comment by michaelperel** [comment]
+1 - This is something that I have encountered and found confusing in the past.

**Comment by mikeball** [comment]
I ran into this problem as well, and the pull fixed it. https://github.com/bigskysoftware/htmx/pull/1222
