### ISSUE TITLE
`Input` contained inside `form` element, prevent `submit` on Enter key

### ISSUE THREAD

**Issue by SHxKM** [bigskysoftware/htmx#1228]
I'm using HTMX together with Django and it's convenient to work with `forms.Form` to render `<form>` elements from server-side.

My requirements are:

1. Trigger a call to the endpoint only on `keyup changed` on the `<input>` element
2. Do not trigger a call to the endpoint on form submission (Enter key), do not close it the form either.

Here's the issue: If I don't put `hx-` properties on the `<form>` element, the `enter` key will cause a call to the endpoint and the form (inside modal) to close (violates `#1`). If I do put `hx-trigger="submit"`, then a server-side call is carried-out on every `Enter` keyup (violates `#2`).

There must be an idiomatic way to achieve this that I'm sure I'm missing.

For now I'm resorting to to Alpine.js' `@submit.prevent`

**Comment by 1cg** [comment]
Unfortunately there isn't an idiomatic way to achieve this in htmx w/o client scripting, so I think you are doing the right thing using alpine.

**Comment by SHxKM** [comment]
Thanks for confirming @1cg. 

Just putting this out here if anybody

**Comment by AxelRHD** [comment]
@SHxKM, can you post an example (with Hyperscript)?

**Comment by andryyy** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/hyperscript.org@0.9.11"></script>
  </head>
  <body>
    <form _="on submit or keyup from #testing debounced at 200ms
      if the event's type is 'submit' or the event's keyCode is 13 halt the event otherwise
      trigger submit on me
    end">
        <label for="testing">Test Input</label><br>
        <input type="text" id="testing" name="testing" value="">
        <input type="submit" value="Submit">
    </form>
  </body>
</html>
```

https://jsitor.com/4XpTQ439GKHp

**Comment by amingheibi** [comment]
Add this line to your input textbox:
```onkeydown="if (event.keyCode === 13) event.preventDefault();"```
