### ISSUE TITLE
Closing SSE connection on events

### ISSUE THREAD

**Issue by aurecchia** [bigskysoftware/htmx#1234]
Hello :wave:

I was wondering if there is any way, using the SSE extension, to close the connection when receiving a message. For example, something like `sse-close="<message-name>"`.

I had a brief look through the extension's code, but I could not find anything.

**Comment by 1cg** [comment]
@Renerick any thoughts?

**Comment by Renerick** [comment]
Interesting. The extensions are designed to keep connections up while their element is on the page. Removing an element will automatically close the connection

What's your use case? Specifically, why do you need to control the connection state manually?

**Comment by aurecchia** [comment]
> The extensions are designed to keep connections up while their element is on the page. Removing an element will automatically close the connection

I did see the code that takes care of closing the connection when the element is not on the page any more, but I didn't realise that `hx-swap` would work in conjunction with the swapping triggered by messages. I could have checked that before writing :see_no_evil: 

Thanks for the help!

**Comment by Chris-May** [comment]
For anyone in the future that needs a little more help connecting the dots like I did, `hx-swap` will swap the contents of the target tag. 

That means if you want to disconnect SSE, you will need to target the parent of the SSE tag.

For example, this will remove the SSE connection by setting the target to the element with the `id` of `"foo"`. When an SSE event is received, it will overwrite the SSE element:

```html
<div id="foo">
  <div hx-ext="sse" sse-connect="/sse-url" sse-swap="message" hx-target="#foo" >
    <!-- placeholder -->
  </div>
</div>
```

**Comment by patrickviz** [comment]
How do you handle this when you want to stream events like an OpenAI call, then close the connection when all of the generation has been received?
