### ISSUE TITLE
Request for wsConnecting event

### ISSUE THREAD

**Issue by aral** [bigskysoftware/htmx#1241]
While implementing [Kitten](https://codeberg.org/kitten/app), I added `wsOpen`, `wsClose`, and `wsConnecting` events to the htmx WebSocket extension (this was during version 1.8.0). It looks like all but `wsConnecting` (and a few more very useful ones like `wsConfigSend` – thank you, lifesaver!) have been implemented in 1.8.5.

Was wondering if you’d be open to adding a `wsConnecting` event that gets called before `htmx.createWebSocket()`?

This is useful for presenting socket connection status (to separate it from the initial state where a connection has not been attempted yet).

This is how I’m currently using it in Kitten’s chat example: https://codeberg.org/kitten/app/src/branch/main/examples/kitten-chat/StatusIndicator.component#L6

Happy to contribute a pull request if you could let me know where it would make sense as I see `createWebSocket()` being called in quite a few places in the code now.

Thanks!

**Comment by Renerick** [comment]
Hi! Thanks for raising the issue

I agree, this event makes sense, especially in scenarios, when the socket is not present on the page constantly, but loaded dynamically. 

If you wish to work on this, the most relevant place is here: https://github.com/bigskysoftware/htmx/blob/master/src/ext/ws.js#L240, right after calling `socketFunc()`

**Comment by aral** [comment]
@Renerick Cool, will do, Denis, thanks :)
