### ISSUE TITLE
ws extension socketWrapper methods are undefined

### ISSUE THREAD

**Issue by aral** [bigskysoftware/htmx#1246]
In the `wsConfigSend` handler, the `send` and `sendImmediately` methods of the `event.detail.socketWrapper` object, as well as its `queue` array are `undefined`.

## Reason

- Methods: Scope/lack of binding
- Array: typo in name (`this.queue` vs `this.messageQueue`)

I’m about to submit a pull request for this but just wanted to document it as an issue first.

**Comment by 1cg** [comment]
@Renerick can you review this?

**Comment by Renerick** [comment]
@1cg approved, see #1247
