### ISSUE TITLE
POSTing <input type='file'>

### ISSUE THREAD

**Issue by Julienboyreau** [bigskysoftware/htmx#125]
Hello,

I tried this : 

```
<form>
<input accept="video/*" hx-post="/%23video%2F" capture="camera" id="media" style="display:none" id="files-upload" type="file" multiple>
</form>
```

But the sent HTTP Request triggered by my selecting a video has a Content-Type: application/x-www-form-urlencoded; charset=UTF-8.
Is there a way to make this work natively ?

Best regards,

Julien

**Comment by chg20** [comment]
Hi Julien,

I have not yet implemented `multipart/form-data` uploading in htmx.  Very sorry about that,

**Comment by rros** [comment]
Hi @Julienboyreau @1cg ,

I added some support for `multipart/form-data` in this commit: 29b503e24a598c03b4da42bdd0e84d47f79a04fc. 

Note this just uses the form encoded as FormData for the request body but doesn't add expression vars and doesn't do filtering of parameters.
I just needed something simple that worked, ideally this should be handled in the `getInputValues()`, `addExpressionVars()` and `filterValues()` functions instead.

**Comment by bencroker** [comment]
This seems like a nice-to-have for 1.0.0 type of feature.

**Comment by 1cg** [comment]
This has been added in the `0.2.0` release:

https://htmx.org/docs/#files
