### ISSUE TITLE
Adding an 'exit' transition animation / delay on hx-boost links

### ISSUE THREAD

**Issue by paulburgess** [bigskysoftware/htmx#1252]
Hi, I have some hx-boosts working just fine:

`<li class="case-study-list__item" hx-boost="true" hx-target="#site-wrapper" hx-select="#site-wrapper" hx-swap="outerHTML settle:0.25s">` (applies to links inside the list item)

...and I am using the hx-settling class to animate the new page in, controlled via settle: 0.25s above.

Is there a way to specify a small delay before leaving the current page?
I have tried delay:1s and throttle:1s on various attribues but has no effect. It seems hx-boosts work a little bit differently to regular GETs.

I notice there is a tiny delay whilst the 'hx-selected' class is applied, is there a way to control that?

This will allow me to add a nice exit css transition.

Many thanks!

**Comment by 1cg** [comment]
You can use the swap delay to introduce a small amount of time between when the old content is marked as .htmx-swapping and when it is actually removed:

https://htmx.org/examples/animations/#swapping
