### ISSUE TITLE
Issue with first key press and content refresh with input trigger "keyup changed"

### ISSUE THREAD

**Issue by strandofgenius** [bigskysoftware/htmx#1259]
I'm using a plugin called sprig that is using htmx 1.7.0.

I have page that has a listing of projects with a search input field that is meant to filter down results. When using the keyboard to navigate I am running into an issue with the input trigger "keyup changed delay:300ms".

What's happening is the first time I tab to the search input and then try and focus on the first search result the content is refreshed and the focus state is reset to then have to tab again to regain focus on the first search result.

I would expect that because the input didn't change it should not trigger a refresh of the target element.

To replicate I tabbed quickly to focus on the first result. Here is a screen capture of whats happening: https://capture.dropbox.com/2VT5X9lzBxcYqyam

```html
<input sprig s-trigger="keyup changed delay:300ms" s-target="#results" type="text" name="search" value="{{ search }}" placeholder="Search">
<div id="results">
  // links to results
</div>
```

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/issues/1259, will be in next release
