### ISSUE TITLE
How conditionally fire the trigger?

### ISSUE THREAD

**Issue by mamcx** [bigskysoftware/htmx#126]
I have an input that represent the qty of an item in an invoice. I need to start it empty and only fire the trigger if the user change de value. So this are the sequence of steps:

```
<input name="qty" placeholder="old.qty">
load: ""
change: "1" -> fire
change:"" -> not fire
change: "1" -> fire
change: "10" -> fire
```

**Comment by chg20** [comment]
We don't have a way to conditionally fire right now.  Currently I would recommend firing it no matter what and just ignore the empty state.

If you want to be really, really (still in early alpha) adventurous, you could use hyperscript and do something like this:

```html
<input hx-trigger="doRequest" hx-post="/whatever"
           _="on change if my.value !== "" trigger doRequest" .../>

```

**Comment by mamcx** [comment]
> just ignore the empty state

How?

**Comment by chg20** [comment]
On the server side, just ignore if the empty value comes in.

**Comment by mamcx** [comment]
> ```
> _="on change if my.value !== '' trigger doRequest" .../>
> ```
This cause:

> Uncaught Error: Expected 'end' but found '!'
> 
> on change if my.value !== '' trigger keyup changed delay:2s //or doRequest, is the same
>                      ^^

Ignoring server side clash with other behaviors so I hope to solve it client side...

**Comment by chg20** [comment]
I put out an alpha4 for hyperscript and this should now work:

```
_="on change if my.value !=='' trigger doRequest"
```

**Comment by mamcx** [comment]
Is in another branch? I try again and it fail. I try the dev branch too.

**Comment by chg20** [comment]
Are you getting the same error?  Can you share the code?

**Comment by mamcx** [comment]
I just do:

`<input type="number" id="qty" name="qty" value="2" placeholder="2" required="" autofocus="" hx-post="" hx-trigger="keyup changed delay:2s" hx-swap="outerHTML" hx-target="#content" hx-select="#content" _="on change if my.value !=='' trigger doRequest">`

I also change ` hx-trigger` to be `doRequest` or in the on change swap with `keyup changed delay:2s`

Also i try a jsfiddle but it not work. How do it?

https://jsfiddle.net/z6ot7efp/

**Comment by chg20** [comment]
Here is a cleaned up version of what you have in that fiddle:

```html
<input type="number" id="qty" name="qty" value="2" placeholder="2" required  autofocus 
        hx-post="/foo"
        hx-swap="outerHTML"
        hx-target="#content"
        hx-select="#content"
        hx-trigger="doRequest"
        _="on change if my.value !=='' trigger doRequest"/>
```

**Comment by mamcx** [comment]
Sorry, but this still not fixed. I try again with the minimal fiddle locally and it show the same error, in firefox and chrome.

Is possible to do the same without hyperscript?

**Comment by tv42** [comment]
Similarly, I would love to not hx-trigger when an input field is `:invalid`. This is easy to demo with e.g. `<input type="url">`, the server doesn't want anything to do with it until it's a valid URL.

**Comment by bencroker** [comment]
@1cg I'm wondering if we could introduce a `valid` modifier on `hx-trigger` that would only trigger the htmx request if the field is valid. The [Constraint Validation API](https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation) would allow us to check whether `validity.valid` is `true`.

**Comment by 1cg** [comment]
@bencroker the validation API is awesome, I had no idea.  Are you interested in integrating it with htmx?

**Comment by bencroker** [comment]
Sure, I can take a shot at it, don't want it to delay a 0.1.0 release though.

**Comment by bencroker** [comment]
@1cg I see you added integration with the HTML validation API in https://github.com/bigskysoftware/htmx/commit/a01fac40a2fd60d8d6a6efb5bf18a7109643e588 which looks amazing!!
