### ISSUE TITLE
Combine Server Requests and Updates to Document

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#129]
When updating combine updates:

- when an event cases multiple elements to update, combine the updates if the results are returned within a reasonable time window
- if a retuned HTML has other HTMX elements, then combine these updates within a reasonable time window

These can also be broken down as:
- ability to queue server requests to be called in parallel and/or quick succession
- ability batch updates to the document for multiple elements with the same trigger or triggers foreign at the same time
- when returned HTML contains HTMX recursively get the additional HTML and combine them to one document update

If there is a delay in getting the results then to move it to the next update cycle.

**Comment by 1cg** [comment]
This is something that I would like handled in hyperscript
