### ISSUE TITLE
possible to use hx-ext parammeter on htmx.ajax() api?

### ISSUE THREAD

**Issue by KenyOS** [bigskysoftware/htmx#1334]
I wish to trigger a custom js with `htmx.ajax` after the user select a time range on datepicker.

From this page  [https://htmx.org/api/#ajax](https://htmx.org/api/#ajax) I can't see a subitem for hx-ext on `context`, it possible to include it? I'm using a custom extension `path-params` to send custom hx-vals with javascript.

**Comment by 1cg** [comment]
It should use any `hx-ext` declared on the `element` object, but you can't pass it in explicitly.
