### ISSUE TITLE
Document automatic Title change

### ISSUE THREAD

**Issue by cjfloss** [bigskysoftware/htmx#1345]
If the returned HTML contains a `title` tag, the page's title will be changed, but that doesn't appear on the [documentation](https://htmx.org/docs/).

**Comment by DataHearth** [comment]
@cjfloss Hey! I don't know when you looked at the doc, but I found a reference to it here: https://htmx.org/attributes/hx-swap/

Hope this could help someone ^^.

```text
Title: ignoreTitle

By default, htmx will update the title of the page if it finds a <title> tag in the response content. You can turn off this behavior by setting the ignoreTitle option to true.
```

**Comment by Telroshan** [comment]
On top of the `hx-swap` attribute's own documentation linked above, mentions to title swapping also appear
- in the documentation you linked, [in the `Swap Options` section](https://htmx.org/docs/#swap-options)
> The [hx-swap](https://htmx.org/attributes/hx-swap/) attribute supports many options for tuning the swapping behavior of htmx. For example, by default htmx will swap in the title of a title tag found anywhere in the new content. You can turn this behavior off by setting the ignoreTitle modifier to true:
- in that same page [in the `Configuring htmx` section](https://htmx.org/docs/#config)
> <html>
<body>


htmx.config.ignoreTitle | defaults to false, if set to true htmx will not update the title of the document when a title tag is found in new content
-- | --



</body>
</html>

**Comment by mholt** [comment]
Does this happen for `hx-boost` too? Or just swap?
