### ISSUE TITLE
ws-send does not respect hx-trigger

### ISSUE THREAD

**Issue by gamgi** [bigskysoftware/htmx#1396]
Hi!

I am unable to send data over a websocket triggered by anything other than the "natural" event of an element. I am using the new websocket extension.

It seems that elements with `ws-send` do not support using `hx-trigger` to specify the trigger for sending a websocket message. The documentation at https://htmx.org/extensions/web-sockets/ indicates that using `hx-trigger` should be possible:
> ws-send - Sends a message to the nearest websocket based on the trigger value for the element (either the natural event of the event specified by [hx-trigger])

Am i missing something, or is the extension not working correctly?

**Example repro (fiddle at https://jsfiddle.net/q0z87uko/):**

```html

<script src="https://unpkg.com/htmx.org@1.9.0"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>

<div hx-ext="ws" ws-connect="wss://ws.postman-echo.com/raw">
  <div ws-send>
    Click me to send WS (this works)
  </div>
  <div ws-send hx-trigger="click">
    Click me to send WS (this does not work)
  </div>
  <input ws-send hx-trigger="keyup changed" value="Edit me to send WS (this does not work)" />
</div>
```

**Comment by Renerick** [comment]
Thank you for the report. I'll check both hx-ws and hx-signalr regarding this issue

**Comment by Renerick** [comment]
I opened a PR with a fix and published an update for htmx-signalr extension https://github.com/Renerick/htmx-signalr/pull/7

**Comment by Renerick** [comment]
Yes, I'll close this issue, it works and no additional problems occured
