### ISSUE TITLE
Minor issue, scary console error on chromium

### ISSUE THREAD

**Issue by cscortes** [bigskysoftware/htmx#14]
Get these errors, but googling the error they seems to be a non issue.  These guys says there is a  fix.  https://trackjs.com/blog/refused-unsafe-header/

Despite the RED LETTER ERRORS on the console, program never stops. 

```
kutty.js:1169 Refused to get unsafe header "X-KT-Trigger"
xhr.onload @ kutty.js:1169
load (async)
issueAjaxRequest @ kutty.js:1165
issueRequest @ kutty.js:609
eventListener @ kutty.js:614
kutty.js:1170 Refused to get unsafe header "X-KT-Push"
xhr.onload @ kutty.js:1170
load (async)
issueAjaxRequest @ kutty.js:1165
issueRequest @ kutty.js:609
eventListener @ kutty.js:614
```

**Comment by chg20** [comment]
OK, should probably fix it.

**Comment by chg20** [comment]
Want to take a crack?

**Comment by cscortes** [comment]
okay, got this fixed. Will do a pull request in a bit.

**Comment by chg20** [comment]
Was this fixed by https://github.com/bigskysoftware/htmx/commit/3eb4a56e285ec6e0586c10bdaa2a42661f0f3af1 ?

**Comment by chg20** [comment]
Apparently yes
