### ISSUE TITLE
Search event missing from hx-trigger docs 

### ISSUE THREAD

**Issue by nickchomey** [bigskysoftware/htmx#1401]
In ch 6 of the hypermedia book, active search uses `hx-trigger="search, keyup delay:200ms changed"/> (3)`

But there's no mention of this event in the website documentation. 

https://github.com/bigskysoftware/htmx/blob/master/www/content/attributes/hx-trigger.md

**Comment by daturkel** [comment]
Was wondering the same thing. The search trigger is also mentioned in the [active search example](https://htmx.org/examples/active-search/), but not in the official docs.

**Comment by andryyy** [comment]
You can use any event as trigger. "search" is the event fired when a `type="search"` element is used.

**Comment by daturkel** [comment]
> You can use any event as trigger. "search" is the event fired when a `type="search"` element is used.
> 
> A useful event reference can be found on [MDN](https://developer.mozilla.org/en-US/docs/Web/Events).
> 
> Example: https://jsfiddle.net/pf0bn6cq/ - you need to open the console to see the failed request to /bla.

Thank you @andryyy ! I suspect this is obvious to more experienced JS developers (i.e. not me) so I appreciate you pointing to the MDN docs.
