### ISSUE TITLE
oob swap via extension fails if parent had [hx-swap]="outerHTML" 

### ISSUE THREAD

**Issue by anpin** [bigskysoftware/htmx#1419]
I'm using htmx `1.9.2` with [htmx-signalr](https://github.com/Renerick/htmx-signalr) and it fails on this line https://github.com/bigskysoftware/htmx/blob/990cdd61a110bd497cb50d2286407ac6b7b64183/src/htmx.js#L948 with 
```
023-04-29T12:36:15.320Z] Error: A callback for the method 'component-update' threw error 'TypeError: Cannot read properties of null (reading 'firstChild')'.
 ``` 
If element received via signalr had  `hx-swap-oob="outerHTML" ` and some parent of the target had `hx-swap="outerHTML"`

For example with such layout:
```
<div hx-ext="signalr" signalr-connect="/hub" > 
 <div id="second-level" hx-swap="outerHTML"> 
   <div id="component" signalr-subscribe="component-update" hx-target="this" > <div/>
  <div/>
<div/>
```
When extension receives 
```
   <div id="component" signalr-subscribe="component-update" hx-target="this" hx-swap-oob="outerHTML" >Some new content here<div/>
```
It replaces the content correctly, but then throws above exception after which any further updates would be ignored. 

The workaround is to set `hx-swap="innerhtml"` on the target node in the original layout [1], so call to `getSwapSpecification` [here](https://github.com/Renerick/htmx-signalr/blob/b7f7dc98ff0bb4d2cb691b04ed3026a245a02eb6/hx-signalr.js#L194) returns `innerhtml`.

[1] Workaround 

```
<div hx-ext="signalr" signalr-connect="/hub" > 
 <div id="second-level" hx-swap="outerHTML"> 
   <div id="component" signalr-subscribe="component-update" hx-target="this" hx-swap="innerhtml"> <div/>
  <div/>
<div/>
```

(Please let me know if the issue should be moved to the extension repo)

**Comment by Renerick** [comment]
Yes, hx-signalr is supported by me, not bigskysoftware, please move this issue to the repo, I'll take a look
