### ISSUE TITLE
Events from HTTP response header do not trigger 

### ISSUE THREAD

**Issue by kbruegge** [bigskysoftware/htmx#1435]
Hello there, 
I'm adding a "HX-Trigger" entry to my response headers from an endpoint on my server (Python w. Flask). However no events are being triggered on the `document.body` as far as I can tell. I tried following the instructions on https://htmx.org/headers/hx-trigger/

Here is the most minimal example I could come up with:

```python
from flask import Flask, make_response
from flask_cors import CORS

ORIGINS = [
    "*",
]
app = Flask(__name__)
CORS(app, origins=ORIGINS)


@app.post("/api/foo/")
def foo():
    r = make_response("Wow!!")
    r.headers["HX-Trigger"] = "awesomeEvent"
    return r

```
And on the "frontent":

```
<!DOCTYPE html>
<html>

<head>
    <script src="https://unpkg.com/htmx.org@1.9.2"
        integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
        crossorigin="anonymous"></script>
</head>

<body>
    <button hx-post="http://127.0.0.1:5000/api/foo/" hx-target="#someTarget">
        Click Me!
    </button>
    <p id="someTarget"></p>
</body>

<script>
    document.body.addEventListener("awesomeEvent", function (evt) {
        console.log(`Event ${evt} was triggered!`); // never happens
    })
</script>
```

I checked the response in Firefox Dev tools and it looks correct to me: 
<img width="546" alt="Screenshot 2023-05-11 at 13 17 39" src="https://github.com/bigskysoftware/htmx/assets/4076745/dbdc473a-aa18-4bf4-be7a-b6ba7817cd5d">

I also tried the other ways to respond to a "HX-Trigger" as written in the docs to no avail.  I'm probably not seeing the forest for the trees here. Any help would be greatly appreciated.

**Comment by andryyy** [comment]
CORS(app, origins=ORIGINS, expose_headers="HX-Trigger")

👍🏻 

See https://htmx.org/docs/#cors

**Comment by kbruegge** [comment]
That's it! Never heard of it before. Here is some more detail for anyone else stumbling upon this. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
> The Access-Control-Expose-Headers response header allows a server to indicate which response headers should be made available to scripts running in the browser, in response to a cross-origin request.

I had a hunch it was a CORS issue but was misdirect due to the fact that the browser apparently got the correct headers. 
Good to know! Thanks for working on HTMX ❤️
