### ISSUE TITLE
htmx tags do not work inside bootstrap popovers

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#1437]
[bootstrap popovers](https://getbootstrap.com/docs/5.0/components/popovers/) allows the display of HTML code inside popovers. However, the HTMX tags such as `hx-get` inside the HTML code do not appear to work. The reason appears to be that the HTML code is dynamically generated so the tags `hx-get` are not activated for the elements.

I can provide a detailed example if needed but the process essentially is

```html
<a data-bs-html="true" data-bs-trigger="focus" data-bs-container="body" data-bs-toggle="popover" 
        data-bs-placement="bottom" data-button-url="a-url" >
        button
</a>
```
The popover is triggered with a customized content generator

```javascript
function get_popover_content() {
    return 'some other text <a href="#" hx-get="${this.dataset.buttonUrl}">button</a>`
}

var popoverTriggerList = [].slice.call(
  document.querySelectorAll('[data-bs-toggle="popover"]')
);
popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl, {
    content: get_popover_content,
  });
});
```

When the user click the button, a popover is created with a link, but clicking the link will not trigger `hx-get`. It looks that I need to handle the `shown.bs.popover` and do something to the generated popver elements to enable `hx-get`. How can this be done?

**Comment by BoPeng** [comment]
@dz4k This issue is very similar to https://github.com/bigskysoftware/_hyperscript/issues/432 but I cannot seem to call `htmx.processNode`. What is the proper way to process dynamically generated element with htmx tags?

**Comment by dz4k** [comment]
It's `htmx.process`: https://htmx.org/api/#process

**Comment by BoPeng** [comment]
This works! In case someone has the same issue, the `get_popover_content` function should look something like

```javascript
function get_popover_content() {
  let div = document.createElement("div");
  div.innerHTML = htmlcode;  // this is the html code with htmx tags etc
  htmx.process(div); // this is what is needed
  return div;
}
```
