### ISSUE TITLE
Suggestion.Htmx and service workers.

### ISSUE THREAD

**Issue by GEORGES-DTECH** [bigskysoftware/htmx#1445]
I believe htmx and progressive web application are the future.Is there a way html fragments can be cached by the service worker.

**Comment by corlaez** [comment]
A simple service worker that caches pages is possible for sure... I have an example one here, but you will have to find specific resources of service workers to adjust it to your needs:

This one downloads the pages every time and caches them before serving them. The install part, I think helped to quickly update when a new serviceWorker was sent to the browser. For me that worked best, as I was constantly changing the website and it run so fast I didn't really care about getting to agressive for caching. It was therefore only serving from cache when the real request failed:

https://raw.githubusercontent.com/corlaez/web/8ef0aed711a9545d0d02dc4881f63d986b69fecc/static/serviceWorker.js

**Comment by 1cg** [comment]
i agree that is an interesting idea, but it's beyond the scope of the core htmx project at this time

if you want to explore the idea, however, (maybe as an extension?). I am happy to link to that project from the main project
