### ISSUE TITLE
Can I do an hx-get on a specific element? 

### ISSUE THREAD

**Issue by paulburgess** [bigskysoftware/htmx#1447]
Hi, I have a set up with regular links like and I'd like to enhace them with a modal conatining #main element of the URL I'm hx-get-ting. (Looking at the great examples here: https://htmx.org/examples/modal-custom/)

I have this:

`<a href="/music/release-name">Info</a>`

Can I do this and pull in just the element with the #main ID? bascially excluding the header and footer of the URL I'm getting, like so:

`<a hx-get="/music/release-name#main" href="/music/release-name">Info</a>`

Does it work that way?

Many thanks!

**Comment by matiboy** [comment]
Hi @paulburgess I believe what you're looking for is [hx-select](https://htmx.org/attributes/hx-select/)

Original page:

```html
<div id="modal"></div>
<a hx-get="your_url" hx-select="#main" hx-target="#modal">Click</a>
```

with response

```html
<div>Some stuff</div>
<div>More stuff <div id="main">Target content</div></div>
```

Should result in the following html:

```html
<div id="modal">Target content</div>
<a hx-get="your_url" hx-select="#main" hx-target="#modal">Click</a>
```

Hope this helps

**Comment by paulburgess** [comment]
Over 6 months later... thank you @matiboy - this worked a treat
