### ISSUE TITLE
Submitting Two Forms with One Button Click

### ISSUE THREAD

**Issue by thecodeclimber** [bigskysoftware/htmx#146]
Hello, I just stumbled upon htmx a few minutes ago and am wondering if it can help me with the following.  

I have two forms that I want to submit with the same button click.  I.e., I click on a submit button and the data from both form1 and form2 gets submitted.  Is this possible with htmx?  If so, how would I do it?  

Thanks.

**Comment by tapvt** [comment]
I was toying with the idea of building an extension to handle this exact use case for a complex backoffice application UI.

I do not believe such functionality is currently baked into `htmx`.

(I'm a user, not the developer.)

**Comment by 1cg** [comment]
Easiest thing right now would be to catch the event and then click submit buttons in both forms. 

Are the forms submittable independently as well?  

If you are really adventuresome, you could try using hyperscript:

```html
  <button _="on click send submitIt to #form1 then send submitIt to #form2">Submit Both Forms</button>
```

But I can't recommend that for production stuff yet.

**Comment by 1cg** [comment]
Actually, even better, you could use a class to wrap them both up:

```html
  <button _="on click send submitIt to .myForms>Submit Both Forms</button>
```

But, again, hard to recommend an alpha technology

**Comment by bencroker** [comment]
I tend to agree that using Javascript (or hyperscript) to achieve this sounds reasonable. Well ideally, you'd just have a single form and let the backend take care of submitting it to multiple endpoints.

**Comment by bencroker** [comment]
Die you mean to reopen this issue @1cg?

**Comment by 1cg** [comment]
Yes, I did think it was worth thinking about in a more general sense

**Comment by bencroker** [comment]
I'm struggling to find a common use-case for this, which to me says reach for JS or an extension.

**Comment by mmokross** [comment]
Hmmm... Maybe the following example can help?

**data:**
- there are different locations
- for each location there may be weekly events
- for each location there may be events on specific dates

**ui:** the user sees
  - both weekly events and specific dates
  - for one selected location and
  - for one selected specific year

**interactions:**
- user can change the location he wants to see, resulting in
  - seeing the weekly events for that new selected location for the previous selected year
  - seeing the specifics dates for that new selected location for the previous selected year
- user can change the specific year he wants to see, resulting in
  - seeing the weekly events for the previous selected location for that new selected year
  - seeing the specifics dates for the previous selected location for that new selected year

Thus both selections should result in replacing two different html contents.

**Comment by 1cg** [comment]
thinking on it more, I feel like this is a job for hyperscript or for using out of band responses

it doesn't strike me as being a general enough problem to warrant additional functionality in htmx, and there are existing work arounds

**Comment by emanueldonalds** [comment]
What do you think about using cookies for this use case, or is that against the whole idea of HTMX? 

In mmokross's example, the location and specific year would both be stored in a cookie, so when the selected year is change, the server gets the location from the cookie, and vice versa.
