### ISSUE TITLE
Lazy or Eager Loading

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#147]
Sometimes we might need to only send the server request when the element becomes viewable. So need of server request when it is hidden from view.

Some elements we might need loading no matter what.

**Comment by benpate** [comment]
Your first idea should be covered by `trigger="revealed"`.  I'm not sure how much farther @1cg is planning to go on this.  While working on the infinite scrolling issue (PR #169), I did find myself wanting to know when an element was revealed from the top vs. bottom of the page.  Perhaps we could propose a more comprehensive "onscreen/offscreen" event mechanism that includes more data about a node's previous position?

**Comment by 1cg** [comment]
The second use case is covered by the `load` event, see the lazy loading demo here:

https://htmx.org/examples/lazy-load/
