### ISSUE TITLE
HTMX Active Search example on the htmx.org website

### ISSUE THREAD

**Issue by rcorsari** [bigskysoftware/htmx#1473]
Dear friends

on this page
https://htmx.org/examples/active-search/

in the example code, you write this

`hx-trigger="keyup changed delay:500ms, search"`

can you kindly address to the piece of documentation that explains what is that comma simbol after 500ms with 'search' keyword right after? So I'm referring to the final part of that line of code

`,search"`

I can't find it in the documentation https://htmx.org/docs/#triggers

Thank you

**Comment by andryyy** [comment]
Hi,Check this: https://htmx.org/docs/#trigger-modifiers"Multiple triggers can be specified in the hx-triggerattribute, separated by commas."Am 03.06.2023 um 14:21 schrieb Robert ***@***.***>:﻿
Dear friends
on this page
https://htmx.org/examples/active-search/
in the example code, you write this
hx-trigger="keyup changed delay:500ms, search"
can you kindly addres to the piece of documentation that explains what is that comma simbol after 500ms with 'search' keyword right after? So I'm referring to the final part of that line of code
,search"
I can't find it in the documentation https://htmx.org/docs/#triggers
Thank you
