### ISSUE TITLE
Image not uploaded when submitting a form with hx-include

### ISSUE THREAD

**Issue by housUnus** [bigskysoftware/htmx#1477]
Hi,

Thanks for the great package, for a reason, I can't use the submit button inside the form, that's why I'm submitting it with hx-include="#myform", THE issue here is the fields are sent to the backend except for the File input, it is not included with request.FILES but with request.POST so I'm not receiving any files to save, I used the enctype as well "x-encoding=multipart/form-data", the input has the right name, so I think it's an issue with hx-include itself.

Regards.

**Comment by alexpetros** [comment]
Can you share why you can't use the submit button in the form? There might be a workaround for that problem, which would make your life a lot easier—generally speaking, you want to use HTMX to supplement browser functionality like form submission, not replace it.
