### ISSUE TITLE
Reconnect WebSockets

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#148]
WebSockets don't automatically reconnect, for instance, in the case of a server restart or failover.  I have skimmed through the HTMX source code, but I don't see it attempting to reconnect automatically, and I don't see anywhere that I (as the site developer) can change this behavior.

It seems like this would be a useful addition to the HTMX Websocket handling, and adding it should not break any existing developer expectations.

Here's an article on StackOverflow that outlines the basic idea -- essentially listening for an `onclose` event, waiting 5 seconds (or some other configurable duration), then trying to start a new WebSocket connection.

https://stackoverflow.com/questions/3780511/reconnection-of-client-when-server-reboots-in-websocket

Would you like me to make a pull request?

**Comment by 1cg** [comment]
Sure, happy to look at one!

**Comment by vlcinsky** [comment]
Docs at https://htmx.org/api/#config already show `wsReconnectDelay:full-jitter` configuration option what means PR #381 is merged.

Could @benpate or someone else involved in this ticket review and possibly close this issue?

**Comment by benpate** [comment]
:)
