### ISSUE TITLE
Proposal: `on:` listener attributes 

### ISSUE THREAD

**Issue by alexpetros** [bigskysoftware/htmx#1480]
## Problem
HTML does not support attribute listeners for custom DOM events. For example, HTML supports `onclick` for the [click](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) event, but nothing for HTMX custom events like [htmx:beforeSwap](https://htmx.org/events/#htmx:beforeSwap):

```html
<!-- Legal -->
<button onclick="doSomething()">

<!-- Not legal -->
<button onhtmx:beforeSwap="doSomething()">
```

The `hx-on` [attribute](https://htmx.org/attributes/hx-on/) was added to rectify this problem, but the introduction of an additional mini-language is somewhat out of step how the rest of HTML works:

```html
<!-- DOM built-in -->
<button onclick="alert('Clicking!')" onmouseover="alert('Hovering!')">

<!-- HTMX -->
<button hx-get="/info" hx-on="htmx:beforeRequest: alert('Making a request!')
                              htmx:afterRequest: alert('Done making a request!')">
```

## Solution
I think the ideal interface is a more HTML-style interface that looks something like this:
```html
<!-- DOM built-in -->
<button onclick="alert('Clicking!')" onmouseover="alert('Hovering!')">

<!-- HTMX -->
<button hx-get="/info" 
        on:htmx:beforeRequest="alert('Making a request!')" 
        on:htmx:afterRequest="alert('Done making a request!')"
>
```
Because you cannot `querySelector` for attribute wildcards (i.e. `querySelectorAll('button[on*]')`), HTMX needs another way to identify elements to which it should attach custom events. For elements that have an `hx-METHOD` attribute already, that isn't a problem, but you might like to add listeners to elements that do not make requests. I propose re-using the `hx-on` attribute, empty, for this purpose:

```html
<button hx-on on:htmx:afterSwap="alert('I was swapped in!')" >
```

When composed with triggers, this completes the idea I was getting at in https://github.com/bigskysoftware/htmx/pull/1327, allowing you to trigger actions based on `hx-trigger` syntax without having to use any javascript (outside the element):

```html
<button hx-on 
        hx-trigger="load delay:1s"
        on:htmx:trigger="this.innerText='Back to normal!'"
>Just Swapped!</button>
```

In addition to being already part of the spec, re-using `hx-on` allows you to write its documentation in such a way that makes it clear this new way is the preferred way of using it, while preserving backwards compatibility with all existing HTMX code that made use of `hx-on`. The new way of using `hx-on` (with `on:` attributes) would _only_ work if its value were empty; otherwise it would default to the deprecated functionality.

I also believe that even though it's not strictly necessary, `hx-on` should be required even if the element has an `hx-METHOD` method already, because it prevents some subtle bugs where a seemingly unrelated event listener stops working because you removed the `hx-get` method.

You can also include the existing DOM events in the new style, under a `dom` namespace:

```html
<!-- DOM events HTMX-style -->
<button hx-on on:dom:click="alert('Clicking!')" on:dom:mouseover="alert('Hovering!')">
```
which is obviously strictly worse than just using the actual `onclick` attribute, but you get it for "free" as part of the interface and demonstrates the naming convention nicely.

_Thanks to @dz4k for bringing this back up in the Discord; I incorporated a lot of his suggestions._

**Comment by 1cg** [comment]
merged, will be standard for htmx 2.0
