### ISSUE TITLE
Weird behaviour (bug?) when using back button

### ISSUE THREAD

**Issue by kocakosm** [bigskysoftware/htmx#1481]
Hi,

I'm facing a weird issue with HTMX's history support... When a previous state is retrieved from the browser's history some classes are not restored correctly. It's quite difficult to explain, but (hopefully) easy to reproduce:

1. Create the following files :
**index.html** 
```
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <title>HTMX history test</title>
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    <style>
      nav .nav-entry.selected {
        color: white;
        background-color: black;
      }
    </style>
  </head>
  <body>
    <nav hx-push-url="true">
      <a class="nav-entry" href="#" hx-get="item1.html" hx-target="main" onclick="htmx.takeClass(this, 'selected')">Item1</a>
      <a class="nav-entry" href="#" hx-get="item2.html" hx-target="main" onclick="htmx.takeClass(this, 'selected')">Item2</a>
      <a class="nav-entry" href="#" hx-get="item3.html" hx-target="main" onclick="htmx.takeClass(this, 'selected')">Item3</a>
    </nav>
    <main></main>
  </body>
</html>
```

**item1.html**
```
<h2>Item 1</h2>
```

**item2.html**
```
<h2>Item 2</h2>
```

**item3.html**
```
<h2>Item 3</h2>
```

2. Start a local web server 
`python3 -m http.server 8080`

4. Open your browser and go to localhost:8080, navigate to item1, item2 and item3

5. Hit the back button (up to 3 times). You'll see that the page content somehow matches the previous state but the selected nav entry does not.

FWIW, I've tested this exact scenario on Firefox LTS (102.11.0) and Chromium (114.0.5735.90) and got the exact same behaviour.

I don't know if this is a bug or a misuse/misunderstanding of HTMX's history support.

Thanks for your help !

**Comment by 1cg** [comment]
htmx doesn't intervene for anchors with a local anchor href, so this is the regular browser back button (which is not aware of the javascript class switching you are doing)

**Comment by kocakosm** [comment]
Hi,

Thank you very much for this explanation. 

May I ask a few more questions ?... 
- What do you mean by "htmx doesn't intervene" here since, for instance, the  ̀htmx:historyRestore` event is actually fired when pressing the back button ?
- What would be the best solution to work around this in this exact use case (where the selected element is set client-side) ? Of course the best solution would be to render both the `nav` and the `main` elements "server side" but IMHO this is a perfectly valid use case to set the selected element client side...

Thanks.
