### ISSUE TITLE
<div hx-trigger="search from:closest div"> seems to see itself as closest instead of parent

### ISSUE THREAD

**Issue by krims0n32** [bigskysoftware/htmx#1487]
I am working on a search box, using alpine to dispatch an event when the search should be performed. I know I can do this with htmx key events but it's not what I want in this situation.

The event is not picked up by htmx in the example below. When I change the inner div to a span, it does work. So it seems from:closest div is looking at itself somehow while it should be looking at the parent div according to the docs?

```
<div @keyup.debounce.250ms="() => { $dispatch('search'); }">
  <div hx-trigger="search from:closest div" hx-post="some_url" hx-target="this">
  </div>
</div>
```

**Comment by Telroshan** [comment]
This selector resolves to [element.closest](https://developer.mozilla.org/docs/Web/API/Element/closest#return_value), and according to its doc :
> Return value
The closest ancestor [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) or itself, which matches the selectors. If there are no such element, null.

So if the element itself matches the selector, it is returned.

I agree that the [htmx doc](https://htmx.org/attributes/hx-target/) should mention that explicitly though.
In your case, you might want to add a class to your parent container, to query it specifically, or as you already said, use another tag for your child element so it doesn't match that `closest` query anymore

**Comment by krims0n32** [comment]
Thanks for clarifying! I found another solution that works well.
