### ISSUE TITLE
Best way to contribute?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#149]
This is not an issue, but a question that I mentioned briefly in #148.  I'm currently modeling a server that may end up using HTMX, and am very interested in its potential.  What's the best way for me to contribute?  I'm happy to "just submit pull requests" but I want to make sure that I'm being helpful, and not just adding noise.

Do you have a list of priorities that I could start knocking out? Or, are you looking for real-world use cases that would help guide the architecture.  What would be the best way to give a few hours a week to this project?

**Comment by 1cg** [comment]
Hi Ben,

Happy to look at pull requests.  If you want to jump on discord to talk about ideas you can do so here:

https://htmx.org/discord

I am slammed for the next few weeks so I might not be as responsive as I would like, but should be back to htmx development in mid to late august.

**Comment by benpate** [comment]
Done.  Sorry you're slammed.  Hopefully, it works out for the best :)
