### ISSUE TITLE
`hx-confirm` issues the request without confirmation on some browsers

### ISSUE THREAD

**Issue by LucianoLaratelli** [bigskysoftware/htmx#1505]
It appears that `hx-confirm` isn't correctly blocking the request in some browsers.

I made test.html below, then served it with `python3 -m http.server`.
```
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
</head>
<body>
    <button type="button" hx-delete=
    "my-endpoint-for/a-resource-id" title=
    "Delete this checklist" hx-confirm="Careful!" btn=""
    btn-danger=""><span>Delete</span></button>
</body>
</html>
```

If I click the button on my desktop (Firefox), the confirmation dialog pops up and correctly blocks the request until I hit `OK`. On mobile (iOS 16.5, Firefox 114.2 [31625]), the request fires before I hit `OK`. In fact, it fires almost immediately after the confirmation dialog pops up. The issue doesn't reproduce on Safari on the same device.

Not sure if this is an HTMX bug or a Firefox bug, but figured I would start here. 

P.S. Do also want to say thanks! for the wonderful idea, HTMX feels good to work with.

**Comment by 1cg** [comment]
hey @LucianoLaratelli this seems like a pretty serious issue w/ the Firefox mobile browser: the `hx-confirm` attribute simply calls `confirm()` in javascript, which should absolutely be blocking.
