### ISSUE TITLE
Proposal: event filtering in hx-on

### ISSUE THREAD

**Issue by metametadata** [bigskysoftware/htmx#1519]
I expected event filtering to work in `hx-on` similarly to `hx-trigger`.

But, for example, `htmx:afterRequest[successful]: alert('hi')` currently produces `SyntaxError: unexpected token: ':'`.

Workaround is to filter in JS: `htmx:afterRequest: if(event.detail.successful) {alert('hi')}`.

**Comment by alexpetros** [comment]
The new `hx-on` syntax probably wouldn't support this, because now the events are defined in the attribute names themselves: https://htmx.org/attributes/hx-on/

Closing this issue because the proposal isn't compatible with the current syntax. Definitely do the oneline `if` statement for this, though.

**Comment by stella6767** [comment]
is there a simple solution that call diffrent behavior by response Status.
i write this code. but i'm not satisfy.  

```

    document.body.addEventListener('htmx:responseError', function (evt) {

        console.log("check error",evt.detail.xhr.responseText)
        alert(JSON.parse(evt.detail.xhr.responseText).detail);

    });

    document.querySelector('#post-delete-btn').addEventListener('htmx:afterRequest', function (evt) {
        //var xhr = evt.detail.xhr;
        //var statusCode = xhr.status;
        let successful = evt.detail.successful;
        if (successful) {
            location.reload();
        }
    });
    
    

```

**Comment by stella6767** [comment]
> 새 구문은 아마도 이것을 지원하지 않을 것인데, 이제 이벤트가 속성 이름 자체에 정의되어 있기 때문입니다 https://htmx.org/attributes/hx-on/`hx-on`
> 
> 제안이 현재 구문과 호환되지 않기 때문에 이 문제를 종료합니다. 확실히 이것에 대한 oneline 문을 수행하십시오.`if`

is there a simple solution that call diffrent behavior by response Status.
i wrote this code. but i'm not satisfy with this.  

```

    document.body.addEventListener('htmx:responseError', function (evt) {

        console.log("check error",evt.detail.xhr.responseText)
        alert(JSON.parse(evt.detail.xhr.responseText).detail);

    });

    document.querySelector('#post-delete-btn').addEventListener('htmx:afterRequest', function (evt) {
        //var xhr = evt.detail.xhr;
        //var statusCode = xhr.status;
        let successful = evt.detail.successful;
        if (successful) {
            location.reload();
        }
    });
    
    

```
