### ISSUE TITLE
Editing while request is in flight leads to lost events

### ISSUE THREAD

**Issue by tv42** [bigskysoftware/htmx#152]
1. Set up a form like this

```
<input hx-post="someURL" hx-trigger="keyup changed delay:1">
```

2. Set up a server that intentionally delays a few seconds before it responds.
3. Type "foo"
4. Observe the POST happening
5. Type "bar" while the server is delaying the response
6. Observe server response completing; even observe the UI acknowledge a successful save, if you have that wired up.
7. (Optional, for extra effect:) Walk to the kitchen and back
8. See everything on page looks successful, navigate away from the page
8. Notice that the server never saw "foobar", only "foo". You've lost data!

I think dirty state existing at a time when a request completes should submit another request immediately.

**Comment by 1cg** [comment]
That's a good point.  Intercooler would queue a request and fire it after the current request ended, and htmx should have the same behavior.

A work around is to disable input while the request is in flight.  Not always ideal or even possible, so this should definitely be fixed.

**Comment by mamcx** [comment]
I'm hit for this. Is terrible UX because is for a invoice entry and constantly lose the entered data.

Exist other libraries like this that is more battle-tested?

**Comment by clarkevans** [comment]
> I'm hit for this. Is terrible UX because is for a invoice entry and constantly lose the entered data.
> Exist other libraries like this that is more battle-tested?

This was rude. This is a relatively new, and quite innovative, open source project. You are welcome to submit a pull request that fixes the issue. At this time `1cg`, the initial author, said he's away for a month or so.  He's got a well earned break; it's not like we're paying him.

**Comment by mamcx** [comment]
> This was rude. 

Yeah?. Was _not_ the intention anyway. Just stating what is the perception from my users.

I think htmx is an incredible idea and that is why I'm using it. It already saves a lot of time. But without a workaround, I must face the decision to swap it or create a hack.
 
> Anyway, you could always use the predecessor project, https://intercoolerjs.org/

I will check it, thanks.

**Comment by 1cg** [comment]
No worries guy, yes, this is a very annoying issue if you are having things save on keystrokes, for example.

@mamcx intercooler is more mature and does the right thing, queuing up a request if another one is in flight, instead of cancelling it.

I plan on fixing this as soon as possible, but unfortunately some life events have made it very difficult to get open source work done.

**Comment by 1cg** [comment]
OK, I felt sufficiently bad about this to address it this morning.  The fix is available in dev (and master, on accident).
