### ISSUE TITLE
trigger for keyup + enter and escape key combinations

### ISSUE THREAD

**Issue by ptrthomas** [bigskysoftware/htmx#153]
thanks for this great framework ! I am trying to port the TodoMVC Vue example http://todomvc.com/examples/vue/ to  a custom implementation.

I'm having trouble porting this specific behavior expressed in Vue:

```html
<input @blur="doneEdit(todo)" @keyup.enter="doneEdit(todo)" @keyup.esc="cancelEdit(todo)">
```

so the requirement is to do 2 different triggers for the same element, and only for specific keyup + key combinations. I was able to get `hx-trigger="blur"` to work perfectly. but I don't know how to handle the ENTER and ESCAPE keys on the same element

if this needs some custom JS event handlers, can you provide some pointers, or what you feel would be the best way to do this

**Comment by 36864** [comment]
There is currently no way to do this with just htmx. You could do this with hyperscript, it would look something like this:

```
_="on keyup if (event.key == 'Enter') then doneEdit(todo) else if (event.key == 'Escape') then cancelEdit(todo) end end"
```

**Comment by ptrthomas** [comment]
@36864 thanks. was just looking at the docs and got an idea. if I am able to generate custom events with custom names e.g. `keyup-enter` and `keyup-escape` and emit them from the element, I should be able to do `hx-trigger="blur, keyup-enter, keyup-escape"` right ? I know it bends the rules, but

**Comment by 36864** [comment]
In your example, all of your events would trigger the same behavior.

**Comment by ptrthomas** [comment]
@36864 yes, but if I have this client-side JS available:

```js
      var handleEdit = function (event, element) {
        switch (event.code) {
          case 'Escape':
            element.value = '';
            element.dispatchEvent(new Event('keyup-escape'));
            break;
          case 'Enter':
            element.dispatchEvent(new Event('keyup-enter'));
            break;
        }
      }
```

and on the element:

```html
<input onkeyup="handleEdit(event, this)" hx-trigger="blur,keyup-enter,keyup-escape">
```

it does work. I will look at hyperscript, but it seems to be new / evolving. thanks you can close this issue if appropriate

**Comment by 36864** [comment]
>but it seems to be new / evolving.

Just a quick note, so is htmx. Hyperscript is a companion project to htmx specifically made to offer extended functionality where htmx might fall short.

**Comment by rmmcgr** [comment]
As an aside, I found the following trigger on an input to work for when the enter key is pressed:

hx-trigger="keyup[key=='Enter']"
