### ISSUE TITLE
Make it possible to send form params in the URL, instead of the request body

### ISSUE THREAD

**Issue by alexpetros** [bigskysoftware/htmx#1539]
Make it possible to use query parameters in DELETE requests via two mechanisms:

* Expose this as an option in the `htmx:configRequest` event 
* Introduce a global config

This config should be generic i.e. it will allow you to do so in any request type (including GET) if so desired.

Follow-up issue from #1514

**Comment by 1cg** [comment]
resolved by https://github.com/bigskysoftware/htmx/issues/1539 thank u @alexpetros!
