### ISSUE TITLE
best way to trigger JS to focus an input text field that was newly swapped in

### ISSUE THREAD

**Issue by ptrthomas** [bigskysoftware/htmx#154]
this seems to be a common use case. 

so I have a section of the page swapped with multiple elements that can include multiple `<input>` fields

but I want to focus only one of these fields, i.e. the cursor should be within a specified text field, and positioned after any text value that may be present

I'm finding it hard to figure out the best way to achieve this, I know `afterSettle` may be involved: https://htmx.org/events/#htmx:afterSettle

do suggest what you think would be the best / most elegant way to handle this

**Comment by ptrthomas** [comment]
I figured out one possible approach which may be a massive hack, but posting here in case it helps others and for feedback. I also feel a built-in way to "post process" some JS after a swap would be a nice addition to htmx

so in the HTML chunk returned, my server-side templating adds a `<script>` tag like this. this just needs to be added at the end of all the HTML, and it won't appear on the page

```html
<script id="afterSettle">document.querySelector('#todo2').focus()</script>
```

and all that remains is to do an `eval()` on it. this event handler set up at the root page level does the trick:

```js
      htmx.on("htmx:afterSettle", function (evt) {
        var el = document.getElementById('afterSettle');
        if (el) {
          Function('"use strict";return (' + el.innerHTML + ')')();
        }
      });
```

do you think a built-in way to `eval()` pre-JS and post-JS sent similar to an out-of-band HTML snippet would be a feature request worth considering ?

**Comment by benpate** [comment]
I'd vote for `eval()`-ing any `script` tags in the swapped content.  If performance is a consideration, then perhaps it could be put behind another tag, for example, `hx-script="true"`

I think this would be simpler than adding before/after logic, and less overhead than having to make another magic script id to be baked in to the library.

**Comment by clarkevans** [comment]
Lacking any experience with htmx, doing an `eval` of script tags seems like a simple solution.  It has the nice advantage of keeping the code local to the widget that constructs the corresponding HTML.  Would the <script> tag remain in the DOM, or would it be removed?  Is there a way for the script to get the `id` of the element that was swapped, or must user code keep track of this?  Is there a need for `afterSettle` (simpler is better), are there any reasons why the script would need to run before the swap? What sort of nasty edge cases can we think of?

**Comment by ptrthomas** [comment]
@clarkevans I have been using this in a sample app.

> nice advantage of keeping the code local to the widget that constructs the corresponding HTML

totally agree

> Would the <script> tag remain in the DOM, or would it be removed?

it doesn't need to be removed. it actually won't be auto-eval-ed by default, and helps for troubleshooting. I would leave it in

> Is there a way for the script to get the id of the element that was swapped, or must user code keep track of this?

personally I think a "magic id" is fine. we are talking only one HTML swap at a time. the JS can do multiple things if needed. if htmx can detect any incoming script tag and auto-eval it, I think that is the ideal solution as @benpate  mentioned. BTW I have even more interesting use-cases in mind, a widget should be able to "lazily" contribute CSS and JS to the `<head>` - I'm curious if any thing like this is possible in htmx today

> are there any reasons why the script would need to run before the swap?

personally I would design this. one use case could be animation or advanced "spinner" implementations. or maybe setting up a websocket / SSE connection

> What sort of nasty edge cases can we think of?

can't think of much other than an eval error

**Comment by benpate** [comment]
HTMX has mechanisms for spinners when waiting for something to load over the network.  Though it doesn't have that for setting up a web socket connection, it could be added if necessary.  You can set up a dynamic WebSocket/SSE declaratively when HTMX swaps in the partial markup sent back by the server.  This part works great -- although I think there's still some work to be done in *disconnecting* a WebSocket/SSE when its root node is swapped out.  I still need more research here.  

I think this is my long-winded way of saying that I'd look into other ways to add "before" code into the call.  That would mean that any javascript included along with a partial HTML could just run "after" it's loaded, and we wouldn't need the distinction, and we could keep the API as simple as possible.

**For nasty errors and edge cases**, `eval()` potentially opens up security issues inside of HTMX.  Although it's a relatively low risk, I'd suggest we find some sort of "safe eval" to implement.  I know (for example) Angular had some mechanism for this, so it should be simple to research.

I agree with @ptrthomas, adding CSS sounds like a similar situation that we could explore here.  From work in other environments, I think that browsers automatically use any CSS you dynamically add to the DOM, but the same is not true for Javascript.  Either way, it would be nice to do some experiments and see how HTMX could make both of them "just work."

**Comment by benpate** [comment]
I've done a little digging on this, and HTMX already has a function called `processScripts` that does what we're looking for.  It's even called after several kinds of swaps.  So, it looks like this feature is already intended to work.  However, I'm not getting a simple alert() to fire in my tests, so something is not wired up correctly (and that "something" could still by my lack of understanding inside the HTMX code)

One more thing, the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!) recommends using `window.Function` instead of eval, which executes the new function in the global scope, and may even run a bit faster.  This sounds like the default behavior we'd want anyway, so I'll recommend using that.

[I'm putting together a pull request](https://github.com/benpate/htmx/tree/processScripts) but won't submit it until I've figured out how the existing `processScripts` function is supposed to work, and why it's not already firing in my tests.

Suggestions welcome :)

**Comment by benpate** [comment]
Sorry to be a spammer, but I re-read your original comments, and remembered the standard HTML `autofocus` attribute that should solve your problems.  Currently, this doesn't work with an HTMX swap, but I made a pull request that should address this issue.  Just add "autofocus" to your input element, and HTMX keeps it in the spotlight when it swaps in.  🍺

**Comment by ptrthomas** [comment]
> Just add "autofocus" to your input element, and HTMX keeps it in the spotlight when it swaps in. 

that certainly sounds like the best option, thanks @benpate - I hope it will "override" any `autofocus` instances that may be present in the DOM

**Comment by benpate** [comment]
Yes, it should.  It there are any other nodes still in the DOM that have “autofocus”, they should have already gotten their chance to be focused.  The pull request just scans the NEW content for the first “autofocus” attribute it can find.  If there are any, then it calls `.focus()` on it.  

Check it out, then nag @1cg to merge it 😉

**Comment by 1cg** [comment]
OK, I'm gonna go ahead and merge this and I'll add tests.

**Comment by 1cg** [comment]
merged and tested:

https://github.com/bigskysoftware/htmx/commit/278b5f119645ef1d7a49c0db6338b3be43c513c5
