### ISSUE TITLE
Question: Session cookies when using HTMX

### ISSUE THREAD

**Issue by mborus** [bigskysoftware/htmx#1558]
Is there a recommended way of using session cookies (and resetting a session) using HTMX?

I'm trying to write a multi page application with HTMX but lack a way to linking the pages together with a session ID that survives a mixture of GET and POST requests and resets once you return to the first page.

**Comment by Telroshan** [comment]
I would say, simply do it the easy way:
- Generate a session ID on your backend
- Save it in a database _(you can map that to a User ID to make an authentication)_
- Instruct your client to store it as a cookie using a [Set-Cookie](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1) header
- Then, on your backend, check whether the incoming requests (whether they are GET, POST or any other method) passed a session cookie or not, and use it to identify your client

Notice how, in the process described above, htmx doesn't have anything to do. You could do the exact same process using vanilla JS or any other lib that is similar to htmx.
You don't need a JWT, but you could totally use one if you want, in which case you'll just have to adjust your backend, but the process of storing a cookie remains the same, and htmx doesn't have to care about it.

As for resetting the session, you could
- Add a route to your backend to clear the session (thus removing the ID from the database), which would invalide the cookie value for any future request
- Add [1 line of handwritten JS](https://stackoverflow.com/a/23995984/12742595) to clear the cookie _(though the session ID would persist in the database)_

Hope this helps!

**Comment by mborus** [comment]
Thanks. This approach works so far that after setting the cookie like this
    function setSessionCookie(session_id) {
        // alert("cookie " + session_id);
        document.cookie = "session_id=" + session_id + "; path=/;";  
    }

The cookie is sent on each following htmx request, so I can react to it.

**Comment by luist1228** [comment]
@mborus Be careful using session cookies that way, you shouldn't use the browser cookie because it exposes your session data to  Cross Site Scripting (XSS) attacks, as @Telroshan said your backend should handle the session with secure cookies, that way your backend can send the correct HTML according to the session you got within your db

**Comment by mborus** [comment]
@luist1228, @Telroshan Thanks for the session header recommendation - it looks like a good suggestion. 

I generate the session IDs on the server and store them in a local database. 

My original question was about how to get that generated session ID to be sent with each next request. (There was no mention of this in the HTMX docs on how to do this because probably "everyone knows how to do it", on the HTMX discord the recommendation was to just use JavaScript)

After conferring about your answer with ChatGPT, it seems that there's something like a "HttpOnly Attribute" way to send cookies so that JavaScript can not see them. Is this what you mean by "secure"?
Like sending a header "Set-Cookie: session_id=your_generated_session_id; HttpOnly; Path=/"
