### ISSUE TITLE
How to trigger refresh on element after another request changes data

### ISSUE THREAD

**Issue by jsantari** [bigskysoftware/htmx#156]
I have a div with hx-get="/main" hx-trigger="load". I am wondering how I can trigger the load on that div after I've made a change to the data that originally populated the div.

**Comment by benpate** [comment]
Check out [`hx-swap-oob`](https://htmx.org/attributes/hx-swap-oob/).  It may not be exactly what you're looking for, but I think it may do the trick.  Put this attribute in one DIV in the server-generated code that you return to HTMX as a partial page.    That DIV will be swapped into your original page separately from the original request, and can be used to update another part of your document.

For a more advanced situation, you might look in to using [Hyperscript](https://hyperscript.org/) to hook in to HTMX's event handlers.  I don't have much experience with that, but I know it's another option.

Does this answer your question?  If so, close the issue so we can keep the list clean -- and, if not, help me understand the use case you're trying to solve, and I'll try to dig more :)

**Comment by jsantari** [comment]
hx-swap-oob would work but it makes it more difficult on the server side. I resolved this through an Discord discussion which started on 8/6/20 - I created a htmx plugin script to listen for a custom event that gets htmx to re-trigger multiple element requests.

**Comment by 1cg** [comment]
@jsantari the `hx-trigger` attribute supports multiple events, so you could have something like:

```html
<div hx-trigger="load, myCustomEvent" hx-get="/whatever"> ... </div>
```

And then trigger the event programmatically.

Alternatively, you might look at the `path-deps` extension, if that mechanism captures what you want:

https://htmx.org/extensions/path-deps/
