### ISSUE TITLE
changed + from in hx-trigger

### ISSUE THREAD

**Issue by Telroshan** [bigskysoftware/htmx#1565]
Using `changed` along `from` in [`hx-trigger`](https://htmx.org/attributes/hx-trigger/) seems to have an unexpected behaviour.

Given the following code (you can also play it in [this JSFiddle](https://jsfiddle.net/7ygfa9zn/)):
```html
<form hx-get="/search" hx-target="#result" hx-trigger="keyup changed delay:250ms from:#searchInput, change">
  <label>Search <input id="searchInput" class="flex-grow" type="search" name="search"></label>
  <label>Category <select name="category">
      <option value="A">A</option>
      <option value="B" selected>B</option>
      <option value="C">C</option>
    </select>
  </label>
</form>
```
You can see here how the request isn't triggered when typing in the input, only when the `change` event is fired _(which happens in my case, when focusing out the input)_

it _seems_, that `changed` is checked for the form itself, not for the element that triggered the request using the `from` modifier.

I would naively expect htmx to check if the value changed, for the element that triggered the event, not on the element that declares hx-trigger.

A convoluted example I'll admit, but just to showcase the issue more clearly, on [this JSFiddle](https://jsfiddle.net/bxmj3czo/)
```html
<label>Defines Hx-trigger <input type="text" hx-get="/search" hx-trigger="keyup changed delay:250ms from:#searchInput" hx-target="#result" hx-include="#searchInput"></label>
<label>Type in to search <input id="searchInput" type="search" name="search"></label>
```

You can see here how, typing in the second input, has no effect, **unless** you modified the value of the first input first.

Such a setup _(the first one, not the second one which directly comes from hell)_ seems common to me as it basically comes down to factoring the hx-get/trigger/swap on a single root element, and having multiple children trigger it differently without specifying hx-get/trigger/swap on every single one of them.

**Comment by 1cg** [comment]
long standing issue, thank you for working on it!

**Comment by dev-SR** [comment]
Using `input` and `change` together worked for me:

```python
<form hx-get="{% url 'index' %}"
        hx-target="#product_list"
        hx-trigger="input change">
    <input type="text" name="search" id="search">
    <select name="category" id="category">
        <option value="">All</option>
        {% for category in categories %}<option value="{{ category.id }}">{{ category.name }}</option>{% endfor %}
    </select>
</form>
```
