### ISSUE TITLE
Active-search example partially incompatible with Firefox

### ISSUE THREAD

**Issue by xSke** [bigskysoftware/htmx#1569]
The [active-search](https://htmx.org/examples/active-search/) example includes the following paragraph:

> Since we use a `search` type input we will get an `x` in the input field to clear the input. To make this trigger a new `POST` we have to specify another trigger. We specify another trigger by using a comma to separate them. The `search` trigger will be run when the field is cleared but it also makes it possible to override the 500 ms delay on `keyup` by just pressing enter.

However, both the `x` in the input field, and the ability to override the delay by pressing enter, seem to be Chrome-specific behavior.

While `type="search"` is standardized, it's supposed to behave equivalently to a `type="text"`. And the `search` event is, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event), also non-standard and should not be relied on.

It may be worth either redoing this example in a browser-compatible way, or at least adding a line to the page saying a lot of the functionality only works in Chrome.

**Comment by alexpetros** [comment]
> It may be worth either redoing this example in a browser-compatible way, or at least adding a line to the page saying a lot of the functionality only works in Chrome.

Both of these are reasonable, feel free to submit a PR.

**Comment by alexpetros** [comment]
On second thought, let's just fix the example.
