### ISSUE TITLE
Use kebab-case for event names

### ISSUE THREAD

**Issue by vmsp** [bigskysoftware/htmx#157]
I can't use alpine to listen for htmx's events since `@htmx:afterSettle` becomes `@htmx:aftersettle` in HTML. More details in [Vue's documentation](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names).

**Comment by jreviews** [comment]
@vmsp The latest version of Alpine supports namespaced, camelCase events

```
@htmx:after-settle.camel
```

**Comment by 1cg** [comment]
In dev we now dispatch events in both camel case as well as kebab case:

https://github.com/bigskysoftware/htmx/commit/c3b1c63484cbee1618b1b59cee639015d9bc6421

Will be included on the 0.1 release, hopefully by the end of the month
