### ISSUE TITLE
How to trigger toastify notifications?

### ISSUE THREAD

**Issue by turbopixel** [bigskysoftware/htmx#158]
Hello there,

after a successfull/failed request, how can I trigger JavaScript functions? In my case, I want to call `Toastify()` [1]
I didn't find something about this.

[1] https://github.com/apvarun/toastify-js

**Comment by benpate** [comment]
HTMX triggers a number of custom events on the `document.body`.  I think you're looking for [afterSwap](https://htmx.org/events/#htmx:afterSwap).

```
document.body.addEventListener('htmx:afterSwap', function(evt) {
    // do the thing.
});
```

This also seems similar to #154 where we're discussing executing `<script>` tags embedded in swapped data.  Maybe put your +1 on that, as well?

**Comment by benpate** [comment]
Heads up, it looks like you can put scripts directly in your partial HTML code.  Right now, you just need to include a `type="text/javascript`element in the script tag.  Hope this helps :)
