### ISSUE TITLE
Cannot install 1.9.3 with Node 20 (maybe anything other than 15?) whereas 1.9.2 was not a problem

### ISSUE THREAD

**Issue by violuke** [bigskysoftware/htmx#1584]
Using Node 20, try to install the latest version of htmx (I'm using Yarn).

I don't know really, but maybe this is an accidental consequence of the GitHub Action CI stuff?

```
error htmx.org@1.9.3: The engine "node" is incompatible with this module. Expected version "15.x". Got "20.4.0"
error Found incompatible module.
```

Thanks.

**Comment by alexpetros** [comment]
Yes, that's what happened, it has to do with the `package.json` engine. I'll get that fixed. 

In the meantime, you should just be able to install it by adding `--force` to npm: https://docs.npmjs.com/cli/v9/using-npm/config#engine-strict

**Comment by violuke** [comment]
Thanks. We cannot easily add the `--force` flag due to our CI/CD process, to be honest, so will have to wait for the next release. Thanks so much for picking this up so quickly.

**Comment by alexpetros** [comment]
Understood, and apologies for the churn.

**Comment by 1cg** [comment]
thanks @alexpetros will be fixed in the next release (I hope late this week or early next)
