### ISSUE TITLE
Response Target extension does not correctly set "shouldSwap"

### ISSUE THREAD

**Issue by szepeviktor** [bigskysoftware/htmx#1598]
https://github.com/bigskysoftware/htmx/blob/6336ad61138df3851c03b90bee66edb170001aec/src/ext/response-targets.js#L86

"Should" is missing the letter `l`.

From https://github.com/bigskysoftware/htmx/pull/1590#discussion_r1265543726

**Comment by alexpetros** [comment]
This is probably a bug, which means we also need a test to catch it.
