### ISSUE TITLE
response-targets ext not working to handle http status 500

### ISSUE THREAD

**Issue by fahmifan** [bigskysoftware/htmx#1612]
I try to handle 400 & 500 http status code, but it didn't work. Is there something I missed?
I try to response with http code 400 & 500 from backend, but neither worked

Here is the network console screenshot
<img width="906" alt="image" src="https://github.com/bigskysoftware/htmx/assets/19581621/2d5be76f-052e-44e6-ac33-47a3d37c5e3e">

Here is my code
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commurz</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">

    <script src="https://unpkg.com/htmx.org@1.9.3/dist/htmx.min.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.9.3/dist/ext/response-targets.js"></script>
</head>
<body>
    
    <form>
        <label for="email">Email</label>
        <input type="text" name="email" id="email">

        <button type="button" hx-post="/users"
            hx-target="#list-users"
            hx-target-5*="#internal-error"
            hx-target-4*="#internal-error"
            >
            Create
        </button>

        <span id="internal-error"></span>

        <table>
            <thead>
                <tr>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody id="list-users">
            </tbody>
        </table>
    </form>
</body>
</html>
```

**Comment by alexpetros** [comment]
@siefca is correct, you need to enable the extension. Let me know if you still have problems.

**Comment by fahmifan** [comment]
Very cool, thats worked. I missed the doc on [extension](https://htmx.org/extensions/) and jumped directly here https://htmx.org/extensions/response-targets/. Thanks, I'll closed this issue

**Comment by CONSTANTlNE** [comment]
had exact same problem for exact same reason, solved !   I applied hx-ext="response-targets" to body tag , thank you all

**Comment by fyaacobseek** [comment]
I was using both `loading-states` and `response-targets` extensions and hit the same issue. This is how you define multiple extentions in the same hx-ext attribute

```
hx-ext="loading-states,response-targets"
```

**Comment by sdil** [comment]
I was using both loading-states and response-targets extensions and hit the same issue. This is how you define multiple extentions in the same hx-ext attribute

hx-ext="loading-states,response-targets"
