### ISSUE TITLE
Failed listen to new loaded button

### ISSUE THREAD

**Issue by liuxiawei** [bigskysoftware/htmx#1616]
I loaded another page from one page, which created a table using tabular.js in the loaded page. Each row of the table has a button, and I hope to use this button to load new content in the "div" element with the ID "content" in the loaded element. However, I found that the buttons in each row of the table generated by tabular.js were not being listened to by htmx in the newly loaded page. I don't know if there is a way to re-listen or if this is a bug.
The part code of the tabular.js. It's right when use onclick to triger
```
        {
        "field": "id",
        "title":"Detail",
        frozen:true,
        headerSort: false,
        "formatter": function(cell, formatterParams, onRendered) {
            return '<button class="btn btn-primary btn-xs" hx-get="/detail?gene_id='+ cell.getValue()+'" hx-target="#search_result" >More</button>'
		},
        },
```

**Comment by Telroshan** [comment]
Hello, content added to the DOM outside htmx attributes / ajax function, will not be automatically process them.
You can use [htmx.process](https://htmx.org/api/#process) which is designed for such situations
> Processes new content, enabling htmx behavior. This can be useful if you have content that is added to the DOM outside of the normal htmx request cycle but still want htmx attributes to work.

**Comment by liuxiawei** [comment]
Thanks！ It help a lot！
&nbsp;


刘照宇
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年7月20日(星期四) 中午1:39
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bigskysoftware/htmx] Failed listen to new loaded button (Issue #1616)





 
Hello, content added to the DOM outside htmx attributes / ajax function, will not be automatically process them.
 You can use htmx.process which is designed for such situations
  
Processes new content, enabling htmx behavior. This can be useful if you have content that is added to the DOM outside of the normal htmx request cycle but still want htmx attributes to work.
