### ISSUE TITLE
This never happened before. What is wrong here? does it not support node 20

### ISSUE THREAD

**Issue by code-kasha** [bigskysoftware/htmx#1621]
npm WARN EBADENGINE Unsupported engine { npm WARN EBADENGINE   package: 'htmx.org@1.9.3', npm WARN EBADENGINE   required: { node: '15.x' }, npm WARN EBADENGINE   current: { node: 'v20.3.1', npm: '9.7.2' } npm WARN EBADENGINE }

**Comment by alexpetros** [comment]
Closing as a duplicate of: https://github.com/bigskysoftware/htmx/issues/1584
