### ISSUE TITLE
Triggering via XH-Trigger header doesn't work with delay

### ISSUE THREAD

**Issue by kg-currenxie** [bigskysoftware/htmx#1637]
Adding the header via the response:
![image](https://github.com/bigskysoftware/htmx/assets/48229166/8425d983-3332-4369-ac8a-806bd45f2a93)
![image](https://github.com/bigskysoftware/htmx/assets/48229166/7ef50c18-a09a-41eb-9555-94e85961e55e)

Then I assume this would work:
```
<div hx-get="/example" hx-trigger="myEvent delay:5s from:body">
  Triggered by HX-Trigger header...
</div>
```

But nothing is triggered. I have to do this:
```
<div hx-get="/example" hx-trigger="myEventFromJs from:body">
  Triggered by HX-Trigger header...
</div>
<script>
  document.body.addEventListener('myEvent', function (evt) {
    setTimeout(function () {
      document.body.dispatchEvent(
        new CustomEvent('myEventFromJs', {
          detail: { foo: 'bar' },
        }),
      )
    }, 5000)
  })
</script>
```

**Comment by matiboy** [comment]
Hi @kg-currenxie thank you for opening this issue;
I've tried to reproduce your issue [in this codepen](https://codepen.io/matiboy/pen/MWzzqbo) but it appears to be working as expected; when `HX-Trigger` is set in headers to `myEvent`, it does trigger the `hx-get` of the "delay" element.

Please have a look. Hope this helps

**Comment by esmiralha** [comment]
Can't reproduce it wither. Can the issue be closed?

**Comment by Telroshan** [comment]
> is the trigger case sensitive? seems our server re-formats the header to Hx-Trigger :|

Headers are case insensitive:
- See the case insensitive regex used to check the header's existence [here](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3285)
- Htmx is then using [XMLHTTPRequest.getResponseHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader) which is also case insensitive

**Comment by kg-currenxie** [comment]
Ok thanks :) Well, then I don't know why it wasn't working for me, but since the codepen is, we can close this.
