### ISSUE TITLE
Does processPolling() leak?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#164]
I'm digging deeper into the HTMX's internals, and am coming up with some questions.  I'm going to post them here as issues, but feel free to simply delete them if they're not appropriate for this forum.

It looks like the `processPolling()` function sets up a timeout to repeatedly check a remote URL (yay!) and it also verifies that the original `elt` node is still in the DOM before continuing.  However, it doesn't look like there's any way to remove the timeout if the original node has been removed.  It's not a huge deal, but it does mean leaving other code running in the background of a page indefinitely.

I'm [putting together a PR](https://github.com/benpate/htmx/tree/pullrequest-serverSentEvents-redesign-withMultipleEvents) that keeps track of other event listeners (right now, just SSE's, and hopefully WebSockets in the future) that might fit this nicely.  If that works out, then this ticket could be a placeholder for migrating `processPolling` into that structure, too.

Thoughts?

**Comment by 1cg** [comment]
>  However, it doesn't look like there's any way to remove the timeout if the original node has been removed

If the node that is polling is removed, then the next time the timer fires `bodyContains(elt)` should fail, which will cancel the polling.  

I *think* that should handle this:

>  However, it doesn't look like there's any way to remove the timeout if the original node has been removed

unless I'm misunderstanding you.
