### ISSUE TITLE
Bug: Response Header `HX-Retarget` cause classList error, when `hx-target` attribute works fine

### ISSUE THREAD

**Issue by AjaniBilby** [bigskysoftware/htmx#1640]
I have a normal `a` tag link:
```jsx
<a
	href={"/server"}
	hx-get={"/server"}
	hx-push-url={"/server"}
	hx-headers='{"hx-headless": "true"}'
>{contents}</a>
```

This request's response has the following headers:
![image](https://github.com/bigskysoftware/htmx/assets/11359344/0e0e6511-6e05-402c-bab4-7c19a6949509)

When this request is recieved I get the following error:
![image](https://github.com/bigskysoftware/htmx/assets/11359344/c0819da1-c477-44a8-b7f4-3f18caac5b77)

If I then remove the `HX-Retarget` header from my response and add the exact same value as an attribute of my `<a>` for `hx-target`, I however get no errors, and it behaves correctly - however I want to be able to use `HX-Retarget` for some clever server side dynamic swapping.

Interestingly if I intentionally give an invalid id as the retarget (as in an ID that does not exist in the current HTML) I get this error - which is very interesting that it's a completely different from the error I'm actually seeing.
![image](https://github.com/bigskysoftware/htmx/assets/11359344/67ae179d-9bf8-434c-838c-cecbce21f38f)

I'm not sure of the best way to debug for diagnose this issue, nor if it is a fault with htmX or something I'm doing wrong.

**Comment by matiboy** [comment]
This seems to happen if HX-Retarget contains "closest" but not if it is just the ID as seen[ in this reproduction code pen](https://codepen.io/matiboy/pen/MWzzvPQ)

Will investigate further on other "keywords"

**Comment by matiboy** [comment]
Actually the documentation doesn't mention that HX-Retarget allows for the use the modifiers that hx-target attribute does. It says:

> A CSS selector that updates the target of the content update to a different element on the page

and the code is [indeed straight CSS selector;](https://github.com/bigskysoftware/htmx/blob/61945431aa72d44f244ecf69b5d188796bc0b7e5/src/htmx.js#L3298) so "closest" won't work on the headers.

This should probably be relabeled from Bug to Feature Request if you feel it should be implemented

**Comment by AjaniBilby** [comment]
Ahh, okay my bad - somewhere along the way I assumed it would behave the same as `HX-Reswap` compared to `hx-swap`.
And since I am using a unique id anyway I can just remove closest and get the functionality I need.

Though ideally I feel like since `HX-Reswap` is just a server side override of `hx-swap`, I feel like `HX-Retarget` should be a server side override for `hx-target` for api consistence. But it's also not a feature I need

**Comment by matiboy** [comment]
I see your point and it may be useful to have HX-Retarget be able to take in modifiers and behave more like hx-target.

I've created a PR draft proposing the feature and if the maintainers feel like this could be useful, I'll complete it with tests/documentation.
