### ISSUE TITLE
Refactor: common function for swapping in content?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#165]
I'm digging into the code base in order to fill out the `hx-sse` functionality and bring it up to par with `hx-get` and friends.  But, I'm really struggling with the many options available to modify swapping in content.  It's awesome.  But it's also too much for me to try to replicate without breaking a million things.

I think I'm asking for help from @1cg (or other developers who are more familiar than I am) to make a function that takes a DOM element and a new chunk of text and does something like this:

```javascript
function handleContent(elt, text) {

    // Identify the correct target
    // Handle hx-swap-oob statements
    // Handle hx-select options
    // Cursor management
    // Swap in new content
    // Close orphaned event listeners watching removed content
    // Settling timers and CSS class changes
}
```

Right now, the existing code works great but is spread across several locations, including embedded in the `xhr.onload` event handler, which means that I can't call it directly when we receive an SSE or WebSocket message.  This new centralized function could be called from at least three places in the codebase -- XHRs, SSEs, and WebSockets -- providing a unified, and powerful set of features across the board.

I would usually take a first pass at something like this myself, but I'm certain that I'd break some kind of edge case and do more harm than good.  Help?

**Comment by tomberek** [comment]
I’ve got the beginnings of this function here:
https://github.com/tomberek/htmx/blob/sse_multipleevents/src/htmx.js#L558

**Comment by benpate** [comment]
That looks beautiful!  I'll try starting with that.  

There are a few more things I think the fn needs to do -- for instance, looking up the `swapSpec` and `target` from the root element -- but those are pretty minor.  If it works well in the SSE code, then we can try (gingerly) to use it with WebSockets or back-port it into the AJAX handlers, too.
