### ISSUE TITLE
[Proposal] Github issue template

### ISSUE THREAD

**Issue by matiboy** [bigskysoftware/htmx#1651]
Without getting into really complex Github issue templates, it may be useful to have at least a bit of info when people open issues? Also adding a ready to use codepen would help a lot, and I feel that mainly people find it scary to do (or troublesome).

Would love to hear your thoughts.

Specifically about the Codepen, I've noticed a few issues being created where backend stuff is presented as screenshots from Chrome dev tools.
It may not be obvious to many that `sinon.js` in a codepen can easily mock server responses. 

Maybe a simple (not overwhelming) Github issue template could be:

1. Type: Bug/Feature request/Docs...
2. HTMX version
3. Have you tried creating a codepen? Use this [template for quick setup](https://codepen.io/matiboy/pen/XWyyPjz); it even mocks backend responses too

This points to a Codepen template which has the sinon server set up, latest htmx and hyperscript available if needed

**Comment by Telroshan** [comment]
I like the idea! Adding some template to homogeneize issues can't harm anyone, and would probably greatly help the maintainers

There is also https://demo.htmx.org/ available, that sets up htmx & hyperscript + URLs mocking, letting you add HTML dynamically using a `template` tag, looks [like this](https://jsfiddle.net/c42roaxf/) using your example's code:

```html
<script src="https://demo.htmx.org"></script>

<button hx-get="/demo" hx-target="#outcome">Click me</button>
<button hx-get="/demo" _="on click toggle .red on me">Hyperscript available</button>
<div id="outcome"></div>

<template url="/demo">
  Result
</template>
```

Btw, I don't know if that demo script is mentioned/documented though, except [that Twitter post](https://twitter.com/htmx_org/status/1662090274774953984) where I found out about it
