### ISSUE TITLE
Sanitizing/formatting form values before sending?

### ISSUE THREAD

**Issue by kg-currenxie** [bigskysoftware/htmx#1665]
We have a case with inputs that are auto-formatted while you type
![image](https://github.com/bigskysoftware/htmx/assets/48229166/f803e44e-0617-4c47-a989-e9c22cccdc09)

Which sends the comma in the request, which is not so nice:
![image](https://github.com/bigskysoftware/htmx/assets/48229166/b768160f-fb1c-4892-9d8c-0bd0637bd40b)

The only way I found was this
```
<script>
  window.addEventListener('load', function () {
    htmx.on('htmx:beforeSend', function (event) {
      const params = event.detail.requestConfig.parameters
      params.sellAmount.replace(/,/g, '')
    })
  })
</script>
```

Is there any way other way of manipulating form values, or is this it?

Input:
```
<input
  type="text"
  id="sellAmount"
  name="sellAmount"
  hx-get="/example/quote"
  hx-trigger="change delay:500ms, keyup changed delay:500ms"
  hx-include="[name=sellCurrency]"
  hx-target="#buyAmount"
  hx-vals='{ "side": "sell" }'
/>
```

**Comment by andryyy** [comment]
Perhaps a little bit shorter:

```
<form hx-on::config-request="event.detail.parameters.sellAmount.replace(/,/g, '')">
```

Untested and written from a stupid mobile.

**Comment by kg-currenxie** [comment]
Thanks :) I see, I'll try that.. but I guess manipulating the event details is the "only" way to go?

**Comment by andryyy** [comment]
Hmm, there are probably a few. But I can’t think of an easier HTMX way.

You may also create a function in JS that replicates the input text into a hidden field that is updated to reflect the value as Int.

As you seem to have a function to add punctuation anyway, this might be a cleaner approach.

**Comment by matiboy** [comment]
@kg-currenxie You could have your `hx-vals` do the cleanup. Check[ this codepen](https://codepen.io/matiboy/pen/JjexmxQ)

Basically:

```
hx-vals='js:{"side":"sell","amount":compileData()}
```
and define your compileData as

```js
function compileData() {
  return document.getElementById("sellAmount").value.replace(/,/g, '')
}
```

**Comment by andryyy** [comment]
Oh, that’s also nice.

**Comment by kg-currenxie** [comment]
Ah the `js:` trigger, smart :) I think that's good enough for us :) 
Couldn't make `hx-on::config-request` work, but thank you both :)

**Comment by andryyy** [comment]
> Ah the `js:` trigger, smart :) I think that's good enough for us :) 
> 
> Couldn't make `hx-on::config-request` work, but thank you both :)

Are you using the latest HTMX? It was only recently added. But sure, you are welcome.

**Comment by kg-currenxie** [comment]
"htmx.org": "^1.9.3"
1.9.4 is from 9 days ago, was it that recent? :D

**Comment by andryyy** [comment]
Yes! I think it’s a feature of the very, very recent version. 😄

**Comment by andryyy** [comment]
> Yes! I think it’s a feature of the very, very recent version. 😄 

Indeed, at least this used syntax. 

https://github.com/bigskysoftware/htmx/pull/1489
