### ISSUE TITLE
Scroll Event Throttling

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#168]
I'm running into a situation where `hx-trigger="revealed"` is breaking if I scroll through elements too quickly.  I think it's in part because multiple onscroll events are overlapping each other.  I'll do more digging before I say I have a good handle on the issue, though.

Here's an article that presents [an alternate way of handling scroll events](https://www.benmarshall.me/attaching-javascript-handlers-to-scroll-events/).  Basically setting a flag to guarantee that only one event handler is running at any given time.  There may be better ways to handle this, but it's a good start.

**Comment by benpate** [comment]
I included [code to address this issue ](https://github.com/bigskysoftware/htmx/pull/169/commits/2f0854e65b180c726fb4b31fe03674976c4e7eca) in #169.  It could easily be turned in to its own PR, if we decide not to merge the original PR.

**Comment by 1cg** [comment]
Ah, that explains that code.

Yes, please pull that out to a separate commit.

**Comment by benpate** [comment]
Done.
