### ISSUE TITLE
CustomEvent works only with hx-on deprecated form

### ISSUE THREAD

**Issue by apapsch** [bigskysoftware/htmx#1683]
This example works:

```
<p id="foo" hx-on="bar: alert(event.detail)">baz</p>
<script src="https://unpkg.com/htmx.org@1.9.4"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const foo = document.querySelector('#foo');
    foo.dispatchEvent(new CustomEvent('bar', {detail: 'fnord'}));
});
</script>
```

Changing to the new hx-on form renders it non-working:

```
<p id="foo" hx-on::bar="alert(event.detail)">baz</p>
```

**Comment by matiboy** [comment]
Hi @apapsch , I believe "::" is meant for `htmx` events, so `hx-on::bar` would be equivalent to `hx-on="htmx:bar: ...`
Using `hx-on:bar` should work though as [seen in this codepen](https://codepen.io/matiboy/pen/wvQbvZP) (click on "baz")

**Comment by apapsch** [comment]
OK, thanks for the pointer.
