### ISSUE TITLE
getInputValues does not adhere to the HTML spec about "Constructing the form data set"

### ISSUE THREAD

**Issue by ctheune** [bigskysoftware/htmx#1686]
I was noticing a misbehavior in an existing app both on HTMX "native" actions as well as boosted forms.
I am using [Peppercorn](https://docs.pylonsproject.org/projects/peppercorn/en/latest/) to serialize/deserialize complex form structures. Peppercorn relies on the form data set according to the specification (and historically properly implemented by all browsers): https://www.w3.org/TR/2011/WD-html5-20110405/association-of-controls-and-forms.html#constructing-form-data-set

Unfortunately `getInputValues` does not properly implement this. The first step here is that `getInputValues` uses an object instead of the list of (name, value) tuples that the specification prescribes:

> Let the form data set be a list of name-value-type tuples, initially empty.

I thought I could take a look at the HTMX code and implement proper behaviour, however, this seems to be a core data structure issue that likely will require a bit of discussion to fix, while - at the same time - being a complete blocker for me to use HTMX. :(

Note: This could also be relevant to pay attention to when dealing with #1323 and vice versa.

**Comment by ctheune** [comment]
I wanted to construct a test case, however, due to the impedance mismatch between list-of-tuples and object, that isn't feasible.

To reduce required external reading, here's the Peppercorn example that is in accordance with the HTML spec:

HTML:

```html
<form action="." method="post" enctype="multipart/form-data">
  <input name="name"/>
  <input name="title"/>
  <input type="hidden" name="__start__" value="series:mapping"/>
  <input name="name"/>
  <input type="hidden" name="__start__" value="dates:sequence"/>
  <input type="hidden" name="__start__" value="date:sequence"/>
  <input name="day"/>
  <input name="month"/>
  <input name="year"/>
  <input type="hidden" name="__end__"/>
  <input type="hidden" name="__start__" value="date:sequence"/>
  <input name="day"/>
  <input name="month"/>
  <input name="year"/>
  <input type="hidden" name="__start__" value="sex:rename"/>
  <input type="radio" name="sex1" value="male"/>
  <input type="radio" name="sex1" value="female"/>
  <input type="hidden" name="__end__"/>
  <input type="hidden" name="__end__"/>
  <input type="hidden" name="__end__"/>
  <input type="hidden" name="__end__"/>
</form>
```

Expected stream:

```python
[
('name', 'project1'),
('title', 'Cool project'),
('__start__', 'series:mapping'),
('name', 'date series 1'),
('__start__', 'dates:sequence'),
('__start__', 'date:sequence'),
('day', '10'),
('month', '12'),
('year', '2008'),
('__end__', 'date:sequence'),
('__start__', 'date:sequence'),
('day', '10'),
('month', '12'),
('year', '2009'),
('__end__', 'date:sequence'),
('__end__', 'dates:sequence'),
('__start__', ':ignore'),
('selectall', ''),
('__end__', ''),
('__end__', 'series:mapping'),
]
```


Stream I see:

```python
[
('name', 'project1'),
('title', 'Cool project'),
('__start__', 'series:mapping'),
('__start__', 'dates:sequence'),
('__start__', 'date:sequence'),
('__start__', 'date:sequence'),
('__start__', ':ignore'),
('name', 'date series 1'),
('day', '10'),
('month', '12'),
('year', '2008'),
('__end__', 'date:sequence'),
('__end__', 'date:sequence'),
('__end__', 'dates:sequence'),
('__end__', ''),
('__end__', 'series:mapping'),
('day', '10'),
('month', '12'),
('year', '2009'),
('selectall', ''),
```

**Comment by alexpetros** [comment]
Making sure I understand this properly: the proximate cause of the issue appears to be the `getInputValues` function, but the actual issue is that formdata isn't serialized over HTTP in the manner you're expecting?

**Comment by ctheune** [comment]
Yes, exactly. :)

**Comment by ctheune** [comment]
I did write some tests on my fork to prove the error and saw it being relevant in getInputValues AFAICT.

**Comment by Telroshan** [comment]
Hey, we switched to FormData internally for htmx 2, which now correctly preserves the values order (see test added in 01b292ada48f31276642b587eb67128367349701). We also introduced a FormData proxy object for retro-compatibility reasons, and proxy objects [aren't supported by IE11](https://caniuse.com/proxy), which htmx 1 will always support.
As htmx 2 is now available in beta and on the `dev` branch, I think we can close this issue now ; if you need form data, switch to htmx2 ! 😄
