### ISSUE TITLE
Are HX response headers case sensitive? 

### ISSUE THREAD

**Issue by cprosche** [bigskysoftware/htmx#1697]
I'm using go fiber, and setting a "HX-Redirect" header does not redirect the page, but it's getting changed to "Hx-Redirect"

Example:
Setting `c.Response().Header.Set("HX-Redirect", "/success")` doesn't redirect the page it's sent to, even with the request being 200.

**Comment by Telroshan** [comment]
Hello, headers are case insensitive:
- See the case insensitive regex used to check the header's existence [here](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3285)
- Htmx is then using [XMLHTTPRequest.getResponseHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader) which is also case insensitive
> Note: The search for the header name is case-insensitive.

So the problem must be elsewhere.
Could you add a screenshot of the request response maybe, just to make sure the `HX-Redirect` header is correctly sent by the server?

**Comment by matiboy** [comment]
@cprosche Additional to @Telroshan 's answer focused on the `htmx` side itself, I tried to reproduce your environment using go fiber. Below is the go file and if you run it, you'll see the header being indeed written as `Hx-Redirect` but the redirect does occur as expected:

```golang
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
)

func main() {
    app := fiber.New()

    app.Get("/", func (c *fiber.Ctx) error {
        c.Set("Content-Type", "text/html; charset=utf-8")
        
        return c.SendString("<script src='https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.4/htmx.min.js' integrity='sha512-ZM2vxgVBxhBI5Etj/c/qcJV+upate3VzbVQOQRCx1YGuyEX9dYdMh8pRUot4xIwtAay6QwRQC/FdXRjSWIEHrg==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><button hx-get='/test' >Click me</button>")
    })

    app.Get("/test", func (c *fiber.Ctx) error {
        c.Set("Hx-Redirect", "/redirected")
        return c.SendString("Redirecting...")
    })


    app.Get("/redirected", func (c *fiber.Ctx) error {
        return c.SendString("You have been redirected here")
    })

    log.Fatal(app.Listen(":3000"))
}

```

Dev tools show the upper cased header but also that we do get redirected to `/redirected`

![image](https://github.com/bigskysoftware/htmx/assets/487758/44e17eca-3016-415b-ae35-049e1703b646)

**Comment by cprosche** [comment]
You're test works for me too, it must be something in how I'm using it. Testing further.

**Comment by cprosche** [comment]
I think I was doing it before I had the htmx js loaded on the page, thanks!!
