### ISSUE TITLE
autofocus feature is not documented

### ISSUE THREAD

**Issue by wsantos** [bigskysoftware/htmx#1707]
autofocus is not documented is that expected? should it be called hx-autofocus?

https://github.com/bigskysoftware/htmx/blob/018ba7c2c2f4d99425dc2362e68e4cc6fc2803c5/src/htmx.js#L419

**Comment by Telroshan** [comment]
Hey, autofocus is actually a [standard attribute](https://developer.mozilla.org/docs/Web/HTML/Global_attributes/autofocus), htmx just ensures it works as expected when swapping in an element that has this attribute, hope that helps!

**Comment by wsantos** [comment]
all clear, thank you for the clarification.
