### ISSUE TITLE
Add hx-action attribute

### ISSUE THREAD

**Issue by yidispreiyidienterprises** [bigskysoftware/htmx#1708]
I was working on building an extension for htmx in order to make it able to toggle classes on the target rather than making an ajax request. I ended up succeeding (https://github.com/yidispreiyidienterprises/HTMX-Classify) but the way I managed to do it was by creating a fake get request and intercepting the error message for it. The problem was the htmx won't register an event (regardless of the trigger) unless there is a specified ajax request. We should be able to have custom actions without specifying an ajax request. This would make javascript a lot more minimalist and in line with htmx's mission. 
```js
        else if (name === 'htmx:load') {
            let elementsModified = false;
            document.querySelectorAll('[hx-classify]').forEach(function(el) {
                if (!el.hasAttribute('hx-get') && !el.hasAttribute('hx-post') && !el.hasAttribute('hx-put') && !el.hasAttribute('hx-patch') && !el.hasAttribute('hx-delete')) {
                    el.setAttribute('hx-get', '/noop-classify');
                    elementsModified = true;
                }
            });
            if (elementsModified) {
                htmx.process(document.body);
            }
        }
```
and then in the extension I would intercept the bad requests. 
```js
htmx.on('htmx:beforeRequest', function(evt) {
    const el = evt.detail.elt;
    if (el.hasAttribute('hx-classify')) {
        if (el.getAttribute('hx-get') === '/noop-classify') {
            evt.preventDefault();
        }
    }
})
```

This shouldn't be necessary. It would be amazing if htmx supported custom actions. 
so for example you should be able to specify `hx-action="ajax-get:/some-random-url"` and that would be equivalent to `hx-get="/some-random-url"`. The same funtionality should be possible for custom actions. for example, you should be able to specificy `hx-action="custom:randomJSFunction"` and htmx should pass the target element to the function. 
Another great use of this would be allow extensions to specify thier own actions. For example, in my case of `classify` I would be able to build the extension with registering a custom action that would be able to function as `hx-action="classify-add:random-new-class"`

**Comment by andryyy** [comment]
There is hx-on:anyEvent or hx-on::htmx-event-🐪-case

Blowing this up might not be cool for most users.

**Comment by YidiSprei** [comment]
oh, I'm so sorry, this is my first time commenting here. Wasn't sure how to do it. I'll look into that. Really appreciate it

**Comment by yidispreiyidienterprises** [comment]
oh, I'm so sorry, this is my first time commenting here. Wasn't sure how to do it. I'll look into that. Really appreciate it
