### ISSUE TITLE
Redirects & History

### ISSUE THREAD

**Issue by daaku** [bigskysoftware/htmx#171]
If a request results in a redirect, and `hx-push-url` is enabled, wouldn't it make sense to update the URL with the redirected URL?

A common example: `hx-delete` is used delete a resource, which then redirects to say the listing/index page. The URL should respect this no?

**Comment by 1cg** [comment]
Yeah, absolutely it should.

Last I looked though, that information wasn't readily available in the AJAX request in all browsers:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL

Looks like it only applies to IE now though.  Hmmm.

**Comment by 1cg** [comment]
OK, experimental implementation in dev:

https://github.com/bigskysoftware/htmx/commit/9c592d4e2fe6ec39438a2d07bde162fc9ea899bf

This should work on all platforms except IE, which will use the current behavior instead.  I'm OK w/ that.
