### ISSUE TITLE
Example of hiding and show a password input field

### ISSUE THREAD

**Issue by mammenj** [bigskysoftware/htmx#1713]
I was trying to create user login form with username and password field. I know with JavaScript I can change the input type to text or password to implement it. But is there a way to do this in htmx without JavaScript?

This is the script
 ```
function showPassword() {
            var x = document.getElementById("password1");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }

```

**Comment by matiboy** [comment]
Hi @mammenj 

[This codepen ](https://codepen.io/matiboy/pen/YzdXGqv) does what you're asking (the JS in the codepen is a mock server, not frontend). 

However, I would personally stick with the (likely) more simple JS version; you can even use[ htmx's locality of behavior](https://htmx.org/essays/locality-of-behaviour/) for clarity:

```html
<form hx-post="/save_password">
  <input type="password" name="password2" value="">
  <button type="button" hx-on:click="document.querySelector('input[name=password2]').setAttribute('type', document.querySelector('input[name=password2]').getAttribute('type')=='password' ? 'text' : 'password')">Toggle</button>
</form>
```

**Comment by mammenj** [comment]
Thanks @matiboy I appreciate your response. I agree LOB approach would be better if there's no better approach.
