### ISSUE TITLE
'Unsafe header' error in Chrome

### ISSUE THREAD

**Issue by tomwalkr** [bigskysoftware/htmx#173]
Chrome throws two errors on every XHR:
```
Refused to get unsafe header "HX-Trigger"  xhr.onload @ htmx.js:1500
Refused to get unsafe header "HX-Push"  xhr.onload @ htmx.js:1501
```

The errors are thrown on these lines:
```
handleTrigger(elt, this.getResponseHeader("HX-Trigger"));
var pushedUrl = this.getResponseHeader("HX-Push");
```

I tried with HTMX release and also with latest master. Chrome ver is 84.0.4147.135 (64-bit) Mac.

(Saw the previous issues #37 and #14 marked fixed, but this seems to have come back?)

**Comment by 1cg** [comment]
This is fixed in dev, should be available in the next release.
