### ISSUE TITLE
loading content in a modal window?

### ISSUE THREAD

**Issue by danielzzz** [bigskysoftware/htmx#175]
hello, 

is there any option (or a recommended practice) to manage data edition in a modal window?

thanks, dan

**Comment by 1cg** [comment]
Hi Dan,

Nothing really specific to modals in HTMX.  You can catch show and hide events and use those to trigger htmx requests if you'd like.

I tend to use modals less than I did in the past, and inline UIs more now.

**Comment by danielzzz** [comment]
ok, thanks!
