### ISSUE TITLE
Events fire multiple times after browser history has been used

### ISSUE THREAD

**Issue by indegoberlin** [bigskysoftware/htmx#1753]
When using `hx-push-url="true"` to enable browser history, navigating back through the history will cause all subsequent htmx events to be fired multiple times.

Reproduction:
```
<button
  hx-post="/some_url"
  hx-trigger="click"
  hx-push-url="true"
>
  Click me
</button>

<script>
  htmx.on("htmx:afterSwap", () => {
    console.log('afterSwap');
  });
</script>
```

Clicking the button will show the console.log once. Navigating back and clicking the button again (or any other htmx-enabled element, doesn't need to be the same) will now show two additional logs. The number of times the event gets fired seems to correspond to the number of history steps being used, i.e. going back two steps in the history will then cause events to fire three times etc.

**Comment by croxton** [comment]
Inline scripts get triggered on history restore if they are within the element you have added the `hx-history-elt` attribute to (`body` by default). You can either put your script outside of the `hx-history-elt` element entirely, or you could remove the event listener within the `htmx.on(...)` callback using `htmx.off()`, so it only gets called once (i.e. make it self-destructing).

**Comment by indegoberlin** [comment]
That's not quite what I've been observing. Nothing gets triggered on the restore itself. Instead, pressing the button after a restore will trigger the script twice in a row.

**Comment by croxton** [comment]
Your `<script>` is getting triggered on history restore and adds an additional event listener. Try this and observe the console when you hit the back / forward buttons:

```js
<script>
 console.log('Script triggered');
  htmx.on("htmx:afterSwap", () => {
    console.log('afterSwap');
  });
</script>
```

**Comment by indegoberlin** [comment]
Thanks for the clarification! I can see what's happening now. Closed.
