### ISSUE TITLE
add array support in client-side-extensions (non-breaking)

### ISSUE THREAD

**Issue by vadave** [bigskysoftware/htmx#1775]
I was recently bitten by #1115 (closed), and looking at the proposed fix #1155 (also closed) I realized that the issue could be addressed in non-breaking fashion by adding alternate template extensions with slightly different selectors. This will allow existing code to continue working, but allow folks (like myself) that need to make calls against APIs returning arrays to also function.

I have a PR ready to go for this (largely inspired by #1155 ), will submit that for consideration momentarily.

**Comment by ieugen** [comment]
Would love to see this fixed.

**Comment by vadave** [comment]
This has been fixed - see [the discussion on array versions of the templates in the docs](https://htmx.org/extensions/client-side-templates/)

**Comment by ieugen** [comment]
Thanks @vadave . 
Maybe this issue can be closed then.
