### ISSUE TITLE
what is the function of Event Modifiers Changed

### ISSUE THREAD

**Issue by oxwazz** [bigskysoftware/htmx#1779]
i dont have any clue what it is? i have look the example of this

```html
<input name="q"
       hx-get="/search" hx-trigger="keyup changed delay:1s"
       hx-target="#search-results"/>
```

what is the meaning of `keyup changed`? why we use `changed` event modifiers, and whats the different when iam used `keyup` only?
thank you

**Comment by andryyy** [comment]
It’s another event. It’s usually triggered when blurring (leaving) the input field and its content changed. 

It’s probably used in combination because mobile devices (iOS) do not fire on keyup/keydown. Another way would be keypress, even Safari is able to detect it…

**Comment by Telroshan** [comment]
@andryyy I think you're confusing `changed`, the [hx-trigger modifier](https://htmx.org/attributes/hx-trigger/), with the [`change` event](https://developer.mozilla.org/docs/Web/API/HTMLElement/change_event) there

@oxwazz You can see the details about the `changed` modifier in the [hx-trigger documentation](https://htmx.org/attributes/hx-trigger/):
> changed - the event will only change if the value of the element has changed. Please pay attention change is the name of the event and changed is the name of the modifier.

So,
> whats the different when iam used keyup only?

The difference is that if you hit keys that do not change the value (arrow keys to move the selection around, ctrl, alt and so on), the `keyup` event is fired.
- With `keyup` only, hitting the arrow keys for example would fire the request, even though you didn't type new characters in the input
- With the `changed` modifier, htmx will only fire the request if that hit key changed the actual value of the input. In this case, hitting the arrow keys wouldn't trigger anything, as the value didn't change

Hope this helps!

**Comment by andryyy** [comment]
Oh, thank you! Totally missed that.
