### ISSUE TITLE
Swapping with beforeend and settle fades-in only the new element

### ISSUE THREAD

**Issue by albert-kam** [bigskysoftware/htmx#178]
Hi there,

I have a tbody with the class of fade-me-in, and the server response is put into the last row of the tbody.

```
<tbody id="componentsBody" class="fade-me-in">
```

I would like to have a simple animation for the new `tr` record only, so i add the settle1s on the tbody, and all of records of the body is animated, not only the newly appended record.

```
<button class="btn btn-secondary"
	...
	hx-target='#componentsBody'
	hx-swap='beforeend settle:1s'>Add a New Row</button>
```

I also tried this in hope to affect only the last child, but that also didnt work out:

```
.fade-me-in:last-child.htmx-settling {
  opacity: 0;
}
.fade-me-in:last-child {
  opacity: 1;
  transition: opacity 1s ease-out;
}
```

Any pointers to achieve what i want ? Thank you !

**Comment by 1cg** [comment]
Hi @albert-kam you want animations on a newly inserted element, which the settle phase isn't going to help much with.

There is a plugin that may be useful though:

https://htmx.org/extensions/class-tools/

You can use this to add or remove a class after a delay, and use that to create the CSS animation.

I should also mention that eventually I would like use cases like this to be handled with hyperscript, but that project is very young.
