### ISSUE TITLE
Prevent hx-push-url on htmx.ajax call

### ISSUE THREAD

**Issue by p-baum** [bigskysoftware/htmx#1792]
How can I prevent the URL being pushed when I use the JavaScript Ajax API?

I cannot find an option for that.  Is it possible?

**Comment by p-baum** [comment]
I've found a workaround by setting the response header   HX-Push-Url to false.  I would still like to know if there's a more elegant solution though.

**Comment by andryyy** [comment]
Does any of the closest elements from your defined target have a hx-push-url attribute set?

Perhaps you can set hx-push-url on the target before triggering the ajax function.

**Comment by p-baum** [comment]
It seems setting it on the target doesn't work but setting it on the targets parent does - at least when using `beforeend`
