### ISSUE TITLE
hx-get by default does not trigger a HTTP GET unless hx-trigger load is also added

### ISSUE THREAD

**Issue by pradeeproark** [bigskysoftware/htmx#1797]
As per the [docs](https://htmx.org/attributes/hx-get/) to use hx-get to load something, it should be enough to just use

```html 
<div hx-get='/example/1'>REPLACE EXAMPLE HERE</div> <!-- DOES NOT WORK. EXPECTED. -->
<div hx-get='/example/1' hx-trigger='load'>EXAMPLE 1</div> <!-- WORKS AS EXPECTED -->
```

however it does not issue a HTTP GET until you also add hx-trigger="load". Either the docs have to be updated or the implementation?

**Comment by andryyy** [comment]
The natural event is a click.

You don’t want all @hx-get processed on load. :)

**Comment by pradeeproark** [comment]
👍🏻 In that case the documentation should be updated. At the moment it reads like just having the attribute would fetch it :).

**Comment by andryyy** [comment]
It’s here https://htmx.org/docs/#triggers :)

**Comment by pradeeproark** [comment]
Thanks I was only looking at the docs for hx-get. the 'click' for everything else was not something I came across initially.
