### ISSUE TITLE
gzip version on homepage contains google tag manager

### ISSUE THREAD

**Issue by robert-sjoblom** [bigskysoftware/htmx#1821]
Title.

How is this acceptable?

It's probably UNPKG that injects it. But still.

**Comment by Telroshan** [comment]
Hey, I'm not sure I understand the situation. Are you talking about [this page](https://unpkg.com/browse/htmx.org@1.9.6/dist/htmx.min.js.gz), where I can indeed see a bunch of other things downloaded, including the analytics script?
If so, that's indeed unpkg's browsing page, and you may directly access the gzip file with the [raw file URL](https://unpkg.com/htmx.org@1.9.6/dist/htmx.min.js.gz), in which case I don't see anything else getting downloaded except the htmx script itself.

Am I missing something there? Please let me know!

**Comment by robert-sjoblom** [comment]
Ah, I see. I should probably have inspected things more closely; I was worried the script itself contained analytics, which would be a no-go due to company policies. Thank you for elucidating.
