### ISSUE TITLE
Smarter MouseDown handling

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#183]
For some links in an application, you can improve performance by listening for `onmousedown` events, instead of the `click` events.  It might seem petty, but you can save ~50-100ms by not waiting for the user to release the mouse button before the application starts to load the next page.  The effect makes websites seem insanely fast, and would be great to bake into HTMX.

For just one example, Firefox uses this trick for tab switching.

The trouble is that there are other kinds of "mouse down" events such as right-clicking (or alt-clicking on a Mac) which should pull up a context menu, not a new page.  It would be nice, instead, for HTMX to provide a trigger that filters for just the left (or primary mouse button).

Here's a preliminary suggestion:

```html
<div hx-boost="true">
  <a href="/new-page" hx-trigger="mousedown-left">Navigate Now</a>
</div>
```

Here's a wilder suggestion:

If there's agreement on the new trigger syntax, we might even consider updating `hx-boost` to take additional parameters for how boosted links are triggered.  So, in addition to `true`, hx-boost might also work with "click" or "mousedown-left"

```html
<div hx-boost="mousedown-left">
    <a href="/new-page">Navigate</a>
</div>
```

**Comment by clarkevans** [comment]
Alternatively, could we re-load content on a `mouseenter` event; then, once the`click` event happens, you can complete the action?

**Comment by benpate** [comment]
Howdy @clarkevans - 

That's a great idea for developers to have as an option as well. That sounds like a proposal for `hx-preload="mouseenter"` or something along those lines.  We'd need to do some thinking/experiments on the syntax and side-effects, though, to make sure we're not breaking anything or making things unnecessarily complex.

(This reminds me of the early days when "webmasters" put delete actions behind `GET` URLs and lost their whole sites when Google crawled all the links)

**Comment by clarkevans** [comment]
Absolutely you wouldn't want it to add it on any mutable action.  Then again, I'm not sure you'd want to add `mousedown-left` to anything that is mutable action.  I've seen people press a button.... and _then_ think if they really, really want to do it, if not, they move their mouse outside the button area and let it come back up.  This doesn't trigger the `click` event.  So, in some ways, the `mouseenter` is a cleaner way of doing this.

The core challenge is if someone moves their mouse across the page and triggers several of these pre-load events making the system sluggish. I'm sure there's a reasonable solution.  Someone will probably linger over the button for a split second if they aren't zooming their mouse across an area. Or, alternatively, it could do the 1st such one and the last, not submitting the 2nd and N-1 items if there is a subsequent `onenter` event in short order.

**Comment by benpate** [comment]
Yes on all points.  And I hadn't even started thinking about a user moving their mouse all across the page.

Preloading, if it's too aggressive, has the potential to overload both the client and the server.  To add on, I was thinking that it would be important to separate "preloading" from "settling".  This means we could preload a fragment "A" that we expect to be needed, but would not load any subsequent links that "A" contains (like linking to page fragment "B") until "A" is actually used and displayed on the page.

A preload "queue" sounds really cool, and I'd love to explore that as an option, too.  One thing to watch out for -- it has the potential to be expensive in terms of the amount of code required to deliver it.  If we can deliver something like this that doesn't add too much code to the library, then I think it's a great idea.  

One thing that I really like about HTMX is how small and light the package is over the wire.  I hope that this remains one of the core goals of the project, to not add too much "bloat" to the overall package.  And actually, I'm hoping that some of the suggestions we've been working on will actually help to REDUCE the size of the final download.  Maybe your "queue" suggestion might even accomplish that...

**Comment by bencroker** [comment]
This issue seems to have gone on a tangent in a completely different direction to the original idea which, as far as I can tell, was the ability to specify which `button` on the the `mousedown` event should trigger a htmx request. There is the [MouseEvent.buttons](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons) property on the `MouseEvent` which may be able to help with this, but the buttons are represented by numbers.

![Screenshot 2020-09-16 at 21 36 04](https://user-images.githubusercontent.com/57572400/93383960-ae206c80-f864-11ea-8635-c2d65dd70696.png)

Personally I'd suggest this be kept out of core and added as an extension (at least for the meantime). The preloading idea also sounds like it would be better suited to an extension.

> If there's agreement on the new trigger syntax, we might even consider updating hx-boost to take additional parameters for how boosted links are triggered. So, in addition to true, hx-boost might also work with "click" or "mousedown-left".

Why mix trigger attributes into the boost attribute? Is there any obvious benefit?

**Comment by benpate** [comment]
Yes. It did wander. My original idea itself might be overkill, and could easily be explored as an extension first. The purpose was list to look at common use cases that might benefit from HTMX’s declarative style. 

Is it possible to make an extension that works as a trigger?  If so, I'll try making something down that route first.

**Comment by bencroker** [comment]
You may be able to achieve this using the [htmx:beforeRequest](https://htmx.org/events/#htmx:beforeRequest), however I'm not sure how available the details of the trigger are with that event.

**Comment by benpate** [comment]
So, I was able to make this work with Javascript.  In essence, I'm just hooking in to the browser event and hoping that we can prevent it from continuing before HTMX gets it.  I'm sure it could be applied to all links across the site.  Here's some sample code:

```javascript
document.getElementById("myLink").addEventListener("mousedown", function(event) {
	if (event.button != 1) {
		event.stopImmediatePropagation()
	}
})
```

However, this is really ugly, and I think it would be great to add it to HTMX/Hyperscript in some way.  I'll continue looking into the extension, although I'm not optimistic about success because the documentation leaves out event data, so I'm assuming that it won't be available when I get into it.

**Comment by bencroker** [comment]
Implementing as an extension sounds good and will allow easier consideration for a core feature in future.

**Comment by benpate** [comment]
My original request was recently addressed with the [trigger filtering](https://github.com/bigskysoftware/htmx/commit/6c8c124c420b90b4c0527557af3a9466d74a0b53) commit.  I think a bunch of other cool ideas came out of this discussion, but I'm happy to close this one now.

**Comment by johndunlap** [comment]
Your mileage may vary but this seems to work if I put `hx-trigger="mousedown"` on my `<a>` `<button>` or `<input>` tags.
```js
        document.addEventListener('DOMContentLoaded', function() {
            document.body.addEventListener('mousedown', function (event) {
                const anchor = event.target.closest('a');
                const isButtonOrInput = event.target.tagName === 'BUTTON' || event.target.tagName === 'INPUT';
                console.log(event.target.tagName, isButtonOrInput)

                if ((anchor && (anchor.hasAttribute('hx-get') || anchor.hasAttribute('hx-post'))) || isButtonOrInput) {
                    if (event.button > 0) {
                        event.stopImmediatePropagation();
                    }
                }
            }, true);
        });
```
