### ISSUE TITLE
would you might public official website code ? 

### ISSUE THREAD

**Issue by athsx** [bigskysoftware/htmx#1831]
recently I try to learn HTMX, but it seems to only handle some elements on one page, I wonder how to load another page without refreshing until I aware that HTMX's official website `https://htmx.org/` is the loading page without refresh, it's very easy to load pages from top navigation bar click. Is it possible to make an example repository,?

**Comment by Telroshan** [comment]
Hey, the source code of the htmx website is already available in this repository, under the [`www` directory](https://github.com/bigskysoftware/htmx/tree/master/www)

Other than that, check out the [examples section](https://htmx.org/examples/) on the website, which features a list of common client patterns, as well as the [server-side examples](https://htmx.org/server-examples/)

**Comment by athsx** [comment]
thanks you
