### ISSUE TITLE
"naked" hx-trigger/htmx:trigger doesn't seem to work

### ISSUE THREAD

**Issue by apiontek** [bigskysoftware/htmx#1845]
I noticed in the docs/reference, mention of using hx-trigger with htmx:trigger events.

However, it doesn't seem to be working as expected for me. I'm sure I'm missing something. I'm using htmx.org 1.9.6, and bundling it for my project via

```js
import htmx from "htmx.org";
window.htmx = htmx;
```

Everything else I've been doing with htmx is working. For example:

```html
<button type="button" hx-on:click="console.log(event)">Click me!</button>
```

I get the event logged as expected. However, if I try:

```html
<button type="button" hx-trigger="click" hx-on::trigger="console.log(event)">Click me!</button>
```

Nothing happens. And with `htmx.logAll()` added in my bundler, other htmx logging is seen, but nothing when I click the `hx-trigger` button.

The way I read the documentation, it looks to me like this should be working, but if I'm wrong and this isn't intended to work this way, maybe the documentation needs to be edited for clarity. Or, there's a bug to be fixed?

It would be very convenient to be able to use hx-trigger & htmx:trigger in this manner, since hx-trigger supports modifiers like "from:#my-element" etc., and hx-on does not.

**Comment by guidog** [comment]
One colon versus 2 colons...

**Comment by apiontek** [comment]
@guidog I don't follow you. The event is documented as `htmx:trigger` and the convention is that with `hx-on` the `htmx` can be omitted, so it would be either `hx-on::trigger` or `hx-on:htmx:trigger`, and neither work.

**Comment by apiontek** [comment]
I just found that if I also place an `hx-get` on the element, then the `htmx:trigger` event is fired—but so is an AJAX request, which isn't stopped by having the `hx-on::trigger` handler immediately call `htmx.trigger('#el-to-abort', 'htmx:abort')`, and while I can also try to stop content from being swapped in, I'd rather there just be no AJAX request at all, and any response with `hx-swap-oob` still swaps in the oob content.

All of this is contrary to what is implied by the [`hx-trigger` documentation](https://htmx.org/attributes/hx-trigger/) which states "`hx-trigger` can be used without an AJAX request, in which case it will only fire the `htmx:trigger` event"

It would be good to know what is required to get the behavior described, if possible.

**Comment by andryyy** [comment]
Perhaps it requires that you don’t have a hx-$method attribute on that element. Can you verify this?

**Comment by andryyy** [comment]
BTW, if you need to hook to the event before an AJAX call, check htmx:beforeRequest. You can prevent default here to abort.

**Comment by apiontek** [comment]
> Perhaps it requires that you don’t have a hx-$method attribute on that element. Can you verify this?

That's my original issue above. The way this is documented, it sounds like having only `hx-trigger` and then `hx-on:htmx:trigger` should work, without an hx-$method attribute, but nothing happens at all.

> BTW, if you need to hook to the event before an AJAX call, check htmx:beforeRequest. You can prevent default here to abort.

I can confirm, the following works:

```html
<button
  type="button"
  hx-get="/"
  hx-trigger="click"
  hx-on::before-request="event.preventDefault()"
  hx-on::trigger="console.log('Hello world')"
  >Click me!</button>
```

But I maintain, from the documentation it sounds to me like an hx-$method attribute wouldn't be required for `hx-trigger` to trigger an `htmx:trigger` event.

It would be good to add clarity to the documentation if the intention is that an additional event handler is used to stop the AJAX request.

And, for anyone else trying to do the same thing, I found that I could stop it even earlier using the htmx:confirm or htmx:config-request events. Earliest is htmx:confirm:

```html
<button
  type="button"
  hx-get="/"
  hx-trigger="click"
  hx-on::confirm="event.preventDefault()"
  hx-on::trigger="console.log('Hello world')"
  >Click me!</button>
```

**Comment by apiontek** [comment]
I also just found that `htmx:trigger` isn't fired in another case:

- Working: `hx-trigger="input"`
- Working: `hx-trigger="input changed"
- _Not_ working: `hx-trigger="input changed delay:100ms"

I haven't proceeded to test other modifiers. From the documentation, I would expect `htmx:trigger` to fire under all the conditions that `hx-trigger` would normally cause an AJAX request, but it doesn't.

**Comment by andryyy** [comment]
Sorry for not thoroughly reading the initial issue.

I understand that it could be clarified in the docs.

Did you checkout _hyperscript from the same creators?
It adds useful functionality and reduces JS complexity. 
You can use it like "on click halt the event log 'Hello'". Or "on input or click from closest <form/> log 'Hello' unless the event's name is not 'click'. 

You find many references to _hs in the docs of HTMX.

**Comment by apiontek** [comment]
Yes, I have tried _hyperscript. I respect it a lot, but for me it adds unnecessary complexity. For me, adding an additional ~100k with an additional bundle and a new language/syntax to master is _not_ reducing complexity.

For just a bit of extra convenience on event handling, beyond what `hx-on` currently offers, I'd reach for alpine js first: it only adds ~45k to my bundle, and its attribute-based syntax is more in line with htmx's (plus I'm already familiar with it).

It's just frustrating because htmx can _almost_ already do more flexible eventing, but either `hx-on` would need to handle some extra modifiers like alpine's `x-on`, or `hx-trigger` would need to work without an hx-$method attribute and/or _always_ fire an htmx:trigger event. As it is, it's inconsistent in behavior.

**Comment by andryyy** [comment]
The whole point of HS is to reduce complexity. No matter if it is 1k or 1M. 

Check htmx.on() if you are fine with defining events outside the element. 

Like, from the docs, this:

`var myEventListener = htmx.on("click", function(evt){ console.log(evt); });`

**Comment by apiontek** [comment]
With respect, I think you're missing the point of my issue. `hx-on` works fine, but doesn't support any modifiers for delay/debounce, prevent, stop, from:selector, target:selector -- all things that are already built in to htmx via `hx-trigger`.

`htmx.on()` also does not support these modifiers.

Yes, I could code it myself, or use another library. My point is that `hx-trigger` already supports many modifiers, and the documentation suggests you can use `hx-trigger` alone, with the `htmx:trigger` event. If you could, you wouldn't need to roll your own or use other libraries. But it doesn't work.

I'm suggesting:

- ideally, allow `hx-trigger` to truly work alone, without an `hx-$method` attribute, and have it always fire `htmx:trigger`
- or, fix the documentation to provide clarity: "`htmx:trigger` exists but it isn't always fired, and you can't use `hx-trigger` alone
- or even bettter, allow `hx-on` to support the same modifiers that `hx-trigger` supports

This isn't an issue about "just add another library," this is an issue about a documented feature of htmx and hoping to find some clarity around its functionality, intended purpose, and documentation.

**Comment by andryyy** [comment]
Are you sure you should be so angry?

**Comment by apiontek** [comment]
To me that seems like a very strange response to my attempts to clarify the issue I opened, but thanks for your input.

**Comment by andryyy** [comment]
You are a bit demanding and aggressive, that’s annoying. 

So, I will stop right here. :)

**Comment by apiontek** [comment]
Investigating further, I _think_ I've discovered my problem: I'm using `hx-boost` on my body tag, making any element with `hx-trigger` _not_ "naked" -- per [this section of code](https://github.com/bigskysoftware/htmx/blob/ec126d2e3d973325f53fc69ed591ee908901e839/src/htmx.js#L2033C20-L2033C20).

For anyone else confused about this in the future: the solution seems to be placing `hx-disinherit="*"` on a parent element. For example the following is working for me:

```html
<div hx-disinherit="*">
  <button type="button"
    hx-trigger="click consume"
    hx-on::trigger="console.log('click consumed by hx-trigger')"
    >Click me!</button>
</div>
```

That seems reasonable enough, so I'll close this.

**Comment by esnunes** [comment]
Thanks for investigating this further @apiontek! I'm facing a similar issue and your suggestion has improved the scenario, however, I still have an issue: the htmx:trigger event doesn't contain the detail of the original event, e.g. if you have `hx-trigger="keydown"` the `htmx:trigger` event won't have the key or any other data, even the detail of custom events isn't carried over to the htmx:trigger event. Have you faced something like this? Have you found a workaround?

Thanks!

```html
<input type="hidden"
  hx-trigger="my-custom-event" <!-- my-custom-event has detail = { value: 'xxx', label: 'yyy' } -->
  hx-on::trigger="console.log(event)"
/>
```

**Comment by aral** [comment]
This is still an issue, e.g., see: https://github.com/bigskysoftware/htmx/issues/2131#issuecomment-4225863861
