### ISSUE TITLE
Submit a form programmatically

### ISSUE THREAD

**Issue by billmn** [bigskysoftware/htmx#186]
Hi guys,
I'm trying to submit a form programmatically but it trigger the native form submit (that reload the page).

```html
<form id="form"  hx-post="/my-url">
    <input type="text" name="field1">
</form>

<script>
    function doSomething() {
        document.getElementById('form').submit()
    }
</script>
```

I can definitely add an hidden "submit" button to the form and then click it from js, but i would like to know if there is a better way to do it.

Thank you

**Comment by 1cg** [comment]
See

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit

> No submit event is raised. In particular, the form's onsubmit event handler is not run.

Deeply annoying.

**Comment by billmn** [comment]
Oh thank you. Agree, is really annoying 😔
