### ISSUE TITLE
htmx - focus element (non javascript)

### ISSUE THREAD

**Issue by 8483** [bigskysoftware/htmx#1869]
How are elements focused in htmx?

I can't seem to find an answer anywhere.

The goal is to focus a specific element after a POST request i.e. focus the input with id `#field-description`.

I'd like this to be done without javascript, if possible.

```html
<div class="input-group">
    <span>Description</span>
    <input type="text" name="description" placeholder="task" id="field-description">
</div>

<div class="input-group">
    <span>Amount</span>
    <input type="number" name="amount" placeholder="number" id="field-amount">
</div>

<button 
    hx-post="/api/todos" 
    hx-include="#field-description, #field-amount"
    hx-target="#todos-container" 
    hx-swap="innerHTML"
    hx-focus="#field-description"
>
    Add
</button>

<div id="todos-container" class="todos-container">
    ${getTodos()}
</div>
```

**Comment by alexpetros** [comment]
You'll have to use some javascript to get the exact behavior you want, but you can do it simply with [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) and `hx-on:`

I didn't double-check this, but it should be something along the lines of `hx-on:load="this.scrollIntoView()"`

**Comment by 8483** [comment]
> You'll have to use some javascript to get the exact behavior you want  

Isn't the whole point of htmx to minimize javascript use? This is such a common use case, it should be part of the library.

> hx-on:load="this.scrollIntoView()"

Doesn't seem to work in both cases...  

```html
<div class="input-group">
    <span>Description</span>
    <input type="text" name="description" placeholder="task" id="field-description" hx-on:load="this.scrollIntoView()>
</div>

<button 
    id="button"
    hx-post="/api/todos" 
    hx-include="#field-description, #field-amount"
    hx-target="#todos-container" 
    hx-swap="innerHTML"
    hx-on::afterSwap="htmx.find('#field-description').focus()"
>
    Add
</button>
```

**Comment by alexpetros** [comment]
The first one should have been `hx-on::load`, I edited my original comment accordingly.

**Comment by alexpetros** [comment]
> Isn't the whole point of htmx to minimize javascript use? This is such a common use case, it should be part of the library.

Opinions differ, of course, but if you asked me I'd say the point of htmx is that it allows you to network interactions decoratively, deferring responsibility for the UI that results from those interactions to the server. While we try to fill in common cases, client-side scripting is necessarily going to involve JS, and htmx provides hooks like `hx-on` to allow you to write those scripts with the minimal JS necessary (i.e. no `addEventListener`)

**Comment by t1** [comment]
I have the same issue with a button that is replaced with a text field, and I want that field to be focused after clicking. I'm still trying to get my JavaScript working; it's not exactly trivial, is it? I'm trying out all the various suggestions I've already found, but I didn't get it working, yet.

When I found this issue, I think it would actually be perfectly in the same line of thinking as some of the modifiers of `hx-swap`, namely [focus-scroll](https://htmx.org/attributes/hx-swap/#focus-scroll), [scroll and show](https://htmx.org/attributes/hx-swap/#scrolling-scroll-show).

So another possible syntax would be: `hx-swap focus` in my case when I want to focus the replaced field; or in the use-case of @8483 `hx-swap focus:#field-description`.

**Comment by t1** [comment]
I got it working, now! In the example above, there's a bug:
`hx-on::afterSwap="htmx.find('#field-description').focus()"`
should be:
`hx-on::after-swap="htmx.find('#field-description').focus()"`
Catching an event with `hx-on` needs the kebab case name!
And I use `after-settle` instead... sounds more appropriate to me, somehow.

**Comment by alexpetros** [comment]
Geez, sorry, will edit

**Comment by 8483** [comment]
@t1 I can't get it working :(

```html
<div class="input-group">
    <span>Description</span>
    <input 
        type="text" 
        name="description" 
        placeholder="task" 
        id="field-description"
    >
</div>

<div class="input-group">
    <span>Amount</span>
    <input 
        type="number" 
        name="amount" 
        placeholder="number" 
        id="field-amount"
    >
</div>

<button 
    id="button"
    hx-post="/api/todos" 
    hx-include="#field-description, #field-amount"
    hx-target="#todos-container" 
    hx-swap="innerHTML"
    hx-on::after-swap="htmx.find('#field-description').focus()"
>
    Add
</button>
```

**Comment by t1** [comment]
@8483: have you tried `after-settle` instead of `after-swap`?

**Comment by t1** [comment]
.. oh, and put the `hx-on` on the `todos-container`, not on the button, because the target receives the events, not the button.

**Comment by t1** [comment]
This is still not sufficient, as the `hx-on` remains on the element, i.e. it triggers again when the event gets fired again. I'm not sure how to solve that.

**Comment by janpfeifer** [comment]
For what it's worth, I'm doing my very first small app with HTMX and I immediately bumped into this: every time I switch contents in the main area of my app, I want the focus to go to an specific element -- to avoid mouse use.

I've been using `autofocus` everywhere, despite chrome complaining with `Autofocus processing was blocked because a document already has a focused element.`, but it seems to work.

It feels a natural usability aspect that deserves being a "1st class citizen", no ? -- but i'm really no front-end expert ...

**Comment by 8483** [comment]
@janpfeifer I believe this is such a regular and simple use case, they should provide an htmx way to do it. Anyway, here's how I ended up handling it.

```js
router.get("/", (req, res) => {
    let html = /*html*/ `
        <!DOCTYPE html>
        <html>
            <head>
                <title>HTML -TODO</title>

                <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />

                <link rel="stylesheet" type="text/css" href="style.css" />
                <script src="https://unpkg.com/htmx.org@1.9.6"></script>

                <style>
                    body {
                        padding: 10px;
                        display: grid;
                        grid-template-rows: 50px 50px 300px;
                    }

                    .form {
                        display: flex;
                        align-items: flex-end;
                        gap: 10px;
                        margin-bottom: 10px;
                    }

                    .input-group {
                        display: flex;
                        flex-direction: column;
                    }

                    .todos-container {
                        display: grid;
                        grid-template-rows: 4fr 1fr;
                    }

                    .todos {
                        display: flex;
                        flex-direction: column;
                        overflow: auto;
                    }

                    .headers {
                        display: grid;
                        grid-template-columns: 50px 300px 100px;
                        padding: 3px;

                        position: sticky;
                        top: 0px;
                        background: white;
                    }

                    .todo {
                        display: grid;
                        grid-template-columns: 50px 300px 100px;
                        border: 1px solid rgba(0, 0, 0, 0.1);
                        padding: 3px;
                    }

                    .total {
                        padding-top: 10px;
                    }
                </style>              
            </head>

            <body>
                <h1>TODO</h1>


                <div class="form">
                    <div class="input-group">
                        <span>Description</span>
                        <input 
                            type="text" 
                            name="description" 
                            placeholder="task" 
                            id="field-description"
                            hx-on:keyup="if (event.key=='Enter') focusElement('field-amount');"
                        >
                    </div>

                    <div class="input-group">
                        <span>Amount</span>
                        <input 
                            type="number" 
                            name="amount" 
                            placeholder="number" 
                            id="field-amount"
                            hx-on:keyup="if (event.key=='Enter') focusElement('button');"
                        >
                    </div>

                    <button 
                        id="button"
                        hx-post="/api/todos" 
                        hx-include="#field-description, #field-amount"
                        hx-target="#todos-container" 
                        hx-swap="innerHTML"
                        hx-on:keyup="
                            if (event.key=='Enter') {
                                focusElement('field-description');
                                clearInput('field-description');
                                clearInput('field-amount');
                            }
                        "
                    >
                        Add
                    </button>
                </div>

                <div id="todos-container" class="todos-container">
                    ${renderTodos()}
                </div>
            </body>

            <script src="/scripts.js"></script>
            <script>
                document.getElementById("field-description").focus()
            </script>
        </html>
    `;

    res.send(html);
});
```
