### ISSUE TITLE
Publish Extensions on npm

### ISSUE THREAD

**Issue by t1** [bigskysoftware/htmx#1871]
It would be nice, if not only htmx itself would be available on [hpm](https://www.npmjs.com/package/htmx.org), but also the extension.

**Comment by wimdeblauwe** [comment]
I believe they are all part of the htmx package. If you check out the "Code" tab at https://www.npmjs.com/package/htmx.org?activeTab=code then you can see them in the `dist/ext` folder.

**Comment by t1** [comment]
oh... didn't see that. sorry for bothering.
