### ISSUE TITLE
Script tags in head of requested page aren't run when boosting

### ISSUE THREAD

**Issue by vincer2040** [bigskysoftware/htmx#1873]
### Problem: 

When using hx-boost, and the link clicked returns html that contains a script tag in the head of the body, that script won't be run

This is the page where the link is clicked: 

```html 
<div hx-boost="true">
     <a href="/page-with-script-in-head">link</a>
</div>
```

and this is the html the server responds with when the link is clicked: 

```html 
<html>
    <head>
        <script>
         console.log("hello");
        </script>
    </head>
    <body>
          <div>page with script in head</div>
    </body>
</html>
```

In this case, the script isn't run until the user refreshes the page. This is problematic when the script in the head does some 
modifications to the dom, and they don't appear until the user refreshes the page.

### workaround 

simply moving the script to the body resolves the issue and the scripts run fine, but sometimes this isn't always ideal, and some scripts require that they be in the head. 

### Possible solution 

I have seen some front-end routing libraries remove the scripts in the head and immediately inject them back into the head, which triggers them to run. Something like this: 

```js 
function replaceAndRunScript(oldScript) {
    const newScript = document.createElement('script');
    const attrs = Array.from(oldScript.attributes);
    for (const { name, value } of attrs) {
        newScript[name] = value;
    }
    newScript.append(oldScript.textContent);
    oldScript.replaceWith(newScript);
}
```

this can possibly be made opt-in by using an attribute on the script tag like `<script hx-reload="true">`  that tells htmx that it wants the script replaced and ran

**Comment by danjessen** [comment]
No. Because the scripts are not rerun. Boost only replaces body. Look at the head extension for the desired effect

**Comment by vincer2040** [comment]
> Boost only replaces body.

Okay, I am slightly confused because Boost replaces the title of the page, and that information is in the head. Are there certain elements in the head that boost will replace without the head extension?

**Comment by danjessen** [comment]
Yes, `<title>`

**Comment by vincer2040** [comment]
Would it be worth mentioning that in the documentation? because it says that _only_ the body is swapped, and the title is certainly not in the body. I don't mind writing it in the documentation if so

**Comment by danjessen** [comment]
@vincer2040 "Swap Options
The hx-swap attribute supports many options for tuning the swapping behavior of htmx. For example, by default htmx will swap in the title of a title tag found anywhere in the new content. You can turn this behavior off by setting the ignoreTitle modifier to true:"
 https://htmx.org/#:~:text=Swap%20Options,modifier%20to%20true%3A
