### ISSUE TITLE
How to change hx-attributes to something that is valid HTML?

### ISSUE THREAD

**Issue by krompaco** [bigskysoftware/htmx#1879]
Thank you for htmx! I love it and would like to use it even more but can't because it gives validation errors when checking our HTML output.

Couldn't find an existing issue or a way to configure the attribute names?

Of course very easy to check this using https://validator.w3.org or using the package https://html-validate.org/ in some JS project.

Errors reported are similar to this:
Attribute `hx-delete` not allowed on element `button` at this point.

I assume one solution could be to use `data-hx-*` as the attribute name or make it configurable for those that care.

**Comment by BartChris** [comment]
Already possible

https://htmx.org/docs/#introduction

"It’s worth mentioning that, if you prefer, you can use the data- prefix when using htmx:"

<a data-hx-post="/click">Click Me!</a>

**Comment by krompaco** [comment]
Ah, there it was! Thanks 😅
