### ISSUE TITLE
Boosted form submission (GET) creates query string with wrong parameter order

### ISSUE THREAD

**Issue by kautsig** [bigskysoftware/htmx#1895]
I  am implementing a dynamic filter system for a CRUD application and encountered following issue.

The application allows to add `div`s containing form fields dynamically using javascript. This results roughly in a form like this (simplified):

```
<form action="/persons">
  <div>
    <input name="field[]" value="first_name">
    <input name="operator[]" value="eq">
    <input name="value[]" value="joe">
  </div>
  <div>
    <input name="field[]" value="last_name">
    <input name="operator[]" value="eq">
    <input name="value[]" value="user">
  </div>
</form>
```

When submitting this form in a regular multi-page application through the browser form submission, this results in following path and query:

```
/persons?field[]=first_name&op[]=eq&value[]=joe&field[]=last_name&op[]=eq&value[]=user
```

When submitting this form via htmx from a `hx-boost`ed context, this result in the following path and query:

```
/persons?field[]=first_name&field[]=last_name&op[]=eq&op[]=eq&value[]=joe&value[]=user
```

I tried to find the appropriate section in the html standard, which states:

> Let controls be a list of all the [submittable elements](https://html.spec.whatwg.org/multipage/forms.html#category-submit) whose [form owner](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner) is form, in [tree order](https://dom.spec.whatwg.org/#concept-tree-order).

See https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set

This can cause issues, if the order of parameters is important. 

I tried to replicate this using `FormData` and `URLSearchParams`, they would preserve the order correctly.

```
for (x of new FormData(document.getElementsByTagName('form')[0]).entries()) { console.log(x) }
Array [ "field[]", "first_name" ]
Array [ "op[]", "eq" ]
Array [ "value[]", "joe" ]
Array [ "field[]", "last_name" ]
Array [ "op[]", "eq" ]
Array [ "value[]", "user" ]
```

And:

```
new URLSearchParams(new FormData(document.getElementsByTagName('form')[0])).toString();
"field%5B%5D=first_name&op%5B%5D=eq&value%5B%5D=joe&field%5B%5D=last_name&op%5B%5D=eq&value%5B%5D=user"
```

I tried to dig into the htmx code, but could not figure out where things go wrong exactly. My guess would be that parameters are handled as javascript objects which means order is lost. See https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3093

**Comment by kautsig** [comment]
@nickchomey The form is used for filtering which data should be displayed in the result set listing persons. This filter should be part of the URL, as I want it to be e.g. bookmarked. I don't see anything wrong with that.

Even the link you provided says:

> GET for reads. (reading data and displaying it)
> POST for anything that writes (i.e updating a database table, deleting an entry, etc.)

In the case I am describing, data is only read.

Of course I could use a different way of submitting the data, but this is not what I am reporting.

Rather I am reporting an unexpected difference in behavior when submitting a form via browser or via `hx-boost`, which matters for e.g. legacy applications or progressive enhancement scenarios.

**Comment by kautsig** [comment]
@nickchomey All good, thanks for the hint.

You are right, they are not needed, but removing them doesn't change the problem.

```
/person?field=first_name&field=last_name&op=eq&op=eq&value=joe&value=user
```

The RFC linked in the stackoverflow post says:

> These characters are called "reserved" because they may (or may not) be defined as delimiters by the generic syntax, by each scheme-specific syntax, or by the implementation-specific syntax of a URI's dereferencing algorithm. If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.

Which I'd interpret as "they are allowed except when they aren't". At least firefox has no problem with them and shows the submitted data as arrays of values.

![image](https://github.com/bigskysoftware/htmx/assets/1544008/5588e5f3-6805-4078-a662-daded7027d19)

**Comment by kautsig** [comment]
I tried to see how other libraries deal with the situation (preserving order of query string parameters).

Here is an example from go:

```
func main() {
	req, _ := http.NewRequest("GET", "http://example.com?a=1&b=2&a=3&a=4&b=5", nil)

	// prints http://example.com?a=1&b=2&a=3&a=4&b=5
	fmt.Println(req.URL.String())

        // call to encode on the query causes parameter order to change
	q := req.URL.Query()
	req.URL.RawQuery = q.Encode()

	// prints http://example.com?a=1&a=3&a=4&b=2&b=5
	fmt.Println(req.URL.String())
}
```

https://go.dev/play/p/7xz_NKzlQst

Or here the javadoc from the servlet api:

https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameterMap()

This means, multiple libraries represent the parsed query string as a map using the parameter name as key, not guaranteeing any given order.

So the question which is left is if htmx should be expected to implement the behavior exactly as described by the html spec (tree-order), but the answer is probably no.

**Comment by danjessen** [comment]
If it's a big problem. Just index the array. From my knowledge you can not rely on the order. So:
```
<form action="/persons">
  <div>
    <input name="field[0]" value="first_name">
    <input name="operator[0]" value="eq">
    <input name="value[0]" value="joe">
  </div>
  <div>
    <input name="field[1]" value="last_name">
    <input name="operator[1]" value="eq">
    <input name="value[1]" value="user">
  </div>
</form>
```

**Comment by kautsig** [comment]
Thanks a lot @danjessen for your input. It's not a big problem and I could work around it.

Respectfully, I think the point I was trying to make still stands. The htmx docs say:

> The hx-boost attribute allows you to “boost” normal anchors and form tags to use AJAX instead. This has the [nice fallback](https://en.wikipedia.org/wiki/Progressive_enhancement) that, if the user does not have javascript enabled, the site will continue to work.

My intention when filing this issue was to highlight inconsistent behavior between how htmx submits forms compared to what browsers do and the problems that can come from this.

> From my knowledge you can not rely on the order.

The html spec defines an order and browers implement that (see above). Server side libraries might or might not (see the java servlet api or the golang example above). Maybe I miss something and you could provide a link which backs your claim.

Regarding the indexing you suggested: I use the following button to append form parts dynamically, needing to know the index would make this more complex.

```
<button
  type="button"
  hx-get="/components/person-filter"
  hx-target="this"
  hx-swap="beforebegin"
  hx-trigger="click">Add</button>
```

**Comment by glu-lumera** [comment]
Was just about to report what I am pretty sure is the same underlying issue.

Minimal example:
```
<form method="post" action="/dummy">
  <label for="name">Name</label>
  <input name="name" value="">
  <label for="email">Email</label>
  <input name="email" value="">
  <input name="divider" hidden="" value="">
  <label for="name">Name</label>
  <input name="name" value="">
  <label for="email">Email</label>
  <input name="email" value="">
  <button hx-post="/dummy/validate" hx-target="closest form">Validate</button>
  <button type="submit">Submit</button>
</form>
```

Order when pressing Submit: `name=&email=&divider=&name=&email=`. Order when pressing validate: `name=&name=&email=&email=&divider=divider`

Serialization order is crucial for most methods of handling structured nestled data in forms.

**Comment by kautsig** [comment]
@danjessen, the document says:

> The Infra Standard aims to define the fundamental concepts upon which standards are built.

Those are important concepts, but I would not conclude anything specific from that. Rather, I would read the spec in a way that you go from the specific behavior, such as "form submissions" and follow the links to the more abstract.

The document I referred to deals with form submissions specifically and how data which is submitted constructed.

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set

It links to the infra standards, saying form controls are a "list", not a "set" nor "sorted set".

It also tells you the details about order:

> Let controls be a list of all the submittable elements whose form owner is form, in tree order.

Where tree-order means specifically:

> A tree is a finite hierarchical tree structure. In tree order is preorder, depth-first traversal of a tree.

I'd think the tree in question is the document.

@glu-lumera: Yes, that is the exactly the issue I tried to describe, thanks for confirming.

**Comment by Telroshan** [comment]
Hey, we switched to FormData internally for htmx 2, which now correctly preserves the values order (see test added in 01b292ada48f31276642b587eb67128367349701). We also introduced a FormData proxy object for retro-compatibility reasons, and proxy objects [aren't supported by IE11](https://caniuse.com/proxy), which htmx 1 will always support.
As htmx 2 is now available in beta and on the `dev` branch, I think we can close this issue now ; if you need form data, switch to htmx2 ! 😄
