### ISSUE TITLE
Websocket Extension Errors when used with a polling trigger

### ISSUE THREAD

**Issue by orthanc** [bigskysoftware/htmx#1896]
The following example run with HTMX 1.9.6 and the webscoket extension fails

```
<div hx-ext="ws" ws-connect="/chatroom"  hx-trigger="every 60s">
    <form id="form" ws-send>
        <input name="chat_message">
    </form>
</div>
```

With the attached error
![Screenshot from 2023-10-16 17-55-25](https://github.com/bigskysoftware/htmx/assets/590698/1ffda59a-4569-4fae-a6da-78313929af5d)

Tracking this down, it appears to be the [call to api.shouldCancel](https://github.com/bigskysoftware/htmx/blob/master/src/ext/ws.js#L382) in the websocket extension. The event is undefined when using a polling trigger so this call fails with the attached error.

I think this could be fixed by just checking the event is not undefined before calling shouldCancel

---

Correction: the version of HTMX this was seen in is 1.9.6, the file saved with the wrong version in the name which is why it appears as 1.6.9 in the stack trace.

**Comment by Renerick** [comment]
Thank you for reporting this, I'll have a look

**Comment by andryyy** [comment]
Wondering if the bug also occurs using the latest HTMX. Have you tried?

**Comment by orthanc** [comment]
I reversed the version number when I saved the file, my apologies. I'm seeing this on 1.9.6 not 1.6.9. I believe 1.9.6 is the latest release.

So yes, present on the latest release.

**Comment by Renerick** [comment]
The PR was merged so I'll close this iseue
