### ISSUE TITLE
htmx.ajax error in Promise

### ISSUE THREAD

**Issue by carlos-verdes** [bigskysoftware/htmx#1901]
Context
I'm using `htmx.ajax()` method and I need to catch errors on the response, I expect to use the `Promise.prototype.catch()` for this.

On the next example the console.log and alert are not executed:
```js
  htmx
    .ajax('POST', '/myPath', { target: '#targetDiv', swap: 'outerHTML'})
    .catch(error => {
      console.log('error calling service', error)
      alert('Server error, try again later')
    })
```

[Promise catch spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)

**Comment by danjessen** [comment]
@carlos-verdes can you use the log to see what events are fired up until your catch?

It seems that htmx is calling resolve even with errors
https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3147
But probably needs more of an example to verify

**Comment by carlos-verdes** [comment]
I created this fiddle to reproduce the issue:
https://jsfiddle.net/buhf7cza/

The code:
```html
<html>
      <head>
          <script src="https://unpkg.com/htmx.org@1.9.6"
                integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
      </head>
      
      <script>
        function sendRequest() {
          try {
            htmx
              .ajax('POST', '/randomPath')
              .catch(error => {
                console.log('error calling service', error)
                alert('Server error, try again later')
              })
          } catch(e) {
            console.log('error calling service in try/catch', error)
            alert('Server error, try again later')
          }
        }
          
      </script>
      <button hx-on:click="sendRequest()">
        test
      </button> 
```

![image](https://github.com/bigskysoftware/htmx/assets/8631522/8866acf2-983f-47ab-be78-90229c969b14)


Log:
```txt
htmx.org@1.9.6:1     POST https://fiddle.jshell.net/randomPath 404 (Not Found)
ce @ htmx.org@1.9.6:1
wr @ htmx.org@1.9.6:1
sendRequest @ ?editor_console=true:116
eval @ VM71:3
(anonymous) @ htmx.org@1.9.6:1
gr @ htmx.org@1.9.6:1
a @ htmx.org@1.9.6:1
?editor_console=true:72 Response Status Error Code 404 from /randomPath
error @ ?editor_console=true:72
y @ htmx.org@1.9.6:1
fe @ htmx.org@1.9.6:1
ue @ htmx.org@1.9.6:1
Tr @ htmx.org@1.9.6:1
b.onload @ htmx.org@1.9.6:1
load (async)
ce @ htmx.org@1.9.6:1
wr @ htmx.org@1.9.6:1
sendRequest @ ?editor_console=true:116
eval @ VM71:3
(anonymous) @ htmx.org@1.9.6:1
gr @ htmx.org@1.9.6:1
a @ htmx.org@1.9.6:1
/buhf7cza/embedded/:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.

**Comment by danjessen** [comment]
@carlos-verdes could you check with `htmx.logAll()` called before.

**Comment by carlos-verdes** [comment]
I shared a fiddle, I don't know exactly where do you want me to put that sorry

**Comment by nuriaruiz** [comment]
@carlos-verdes  You can put htmx.logAll() inside your function.

I don't know much about the project, but from what I see, the AJAX error is handled by the htmx library, so you don't catch it in the catch block. If you want to capture the error, use one of the events, such as the responseError event.

For example:
 htmx.on("htmx:responseError", function(evt) {
        console.log('Error 404: Recurso no encontrado');
        alert('Recurso no encontrado, inténtalo de nuevo más tarde');
    });

**Comment by carlos-verdes** [comment]
Thanks to both of you, I got some insights after the comments (gracias Nuria)

My new learnings:
- When you call directly `htmx.ajax()` with `hx-on:click` you don't get the normal events like `hx-on:load` on that component, so you need to capture them on the body element or manually call `htmx.process()`
- To capture ajax errors you can't use the `Promise.catch` method but you can register for `hx-on:response-error`. Important to define your target with you make the ajax call so you understand which element/button triggered the error

**Comment by matiboy** [comment]
Hi @carlos-verdes just to mention that 404s and 500s are [not considered XMLHttpRequest errors](https://stackoverflow.com/a/10584491), nor are they rejections in [the newer, promise based `fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful), thus `htmx.ajax`. This is likely the rationale for how `.ajax` behaves. The actual error is however not passed down to the `reject` of the promise, which is a shame.

You would see an error in your catch if you were to point your call to something that doesn't allow CORS e.g. google.com or used Chrome dev tools's throttling set to "Offline"

Glad to see you figured out how to solve your problem with htmx's events 👍

**Comment by carlos-verdes** [comment]
Yeah, thanks for the answer in any case I'm closing this issue, still I would love to see my other issue addressed (chunk http responses)
