### ISSUE TITLE
Custom Form Serialization

### ISSUE THREAD

**Issue by StephanSchmidt** [bigskysoftware/htmx#1909]
If I have my own function that turns a form into JSON e.G. serializeForm(form) (with some type conversion etc), can I plug this in before a POST request is send? 

I've looked at json-enc but could not figure out how to adapt, e.g. get a ref to the form.

**Comment by najamkhn** [comment]
Just looking at the documentation, seems like it is possible to do it with [beforeSend](https://htmx.org/events/#htmx:beforeSend). Have you tried it already?

**Comment by StephanSchmidt** [comment]
I got it working with

        encodeParameters : function(xhr, parameters, elt) {
            xhr.overrideMimeType('text/json');
            let form = formToJson(elt)
            return (JSON.stringify(form));
        }
