### ISSUE TITLE
Request fails with Uncaught TypeError: XMLHttpRequest.setRequestHeader: Cannot convert argument 2 to ByteString

### ISSUE THREAD

**Issue by tommsawyer** [bigskysoftware/htmx#191]
![error image](https://i.imgur.com/s35TLFG.png)

Minimal reproducable code:

```
<script src="https://unpkg.com/htmx.org@0.0.8"></script>

<form hx-post="/submit" hx-swap="none">
	<input type="text" name="input" value="привет"/>
 </form>
```

I think the problem is that the field value is not just plain ASCII, but contains cyrillic letters. HTMX trying to set this value to the `HX-Active-Element-Value` header, which is invalid, because header should contains only ASCII.

I am wrapping header with `encodeURI` to workaround this problem [here](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1497), but I believe this will break existing users of htmx. Any ideas how to fix this? Thanks

**Comment by 1cg** [comment]
Seems like it's reasonable to have a try/catch and URL encode the header if this exception occurs.  Existing users would be unaffected and it would work reasonably well for people using non-ASCII values

**Comment by 1cg** [comment]
Another option would be to support a `urlEncodeHeaders` option in the htmx config

That might be better since you wouldn't need to check if the header was encoded or not on the server side every time, you'd just know.

**Comment by 1cg** [comment]
I can't really make sense of it, but this RFC is for non-ASCII header support:

https://tools.ietf.org/html/rfc5987

**Comment by 1cg** [comment]
OK, we now auto-encode when an exception occurs, which should preserve the current behavior for ASCII users but transparently fall back to URI encoding when needed

URIDecoding is a no-op on ASCII characters, so you can safely URI-Decode stuff on the server side.
