### ISSUE TITLE
htmx:afterSettle event print same value for evt.detail.elt and evt.detail.target

### ISSUE THREAD

**Issue by fbzyx** [bigskysoftware/htmx#1916]
Hello,

This is a basic question. If i have an element like this:

`              <div id="target-id">
                    <a href="" id="trigger-elt-id" hx-target="#target-id" hx-post="{% url 'iotplot:hx-plot-line-create' %}" hx-swap="innerHTML">Line chart</a>
                </div>
`
and listen to the event like this:

`
    $("body").on('htmx:afterSettle', function(evt) {
          console.log(evt.detail.elt["id"]);
          console.log(evt.detail.target["id"]);
    });
`
My understanding is that these lines of codes should print the following:
console.log(evt.detail.target["id"]);  _should print -> "target-id"_
console.log(evt.detail.elt["id"]);  _should print -> "trigger-elt-id"_       

**but both lines prints "target-id"**

In the [documentation](https://htmx.org/events/#htmx:afterSettle) it says:

_"detail.elt - the element that dispatched the request
detail.target - the target of the request"_

**Comment by andryyy** [comment]
The element triggering the settle is actually your div. And your inner a's target is also the parent div. So they both match.

You may hook to afterSwap or some other event, where the triggering element is somehow involved.
