### ISSUE TITLE
Response Targets Extension Does Not Work on Elements With hx-select

### ISSUE THREAD

**Issue by josephetareh** [bigskysoftware/htmx#1939]
Is it possible to use the response redirects extension when hx-select is used as well. Been trying it out and it doesn't seem to work. 

**So This Works:**

```
<div hx-ext="response-target">
   <div hx-post="/page" hx-target="#content" hx-target-5*="#error">click me<div>
</div>
```

**But This Does Not Work For Me:**
```
<div hx-ext="response-target">
   <div hx-post="/page" hx-target="#content" hx-select="#other-content" hx-target-5*="#error">click me<div>
</div>
```

Obviously, the `hx-select` seems to be the culprit here. Anyone figure out a way to work around this?

**Comment by vb8448** [comment]
I have the same issue and reason is that you don't have `#other-content` element in your server response.

I found a workaround adding the `HX-Reselect` response header. I'm using django and wrote a custom middleware to do it:

```
class HtmxReselectMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        if response.status_code >= 400:
            response["HX-Reselect"] = "*"  # this means everything, if you put something like 'body' it won't work.
        return response
```


I wonder if there is a way override the hx-select attribute without involving the server.

**Comment by josephetareh** [comment]
Thanks @vb8448 the Middleware solution worked perfectly for me. I did try the eventListener solution but wasn't really able to get that to work though. But fine with the Middleware solution for now
