### ISSUE TITLE
Warning while vite compiling

### ISSUE THREAD

**Issue by athulrajdr** [bigskysoftware/htmx#1944]
node_modules/htmx.org/dist/htmx.min.js (1:5151) Use of eval in "node_modules/htmx.org/dist/htmx.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.
<img width="651" alt="image" src="https://github.com/bigskysoftware/htmx/assets/7678226/540bdadf-985f-4682-bf87-5f8dee4bb427">

**Comment by alexpetros** [comment]
🤷 we use `eval` for attributes where you can write JS. There is an `allowEval` config that allows you to turn it off. Nothing that we can do about Vite warning against it.

**Comment by ColonelThirtyTwo** [comment]
To silence it, alter your `vite.config.js` file:

```js
return {
  build: {
    rollupOptions: {
      onwarn: (entry, next) => {
        if(entry.loc?.file && /htmx\.esm\.js$/.test(entry.loc.file) && /Use of eval in/.test(entry.message))
          return;
        return next(entry);
      },
    },
  },
};
```

**Comment by alexpetros** [comment]
More complete answer on why we use eval here, fyi: https://github.com/bigskysoftware/htmx/pull/1988#issuecomment-1806290317
