### ISSUE TITLE
Esbuild can't import v1.9.7 release

### ISSUE THREAD

**Issue by donchev7** [bigskysoftware/htmx#1955]
I use to install htmx via NPM:

```
npm i htmx.org --save
```

and use it in my frontend with TypeScript bundled with **esbuild**:

**index.ts**
```
import htmx from 'htmx.org'

function updateLimit() {
  const newLimit = calculate()
  if (newLimit === limit) return

  const el = document.getElementById('status')
  if (!el) return

  limit = newLimit
  htmx.trigger(el, 'limitchange', { limit })
}

...
```

Now when I updated to 1.9.7 from 1.9.6 I get this error:
```
✘ [ERROR] No matching export in "node_modules/htmx.org/dist/htmx.min.js" for import "default"

    static/index.ts:2:7:
      2 │ import htmx from 'htmx.org'
        ╵        ~~~~
```

I looked at the changes from 1.9.6 -> 1.9.7 but couldn't find any changes that might cause this issue.

**Comment by cethien** [comment]
same issue here. some additional info:
- pnpm works, but getting "no import"-error on "hyperscript.org"-package
- bun has no problems at all

**Comment by alexpetros** [comment]
I think this will resolve it: https://github.com/bigskysoftware/htmx/pull/1968

**Comment by donchev7** [comment]
Can confirm 1.9.8 doesnt have this issue anymore. Thanks.

I'll close the ticket.
