### ISSUE TITLE
In Webpack installation, global HTMX properties undefined in 1.9.7

### ISSUE THREAD

**Issue by craiga** [bigskysoftware/htmx#1964]
I've installed HTMX using [the recommended Webpack process](https://htmx.org/docs/#webpack):

```javascript
window.htmx = require("htmx.org");
```

Everything's been hunky-dory until version 1.9.7, in which I can no longer configure HTMX:

```javascript
// Gives Uncaught TypeError: Cannot set properties of undefined
htmx.config.includeIndicatorStyles = false;
```

I suspect this is a duplicate of https://github.com/bigskysoftware/htmx/issues/1955, but I'm not knowledgeable enough to fully understand what's being said in that issue.

**Comment by 1cg** [comment]
Sorry about that folks, will investigate and try to cut a new release tonight.

**Comment by craiga** [comment]
No worries @1cg ! Appreciate all your hard work.

**Comment by donchev7** [comment]
Can confirm 1.9.8 doesnt have this issue anymore. Thanks.
