### ISSUE TITLE
Missing render command

### ISSUE THREAD

**Issue by pradeeproark** [bigskysoftware/htmx#1965]
Is the render command as described in here exported in the distribution on unpkg?

I can't get https://hyperscript.org/commands/render/ to work.

```
<a _="on click render #address-title with (a:1) then put it into #address_type">addressed?</a>

"Unexpected Token : render

on click render #address-title with (a:1) then put it into #address_type
```

**Comment by alexpetros** [comment]
Check out the hyperscript repo here: https://github.com/bigskysoftware/_hyperscript/issues
