### ISSUE TITLE
wrong sha384 integrity hash?

### ISSUE THREAD

**Issue by jblachly** [bigskysoftware/htmx#1971]
tried to use htmx for first time, wasn't working; loaded up javascript console and found:

`None of the “sha384” hashes in the integrity attribute match the content of the subresource. The computed hash is “rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr”.`

The current documentation indicates: 
`<script src="https://unpkg.com/htmx.org@1.9.8" integrity="sha384-EAzY246d6BpbWR7sQ8+WEm40J8c3dHFsqC58IgPlh4kMbRRI6P6WA+LA/qGAyAu8" crossorigin="anonymous"></script>`

**Comment by Crazy3lf** [comment]
It seems like the version in the document is updated without but the integrity is still that of version `1.9.7` in [this commit](https://github.com/bigskysoftware/htmx/commit/6fe62580e001d10b1d6fe4e27e778c3f23bb2f75#diff-e772080787482bb78eeddd4d3c75a4ecd414c5e06674fde21d4383c1c3927735R117).

@jblachly if you just want it to work, you can change the version back to 1.9.7.
`<script src="https://unpkg.com/htmx.org@1.9.7" integrity="sha384-EAzY246d6BpbWR7sQ8+WEm40J8c3dHFsqC58IgPlh4kMbRRI6P6WA+LA/qGAyAu8" crossorigin="anonymous"></script>`

**Comment by 1cg** [comment]
sorry, sha is updated

man, what a cluster of a release...
