### ISSUE TITLE
Can't combine "closest tr" with another selector

### ISSUE THREAD

**Issue by figjeti** [bigskysoftware/htmx#1974]
Hello,

On a button I attempted to combine the following on an hx-include:

hx-include="closest tr, #id"

this will only include one or the other, whichever is first. If I add custom classes in lieu of "closest tr", it will, it just can't seem to handle both a regular selector and one of the more complex ones(ie. closest, find, etc.)

**Comment by alexpetros** [comment]
Closing as a duplicate of: https://github.com/bigskysoftware/htmx/issues/1946
