### ISSUE TITLE
The "revealed" trigger is not working when the element is the first few in the page and not scrolled in.

### ISSUE THREAD

**Issue by hourloop-jeffcai** [bigskysoftware/htmx#1984]
When a element is at the front of page and will be presented on the page instead being scrolled into the page, the "revealed" trigger will not fire.

**Comment by Telroshan** [comment]
Hey, could you by any chance provide a reproducible example, using a codepen or a jsfiddle for example?
This would greatly help identifying the issue!

**Comment by hourloop-jeffcai** [comment]
Closing this issue, seems like that's something to do with my library conflict.

**Comment by hourloop-jeffcai** [comment]
> Hey, could you by any chance provide a reproducible example, using a codepen or a jsfiddle for example? This would greatly help identifying the issue!

Thanks for helping.
