### ISSUE TITLE
Indicator class incorrectly persisting in history snapshot

### ISSUE THREAD

**Issue by piotrpog** [bigskysoftware/htmx#200]
hx-push-url makes snapshot of DOM after htmx-request class is added to loading indicator resulting in situation when someone clicks back button, `htmx-request` class stays in DOM pernamently.

**Comment by bencroker** [comment]
This appears to be a bug that is happening because the history is being saved (https://github.com/bigskysoftware/htmx/blob/v0.1.2/src/htmx.js#L1682) _before_ the request indicator class has been removed (https://github.com/bigskysoftware/htmx/blob/v0.1.2/src/htmx.js#L1762).

**Comment by 1cg** [comment]
fixed in `dev`: https://github.com/bigskysoftware/htmx/commit/bf5e1804acf2431dee7a213f48ad37c1267bc6b4

**Comment by bencroker** [comment]
Excellent!
