### ISSUE TITLE
Who is using htmx in production?

### ISSUE THREAD

**Issue by BTruer** [bigskysoftware/htmx#2006]
Are there any serious startups or businesses using HTMX for their production application (I assume with a backend api framework)? As opposed to next JS or whatever JavaScript framework library, people are using for their web apps these days?

If so are these listed somewhere?

**Comment by Telroshan** [comment]
Hey, see [htmx webring](https://htmx.org/webring/) that lists a few projects!

**Comment by andryyy** [comment]
Im working on an email router, scaleable with a fancy UI using htmx and _hyperscript. 

You can do all the fancy stuff you could do with your own mail server but piggybacked on existing ESPs (optionally) that try to kill open mailing. Looking at you, MS. 

What I learned from previous projects: You do not want to rely on a trend or huge frameworks in general. You will at some point struggle to maintain it. Dependencies are bad. Very bad. htmx offers you a pretty much JS-only dependency which will not break from one day to the other as that would basically kill most websites.

To add to this I feel like heavily backed trend frameworks push you away from programming into being able to configure a foreign product.

Not even talking about costs but nerves; I wouldn’t want to keep track of a gigantic frameworks compatibility that comes with 5 MiB of $things to keep my 50 KiB application alive. 

When you work as freelancer you will find yourself fixing old ass web apps so huge, deprecated and vulnerable that it hurts.

Whatever you decide to use, make sure to plan ahead. :)

**Comment by David-Guillot** [comment]
Hi there,

This should be a discussion, not an issue.

At @contexte we use htmx in production:
* On our website for our search page with faceted search (you can see it live [here](https://www.contexte.com/chercher/) ; type for example `von der Leyen` in the field then press Enter) and some other minor stuff (lazy-loading link previews, etc.) 
* On our B2B SaaS webapp for more major/complex/serious stuff that I described in [this talk](https://www.youtube.com/watch?v=3GObi93tjZI) at DjangoCon 2022

For both usages Django is the "backend" technology.

**Comment by M1Screw** [comment]
I use htmx in https://github.com/Anankke/SSPanel-Uim (A Slim Framework-based PHP project) as a drop-in replacement for existing jQuery code with a standard REST backend, a little bit of extra javascript and it can work just fine.

Learned about htmx because @ThePrimeagen, impressed by its simplicity, fell in love the exact same day. It's like a breath of fresh air inside an endless JavaScript/TypeScript shitstorm.

**Comment by BTruer** [comment]
Thank you! This is not an issue but a discussion so closing this
