### ISSUE TITLE
Is "htmx:confirm" supposed to fire on every htmx request?

### ISSUE THREAD

**Issue by pbouzakis** [bigskysoftware/htmx#2029]
It is not clear from the docs that "htmx:confirm" is fired on every request. 

The docs show the following example, which would have a sweet alert pop-up for every request.

```js
document.body.addEventListener('htmx:confirm', function(evt) {
    evt.preventDefault();
    swal({
      title: "Are you sure?",
      text: "Are you sure you are sure?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    }).then((confirmed) => {
      if (confirmed) {
        evt.detail.issueRequest();
      }
   });
});

```

Here's a simple example demonstrating "htmx:confirm" fires regardless if hx-confirm attribute exists: https://codepen.io/SFSeeger/pen/YzBeJVO?editors=1111

I imagine most developers would expect this to only fire on attributes with the "hx-confirm" attribute set. 

If it is the desired behavior, it might be a good idea to update the docs to show a guard clause and make it more clear that this event is triggered on all requests.

Otherwise, we probably don't need the last parameter in `issueAjaxRequest` and instead can rely on the HTML attribute to dictate the behavior.

**Comment by pbouzakis** [comment]
Looks like this is per design.

**Comment by mkgn** [comment]
I am not sure what was the thought process behind this to make the decision to make hx-confirm this way. However in a real world application, you really don't expect the user to confirm every get/post etc. So, if this fires only for the elements that has the hx-confirm attribute I think that'll be useful and practical. What is the best alternative to achieve this?

**Comment by andryyy** [comment]
Never used it bound to body. But...

You should be able to add a check for e.detail.question and only fire if it's not null. Untested.

**Comment by abe-101** [comment]
```
document.addEventListener("htmx:confirm", function(e) {
    // Check if the question is null or empty
    if (!e.detail.question) {
        // If it is, issue the request directly
        e.detail.issueRequest(true); // use true to skip window.confirm
    } else {
        // If not, show the Swal confirmation dialog
        e.preventDefault();
        Swal.fire({
            title: "Proceed?",
            text: `${e.detail.question}`,
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: "Yes",
            cancelButtonText: "No",
            reverseButtons: true
        }).then(function(result) {
            if(result.isConfirmed) e.detail.issueRequest(true); // use true to skip window.confirm
        });
    }
});
```

**Comment by SFSeeger** [comment]
Alternativly you could use `e.target.hasAttribute('hx-confirm')`, however I'm not sure if this could cause some performance issues. I currently use the following setup for the event:
```javascript
document.addEventListener("htmx:confirm", function(e) {
    e.preventDefault();
    if (!e.target.hasAttribute('hx-confirm')) {
        e.detail.issueRequest(true);
        return;
    } 
    Swal.fire({
        title: "Proceed?",
        text: `${e.detail.question}`,
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Yes",
        cancelButtonText: "No",
        reverseButtons: true
    }).then(function(result) {
        if(result.isConfirmed) e.detail.issueRequest(true); // use true to skip window.confirm
    });
});
```

**Comment by abe-101** [comment]
> Alternativly you could use `e.target.hasAttribute('hx-confirm')`, however I'm not sure if this could cause some performance issues. I currently use the following setup for the event:
> 
> ```js
> document.addEventListener("htmx:confirm", function(e) {
>     e.preventDefault();
>     if (!e.target.hasAttribute('hx-confirm')) {
>         e.detail.issueRequest(true);
>         return;
>     } 
>     Swal.fire({
>         title: "Proceed?",
>         text: `${e.detail.question}`,
>         icon: "warning",
>         showCancelButton: true,
>         confirmButtonText: "Yes",
>         cancelButtonText: "No",
>         reverseButtons: true
>     }).then(function(result) {
>         if(result.isConfirmed) e.detail.issueRequest(true); // use true to skip window.confirm
>     });
> });
> ```
thanks for sharing
I see my issue
I need to put `    e.preventDefault();` before the if clause that is probably the reason for the infinite behaviour

**Comment by mkgn** [comment]
I used a different approach as shown below.

    <button hx-get='/person/delete/id' hx-trigger="confirmed" hx-on:click="showMessage(event,'Ok to delete?')" />

note the use of hx-trigger and onclick function. Then I have a common showMessage() as below

             function showMessage(e,msg) {
                Swal.fire({
                    text: msg,
                    title: 'Please confirm',
                    showCancelButton: true,
                    confirmButtonText: 'Yes',
                    cancelButtonText: `No`,
                }).then((result) => {
                    if (result.isConfirmed) {
                        htmx.trigger(e.target, "confirmed")
                    } 
                })
         }

in the showMessage if it's confirmed, htmx.trigger() is fired against the e.target (the clicked button) with the "confirmed" trigger. This will then "trigger" the hx-get mentioned in the clicked button. In my case since all delete buttons are asking the same message I can make this even more simpler.

**Comment by nickheyer** [comment]
> I used a different approach as shown below.
> 
> ```
> <button hx-get='/person/delete/id' hx-trigger="confirmed" hx-on:click="showMessage(event,'Ok to delete?')" />
> ```
> 
> note the use of hx-trigger and onclick function. Then I have a common showMessage() as below
> 
> ```
>          function showMessage(e,msg) {
>             Swal.fire({
>                 text: msg,
>                 title: 'Please confirm',
>                 showCancelButton: true,
>                 confirmButtonText: 'Yes',
>                 cancelButtonText: `No`,
>             }).then((result) => {
>                 if (result.isConfirmed) {
>                     htmx.trigger(e.target, "confirmed")
>                 } 
>             })
>      }
> ```
> 
> in the showMessage if it's confirmed, htmx.trigger() is fired against the e.target (the clicked button) with the "confirmed" trigger. This will then "trigger" the hx-get mentioned in the clicked button. In my case since all delete buttons are asking the same message I can make this even more simpler.

I did something similar, kind of. 

```javascript

// ON HTMX LOAD CONTENT / AJAX
htmx.on("htmx:load", function () {
  function confirmSwal(promptData, e) {;
    Swal.fire({
      title: "Proceed?",
      text: promptData,
      icon: "question"
    }).then(function (result) {
      if (result.isConfirmed) {
        Swal.fire({
          position: "top-end",
          icon: "success",
          showConfirmButton: false,
          timer: 1500
        }).then(() => htmx.trigger(e.target, 'confirmed'));
      }
    })
  }

  // BIND CONFIRMATION FUNCTION TO ALL DATA-CONFIRM TAGS
  const confirmators = document.querySelectorAll('[data-confirm]');
  Array.from(confirmators).forEach((element) => {
    const promptData = element.getAttribute('data-confirm');
    element.addEventListener('click', confirmSwal.bind(this, promptData));
    element.setAttribute('hx-trigger', 'confirmed');
    htmx.process(element); // HTMX ATTR REQUIRES PROCESSING
  });
});
```

This way, we've essentially replaced `hx-confirm` with `data-confirm`.

Here is it used in HTML (pug...sorry):

```html
    div.powerIcon#powerToggle(
      hx-get="/toggle-power" 
      hx-swap="outerHTML"
      data-confirm=`Turn power ${state.power_state ? 'off' : 'on'}?`
    )
 ```
 
 We've tapped into the htmx load event to re-add the click event listener to the element everytime htmx (or the window itself) brings in new data, even via ajax, etc. In that event listener, we bind the confirmation functionality (with success modal) and the passed in `data-confirm` prompt to the event triggered function. We then tell htmx to only trigger it's request upon recieving a custom `confirmation` event, which is set via `hx-trigger` in our `forEach`. 
 
 Unfortunately, htmx does not allow you to just set an hx-* attribute on an element and expect it to work. You have to `htmx.process(elementWeAreModifying)` for it to populate it's logic through what I imagine is some cached virtual DOM created by the htmx lib. 
 
 I wonder though what kind of performance impact this might have given the post processing and resetting of event listeners - though it may even be pretty close to what is done in native htmx.

**Comment by JanRomero** [comment]
> Looks like this is per design.

But why? It seems to me that this issue is still unresolved. We don’t know why it should fire on every request (even on `hx-trigger="load"` and manual requests using `htmx.ajax()`!) and while I guess the docs are clear, they could be more explicit about it.

Currently the docs say “This event is triggered immediately after a trigger occurs on an element”. If this behaviour is indeed desired, I suppose it should say something like “This event is triggered before **every AJAX request issued by HTMX**”. It would also be nice if the docs showed an example for how to ignore requests without `hx-confirm` as discussed in this thread.

The docs also don’t mention the new-ish `e.detail.question` property.

**Comment by MosesMachua** [comment]
> But why? It seems to me that this issue is still unresolved. 

I agree. This issue is unresolved and should not have been closed. I ran into the same issue recently

[https://stackoverflow.com/questions/78479683/htmxconfirm-event-firing-on-every-ajax-call/78479819?noredirect=1#comment138375768_78479819](url)

**Comment by micka190** [comment]
I ran into an issue [following the official documentation for custom confirm prompts](https://htmx.org/examples/confirm/#vanilla-js-hx-confirm) where doing the `e.preventDefault()` resulted in every single `hx-VERB` attribute to silently fail (i.e. never send a network request) because the implicit `hx-confirm` was being suppressed.

This definitely needs to be more clear in the documentation, at the very least.
