### ISSUE TITLE
Questions about swap and experience with Laravel

### ISSUE THREAD

**Issue by thewebartisan7** [bigskysoftware/htmx#203]
I am playing with all interesting feature of htmx very nice lib, I never hear before about it nor about intercooler.js. I was looking an alternative to livewire because I don't like it too much since I need to change my backend with Laravel controllers and requests with livewire components. And seem Laravel 8 are pushing on that direction. I was searching for something that allow to keep my backend almost nearly the same as now. If someone can share their experience with Laravel, I would like to hear about.

First with tabs that load new tab works fine with below attributes:

```html
                                    <li class="nav-item">
                                        <a class="nav-link"
                                           href="/tab1"
                                           hx-get="/tab1"
                                           hx-trigger="click"
                                           hx-target="#tabs"
                                           hx-swap="outerHTML"
                                           hx-select="#tabs">Tab1</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link"
                                           href="/tab2"
                                           hx-get="/tab2"
                                           hx-trigger="click"
                                           hx-target="#tabs"
                                           hx-swap="outerHTML"
                                           hx-select="#tabs">Tab2</a>
                                    </li>
      <div class="tab-content" id="tabs">
              <div class="tab-pane fade active show" role="tabpanel">
 Tab1 content
                </div>
        </div>
```

How I can replace multiple part of page, for example something outside swap? I see hx-select allow also multiple elements, https://htmx.org/attributes/hx-select/ but can't see example how to do this. I see someone else already asked about and seem pending a solution or there is already a way?

Second things is about submitting forms, I add:

```html
    <div class="page" id="page">
        <form method="POST" action="{{ route('users.update') }}"
              hx-post="{{ route('users.update') }}"
              hx-select="#page">

form content here..
</form>
</div>
```

Works fine, but I am using sweetalert to show message that form is submitted successfully, with normal page load the success message is shown using Laravel sessions() or if I submit form via ajax then I use JSON response of Laravel. I suppose I need to use htmx events https://htmx.org/reference/#events but how to access message returned from server since the response is HTML and not JSON? 

I try also the extension morphdom by hoping that my elements initializes with plugins will works, but seem not, seem that I need also here to use htmx events to re-initialize all plugins, am I right?

Thanks

**Comment by thewebartisan7** [comment]
I see that you are suggesting to reload plugin on htmx:load:

```
 htmx.on("htmx:load", function(evt) {
        myJavascriptLib.init(evt.details.elt);  
  });
```

But this event is fired multiple times for each elements such as scripts, etc using hx-boost.

Seem that htmx:afterRequest is fired only once, so I can reload my main object like:

```html
    <script>
        htmx.logAll();
        htmx.on('htmx:afterRequest', function() {
            App.init()
        });
    </script>
```

**Comment by 1cg** [comment]
Hi There,

`htmx:load` is called on all new content added to the DOM.  You can initialize things **inside** that new content if you are using another javascript library.  You should be initializing only stuff inside the content though:

```js
 <script>
        htmx.logAll();
        htmx.on('htmx:load, function(event) {
            var loadedElement = event.detail.elt;
            initializeContent(loadedElement);
        });
    </script>
```
If you have some sort of global app that is initializing, you probably want to pull that out to a re-entrant function that checks if it has already been initialized and returns first.
