### ISSUE TITLE
using htmx with bulma or other html framework

### ISSUE THREAD

**Issue by acivitillo** [bigskysoftware/htmx#204]
I am testing htmx with Flask and Bulma. I got the below dropdown which is not using the <select> as many web frameworks do. I am wondering how would I pass the value of <a>? On the server side this hx-post doesn't seem to provide any request data. Is there a best practice I am missing? I guess the question is how to pass html element values via post or get to the server via the html request.

```
<div class="dropdown">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Dropdown button</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        {% for item in items %}
        <a href="#" hx-post="/message" hx-target="#message" name="value" class="dropdown-item">
          {{ item.name }}
        </a>
        {% endfor %}
      </div>
    </div>
</div>
```

**Comment by 1cg** [comment]
Typically you would include a form around the elements you'd like to go up with the post and put the hx-post on that form, having it submit all inputs within it.

In this case you might also consider using the following attributes:

https://htmx.org/attributes/hx-include/

or

https://htmx.org/attributes/hx-vars/

both give you the ability to add additional parameters to the submission

**Comment by acivitillo** [comment]
Thanks! The way you manage this open source project is just too good to be true.
