### ISSUE TITLE
Response Targets extension should be mentioned in the homepage

### ISSUE THREAD

**Issue by Sleepful** [bigskysoftware/htmx#2043]
This one:

https://htmx.org/extensions/response-targets/

Why?

Input validation is _The_ most important thing on a web-app. For example, if a login attempt fails, `401 Unathorized` should be the right status code. Returning something like `200` for a failed login attempt is dubious. Like-wise, `422` is a more appropriate response to an invalid form submission than `200`. Additionally, following HTMX philosophy, it makes sense to include the error message in the `body` of the request as HyperMedia. 

But HTMX with its current defaults requires a `200` in order to allow swapping.

**Comment by Telroshan** [comment]
Closing this issue as your PR related to the issue has been merged.

_Also note that merging this extension into htmx's core is being discussed for htmx 2 to have native errors handling support 👀_
