### ISSUE TITLE
hx-trigger="revealed" not triggered in specific divs.

### ISSUE THREAD

**Issue by TownedCrown** [bigskysoftware/htmx#2057]
The containing div has the following css properties:

```
position: absolute;
bottom: 20px;
```

Changing either of those has hx-trigger work as expected.

**Comment by svenberkvens** [comment]
Could you add a little more context or code? It's difficult to help you without just a little more information. Perhaps a codepen or jsfiddle example?

**Comment by TownedCrown** [comment]
Took the code example, placed it in the styled div which was giving me a problem;

https://jsfiddle.net/q50zLuk2/18/

I can probably set up a server to make the demo functional, since I doubt this will help clarify.

**Comment by TownedCrown** [comment]
Changed to `intersect once` in this fiddle; with the same results.

https://jsfiddle.net/glistener/zaLhg6wk/

**Comment by svenberkvens** [comment]
Your jsfiddle works fine for me. **But** I had to add the HTMX script tag, just as in your previous jsfiddle. Without this, HTMX is obviously not active on the page.

```html
  <script src="https://unpkg.com/htmx.org@1.9.9"></script>
```

**Comment by svenberkvens** [comment]
Was your problem solved in the meantime?

**Comment by TownedCrown** [comment]
Yes, it's working.
