### ISSUE TITLE
hx-boost + browser back button = no htmx-swapping body class if link clicked again 

### ISSUE THREAD

**Issue by paulburgess** [bigskysoftware/htmx#207]
Hi, loving HTMX and have hooked up some page transitions to work alongside hx-boost.

On a fresh page load/reload all is fine, htmx-swapping + htmx-settling body classes working fine with a slight delay to allow transitions to complete.

However, if I click a boosted link, hit the browser back button then click any link in the hx-boost group, we lose the htmx-swapping class and it goes straight to htmx-settling. Consequently, half of the page load transition is lost.

The links still work, it's just this stage of the process and class goes missing.

Is this a bug? (or perhaps a cache/history setting I'm missing)

Many thanks!

**Comment by paulburgess** [comment]
hx-boost being applied on a list like so:

`<ul class="team-list" hx-boost="true" hx-swap="innerHTML swap:0.4s settle:0.4s">`

**Comment by 1cg** [comment]
Hi Paul,

That sounds like a bug that was in the pre-0.2 release, where we weren't removing the `hx-request`.  Maybe the history snapshot already has the htmx-swapping class on it?  Can you check what the local history looks like:

```js
parseJSON(localStorage.getItem("htmx-history-cache"))
```

And see if the history element for the given path already has some htmx classes in it?

We may need to scrub additional stuff out of the DOM.

Sorry for the issue and glad to hear you are enjoying htmx.

**Comment by paulburgess** [comment]
Hi 1cg, if I click through to the link successfully, check the history as you say - the htmx attributes are not on that .team-list__list.... does that help? is that what we were after?

![CleanShot 2020-10-11 at 17 30 08@2x](https://user-images.githubusercontent.com/504753/95684167-929c4d80-0be7-11eb-9132-8437c23a04be.PNG)

**Comment by 1cg** [comment]
Is `team-list__list` part of the CSS classes involved in the transition?

I know it's some work, but if you could reproduce on codepen that would help a lot, and I get get a unit test for the situation.

**Comment by paulburgess** [comment]
Hey 1cg, codepen wasn't playing ball with the boosts so I set up an example on my own host:

http://s186971.gridserver.com/htmx/index.html

...and guess what... it works fine.

So I went back to my original example and I've noticed this.

When the page loads, we have this:

`<ul class="team-list__list" hx-boost="true" hx-swap="innerHTML swap:0.4s settle:0.4s">...`

When I go back via the browser... that has all gone from the main parent list and the hx attributes have moved to a span, which is the immediate parent of the link:

`<span class="team-list__text__link" hx-boost="true">
        <a class="btn btn--alt"...` 

So I moved the initial hx attributes there to see if that helped, what's basically happening is if you go back via a browser, the 'hx-swap="innerHTML swap:0.4s settle:0.4s"' attribute drops off...

So why did it work in my other example?

I tried an incognito window - and it all works fine in my original site and the test.

I noticed when making my test that when I went back via a browser, a really old version of the page/content gets cached, that was leading to the issues.

How do we flush the cache for htmx? regular 'Empty Cache and Hard Reload' isn't doing it.

Thanks so much 1cg!

**Comment by paulburgess** [comment]
OK... OK....

`<meta name="htmx-config" content='{"historyCacheSize":"0"}'>`

has fixed it all.... I can set that to 0, reload the page then edit it back to 10 as a way to flush it.

May I ask, what does that number refer to? Default 10 what?

Many thanks!

**Comment by 1cg** [comment]
Hi Paul,

That's 10 slots worth of history, so we store 10 pages in the history cache (otherwise we issue a new GET at the URL and load that content)

It seems like the content coming out of the history cache is wrong.  Do you have any javascript libraries that might be mutating the DOM before saving?

**Comment by 1cg** [comment]
Hi Paul,

Any update here?  I'd like to help if possible.
