### ISSUE TITLE
Pre-swap hook

### ISSUE THREAD

**Issue by alexgagnon** [bigskysoftware/htmx#2073]
Hi there, I'm wondering if there's a way to hook into the time between getting a response and updating the DOM. My particular use case is that I'd like to run some sanitization/processing on the response before swapping it in. Is that doable?

**Comment by svenberkvens** [comment]
There are two events that may be of interest for your use case: [`htmx:beforeOnLoad`](https://htmx.org/events/#htmx:beforeOnLoad) and [`htmx:beforeSwap`](https://htmx.org/events/#htmx:beforeSwap). These events are triggered before the DOM is swapped in. Modifying the response before HTMX processes it further may do what you need.

Another option is to [create an HTMX extension](https://htmx.org/extensions/#defining). If you define a `transformResponse` function, you can influence the response text before it is processed further by HTMX. The nice thing here is that you can selectively use the extension (or not) using the [`hx-ext`](https://htmx.org/attributes/hx-ext/) attribute.

**Comment by alexgagnon** [comment]
Yup, htmx:beforeSwap works like a charm :) thanks!
