### ISSUE TITLE
Pass original trigger-event in htmx events

### ISSUE THREAD

**Issue by alexandergitter** [bigskysoftware/htmx#208]
I am trying to implement an extension that would change a request via the `htmx:configRequest` event. The request gets triggered by a custom Javascript event, which I would like to access in my extension. However, afaict, the data passed in `htmx:configRequest` does not include the original trigger event.
Is it possible to include that, so extensions have access to it?

**Comment by 1cg** [comment]
As luck would have it, I am doing that for an upcoming filtering syntax change in the `feature_event_filtering` branch:

https://github.com/bigskysoftware/htmx/blob/ab88b861095ee1d2644473cf4e9b1d6da0ce59b3/src/htmx.js#L1785

You can work against that branch for now if you want, apologies in advanced if it gets a little bumpy in there.  I don't anticipate that part of the branch to change much though.

**Comment by alexandergitter** [comment]
This is great, thank you! I'll give that branch a try.

**Comment by 1cg** [comment]
This has landed in the `dev` branch and will be in the 0.3 release
