### ISSUE TITLE
DOMException: "The quota has been exceeded" when HX-Push saves HTML content into localStorage

### ISSUE THREAD

**Issue by artjomsimon** [bigskysoftware/htmx#209]
I'm trying to use htmx to implement infinite scrolling.

I have a faceted search feature, and on each request, the backend responds with the content and a `HX-Push` header containing some search parameters in the query so users can copy and paste the search query URL.

After testing this for some time, I've ran into the following error in Firefox:

```
Uncaught DOMException: The quota has been exceeded. htmx.js:1181
    saveToHistoryCache https://unpkg.com/htmx.org@0.2.0/dist/htmx.js:1181
    saveHistory https://unpkg.com/htmx.org@0.2.0/dist/htmx.js:1208
    onload https://unpkg.com/htmx.org@0.2.0/dist/htmx.js:1754
    (Async: EventHandlerNonNull)
    issueAjaxRequest https://unpkg.com/htmx.org@0.2.0/dist/htmx.js:1725
    eventListener https://unpkg.com/htmx.org@0.2.0/dist/htmx.js:777
...
```

Here's the line causing the DOMException:

https://github.com/bigskysoftware/htmx/blob/938130040f13eeee55965a54bb8c9f722315d881/src/htmx.js#L1181

It seems the function `saveToHistoryCache()` fills the limited localStorage with the entire response content if I see this correctly.
I don't understand enough of localStorage to have any idea why this sometimes worked, and then stopped at some point.

Do you have an idea?

**Comment by artjomsimon** [comment]
Additional info: Local Storage, depending on browser implementation, [seems to be limited to about 2-5MB per site](https://web.dev/storage-for-the-web/).

Using [this tool to test fill the storage](https://storage-quota.glitch.me/) I can only add 1MB 5 times until I get the `DOMException` error there.

The infinite scrolling implementation I mentioned above saves an entry per URL that's being pushed. Since I want to update the URL with the search queries the user selects, that's causing the entire HTML response to be stored per URL key, which then fills up the localStorage for this site up very quickly:

![localStorage-cache-full](https://user-images.githubusercontent.com/2609170/95910065-c6ba6e80-0d9f-11eb-9ce6-ad6c1ab692cc.png)

**Comment by 1cg** [comment]
Are the pages very large?  

You can use the [htmx.config.historyCacheSize](https://htmx.org/docs/#config) configuration variable to make the cache smaller in number.

Another option, if the content isn't so large but there is a lot of content around the results, would be to use the [`hx-history-elt`](https://htmx.org/attributes/hx-history-elt/) attribute to narrow down what is snapshotted, however that element needs to be present at all times in order to properly restore history on a back button or history navigation action.

**Comment by 1cg** [comment]
Regardless, we should be catching this exception and not failing when we aren't able to write to the store...

**Comment by 1cg** [comment]
Fixed with https://github.com/bigskysoftware/htmx/commit/d018ef4f0f76ddba86fb2e5656002669422febde

**Comment by artjomsimon** [comment]
@1cg thank you so much for your dedication and continuous support!
