### ISSUE TITLE
Using json-enc on a form, without hx-post (or at least without XHR)

### ISSUE THREAD

**Issue by noteed** [bigskysoftware/htmx#210]
Hi,

I'd like to "enhance" a simple form with htmx so the form posts its body using JSON. I have tried something like

```
<form method="POST" action="/api" hx-ext="json-enc">
    ...
```

but it still posts using `application/x-www-form-urlencoded`.

If I also add `hx-post="/api"`, it uses `application/json` (good) but also uses XHR. I know I can use `hx-target` and `hx-swap` to somehow control where and how the XHR response is used, but I'd like a regular HTTP POST that loads a new page, just like a regular form without using any JavaScript.

Is it possible ?

**Comment by 1cg** [comment]
Hi There,

Unfortunately all requests issued by htmx are going to be XHR.  You could, however, target the body of the page, issue the request and pluck out the body with a selector:

```html
  <button hx-target="body" hx-select="body" hx-post="/api" ...>Load Content To Body</button>
```

Attribute docs:

https://htmx.org/attributes/hx-target/
https://htmx.org/attributes/hx-select/

**Comment by noteed** [comment]
Yes, I guess I can do that, but I also guess that this means removing part of the normal HTML document (the `<head>` for instance), and also that I would have to change the address bar, and manipulate the history...

Thanks for the quick answer.
