### ISSUE TITLE
[BUG] Active Search Demo Initial State Is Blank

### ISSUE THREAD

**Issue by elibroftw** [bigskysoftware/htmx#2126]
I was checking out htmx as I have heard great things but when I went to this demo:

https://htmx.org/examples/active-search/

I saw that the initial list is filtered out already. This isn't exactly what I'd expect from a framework I want to use.

![Screenshot_20231222-194703.png](https://github.com/bigskysoftware/htmx/assets/21298211/17d18b89-c348-4474-bc93-e506732e84ba)

**Comment by ElvisHernandez** [comment]
I was looking into this but I'm a bit confused by the code in `www/content/examples/active-search.md`. Is the `onPost` function actually what's being triggered in production or is that just for development?
