### ISSUE TITLE
Can you select content from the fetched HTML before swapping?

### ISSUE THREAD

**Issue by tronicboy1** [bigskysoftware/htmx#2130]
Hello! Happy holidays.

Is it possible to have selectors on the HTML content you want to swap from a response?

I see that we can use selectors to tell HTMX where we want it to swap in the current DOM, but what about that of the fetched HTML?

**Comment by itepastra** [comment]
I think [hx-select](https://htmx.org/attributes/hx-select/) can be used for your usecase, it can be used to only swap in part of the response (using selectors). 
It is the 'opposite' of [hx-target](https://htmx.org/attributes/hx-target/) which tells HTMX where to put the response.

**Comment by tronicboy1** [comment]
@itepastra 
That was it!! Thank you for your help, really enjoy the philosophy behind htmx.
