### ISSUE TITLE
Why use `var`?

### ISSUE THREAD

**Issue by KTibow** [bigskysoftware/htmx#2137]
HTMX uses `var` in many places. This leads to variable leakage. Oddly, in a couple places it already uses `let` and `const`. Why the inconsistency?

edit: from some short research it seems like IE11 doesn't support the one place where it actually helps leakage, but i'm not entirely sure, would appreciate it if someone who knows more clarified why it's this way

**Comment by sahiljr-111** [comment]
Yes. it is possible to use `var` within the HTMX codebase. it is related to compatibility with IE11

**Comment by lkraav** [comment]
What's the status of phasing out IE11? Is IE11 a requirement of some significant sponsor of this project?

**Comment by andryyy** [comment]
It's planned to be removed from v2 iirc. 

Removing it now would be a disaster and come with a big loss of trust.

**Comment by lkraav** [comment]
> It's planned to be removed from v2 iirc. 
> 
> Removing it now would be a disaster and come with a big loss of trust.

OK. I did a quick search and couldn't locate the epic issue.

Supporting IE11 without transpiling or whatnot has some loss of trust in the other direction.

**Comment by andryyy** [comment]
Sigh. Okay, chief.

**Comment by alexpetros** [comment]
As @andryyy said!
