### ISSUE TITLE
HTMX redirect to difference protocol

### ISSUE THREAD

**Issue by zixsma** [bigskysoftware/htmx#2140]
I am attempting to redirect the user to `http://localhost:8888/login` with a status code of 302 from the request `http://localhost:8888/app/650ac897c70568965390695f/crm/appointments`. 
![Screenshot from 2023-12-29 12-06-27](https://github.com/bigskysoftware/htmx/assets/1133845/a785f020-a256-4c8c-a0aa-e5d8417cda98)

However, HTMX is making a call to `https://localhost:8888/login` instead.
![Screenshot from 2023-12-29 12-07-59](https://github.com/bigskysoftware/htmx/assets/1133845/a5bb608f-07eb-41bf-bd87-9e40b27e829b)

I cannot find any documentation about this. Is this the intended behavior?

**Comment by svenberkvens** [comment]
Not sure whether this is the problem, but I noticed that you're responding with a `Strict-Transport-Security` header for an HTTP (not HTTPS) request. This tells the browser that it must always use HTTPS for this site.

**Comment by zixsma** [comment]
@svenberkvens Oh thank you. I will close this issue.
