### ISSUE TITLE
Support for finite SSE for incremental element building 

### ISSUE THREAD

**Issue by pmeier** [bigskysoftware/htmx#2149]
Currently, the SSE extension seems to be geared to continuous updates from a server. While certainly useful, with the rise of LLMs like ChatGPT there is another use case for SSE: since the full generation of a response can take quite some time, most APIs offer the ability to stream it, e.g. [OpenAI](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream) or [Anthropic](https://docs.anthropic.com/claude/reference/messages-streaming). When connecting to the API like that, each event contains part of the message.

I've tried setting up a simple server that has an SSE endpoint, which I want to connect to with `sse-connect`. This endpoint in turn also opens an SSE connection to an LLM API and passes the formatted event back to the UI. Doing so, I hit a few roadblocks:

1. Hitting the endpoint requires user input, e.g. a question, to pass along to my API. I didn't find a way to trigger the request as part of a form submit or the like.
2. Hitting the endpoint is usually done as part of a POST request, but IIUC the SSE extension currently always does a GET request.
3. In contrast to the continuous update case that the SSE extension currently is built for, with LLM APIs the connection is eventually closed. If that happens the client should not try to reconnect as that would trigger another generation. A similar request was already made in #1234, but for the use case here it is not possible replace the form that has the `sse-connect` attribute on it.
4. If my API responds just with plain text, I can do something like

    ```html
    <div
      hx-ext="sse"
      sse-connect="/ui/event-source"
      sse-swap="message"
      hx-swap="beforeend"
    ></div>
    ```

    to build the complete message. But what if response of endpoint `/ui/event-source` contains anything but plain text? For such a case I didn't find a way to build the message by appending, but rather handled the building inside endpoint. For example, instead of sending `foo`, `bar`, `baz`, I'm sending `<p>foo</p>`, `<p>foobar</p>`, `<p>foobarbaz</p>` with `hx-swap="innerHTML". While this is not terribly bad on the API side, it could be quite taxing on the network for longer messages.

Would it be possible to support this other use case for finite SSE as well?

Closing remark: this is my first time trying `htmx` and one of my first steps into the "front end world" in general. Meaning, if one of the points above isn't actually a problem, but just me being a beginner, I'm blaming documentation :upside_down_face: Jokes aside, happy to improve the documentation if someone gives me a pointer how to solve it.

**Comment by pmeier** [comment]
> stream it back progressively to the browser

Indeed that is what I'm trying to do here. Could you elaborate on how you would do this? When trying to find ways to stream data with `htmx`, Google always points me back to SSE. Otherwise I only found solutions in JS.

> or wait til it finishes and send it all back as one fragment.

That is what I want to avoid. Depending on the length of the question and generated answer, this might take 30+ seconds. And I don't want a user to stare at the screen for that long to await a giant wall of text. This is bad UX especially because the chunks are available after a short delay and the user knows that, since that is what the LLM providers do in their own UIs.

**Comment by pmeier** [comment]
After some more research, I found a clean way to get what I want with the current way SSE works using [named events](https://htmx.org/extensions/server-sent-events/#receiving-named-events). I have something like this in my body

```html
<form hx-post="/answer" hx-target="#chat-feed" hx-swap="beforeend">
  <input type="text" name="prompt" placeholder="Ask a question" />
  <input type="submit" value="Send" />
</form>
<div id="chat-feed" hx-ext="sse" sse-connect="/events"></div>
```

Posting to `/answer` returns something like

```html
<div><b>User</b>: $prompt</div>
<div sse-swap=$id hx-swap="beforeend"><b>Assistant</b>: </div>
```

where `$id` is a unique ID I generate on my server. Simultaneously this fires off a background task to post the question to the LLM API, stream it back to my server, and add new named events with `$id` to `/events`.

Here is the result with dummy return values rather than hooking it up completely:

[Screencast from 2024-01-05 11-52-06.webm](https://github.com/bigskysoftware/htmx/assets/6849766/b14fc746-045b-4197-af89-7280105a957b)

Still, thanks for the input @nickchomey!

**Comment by robvanvolt** [comment]
> After some more research, I found a clean way to get what I want with the current way SSE works using [named events](https://htmx.org/extensions/server-sent-events/#receiving-named-events). I have something like this in my body
> 
> ```
> <form hx-post="/answer" hx-target="#chat-feed" hx-swap="beforeend">
>   <input type="text" name="prompt" placeholder="Ask a question" />
>   <input type="submit" value="Send" />
> </form>
> <div id="chat-feed" hx-ext="sse" sse-connect="/events"></div>
> ```
> 
> Posting to `/answer` returns something like
> 
> ```
> <div><b>User</b>: $prompt</div>
> <div sse-swap=$id hx-swap="beforeend"><b>Assistant</b>: </div>
> ```
> 
> where `$id` is a unique ID I generate on my server. Simultaneously this fires off a background task to post the question to the LLM API, stream it back to my server, and add new named events with `$id` to `/events`.
> 
> Here is the result with dummy return values rather than hooking it up completely:
> Screencast.from.2024-01-05.11-52-06.webm
> 
> Still, thanks for the input @nickchomey!

Can you provide the full example maybe? I am struggling to get your video example done using Django + HTMX SSE.
