### ISSUE TITLE
Some events not triggered

### ISSUE THREAD

**Issue by rauwebieten** [bigskysoftware/htmx#215]
I tried to listen for some events, like this:

    document.body.addEventListener('htmx:beforeRequest', function(evt) {
        console.log('htmx:beforeRequest');
    });

    document.body.addEventListener('htmx:afterRequest', function(evt) {
        console.log('htmx:afterRequest');
    });

    document.body.addEventListener('htmx:beforeOnLoad', function(evt) {
        console.log('htmx:beforeOnLoad');
    });

    document.body.addEventListener('htmx:afterOnLoad', function(evt) {
        console.log('htmx:afterOnLoad');
    });

But only beforeRequest and beforeOnLoad are triggered. 

I am missing something?
Any idea?

**Comment by 1cg** [comment]
Can you try this javascript:
```js
  htmx.logAll()
```
And see if the events are triggering?

**Comment by 1cg** [comment]
Any update?

**Comment by lazymood** [comment]
Hi, I'm facing the same issue on a form with these attributes:

`<form
				  hx-post="/Roles/Edit/3" 
				  hx-target="closest .card" 
				  hx-select=".card" 
				  hx-swap="outerHTML" 
				  method="post" 
				  action="/Roles/Edit/3">` 

`afterOnLoad` is never fired, though the `htmx.logAll()` logs the event as expected. 
The issue seems to be related with the `hx-target` attribute (event is fired by removing it).
Using htmx v. 1.0.0
Any suggestion?

**Comment by danjac** [comment]
I'm seeing the same issue. The problem appears if the trigger element is removed by the event (not necessarily the hx-target). I can see the event being logged but the event itself is not fired.
