### ISSUE TITLE
hx-on:htmx:before-request="function defined from x-data object"

### ISSUE THREAD

**Issue by ericxin1982** [bigskysoftware/htmx#2154]
Hi there,

Just wondering if that is feasible, the hx-on:htmx:before-request can trigger a function I defined in x-data (alpinejs) above, like:

<div x-data='{who:"eric",sayhi(){console.log(this.who)}}'
  <button hx-get="/info" hx-on:htmx:before-request="sayhi">
      Get Info!
  </button>
</div>

![image](https://github.com/bigskysoftware/htmx/assets/9047436/fd7b6edd-3e11-4dfa-ab12-bf8a770dd054)

Thanks
Eric Xin

**Comment by itepastra** [comment]
does `hx-on:htmx:before-request="sayhi()"` (or the shorthand `hx-on::before-request="sayhi()"`) not work?

**Comment by ericxin1982** [comment]
sayhi this function is defined inside the related x-data object, I am not sure whether it works. So I am asking who did this before knew it is feasible or not.
