### ISSUE TITLE
Examples mismatch between HTML and server

### ISSUE THREAD

**Issue by makeworld-the-better-one** [bigskysoftware/htmx#216]
In many of the examples, the client side HTML uses `hx-post` but the fake server shows `GET /example?test=foo`. It'd be nice if the server showed proper POST requests for things like forms, etc, to match the HTML.

Thanks for working on htmx, it's awesome!

**Comment by 1cg** [comment]
I'm seeing the right thing in the server output:

![image](https://user-images.githubusercontent.com/469183/98262288-aca92180-1f42-11eb-81d1-7e809cd1f0bc.png)

Where are you seeing this?

**Comment by makeworld-the-better-one** [comment]
Guess it's not happening with all examples. But the [inline validation](https://htmx.org/examples/inline-validation/) one mentions POSTing to `/contact/email` in the HTML, but then shows GET in the server log.

**Comment by 1cg** [comment]
Ahh, looks like a bug in the example code

Fixed now
