### ISSUE TITLE
How to include `input` information to `ws-send`? 

### ISSUE THREAD

**Issue by renardeinside** [bigskysoftware/htmx#2165]
Imagine the following code:

```
<input id="schorle-input-4400100224" class="input input-bordered input-primary w-6/12" hx-swap-oob="morph" ws-send="">
```
When I trigger the client-side event, it sends the following:

```
{"HEADERS":{"HX-Request":"true","HX-Trigger":"schorle-input-4400100224","HX-Trigger-Name":null,"HX-Target":"schorle-input-4400100224","HX-Current-URL":"http://127.0.0.1:8000/"}}
```

However, I also would expect some payload from the input itself (e.g. input value), otherwise the `ws-send` becomes quite unuseful...

**Comment by aral** [comment]
Put the input element in a form and the values will be automatically JSON encoded and passed along.

e.g.,

```js
<form ws-send>
  <input name="schorle-input-4400100224" hx-swap-oob="morph">
  <button>Submit</button>
</form>
```

**Comment by aral** [comment]
OK, this is a terribly hacky workaround but what does seem to work is to put a hidden input into the element with ws-send.

e.g., 

```html
<button name='action' ws-send>
  <input type='hidden' name='action'' value='cancel'>
  Cancel
</button>
```

**Comment by andryyy** [comment]
I think you need to add type="submit" to your button.

**Comment by andryyy** [comment]
Did you try adding the type to the button as suggested previously?

I encountered a similar behavior in a form today. Without type it would just submit and omit the k:v.

**Comment by renardeinside** [comment]
hi @andryyy , 

it works for me with the following setup:
```html
<div class="flex flex-row w-3/4 justify-center items-center space-x-4" hx-swap-oob="morph">
    <input placeholder="Add a todo" value="" hx-include="this" name="default" class="input form-control input-bordered" id="sle-input-35cad06c" hx-swap-oob="morph" ws-send="" hx-trigger="change" />
</div>
```

I receive the following message:
```
 {"default":"123","HEADERS":{"HX-Request":"true","HX-Trigger":"sle-input-35cad06c","HX-Trigger-Name":"default","HX-Target":"sle-input-35cad06c","HX-Current-URL":"http://127.0.0.1:8000/","HX-Trigger-Type":"change"}}
```
