### ISSUE TITLE
Missed syntax errors in test/ext/sse.js

### ISSUE THREAD

**Issue by Renerick** [bigskysoftware/htmx#2167]
https://github.com/bigskysoftware/htmx/pull/2025#pullrequestreview-1809784832

Aside from fixing the tests, need to ensure that CI will not pass if similar problem occur in the future

**Comment by hawi19952** [comment]
Hi, 
I think adding eslint to the project can be a viable solution and coupling that with the CI pipeline, so the pipeline doesn't approve unless the linter rules are passed. 

I'm not sure if that aligns with the philosophy of the maintainer, however, I'll give it a shot.

**Comment by hawi19952** [comment]
Something I found out, the code is failing 7 tests, all of which are relevant to the syntax error. 

I'll make the PR now for lint, and will pick up the failing tests later @Renerick
