### ISSUE TITLE
clarify hx-validate documentation

### ISSUE THREAD

**Issue by mvolkmann** [bigskysoftware/htmx#2185]
Currently https://htmx.org/attributes/hx-validate/ says "Form elements do this by default, but other elements do not." Some people interpret "form elements" to mean input, textarea, and select elements. But here "Form elements" only refers to actual `form` elements. I recommend changing that line to the following.

`<form>` elements do this by default, but the form control elements `<input>`, `<textarea>`, and `<select>` do not.
When `hx-validate="true"` is added to form control elements that are configured to send their own HTTP requests, the form control value will be validated before the request is sent.

**Comment by MikeMoolenaar** [comment]
This also confused me, and I didn't know how to use hx-validate (with the value "true") which your text change also solves. I could create a PR if you are ok with that?

**Comment by mvolkmann** [comment]
@MikeMoolenaar That would be great. Thanks!
