### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by makeworld-the-better-one** [bigskysoftware/htmx#219]
It would be nice if the htmx docs had a changelog. It's not obvious what has changed between versions. Will my applications break? Have bugs relevant to me been fixed? What new features can I now use? My apologies if I'm missing one, but I can't find anything on the repo nor the website.

If it's helpful, [here's](https://keepachangelog.com/) a good standard to follow for changelogs. But any non-git-commit based changelog would be appreciated. Thanks!

P.S. the website currently references a non-existent 0.2.1 release, while the latest one is actually 0.3.0.

**Comment by 1cg** [comment]
Thanks for catching that, I have fixed the site.

A changelog shouldn't be too hard to produce from my release notes.  I'll try to get to it soon.

**Comment by makeworld-the-better-one** [comment]
Thanks for the fix!

> release notes

Oh I've never seen these! Pretty much exactly what I'm looking for. Having a single changelog file is nice, but this also works just fine. My problem is that I've never seen or heard of these release notes. Am I missing something obvious? Despite being in `www/`, I can't find them on the website. It would be helpful if these were prominently available on the site.

Relatedly, another great thing would would be to put the text of these in your GitHub releases. This would also change your releases from just plain git tags to full GitHub Releases, which means people could subscribe to updates by clicking "Watch > Releases only".

**Comment by benoit-chabord-cdx** [comment]
I am also using "Watch > Releases only". on github as my main way to stay up to date with projects I care about and I would love to see a changelog in the Github release. As the library matures this will give a lot of confidence for people to try it and not be scared to upgrade versions.

**Comment by 1cg** [comment]
https://github.com/bigskysoftware/htmx/blob/master/CHANGELOG.md
