### ISSUE TITLE
Unable to set port using htmx

### ISSUE THREAD

**Issue by TilP** [bigskysoftware/htmx#220]
Hi, please pardon me if this suggestion is not done correctly, I rarely use Github.

I am a big fan of HTMX, I think it is a great alternative to a lot of the bloated solutions out there.   I am kind'a in a bind.   Wondering how I could set a port without messing with the library.

As you can imagine, the htmx front end would point to a back end but in my case I would run two web servers locally in my dev environment on different ports.

Any guidance appreciated.  Thanks

**Comment by 1cg** [comment]
Hello,

Looking at this post:

https://stackoverflow.com/questions/8317059/relative-path-but-for-port

It looks like you cannot change the port in a relative manner due to security constraints.  So you would need to use fully qualified names to do so unfortunately.

Sorry about that!
