### ISSUE TITLE
Remove delayed events when element is removed

### ISSUE THREAD

**Issue by JakeCoxon** [bigskysoftware/htmx#222]
Hi I'm using the load polling technique to poll for messages like in the example. It works well until the user navigates to another page and it keeps continues polling even after the element is removed. I'd like the delay to automatically cancel if the element is removed.

```
<div hx-trigger="load delay:4s"
```

To me intuitively I would expect the load to be cancelled when the element is removed but I wonder if keeping it is an intentional behaviour, and I wonder if anybody is currently relying on this behaviour so it can't be changed at this point?

I couldn't figure out any hyperscript to remove the event so as a work around I'm manually adding an event listener to set .loaded = true in the internal state but this obviously isn't ideal. Is there a better work around?

Keen to know your thoughts

**Comment by 1cg** [comment]
That seems reasonable to check for.  I would call that a bug, thank you for reporting

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/f7617a4653312e06c62e25eb508aad85af4d746c
