### ISSUE TITLE
Improve on load performance

### ISSUE THREAD

**Issue by mihalikv** [bigskysoftware/htmx#223]
**Problem**:
Initial phase is very heavy and create long function call if page have lot of links/forms. Example profile when running in chrome, throttled by lighthouse:
![image](https://user-images.githubusercontent.com/10236315/98022175-90539a80-1e05-11eb-8b9d-caaf51cf3300.png)
There is just two elements that needs to be processed and have data attribute `hx-get`. However init code also look for link and form elements.

**Solution**:
Is it possible to remove form and link from [initial querySelectorAll](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1170) ? What is purpose have form and link in selector ?

**Comment by 1cg** [comment]
I am being lazy and processing all anchors and forms to see if they are "boosted" by `hx-boost`

Better perf would be to look for [hx-boost] and then find all anchor tags and forms below it.  I will try to get this in the next release.

**Comment by 1cg** [comment]
Fixed in dev:

https://github.com/bigskysoftware/htmx/commit/a599286d5cb71bea5e13efbf9891b6fa861d429b

**Comment by mihalikv** [comment]
Thank you for improvement. I check commit and function isBoosted is called with parameter elt and then in function you are not using it.

**Comment by oko-x** [comment]
@1cg could you please check if that is not a problem ^^?

**Comment by 1cg** [comment]
thanks for catching that, I have removed the unused parameter
