### ISSUE TITLE
htmx-request not being removed from element that has hx-attributes after request is finished

### ISSUE THREAD

**Issue by danielmoessner** [bigskysoftware/htmx#2234]
As one of the CEO's of HTMX I really wanted to know if this HTMX product works. And after months of rigorous testing in production I found weird behaviour.

If the hx-indicator points to a another element which also has hx-get on it. It will not remove the htmx-request attribute after the request is finished.

Here is a js fiddle that proves the point: [fiddle](https://jsfiddle.net/2d6s7g0u/)

Code:

```
<section>
    <div id="first" hx-get="https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/94.svg" hx-trigger="load"
    hx-indicator="#second"
    >
      click me
    </div>
    </section>
    
    <section>
  
    <svg class="w-5 h-5 text-gray-500 animate-spin htmx-indicator spinner hidden [&.htmx-request]:block mt-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" id="spinner">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>
  
    now this button is hidden because htmx-request is not removed from this second element:
    <div id="second" hx-indicator="#spinner" hx-get="https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/94.svg" hx-trigger="click, whatever_done from:body"
    class="[&.htmx-request]:hidden"
    >
      click me
    </div>
    </section>
```

But the second element will stay in this state:
```
<div id="second" hx-indicator="#spinner" hx-get="https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/94.svg" hx-trigger="click, whatever_done from:body"
    class="[&.htmx-request]:hidden htmx-request" <!-- <<<< this htmx-request is not removed (PROBLEM) -->
    >
      click me
    </div>
```

Now why am I using this stuff anyway? Basically to show loading spinners with tailwindcss when some filter requests are in progress.

**Comment by brunopereira27** [comment]
I have the same issue in a case where I use polling

**Comment by sanchawebo** [comment]
Had the same problem with `hx-disabled-elt` on the triggering element.
Got this tempfix from [here](https://github.com/bigskysoftware/htmx/issues/2295#issue-2126797577):
```html
hx-on::after-request="this.classList.remove('htmx-request')"
```

**Comment by danielmoessner** [comment]
Hey thanks! will check it until the end of the year

**Comment by danielmoessner** [comment]
I can confirm it is fixed in version 2.0.3. See: https://jsfiddle.net/4fs3btk8/

Thanks!!

**Comment by Telroshan** [comment]
Hey @gregjotau , could you setup a minimal reproducible example repository, to be able to investigate on that issue?

Could you also try reducing the amount of htmx features used, to determine whether it's a specific one of them that causes this? For example, remove the throttle temporarily, or remove the `aiResponseTextArea`'s own hx-trigger / hx-post, remove the response-targets extension...
Just to try to narrow it down and identify what exactly is happening here!

**Comment by Telroshan** [comment]
Hey @gregjotau, it's likely that this Shoelace error throws an exception and interrupts whatever htmx would do next, such as removing the request class.
I would try solving that error first and see how it goes
Alternatively, you might want to use an unminified version of htmx, and add a try catch block temporarily around the line that currently raises this exception, just to see if explicitly catching & ignoring that Shoelace error fixes the htmx issue you are encountering
Hope this helps!
