### ISSUE TITLE
Proposal: Enhanced Syntax for Target Element in htmx ajax Attribute

### ISSUE THREAD

**Issue by alexisvisco** [bigskysoftware/htmx#2263]
Currently, when using HTMX AJAX parameters such as hx-get, hx-post, etc., users often receive entire responses from servers, even when they only need a specific portion of the content. In some cases, users don't have control over these servers and cannot modify their responses (it's true particulary for creating theme in ghost, wordpress ...). This poses a challenge when developers want to update only certain parts of a page without reloading the entire content.

### Proposed Solution

Introduce support for specifying a target element within the response for partial response handling in HTMX AJAX parameters. This enhancement would empower developers to define precisely which part of the response should be extracted and inserted into the specified target element on the page, mitigating the need to manipulate unnecessary DOM elements by adding some weird events with javascript.

### Example Usage

```html
<button hx-get="/posts?page=2 target:#post-container" hx-swap"..." hx-target="#post-container">Next</button>
```

In this example, the target parameter of the hx-get attribute specifies the ID of the target element within the response where the partial content resides. Only the content of this target element should be extracted and inserted into the #post-container on the page.

### Benefits

- Enhances flexibility for developers dealing with servers that return entire responses, without requiring server-side modifications.
- Allows for precise control over updating specific parts of the page, improving user experience and performance.
- Provides a standardised mechanism for handling partial responses in HTMX AJAX requests, benefiting users across various server-side systems.

**Comment by andryyy** [comment]
Hey, just flew over it, but isn’t "hx-select" the Jedi you are looking for?

**Comment by alexisvisco** [comment]
Oh god why nobody is talking about that ! Thanks you !
