### ISSUE TITLE
HTMX not following Location header (or even HX-Location) when working with a 303

### ISSUE THREAD

**Issue by marco-zan** [bigskysoftware/htmx#2268]
I am following the book quite closely, so i'm using Flask and Jinja2, and edge as a browser (but it doesn't work even on firefox)
HTMX version: 1.9.10

I am trying to make the delete row from table but it does not work as intended (even if 2 times it worked and i don't really know why)

The ui is pretty straightforward:
![image](https://github.com/bigskysoftware/htmx/assets/47862158/cbfbdafe-c67e-46b4-ac72-ea2692044654)

As you can see, the response seems correct.
![image](https://github.com/bigskysoftware/htmx/assets/47862158/5b944d3d-5bd1-4b93-abb2-f13811439e17)

But the page that the browser loads is different, and i don't really know why
![image](https://github.com/bigskysoftware/htmx/assets/47862158/01035b37-2c67-4586-94ce-13b47513dba7)

This is the backend code:
```
@collaborators.route('/<int:id_collab>/', methods=['DELETE'], strict_slashes=False)
def delete_collaborator(id_collab):

    c = db.session.execute(db.select(Collaborator).filter_by(id_collaborator=id_collab)).scalar_one()

    try:
        db.session.delete(c)
    except Exception as e:
        ic(e)
        db.session.rollback();

    else:
        db.session.commit();

    finally:

        resp = make_response(redirect("/collaborators/", 303))
        resp.headers['HX-Location'] = '/collaborators/'
        return resp
```

This is the frontend code. The important part is the ion-icon at the top. It's the icon that once clicked, sends the event

```html
{% macro collabo(c) -%}
<a href="/collaborators/{{ c.id_collaborator }}" class='collaborator-item' >
	<img src="/static/organizer/icons/mechanic.png" alt="Mechanic icon" />
	<p>{{ c.name }}&nbsp;{{ c.surname }}</p>
	<ion-icon 
		name="trash-outline" 
		class='collab_delete_btn'
		hx-delete="/collaborators/{{ c.id_collaborator }}/" 
		hx-confirm='Confermi di voler eliminare {{ c.name }} {{ c.surname }} (id: {{ c.id_collaborator }}) ?'
		hx-target='body' 
	></ion-icon>
</a>
{%- endmacro %}

{% block page_content %}
<script>htmx.logAll();</script>
	<div class='lista-header'>
		<h1>Lista collaboratori</h1>
		<a href='/collaborators/new' class='add-new-btn'>
			<ion-icon name="add-outline" ></ion-icon>
			<span>Crea nuovo</span>
		</a>
	</div>

	<ul>
		{% for c in collab_list %}
		<li>{{ collabo(c) }}</li>
		{% endfor %}
	</ul>
{% endblock %}
```

Nothing crazy, but i really don't know why it does not work.

**Comment by marco-zan** [comment]
Update: somehow it works with `hx-boost='true'` on the body, but i don't understand why

**Comment by marco-zan** [comment]
Ok i see how hx-refresh should do the trick, but the problem here is that it works on the other page:

```html
{% extends "collaborators/collab_base.html" %}

{% block title %}
	{{ c.name }} {{ c.surname or "" }}
{% endblock %}


{% block page_content %}

<ul>
	<li><b>Nome:</b>&nbsp;{{ c.name }}</li>
	<li><b>Cognome:</b>&nbsp;{{ c.surname }}</li>
</ul>

<button 
	hx-delete="/collaborators/{{ c.id_collaborator }}/" 
	hx-push-url='true'
	hx-target='body' 
	hx-swap='innerHTML'
	hx-confirm='Confermi di voler eliminare {{ c.name }} {{ c.surname }} (id: {{ c.id_collaborator }}) ?'
>Elimina</button>

{% endblock %}
```

But i spotted a difference. 

This is the working one
![image](https://github.com/bigskysoftware/htmx/assets/47862158/93889aa4-083c-49ab-9f9e-baa1c4ed4f12)

As you can see, this second one is the bad one. And the difference is that in the first one the request is made by htmx, and here it is made by the browser
![image](https://github.com/bigskysoftware/htmx/assets/47862158/4e13fcdf-eab4-4ccd-bd75-37431d057d46)

Look at the blue icon on the left. Don't know why

**Comment by andryyy** [comment]
Looks like you are using push-url in the second request. Can you try that with the first request, too?

**Comment by marco-zan** [comment]
No differences. It does not work. 
The situation in the exact same as photo 2

**Comment by andryyy** [comment]
The fact it’s an ion-icon component within an "a" being boosted makes me nervous. Can you try and place the delete icon after that "a" it is currently wrapped in and perhaps wrap it in a new "a"? The a should be given the HTMX parameters then. The icon becomes just an icon.

**Comment by marco-zan** [comment]
Man thank you very much, I just moved the ion-icon outside of the `a` and it worked!

I thought that maybe the click event was bubbled out to the `a` but even with `hx-trigger="click, consume"` it didn't work. Even with the page not boosted, and it was strange. But moving the icon out the 4 just solved it
