### ISSUE TITLE
Bug evaluating script tag

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#228]
The <script> tag is only evaluated if it is _not_ the first element in the response.

Works:
```html
<div>
    <script>console.log('yello');</script>
</div>
```

Works:
```html
<div></div>
<script>console.log('yello');</script>
```

Doesn't work:
```html
<script>console.log('yello');</script>
<div></div>
```

Possible reason for this is how the first child is treated differently here:
https://github.com/bigskysoftware/htmx/blob/v0.3.0/src/htmx.js#L543-L545

**Comment by 1cg** [comment]
subtle one

turns out makeFragment() isn't returning the script tag for some reason when we parse the HTML

i had to put some hacks in for table-related stuff, so this might be another special case

**Comment by bencroker** [comment]
Hmm, I'll leave this one to you as not sure where to even start tackling this one.

**Comment by 1cg** [comment]
Fixed with https://github.com/bigskysoftware/htmx/commit/e0b5b52979e9e32c20a7d635d7f9cfef16c0b34e

**Comment by bencroker** [comment]
Thanks!
