### ISSUE TITLE
Add redirect and refresh response headers

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#230]
I know that this has already been discussed in https://github.com/bigskysoftware/htmx/issues/83 and https://github.com/bigskysoftware/htmx/issues/27, but I'd like to make a case for adding redirect and refresh response headers nevertheless.

One problem with relying on an event triggered by the `HX-Trigger` [response header](https://htmx.org/headers/x-hx-trigger/) and then triggering a redirect (or refresh) using JavaScript or hypertext, is that a swap will still occur. If the server response is forcing a redirect using the [302 redirect status response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) then it may also return an empty body, which would result in a janky effect.

Example:

```html
<button hx-get="/redirect">Redirect</button>
```

The server returns an empty body so the button's innerHTML is removed and then the redirect occurs.

```html
<button hx-get="/redirect"></button>
```

By adding `HX-Redirect` and `HX-Refresh` response headers, htmx will be able to bypass the swap and modify the `window.location` as early as possible.

What do you think @1cg?

**Comment by 1cg** [comment]
I am good with `HX-Redirect`

With dependencies removed from htmx core, what would the `HX-Refresh` header do?  Refresh the current page?

**Comment by bencroker** [comment]
Yes, refresh the current page. I guess I misunderstood what `X-IC-Refresh` was doing in intercooler.js, but client-side refreshing of the page seems like a nice feature to add if we're anyway adding the redirect.

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/commit/67e6fc89e1c93624a52d5b32ed551b1387cef95a

**Comment by bencroker** [comment]
YESSSS, thank you!!!
