### ISSUE TITLE
hx-boost: how to update <title>

### ISSUE THREAD

**Issue by danjac** [bigskysoftware/htmx#231]
Is there a way to handle <title> changes when using hx-boost? As per docs, it appears just the <body> inner HTML text is swapped out and the title tag remains the same. Turbolinks also diffs the title to ensure this is updated on page change.

**Comment by bencroker** [comment]
This should probably done using JS using a [htmx events](https://htmx.org/docs/#events).

```html
<script>
htmx.on("htmx:load", function(evt) {
    document.title = "New Title";
});
</script>
```

**Comment by danjac** [comment]
I guessed it was doable in the load event, but this just means duplicating the title somewhere else in the code. Not sure what benefit hx-boost brings here vs turbolinks.

**Comment by 1cg** [comment]
I think it's a reasonable request to look for a <title> tag in the returned content an update the title if it is there.

Due to the way swapping works we would need to parse it out ourselves, but that shouldn't be too hard.

**Comment by bencroker** [comment]
This would work too in the server response.

```html
<script>
    document.title = "New Title";
</script>
```

**Comment by 1cg** [comment]
Implemented with https://github.com/bigskysoftware/htmx/commit/0f72543171c5bc10431d8d4a0439952cb46c79e5

**Comment by bencroker** [comment]
Great, you're on a roll!!
