### ISSUE TITLE
Chain css selectors in hx-target (closest .parent, find .somecontainer)

### ISSUE THREAD

**Issue by schosin** [bigskysoftware/htmx#2316]
Hello,

this issue is closely related to #814, but cannot be solved with the proposed solution in that issue.

Given the following HTML fragment:
```
<div class="card">
    <div class="card-body">
        <span class="only-child">No items yet</span><!-- hidden unless :only-child in parent -->
    </div>
    <div class="card-footer">
        <input hx-post="..." hx-trigger="input[keyCode==13]" name="something" hx-target="..." />
    </div>
</div>
```

I would like to express the following jQuery code in the inputs hx-target:
`$(ev.target).closest('.card').find('.card-body').append(...)`.

I know that I can move the hx attributes to .card and just use `find .card-body`, but I was wondering if chaining multiple hx-target values could be considered. Same could be used for hx-include (don't want to wrap a form around a card, but the "Send" button is in the footer while the inputs are in the body).

**Comment by andryyy** [comment]
Hey, `previous .card-body` or `closest .card > .card-body` would work, wouldn’t they?

**Comment by schosin** [comment]
According to the documentation `previous .card-body` will only search the buttons parent, to .card-footer. I tried `closest .card > .card-body` and sadly it did not work as the button does not have a parent .card-body that has a parent of .card (atleast that's how I understand the current implementation, which makes sense for `previous`)

**Comment by andryyy** [comment]
Previous should scan backwards in DOM no matter the parent. It will stop at the first match. 

Perhaps it needs to be written `closest .card>.card-body`. But again, it might not work having the > symbol. 

Previous should be fine anyway. Does HTMX log a targetError?

**Comment by andryyy** [comment]
But… you may be able to target on closest .card and hx-swap the first .card-body.

**Comment by schosin** [comment]
I might have done something wrong yesterday, `previous .card-body` works, even something like `previous .card-body>.some-container` works fine. Cannot think of a useful use-case for chaining selectors then that wouldn't require some ids.
