### ISSUE TITLE
[2.0.0-alpha2] Form submission issue with multipart/form-data.

### ISSUE THREAD

**Issue by heikkilamarko** [bigskysoftware/htmx#2317]
I have the following form in my app, which includes text and file inputs:

```html
<form
	id="task-new-form"
	enctype="multipart/form-data"
	autocomplete="off"
	hx-post="/ui/tasks"
	hx-target="#tasks-table"
	hx-swap="innerHTML"
>...</form>
```

This code worked flawlessly with htmx version `2.0.0-alpha1`. However, after updating to htmx version `2.0.0-alpha2`, the form submission stopped working. I suspect this issue is related to changes in how `multipart/form-data` is handled in htmx:

<img width="1654" alt="Screenshot 2024-02-14 at 21 08 55" src="https://github.com/bigskysoftware/htmx/assets/3757314/425f040d-fc8c-4ad0-9135-87e4f863843d">

**Comment by heikkilamarko** [comment]
Also reproducible in `[2.0.0-beta2]`.

**Comment by Telroshan** [comment]
Hey, is the request not sent at all, or is it that it doesn't contain the expected payload (in which case, could you provide a screenshot of the generated payload) ? Do you have any error in console or does it fail silently ?

**Comment by heikkilamarko** [comment]
Screenshot for `<script src="https://unpkg.com/htmx.org@1.9.11"></script>`

<img width="1337" alt="Screenshot 2024-04-12 at 17 37 27" src="https://github.com/bigskysoftware/htmx/assets/3757314/307c6d00-2d9f-42d7-9ae5-51464868e468">

Screenshot for `<script src="https://unpkg.com/htmx.org@2.0.0-beta2/dist/htmx.min.js"></script>`

<img width="1334" alt="Screenshot 2024-04-12 at 17 41 04" src="https://github.com/bigskysoftware/htmx/assets/3757314/12895e18-e732-4084-9eae-410fbec9acd8">

**Comment by Telroshan** [comment]
Thanks, could you also show us the full content of the `Headers` tab, to be able to fully compare those 2 requests ?

**Comment by heikkilamarko** [comment]
Headers for `<script src="https://unpkg.com/htmx.org@1.9.11"></script>`

<img width="1215" alt="Screenshot 2024-04-12 at 19 52 19" src="https://github.com/bigskysoftware/htmx/assets/3757314/6aced91f-8ae4-48dc-a9c2-06038cf84233">

Headers for `<script src="https://unpkg.com/htmx.org@2.0.0-beta2/dist/htmx.min.js"></script>`

<img width="1219" alt="Screenshot 2024-04-12 at 19 54 43" src="https://github.com/bigskysoftware/htmx/assets/3757314/fffb3546-554e-43b2-a53e-bebaef7c4c50">

**Comment by heikkilamarko** [comment]
I tried the latest beta. Everything works okay now. Thanks.

**Comment by awall** [comment]
Hi, can we re-open? This bug, or a very similar one, still exists in version 2.0.0. My app works properly again when I revert to 2.0.0-alpha1.

I am trying to submit the contents of a PNG file via POST request using `hx-vals`. My code looks like this:

```
<form
    id="plan-approval-dialog-form"
    hx-ext="ignore:json-enc"
    hx-post="/secure/plans/{{ plan_id }}/approval"
    hx-encoding="multipart/form-data"
    hx-vals="js:{ first: fist.value, second_png: second.value }"
>
``` 

where `first` and `second` are custom web components containing PNG images in the `.value` property.

In the old version, this works flawlessly. In the new version, the contents (`first` and `second`) are just completely missing.

**Comment by Telroshan** [comment]
@awall before we reopen this issue, could you tell me whether it works with the latest version (so `2.0.4` instead of `2.0.0`)? Thanks!

**Comment by awall** [comment]
@Telroshan it appears to work correctly in 2.0.4. So I guess somewhere > 2.0.0 and <= 2.0.4 fixed the issue :)
