### ISSUE TITLE
Add hx-vals attribute

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#233]
We discussed adding a new `hx-vals` attribute that works similarly to `hx-vars` but does not evaluate the input. Instead, it expects valid JSON (optionally surrounded by curly braces) on which it will call `JSON.parse`. 

This is a more secure way of adding values to a request while deterring XSS attacks, especially if there is a chance that the values are coming from user generated input.

**Comment by bencroker** [comment]
Perhaps the input should be in the same format as `hx-vars` which would make it easier to explain (and understand). Unlike `hx-vars`, it will _not_ be evaluated.

```html
<div hx-vals="a: 1, b: 'hello'">
```

Instead of the proposed JSON approach which is more complicated to construct since it requires double quotes:

```html
<div hx-vals='"a": 1, "b": "hello"'>
```

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/5acd554a5cbf4568e91f877f3e9869d6f714e6a4

**Comment by 1cg** [comment]
Coverting from javascript object notation to JSON notation would be a lot of work.  I'd basically need to write my own JSON parser at that point.  :/

**Comment by bencroker** [comment]
Yes, of course it would. This is great as it is, thanks!
