### ISSUE TITLE
UTF-8 encoding problems in sample dataStore

### ISSUE THREAD

**Issue by szepeviktor** [bigskysoftware/htmx#2338]
All non-ASCII characters are double encoded.
https://github.com/bigskysoftware/htmx/blob/0355af9c8ad98a41746de1f182d7ccf0b47c954e/www/content/examples/active-search.md?plain=1#L116

Would you welcome a PR fixing them?

**Comment by szepeviktor** [comment]
```
St. AndrÃ¤
Laives/Leifers
TarnÃ³w
KrakÃ³w
KitzbÃ¼hel
Saint-L?onard
St. Asaph
KarapÄ±nar
Ä°skenderun
Strï¿½e
Schï¿½nebeck
HÃ©rouville-Saint-Clair
```

**Comment by alexpetros** [comment]
Yes, go for it, thank you!
