### ISSUE TITLE
Replace eval() with Function()

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#234]
Replace `eval()` with [Function()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) as recommended in this article:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval.

May also solve https://github.com/bigskysoftware/htmx/issues/213.

**Comment by 1cg** [comment]
Fixed w/ https://github.com/bigskysoftware/htmx/commit/5acd554a5cbf4568e91f877f3e9869d6f714e6a4
