### ISSUE TITLE
SSE Event type always "message"?

### ISSUE THREAD

**Issue by pintomau** [bigskysoftware/htmx#2351]
Hey.

Following the guide in https://htmx.org/extensions/server-sent-events/#receiving-named-events, I'm trying to send named events:

```kotlin

val eventBody = "event: Wololo\ndata: <div>Swapped</div>\n\n"

sseSubscriberRegistrar.sendMessage(userId, eventBody)
```
Tried multiple variants such as "\n\n" at the end and so on...

In the frontend part I have:

```html
<div hx-ext="sse" sse-connect="/subscribe/123" sse-swap="Wololo"></div>
```

However, I always get the `message` type instead of the one properly defined and documented.

Can you please clarify what exactly is the expected format for specific message types?

Thank you.

**Comment by Telroshan** [comment]
Hey, looks like it should indeed work as you expect...
Could you inspect the SSE request's event stream in your browser's developer tools (network tab)?
Is everything normal in there, do you see events and data as they should look like?

**Comment by pintomau** [comment]
Hey @Telroshan , the following is captured:

![image](https://github.com/bigskysoftware/htmx/assets/1271442/6a96d92c-acb1-45e8-87fd-1b76680f573c)

**Comment by Renerick** [comment]
Please provide version information about htmx and sse.js, I'll take a look at it

**Comment by pintomau** [comment]
Hi @Renerick . Using the latest (?) versions:

```html

<script src="https://unpkg.com/htmx.org@1.9.10/dist/htmx.min.js"></script>
<script src="https://unpkg.com/htmx.org@1.9.10/dist/ext/sse.js"></script>

```

**Comment by pintomau** [comment]
Indeed. I dug deeper, and it seems like it's how Spring's SSE Emitter works.

It forces data instead of treating as plain.

For those hitting the same issue, use SseEventBuilder as such:

```kotlin

emitter.send(SseEmitter.event().name("Wololo").data("<div>Swapped</div>"))

```

Thanks for the support.
