### ISSUE TITLE
[BUG] HX-Trigger is not working

### ISSUE THREAD

**Issue by gerbil** [bigskysoftware/htmx#2355]
Can't get **hx-trigger** working in localhost html.. 

1. Tried to add response header.
    I can see response header **Hx-Trigger: myevent**
    But nothing happens for second GET  (only first http://localhost/ns GET is working fine)

```html
<html>
<head>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</head>
<body>
    <div hx-get="http://localhost/ns" hx-trigger="load">Test</div>
    <div hx-get="http://localhost/test" hx-trigger="myevent from:body">Test</div>
</body>
</html>
```

3. Tried to add htmx.trigger("body", "myevent", {});
    Nothing happens for second GET (only first http://localhost/ns GET is working fine)

```html
<html>
<head>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</head>
<body>
    <div hx-get="http://localhost/ns" hx-trigger="load">Test</div>
    <div hx-get="http://localhost/test" hx-trigger="myevent from:body">Test</div>
</body>
<script type="text/javascript">
    htmx.trigger("body", "myevent", {});
</script>
</html>
```

**Comment by Telroshan** [comment]
Hey, for the second option, check out [this JSFiddle](https://jsfiddle.net/kw3p8x46/1/).
It looks like you're firing your `myevent` event before htmx had a chance to initialize the elements, thus to bind to listeners for that event.

As for option 1), what request is sending the `HX-Trigger` here? Is it the initial page request or the `/ns` endpoint that is triggered on load and responds with a `HX-Trigger` header set along?

**Comment by gerbil** [comment]
In first example GET call to http://localhost/ns retrieves back myevent HX-Trigger header with 200 + json.

**Comment by andryyy** [comment]
Nothing logged?

Perhaps a CORS issue depending on what real URLs you are using locally. But that would indeed be logged in the request details via console.

**Comment by gerbil** [comment]
Nothing logged; APIs itself is working fine (like http://localhost/ns for instance); CORS is handled by `gin router.Use(cors.New(cors.Config))`

**Comment by gerbil** [comment]
Em.. i don't think you need backend in order to test minimal **html** setup provided above.
Just create index.html locally with the **html code provided**. It's not working both in Chrome and Firefox.

**Comment by andryyy** [comment]
I was asking because of the exact responses. The headers. But whatever.

**Comment by andryyy** [comment]
See https://gyst.debinux.de/playground

```
@app.route("/out")
async def out():
    if "withevent" in request.args:
        return (
            request.args.get("str", ""),
            200,
            {"HX-Trigger": "myevent"},
        )
    return request.args.get("str", ""), 200


@app.route("/playground")
async def playground():
    return await render_template("playground.html")

```

**Comment by gerbil** [comment]
> See https://gyst.debinux.de/playground
> 
> ```
> @app.route("/out")
> async def out():
>     if "withevent" in request.args:
>         return (
>             request.args.get("str", ""),
>             200,
>             {"HX-Trigger": "myevent"},
>         )
>     return request.args.get("str", ""), 200
> 
> 
> @app.route("/playground")
> async def playground():
>     return await render_template("playground.html")
> ```

Can you please try with just a plain html(x) and **htmx.trigger(document.body, "myevent");** or **real** header HX-Trigger? I can see that simulating header response is triggering the event correctly, but in reality is not.

**Comment by gerbil** [comment]
I finally found it! It's **GIN cors setting -> ExposeHeaders**
This feature controls **Access-Control-Expose-Headers** - so the header is visible in dev console, but not **accessible** !

Suggested **DEV** gin cors settings in this regards:

```go
router.Use(cors.New(cors.Config{
  AllowAllOrigins:  true,
  AllowMethods:     []string{"*"},
  AllowHeaders:     []string{"*"},
  ExposeHeaders:    []string{"*"},
  AllowCredentials: true,
  MaxAge:           12 * time.Hour,
}))
```

**Comment by Telroshan** [comment]
Glad you got it sorted out!

> I've check JSFiddle provided.
Still myevent is not triggered when copied to localhost html.
```
htmx.trigger(document.body, "myevent"); <!-- NOT WORKING -->

document.body.addEventListener("htmx:load", function() { <!- WORKING -->
      htmx.trigger(document.body, "myotherevent");
})
```

Just to make it clear ; it is **normal** that the first line of the above code doesn't work, this is precisely what I was showcasing in that JSFiddle ; firing an event before htmx had a chance to initialize elements, thus bind event listeners to it, will result in those listeners not being called (as they were not created yet at the time the event was fired), thus if you're going to do what you were suggesting in the second option of your initial post, you should rely on the `htmx:load` event before firing such an event.

**Comment by andryyy** [comment]
I can't remember which browser it was, but... I think Chromium prints a big warning about the headers being not processed due to CORS, while Firefox (or vice versa) does not.

Can be quiet frustrating. :)
