### ISSUE TITLE
swap oob still replacing the triggered component

### ISSUE THREAD

**Issue by acivitillo** [bigskysoftware/htmx#236]
I have a button like so:

![image](https://user-images.githubusercontent.com/54931660/99413690-58188580-28f6-11eb-82d2-96050f7388f8.png)

The idea being that whatever is returned by the response is swapped based on `id`. This means I don't need to provide a `hx-target` to this button. I must be doing something wrong because htmx still replaces the button `value` with an empty string after click going from this:

![image](https://user-images.githubusercontent.com/54931660/99414028-aded2d80-28f6-11eb-808d-9f341c50d566.png)

To this:

![image](https://user-images.githubusercontent.com/54931660/99414097-c3faee00-28f6-11eb-9fb4-d717f2576898.png)

**Comment by 1cg** [comment]
`hx-swap-oob` should be on the returned content.  Putting it on the triggering content doesn't do anything:

https://htmx.org/docs/#oob_swaps

The easiest thing would be to return content marked out of band, and then the text "Submit" for the button so the button stays the same:

```html
<div id="whatever" hx-swap-oob="true">This content is swapped into the element with id "whatever"</div>
Submit <!-- This text is inserted into the button, essentially a no-op -->
```
