### ISSUE TITLE
SEO and History API considerations

### ISSUE THREAD

**Issue by BigGitWorld** [bigskysoftware/htmx#237]
Hi!
I'm a **senior java developer** with some experience in javascript frameworks.
I read the htmx doc and really love its idea!

But I did not find any doc about the following topics:
**1. SEO
2. History API (back, forward button) support**

I have developed several SPA applications with:
- java as the back end framework
- vanilla js/jquery pjax libraries (such as jquery-pjax) to have both above concerns.

I always was thinking about this scenario:
- using the best practices in a server-side language (for example JAVA) for business logic (security, caching, database connections, managing ROLES, microservice design and etc) 
- and trust to HTML and/or javascript to do their best effort to have a full stack application **without any extra dependency**

Also one of the main notes for JAVA back end developer is that java have **several powerful HTML template engines** to decorate pages and connect them to the back end logic and return a final HTML as a full page or fragment in the response to AJAX request).

Therefore, I always was thinking about this idea why would I have to use javascript front end frameworks (react-based: next.js, angular and etc) to create a SPA, E-commerce site and etc. and **NEVER DID NOT LIKE DO IT!**
because:
- complexity
- time consuming
- managing two front end and back end server application with different languages and their considerations to have the best practices (not only write a dirty code).
- etc.

But one of the my main concern with my approach is how about my SPA is SEO Friendly or successful in using HTML5 History API.

**Can you please clarify me about two above concerns (SEO and History API support) in Htmx?**

**Comment by 1cg** [comment]
Hi There,

History support is documented here:

https://htmx.org/docs/#history

If you want transparent SEO support, you can use the `hx-boost` attribute to boost anchor tags:

https://htmx.org/docs/#boosting

This will give you pjax/turbolinks like behavior on anchor tags and still allow crawlers that do not interpret javascript to navigate the side.

I am a long time java developer as well, and I hope htmx is useful in that community.
