### ISSUE TITLE
hx-boost encoding "<" in title on htmx.org as &lt;

### ISSUE THREAD

**Issue by adamchainz** [bigskysoftware/htmx#239]
The HTMX site uses hx-boost. If you visit one page and click to another, you'll see the `</>` in the title turns into `&lt;/>`.

**Comment by 1cg** [comment]
Thank you, I noticed that too.  Turns out that `window.document.title` doesn't like html entities...

Fixed with https://github.com/bigskysoftware/htmx/issues/239
