### ISSUE TITLE
Gracefully close SSE connection initiated by server

### ISSUE THREAD

**Issue by roharvey** [bigskysoftware/htmx#2393]
There are use cases where the server should deliver a discrete number of events to the client (e.g. a progress bar). It is not intuitive how to stop this using the SSE extension. I propose this is formalized via a `sse-close` attribute, which identifies an event name that can trigger the client to close the eventSource. This is simpler and more intuitive than other solutions that involve swapping elements (see #1234 and #2149).

**Comment by KianYang-Lee** [comment]
This should be closed?

**Comment by Telroshan** [comment]
Indeed, solved in https://github.com/bigskysoftware/htmx-extensions/pull/13
