### ISSUE TITLE
It should be possible to update location.href by #anchor value which is sent from server side, without actual redirection with entire page reloading

### ISSUE THREAD

**Issue by alexandrustinov** [bigskysoftware/htmx#2399]
For en example, we do have opened page 
    
     https://server.intranet/

and after hx-get or hx-put request we would like to update URL next way, but without entire page reloading:

     https://server.intranet/#modalDialog

That is needed to enable here the CSS selector modalDialog:target, in order to show the modalDialog (please see the examples "CSS only modal dialog").

That can be easily done in Browser's  Console using next code

     location.href = '#modalDialog'

while that is not possible to achieve HTMX way yet.

Actual behavior: response header HX-Redirect allows us to execute next code:

            if (hasHeader(xhr, /HX-Redirect:/i)) {
                location.href = xhr.getResponseHeader("HX-Redirect");
                shouldRefresh && location.reload();
                return;
            }

Though that way browser will be redirected to new location and further target swapping/processing will be stopped.

Expected behavior: It would be nice to have new header HX-Relocate, implemented next way:

                        if (swapSpec.settleDelay > 0) {
                            setTimeout(doSettle, swapSpec.settleDelay)
                        } else {
                            doSettle();
                        }

                        /// patch start
 
                        if (hasHeader(xhr, /HX-Relocate:/i)) {
                            location.href = xhr.getResponseHeader("HX-Relocate");
                        }
                        
                        /// patch end

                    } catch (e) {
                        triggerErrorEvent(elt, 'htmx:swapError', responseInfo);
                        maybeCall(settleReject);
                        throw e;
                    }

So after setting/swapping/etc - the location.href will be possibly updated by HX-Relocate value, if any, to reanchor browser's URL and to enable CSS selector :target processing.

**Comment by alexandrustinov** [comment]
[HX-Location](https://htmx.org/headers/hx-location/) is supposed to act as described above. Response header

         HX-Location: #modalDialog

updates the browser URL, but it does not lead to call at final

          location.href = '#modalDialog' 

so actual the #modalDialog anchor selection does not happen (Chrome Version 122.0.6261.111)

**Comment by andryyy** [comment]
Did you try with `HX-Push-Url`?

**Comment by alexandrustinov** [comment]
I tried everthing that HTMX does offer - nothing works there. 
URL is being changed in browser's Address input field, history was changed and so on. But all that does not lead to final activation of CSS :target selector (most recent Chrome and Firefox both were tried). 
The modal dialog which is supposed to be shown by the :target selected - simply is not being shown as it was expected:


      dialog.modal {
        opacity: 0; pointer-events: none;
        display: flex;
        height: 100%; width: 100%;
        position: fixed;
        top: 0; right: 0; bottom: 0; left: 0;
        z-index: 99999; background: lightgray;
        justify-content: space-around;
        align-items: center;
      }
      
      dialog.modal:target {
        opacity: 1; pointer-events: auto;
        background: rgba(128, 128, 128, 0.5);
      }


As initial excample/root of the CSS only modal dialog tecnique you can refer here: https://codepen.io/lblangenois/pen/MWqGEV

The only option at the moment is patch the which was shown above - after swapping/settling HTMX we just need to execute 

           location.href = xhr.getResponseHeader("HX-Relocate"); 

as final step. Please note that it should be something like 

        location.href = '#modal';

 in order to prevent entire page reloading.

**Comment by alexandrustinov** [comment]
That functionality is not required.
It's much easier to implement modal dialogs using standard .showModal(); call
