### ISSUE TITLE
hx-swap should default to outerHTML if hx-select is set?

### ISSUE THREAD

**Issue by mqudsi** [bigskysoftware/htmx#24]
If you consider that `hx-select` is going to pretty much always be used when your backend is serving a full response rather than a partial response (i.e. for graceful enhancement ajaxification of a regular document that would normally link to a full page), I believe it makes sense for `hx-swap` to automatically default to `outerHTML` rather than `innerHTML` so that the entirety of the element in the response is swapped out one-for-one rather than the element being embedded within itself.

**Comment by chg20** [comment]
I agree that makes some logical sense, but I'm more and more against hidden stuff like this in my old age.  Since the attributes are inherited from parents, I don't think this is too much of a burden.
