### ISSUE TITLE
Kindly explain me how show a progess bar using htmx:xhr:progress 

### ISSUE THREAD

**Issue by Nicero** [bigskysoftware/htmx#240]
Could someone explain me how to use `htmx:xhr:progress` to show a progress bar on file uploads?

Docs say that _htmx fires a htmx:xhr:progress event periodically based on the standard progress event during upload, which you can hook into to show the progress of the upload_. But how do I _hook into_?

I would also like to use [hyperscript](https://hyperscript.org/) for this:
```
<form hx-encoding="multipart/form-data" _on="htmx:xhr:progress 
    IS THIS CORRECT? WHAT SHOULD I PUT HERE?
    ">
    <input id="fileSelect" type="file" name="fileToUpload[]" multiple>
    <button id="uploadButton" type="button"
        hx-post="upload.php"
        hx-target="#image-src"
        hx-trigger="click"
        hx-swap="innerHTML">
        Upload
    </button>
    <progress id="bar" value="0" max="100"></progress>
</form>
```

**Comment by 1cg** [comment]
Hi @Nicero 

Thank you for trying something this advanced with htmx and hyperscript!

I'm looking at the code and I'm not sure that we have all the pieces necessary to make this happen.  Here is what it *should* look like:

```html
<form hx-encoding="multipart/form-data" _on="htmx:xhr:progress(loaded, total) set loaded / total into #bar.value">
    ...
     <progress id="bar" value="0" max="100"></progress>
</form>
```
Unfortunately, looking at the code here:

https://github.com/bigskysoftware/htmx/blob/6c5b99b0cdbb7037272bd732503b947104530fce/src/htmx.js#L2062

And the docs here:

https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent

I think I missed the boat.  The properties `loaded` and `total` are directly on the object, not in the details, as far as I can tell.

Would you be willing to work with me to correct this, maybe with a local copy of htmx, so we can get this working properly?

**Comment by Nicero** [comment]
Hi **1cg**,
I would really love to help you working on you excellent scripts, but unfortunately I do not have enought knowledge of javascript. Sorry.

Yes, properties `loaded `and `total `are directly on the object. Infact debugging your code (at line 2060) like this the two properties are shown:

    forEach(['loadstart', 'loadend', 'progress', 'abort'], function(eventName) {
        xhr.addEventListener(eventName, function(event){
            if (eventName == 'progress') {
                console.log(event.loaded + ' ' + event.total);
            } else {
                triggerEvent(elt, "htmx:xhr:" + eventName, mergeObjects({}, event.detail));
            }
        })
    });

A part from this I don't know how to change your code to fix the issue.

On the other hand if I add a check to the property `lengthComputable` used together with `loaded `and `total `to set up a upload progress bar it is never `true`. Don't know why.

    if (event.lengthComputable) {
        console.log(event.loaded + ' ' + event.total);
    }

If it may help you, the following code explains how `lengthComputable`, `loaded `and `total` are used to calculate a progress bar

    var xhr = new XMLHttpRequest();
    xhr.open("GET", "//christopher5106.github.io/img/mac_digits.png?" + new Date().getTime());
    xhr.onprogress = function (e) {
        if (e.lengthComputable) {
            console.log(e.loaded+  " / " + e.total)
        }
    }
    xhr.onloadstart = function (e) {
        console.log("start")
    }
    xhr.onloadend = function (e) {
        console.log("end")
    }
    xhr.send();

**Comment by 1cg** [comment]
Hi @Nicero,

I have made a change that should enable us to complete this work.  If you grab the code from the `dev` branch, we should be able to put together some hyperscript to get this all working.  Are you interested?

I would love to get an example of this working on the main htmx site.

**Comment by Nicero** [comment]
Hi @1cg ,

Before working on a example that uses _hyperscript_ I prefer to have a working form with progress bar using only _htmx_.
I'm using the `dev` branch oh _htmx_ . Now I would like to get the properties `lengthComputable`, `loaded `and `total` but console outputs `[object CustomEvent]` as explained here [https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent). 

The properties `lengthComputable`, `loaded `and `total` are not returned by _htmx_.

Did I used `htmx.on` correctly or there is another way the read `htmx:xhr:progress`?

```
<form hx-encoding="multipart/form-data">
    <input id="fileSelect" type="file" name="fileToUpload[]" multiple>
    <button id="uploadButton" type="button"
        hx-post="upload.php"
        hx-target="#image-src"
        hx-trigger="click"
        hx-swap="innerHTML">
        Upload
    </button>
    <progress id="bar" value="0" max="100"></progress>
</form>

<script>
    htmx.on("htmx:xhr:progress", function(evt) {
        console.log(evt);
    });
</script>
```

**Comment by 1cg** [comment]
Hi @Nicero,

OK, you can use version `0.4.1` now, I have released that fix.

The information should be on the `detail` property (which is part of the CustomEvent api).  Can you try this:

```js
<script>
    htmx.on("htmx:xhr:progress", function(evt) {
        console.log(evt.detail);
    });
</script>
```

Can you let me know if you are seeing `lengthComputable`, `loaded` and `total` in the event detail property?

**Comment by Nicero** [comment]
Hi @1cg ,

No, `lengthComputable`, `loaded` and `total` are not in the `event detail` property. 
`console.log(evt.detail)` shows this. Properties are ordered alphabetically and you may see that those three properties are not listed.

![Image 5](https://user-images.githubusercontent.com/408118/100102950-94069a00-2e64-11eb-9920-8185e141fb68.png)
![Image 6](https://user-images.githubusercontent.com/408118/100102969-979a2100-2e64-11eb-8129-43475e104e1f.png)
![Image 7](https://user-images.githubusercontent.com/408118/100102977-99fc7b00-2e64-11eb-88ed-2fedafd3af72.png)

**Comment by 1cg** [comment]
OK, that's deeply annoying, especially since I cut a 1.0 without this fix.  :/

I have a fix in dev now, if you want to try that, and I verfied with a test that it works:

https://github.com/bigskysoftware/htmx/blob/dev/test/manual/file_upload.rb

In the dev branch, you have the correct properties needed for the progress bar implementation.

```html

    <form hx-encoding='multipart/form-data' hx-post='/'>
        <input id='fileSelect' type='file' name='file'>
        <button >
            Upload
        </button>
        <progress id='bar' value='0' max='100'></progress>
    </form>
    <script>
        htmx.on('htmx:xhr:progress', function(evt) {
          console.log('Here ' + evt.detail.loaded/evt.detail.total * 100)
          htmx.find('#bar').setAttribute('value', evt.detail.loaded/evt.detail.total * 100)
        });
    </script>
```

**Comment by Nicero** [comment]
The progress bar is now shown, but the actual progress is not displayed correctly: the bar is completed suddently only **after** the file/files have been uploaded. I did my tests on localhost and on my VPS, I tried with one big (24Mb) file and with 160 small files and the behaviour is the same.

On the other hand the following code, for example, shows the progress correctly (or at least in two/three steps if I upload one big file). This means that a real progress can be shown and that we are on the right way but there is still something to adjust.
```
var xhr = new XMLHttpRequest();
xhr.open("GET", "//christopher5106.github.io/img/mac_digits.png?" + new Date().getTime());
xhr.onprogress = function (e) {
    if (e.lengthComputable) {
        console.log(e.loaded+  " / " + e.total)
    }
}
xhr.send();
```

**Comment by 1cg** [comment]
OK, I think I found the issue: I was not adding the listener to the `xhr.upload` object.  I have fixed this in dev and now see a good progress bar.  Can you please confirm?

**Comment by Nicero** [comment]
Hi 1cg,
I'm very pleased to confirm you that the progress bar is now working very well with the `dev v1.0.1 prep` branch. 
Tested with 175 files (=200Mb) and 1 file (64Mb) and the progress is fluent and very precise!

Thank you!

**Comment by 1cg** [comment]
Hmm, I wonder if there is a 0 coming in there for total at some point...

I'll add an issue for hyperscript.  Glad to hear it is working!
