### ISSUE TITLE
Extension `json-enc` is encoding JSON numbers incorrectly.

### ISSUE THREAD

**Issue by mbaraa** [bigskysoftware/htmx#2401]
I tried sending a form with `json-enc`, but a numeric value was sent as a string, like this

![Screenshot from 2024-03-15 17-43-45](https://github.com/bigskysoftware/htmx/assets/26228836/4539a35c-150c-4660-831a-d8b3384d5768)

So, I did a little update to the extension, where I parsed each parameter as a float and if it works, assign the new value, so it's a numeric value, and it worked!

![Screenshot from 2024-03-15 17-44-54](https://github.com/bigskysoftware/htmx/assets/26228836/9449598a-5aa5-426b-adf9-9578d8444c17)

And I'll open a PR with the solution with peace.

**Comment by schungx** [comment]
This would be very dangerous. That means we can no longer input text codes that just happen to contain only numbers, such as zip code and phone numbers.

Unless you smartly distinguish the source of the input and check its `typr` atteibute for `number`.

Sending numbers as text hss been an HTML thing for ages and servers know how to handle them.

**Comment by mbaraa** [comment]
> This would be very dangerous. That means we can no longer input text codes that just happen to contain only numbers, such as zip code and phone numbers.
> 
> Unless you smartly distinguish the source of the input and check its `typr` atteibute for `number`.
> 
> Sending numbers as text hss been an HTML thing for ages and servers know how to handle them.
> 

The server should know how handle them with forms, but I think it should be inferred when dealing with json requests.

And I didn't understand the problem you described with zip codes and phone numbers.

**Comment by schungx** [comment]
Some backend will care.

For example, if you use `axum` and expects payload to deserialize into a struct, then obviously numbers won't fit a string and the conversion will fail.

It'll fail only if the texts contain all numbers, but will succeed if it contains any non digit character.

If you don't think this is a problem then I envy you.

**Comment by schungx** [comment]
For example a phone number with prefixes of `0` will give the server huge headaches whether to reattach zeros or not

**Comment by mbaraa** [comment]
Oh I see, so I was FAFOing around the extension, and found out that the parameter `elt` contains the whole form element, which means we can juice `type` out of it, something like this, what do you think?

![Screenshot from 2024-03-16 15-37-50](https://github.com/bigskysoftware/htmx/assets/26228836/0ad892d0-3019-4ad2-822c-8cdd7c74d87b)

**Comment by andryyy** [comment]
Changing the current behavior is bad. There’s already a modified extension and a related issue somewhere in this repository.

It should be renamed, versioned, etc. 

Changing data types can wreck multiple setups.

**Comment by mbaraa** [comment]
> Changing the current behavior is bad. There’s already a modified extension and a related issue somewhere in this repository.
> 
> It should be renamed, versioned, etc.
> 
> Changing data types can wreck multiple setups.

LOL, forgot about wrecking setups, so it'll stay like this forever, or what?

**Comment by schungx** [comment]
I think detecting `<input type="number">` might be a good thing as that's what trips up a lot of backends which primarily work with JSON instead of HTML form submits...

However, how are you gonna handle `select`'s?  For example:

```rust
<select name="age">
    <option value="30">30 days</option>
    <option value="90">90 days</option>
    <option value="120">120 days</option>
    <option value="180">180 days</option>
</select>
```

Here, the user is obviously selecting a _number_ from a list, but still HTML submits it as text.  The backend server would _love_ to have this as numeric, but how do you detect it?

**Comment by mbaraa** [comment]
> I think detecting `<input type="number">` might be a good thing as that's what trips up a lot of backends which primarily work with JSON instead of HTML form submits...
> 
> However, how are you gonna handle `select`'s? For example:
> 
> ```rust
> <select name="age">
>     <option value="30">30 days</option>
>     <option value="90">90 days</option>
>     <option value="120">120 days</option>
>     <option value="180">180 days</option>
> </select>
> ```
> 
> Here, the user is obviously selecting a _number_ from a list, but still HTML submits it as text. The backend server would _love_ to have this as numeric, but how do you detect it?

I was thinking of something like this

```js
  encodeParameters: function (xhr, parameters, elt) {
    parameters = {};
    for (const input of elt) {
      console.log("type", input.type, "name", input.name, "value", input.value);
      if (!!input.name && !!input.value) {
        let isNumber = false;
        switch (input.type) {
          case "number":
            isNumber = true;
            break;
          case "select-one":
            const tryNum = Number(input.value);
            isNumber =
              input.value == tryNum &&
              input.value.length == tryNum.toString().length;
            break;
        }
        parameters[input.name] = isNumber ? Number(input.value) : input.value;
      }
    }

    console.log(parameters);

    xhr.overrideMimeType("text/json");
    return JSON.stringify(parameters);
  },
```

**Comment by andryyy** [comment]
When I needed it a while ago, I added "data-strict" to corresponding fields and had a listener on configRequest to act on it.

**Comment by mbaraa** [comment]
> When I needed it a while ago, I added "data-strict" to corresponding fields and had a listener on configRequest to act on it.

Is that an htmx or html thing, and how is it used?

**Comment by andryyy** [comment]
I used it as pseudo attribute, it has no meaning. Just as a helper to declare that I want a strict type.

**Comment by mbaraa** [comment]
Oh, I see, but I think this would add unwanted complexity when using forms with htmx.

**Comment by andryyy** [comment]
Yes, but anyway. That’s too fragile. You can have a separate input for the country code and a field for the actual number that is concat‘ed as string in the backend etc., etc. 

Check the existing issue and the other extension.

**Comment by mbaraa** [comment]
> Yes, but anyway. That’s too fragile. You can have a separate input for the country code and a field for the actual number that is concat‘ed as string in the backend etc., etc.
> 
> Check the existing issue and the other extension.

What's the other extension's name?

**Comment by smingam** [comment]
Hi everyone,
I'm facing the same issue. I'm using a go backend with gin and the unmarshalling of number-as-string in the JSON fail when you use Integer or Float types in your structs... Which is perfectly logical, JSON numbers are not string after all, but it's pretty confusing when using bog standard HTML form input type doesn't work as expected. 
`JSON.stringify(parameters)` in [json-enc](https://github.com/bigskysoftware/htmx/blob/8e26d12c33caf7dc99c49d4918e7b8abd8028f98/src/ext/json-enc.js#L10C17-L10C43) would work as it should if only parameters could be Numbers, which is not the case currently.

I've found that the best place for a change is in `processInputValue` : https://github.com/bigskysoftware/htmx/compare/master...smingam:htmx:smingam-patch-fix-input-number
It's just a quick test, I should probably check valueAsNumber for NaN. 
What do you think ? In my case, I just need input of type number to be encoded as number in JSON (as it should, IMHO).

**Comment by mbaraa** [comment]
> Hi everyone, I'm facing the same issue. I'm using a go backend with gin and the unmarshalling of number-as-string in the JSON fail when you use Integer or Float types in your structs... Which is perfectly logical, JSON numbers are not string after all, but it's pretty confusing when using bog standard HTML form input type doesn't work as expected. `JSON.stringify(parameters)` in [json-enc](https://github.com/bigskysoftware/htmx/blob/8e26d12c33caf7dc99c49d4918e7b8abd8028f98/src/ext/json-enc.js#L10C17-L10C43) would work as it should if only parameters could be Numbers, which is not the case currently.
> 
> I've found that the best place for a change is in `processInputValue` : [master...smingam:htmx:smingam-patch-fix-input-number](https://github.com/bigskysoftware/htmx/compare/master...smingam:htmx:smingam-patch-fix-input-number) It's just a quick test, I should probably check valueAsNumber for NaN. What do you think ? In my case, I just need input of type number to be encoded as number in JSON (as it should, IMHO).

Wow this sounds promising, I kinda should've mentioned that I'm using a Go backend, let's hope they accept your changes 😬

**Comment by 1cg** [comment]
do I understand correctly that the behavior is as expected and this would break things if we changed it?

**Comment by mbaraa** [comment]
it does break backward compatibility, but I think this is the correct behavior of a multipart-form to json, since the current solution only maps values to json, and this might be problematic for strict backends like Go's, the breaking compatibility part is really what's stopping this change :(

**Comment by schungx** [comment]
It'll break compatibility with HTML forms behavior, which has been text-based for all of eternity.  Remember that in the beginning there was no `number` type, in fact the `type` attribute was a later addition.  So for compatibility's sake, they made everything text so "older" browsers can handle the new HTML pages by ignoring the `type` attribute.

If you change how this is handled, then future maintainers may not know that you've broken from standard and cause unforeseen problems.  The benefits of a "standard" is that it is ... standard, and predictable.  You don't break from standard just because you don't like it, like swapping the gas paddle with the break in a car just because you think it is better -- other people driving your car will have a nasty surprise.

**Comment by smingam** [comment]
> It'll break compatibility with HTML forms behavior, which has been text-based for all of eternity. 
I agree, but we are talking about JSON here, which is also a standard, that htmx is breaking. You are using Javascript to get the values from the form, and they are "typed", it's too bad your throwing away this information. 
I don't know the htmx code very well, just investigated this issue, but from what I could gather, the only problem is everything is converted to string before it reach the json-enc extension. Which is too bad, because like I said, JSON.Stringify() do the job as it should, if only it had the original objects from the browser. Ideally the json-enc extension should get the forms values before they go through the function "processInputValue". I don't know what's more standard that not modifying the browser behavior...

If my proposal of change in processInputValue is not acceptable, i gladly accept some guidance on how to pass the native form values to the json-enc extension.
