### ISSUE TITLE
Open links like normal but also perform HTMX triggers

### ISSUE THREAD

**Issue by spiffytech** [bigskysoftware/htmx#241]
I have links that should open in new tabs (`target="_blank" rel="noopener noreferrer"`). When the links are clicked I want to report that to the server via `POST` and update page content accordingly. Bonus points if opening the link happens immediately, instead of waiting for the server's response.

If I apply HTMX to my link, the `POST` to the server works fine, but the browser no longer opens the link.

What's the best way to handle this?

**Comment by 1cg** [comment]
Hi There,

So you are trying to both launch the new link and also update content... Hmm.

Maybe some hyperscript or javascript?

```html
<a href="/whatever" hx-post="/whatever" _="on click window.open(me.href)">...</a>
or
<a href="/whatever" hx-post="/whatever" onclick="window.open(this.href)">...</a>
```

Not tested, but maybe something like that?

**Comment by spiffytech** [comment]
I went ahead with (2), just with `addEventListener` instead of `onclick`. It's working okay, but it would be nice if I could do `hx-boost="false"`. It'd be simpler, but also this feels like I'm kinda fighting HTMX a bit to do this.

**Comment by 1cg** [comment]
You can definitely do `hx-boost='false'` to deboost the anchors.

Maybe what you want is to put an `hx-post` on a parent element, record the click with that (it should still trigger) and return a `204` response code (no content) for the post?

But if what you have is working, no need to fight with it.
