### ISSUE TITLE
Form element behaving oddly when using hx-get requests and hx-select

### ISSUE THREAD

**Issue by cbmeeks** [bigskysoftware/htmx#2424]
I have a layout somewhat like this:

    <form id="search-form" 
                hx-get="/search" 
                hx-target="#amd-table"
                hx-trigger="change"
                hx-replace-url="true"
                hx-swap="outerHTML"
                hx-select="table">

                <div>.... various search elements .... </div>
                <table id="amd-table">....</table>
                
                <div id="blah"
                        hx-get="/someurl"
                        hx-target="#blah"
                        hx-trigger="click"
                        hx-swap="outerHTML">
                        Click me!
                </div>
    </form>

When click the "Click me!" div, the entire "blah" div will disappear.  Completely.  Even though the response from the server returned the correct HTML.

However, if I remove the `hx-select="table"` from the outer form, it works.  However, I loose the functionality of the various search boxes, etc. inside the form.  And the URL is replaced with the BLAH's "/someurl" URL.

This particular app has lots of search filters inside that form and moving the "blah" div outside the form breaks everything (it's a part of the search form too).

Any ideas how to handle this?

Thanks

**Comment by andryyy** [comment]
One way would be to add hx-disinherit="*" to the div. Can you give it a try?

**Comment by cbmeeks** [comment]
Well, adding that to the DIV did not fix the problem.  But adding it to the outer form did.
Is that correct?

I mean, it seems to be working now.  ;-)

**Comment by andryyy** [comment]
That’s good! I forfeiting has to be placed on the parser.  :)

**Comment by cbmeeks** [comment]
Sweet.  Thanks for the help!
