### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by tomberek** [bigskysoftware/htmx#244]
It sometimes makes it hard to apply an extension or certain attributes when they are automatically inherited by children and when those attributes are not wanted at that lower level. I'm not sure there is a clean design to opt-out of hx-attribute inheritance.

**Comment by 1cg** [comment]
Hey Tom,

Can you give me some examples? 

Maybe hx-ext needs to support a `-` syntax too?

```html
<div hx-ext='-some-ext' ...>...</div>
```

**Comment by tomberek** [comment]
My example involved using `client-side-templates` and a custom extension for a component that transforms the raw text to the right kind of JSON (newline delimited info into an array of lines).

Inside that component I wanted a `hx-get` to bypass this processing and just display the raw result. My workaround for the situation was to add a conditional into my custom extension that detected if the element had the right hx-ext attribute.

**Comment by bencroker** [comment]
@tomberek does setting `hx-ext=""` not oveerride the inherited behaviour?

**Comment by benpate** [comment]
@bencroker -- It doesn't look like setting `hx-ext=""` would override the inherited behavior. The `getExtensions` function just [appends extensions to the list from its parents](https://github.com/bigskysoftware/htmx/blob/c0f1e06eab0c7d510e1d8ee95f84ff443a7ede70/src/htmx.js#L2142).  An "override" should be easy to add in, but it's not there now.

**Comment by bencroker** [comment]
Thanks for clarifying @benpate!

**Comment by 1cg** [comment]
I would like to introduce a syntax for disabling an extension at a given point.  I don't think just having a blank `hx-ext` attribute is clear enough.  Some proposals:

```html
  <div hx-ext="ignore my-ext">...</div>
  <div hx-ext="remove my-ext">...</div>
  <div hx-ext="exclude my-ext">...</div>
  <div hx-ext="disable my-ext">...</div>
```

I like `ignore` the best, the other ones seem to imply a more global disabling of the extension to me.  What do you all think?

**Comment by bencroker** [comment]
`disable` would probably be my first choice, `ignore` second.

**Comment by benpate** [comment]
I'll just add that we use the `command:argument` pattern that we use in other places, and it would be nice to stay consistent with that syntax.  So I'd recommend `hx-ext="disable:extension-name"` or `hx-ext="ignore:extension-name"`.

I'm not to stuck on any particular command.  But fewer letters (and syllables) are usually less cognitive overhead, so I'd vote for "ignore" or "remove" (if we are, indeed, voting)

**Comment by 1cg** [comment]
OK, seems like ranked ordering would give us:
```html
  <div hx-ext="ignore:extension-name" ...>...</div>
```
@benpate you want to take a crack at it?

**Comment by benpate** [comment]
Wait, what?  I was just giving an opinion on the work **other people** should do 😉

Of course. I'm happy to take a shot at this.

**Comment by benpate** [comment]
Since this PR has been merged, I think this issue can be closed.

**Comment by 1cg** [comment]
Agreed!
