### ISSUE TITLE
Microsoft Edge ignoring `hx-history="false"`

### ISSUE THREAD

**Issue by 22ispencer** [bigskysoftware/htmx#2445]
I use Microsoft Edge at work and have been working on a new project using HTMX, I'm pretty new to it however when I attempted to use `hx-history="false"` to stop the page from caching an authorized page I noticed that the page was still being cached, because most users don't use Edge I tried this out in both Firefox and Chrome and found the site behaved as expected on these browsers. I know this is an edge case however the back button on the history doesn't seem to be firing a new HTTP request so my authentication middleware cannot prevent the page from loading.

**Comment by Lord-Y** [comment]
I have the same problem on a common page with chrome version `123.0.6312.86` and htmx version `1.9.10`.

**Comment by Lord-Y** [comment]
Alright so for my purpose I added those response headers when returning the html code:
```
responseWriter.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
responseWriter.Header().Set("Pragma", "no-cache")
responseWriter.Header().Set("Expires", "0")
```
and it works.
