### ISSUE TITLE
Improve typings

### ISSUE THREAD

**Issue by tomasvn** [bigskysoftware/htmx#2448]
- According to https://htmx.org/api/#parameters-1 the verb accepts `GET`, `POST` etc.
- Wouldn't be better to type it? Instead of having it as plain `string`?

If this would be welcomed improvement, I am happy to contribute

**Comment by Telroshan** [comment]
Hey, htmx 2 will come with a types refactor across the whole lib, and precisely includes [a type such as the one you describe](https://github.com/bigskysoftware/htmx/blob/dev/src/htmx.d.ts#L61)
```ts
type HttpVerb = 'get' | 'head' | 'post' | 'put' | 'delete' | 'connect' | 'options' | 'trace' | 'patch';
```

**Comment by tomasvn** [comment]
So I will close my issue 👍
