### ISSUE TITLE
What are the mechanics and implications of swapping the contents of the HEAD tag?

### ISSUE THREAD

**Issue by deanebarker** [bigskysoftware/htmx#245]
(I'm really having a wonderful experience with htmx so far, so thank you.)

My question: what performance implications are there in swapping out the entire contents of the `HEAD` tag?

In my response from my server, I include a `HEAD` tag like this:

```
<head hx-swap-oob="true"> ... contents here ... </head>
```

This works beautifully -- in addition to the other swap, htmx also reaches up and swaps out the contents of the `HEAD`. (I'll admit to being shocked. I didn't expect it to "just work.")

But does this actually swap the _entire_ inner HTML of the `HEAD`, and is there a performance penalty there? I feel like doing this would force a reload and recalculation of all the CSS/JS, but perhaps I just don't understand how that works.

In my...head (ha!), I feel like the contents of the existing `HEAD` just need to be "reconciled" against the contents of the new `HEAD`, and some changes need to be made -- usually just the `TITLE` and some `META`. Ideally, the smallest number of changes would be made to make the existing `HEAD` match the incoming `HEAD`.

So, two questions:

1. How does htmx swap out the `HEAD`?  I'm watching in inspector, and I just see the `TITLE` tag change, but that might just be how the inspector UI works -- it only highlights what changes, even though the entire inner HTML was swapped.
2. If I did want more selectively swapping, would [the morphdom extension](https://htmx.org/extensions/morphdom-swap/) be the right way to do this?
3. If morphdom is the right way to do, where to I put the `hx-ext="morphdom-swap"` and ` hx-swap="morphdom"` attributes?  On the `MAIN` element (where the `hx-boost` attribute is) or on the `HEAD` (and which one -- the original, or the incoming)?

**Comment by bencroker** [comment]
The `head` tag is _not_ being swapped out, as you are suggesting. I think you're getting confused by the fact that the `title` tag is being updated, but that is only happening because htmx will change the value of the title if it sees a `title` tag in the response.

> <title> tags in responses will be used to update page titles
Source: https://htmx.org/posts/2020-11-16-htmx-0.4.0-is-released/

You might be able to swap the `head` tag, if you really wanted to, by assigning it an ID, but I haven't tested this. As far as I know, the only way to add tags to the `head` at the moment is to do this using JS:

```js
<script>
    var meta = document.createElement('meta');
    meta.name = "description";
    meta.content = "New page descrition.";
    document.getElementsByTagName('head')[0].appendChild(meta);
</script>
```

**Comment by deanebarker** [comment]
>The head tag is not being swapped out, as you are suggesting.

Yeah, I just realized this. It is _just_ the `TITLE` tag that's swapping (which is a nice feature, BTW, I just wasn't expecting it).

So does "out-of-band" swapping only work by IDs, not by tag names?

**Comment by bencroker** [comment]
> So does "out-of-band" swapping only work by IDs, not by tag names?

Yes, that's correct. Note to @1cg that we should probably document this at https://htmx.org/attributes/hx-swap-oob.

**Comment by deanebarker** [comment]
FYI: my testing indicates that the `HEAD` tag will _not_ swap OOB even if there's an ID on it.

**Comment by deanebarker** [comment]
Here is my truly awful solution. It works, but clearly needs to be refined a bit.

```
htmx.on("htmx:beforeSwap", function(evt) {
    var doc = new DOMParser().parseFromString(evt.detail.xhr.response, "text/html");           
    swapTags("meta[property='dc:date']", doc);
    swapTags("meta[property='og:title']", doc);
    swapTags("meta[property='og:image']", doc);
    swapTags("meta[name='twitter:title']", doc);
    swapTags("meta[name='twitter:image']", doc);
});

function swapTags(path, newDom) {
    var existingEl = document.querySelector(path);
    var newEl = newDom.querySelector(path);

    if(existingEl == null || newEl == null)
    {
        return;
    }
    if(existingEl.outerHTML == newEl.outerHTML)
    {
        return;
    }

    existingEl.outerHTML = newEl.outerHTML;
}
```

**Comment by deanebarker** [comment]
I'm thinking about maybe something like this:

```
<meta name="whatever" content="whatever" data-page-specific="true"/>
<style data-page-specific="true">...</style>
```

Then `htmx:beforeSwap` would remove anything in the existing DOM that carries the `data-page-specific` attribute, and add anything from the response DOM that had that same attribute.

**Comment by deanebarker** [comment]
So, this does work...

```
htmx.on("htmx:beforeSwap", function(evt) {

	var incomingDOM = new DOMParser().parseFromString(evt.detail.xhr.response, "text/html");           

	var path = "head *[data-page-specific='true']";
	document.querySelectorAll(path).forEach(function(e) {
		e.parentNode.removeChild(e);
	});
	incomingDOM.querySelectorAll(path).forEach(function(e) {
		document.head.appendChild(e);
	})
	
});
```

...but, at this point, I'm left wondering if I actually solved a problem or if I just walked in circles back to where I started. I feel like I'm now no better off than if I had just done `hx-boost="true"` on the `BODY` tag and left it at that.

My original goal was this --

To save bandwidth, I wanted to only send back the unique contents of the `HEAD` (the elements specific to this request) and the contents of the `MAIN` (which is the only part of the body which changes from page to page), and skip everything else. I figured I could cut page weight by 50% or more in some cases.

But I ran into some weird issues where my abbreviated htmx response would be used if I pressed the back button (I would see it if I viewed source), and then my server starting caching that and serving it up for non-htmx responses (which may have caused the prior problem).

So I abandoned that and returned to serving up the entire HTML document...which has led me to this "solution" for which the original problem might no longer exist.

I'm going to close this because I've wandered pretty far from the original issue, and the above thread answers all the questions I had when I opened it.

I hope some of this helps someone else.

**Comment by 1cg** [comment]
Hey @deanebarker yes, htmx right now works almost exclusively within the `<body>` tag, with the exception of the title tag, which I handle as a one off to make `hx-boost` a bit friendlier.

IIRC, turbolinks does some management with script tags in the head block to ensure that new javascript libraries are included correctly, but I believe it involves some state where they track which libraries have been already added.  Since htmx is partial-HTML focused, I haven't put as much effort into treating full page responses fully, and the head stuff falls into that category.

That said, what you have looks like an excellent start to a `head` extension:

https://htmx.org/extensions/

Please let me know if you are interested in pursuing that, I'd be happy to help out.

@bencroker you are right, we should document that about OOB swaps.  Looks like we do fire an error if no id is included:

https://github.com/bigskysoftware/htmx/blob/a809743fd36a5477b423c401f77a1c0d9084fa58/src/htmx.js#L436

**Comment by deanebarker** [comment]
>That said, what you have looks like an excellent start to a head extension. Please let me know if you are interested in pursuing that, I'd be happy to help out.

Well, @1cg, I guess my most basic two questions would be:

1. Is `afterSettle` the right event to do this in?
2. Does that event (or any other) get a parsed DOM which includes the `HEAD`?  I parse it myself from the raw Ajax response, because any parsed representation I could find only included the `MAIN`, not the `HEAD`.

**Comment by 1cg** [comment]
Seems like a new event here would be ideal for this:

https://github.com/bigskysoftware/htmx/blob/fda4957d653ebf683d6017c07a6ef34ed2d72983/src/htmx.js#L136

**Comment by bennash** [comment]
This approach is seemingly working out well for myself. I'm returning this in the swap:
<title id="pageTitle"  hx-swap-oob="true">Contact</title>
