### ISSUE TITLE
Allow for multiple elements to be targets

### ISSUE THREAD

**Issue by Ragudos** [bigskysoftware/htmx#2455]
My use case is to target elements with the attribute [data-type="read-notifications"] and remove them from the DOM when 204 is returned. The problem is htmx is probably only doing this:

```js
document.querySelector(attr).remove();
```

It's not selecting all the elements for swapping. The content is properly being removed, but only the first element to be detected by querySelector, which makes my view out of sync with the data on the server.

**Comment by andryyy** [comment]
Or e.innerHTML='' - forgot you were trying to empty them.

**Comment by Ragudos** [comment]
> hx-on::after-request="event.detail.xhr.sta

I'll try this out. I did the same but on a script tag. Thanks!
