### ISSUE TITLE
CDN version of the non-minified HTMX code, please?

### ISSUE THREAD

**Issue by hrstoyanov** [bigskysoftware/htmx#2457]
In the absence of non-minified HTMX in unpkg.com, I am forced to point to the GitHub.com file, which is not the best option.

**Comment by Renerick** [comment]
It's available at https://unpkg.com/htmx.org@1.9.11/dist/htmx.js

**Comment by Renerick** [comment]
tbf, this one's on us, I don't believe this was explicitly mentioned

**Comment by Renerick** [comment]
![image](https://github.com/bigskysoftware/htmx/assets/20725046/e0688b1b-772e-4a2c-87fc-9d9c5d9619b1)
Fixed

**Comment by Renerick** [comment]
This is the exact snippet used in the updated docs, you can see `integrity=` on the screenshot

**Comment by Renerick** [comment]
https://unpkg.com/hyperscript.org@0.9.12/dist/_hyperscript.js 

Also, on unpkg you can open package explorer to see what files are available in the distribution

https://unpkg.com/browse/hyperscript.org@0.9.12/
