### ISSUE TITLE
Don't put blocking <script> in <head>

### ISSUE THREAD

**Issue by niutech** [bigskysoftware/htmx#2473]
You tell users in the [docs](https://htmx.org/docs/#via-a-cdn-e-g-unpkg-com) to insert the `<script src="https://unpkg.com/htmx.org@1.9.11"></script>` in the `<head>`, but it is a well-known web performance bottleneck, because it blocks rendering the web page until the script (hosted on 3rd party server) loads. Please tell users to put the `<script>` before `</body>` or at least use `defer` attribute.

**Comment by Wolf-Quiteque** [comment]
The statement raises a valid concern regarding web performance optimization. Placing scripts, especially those hosted on third-party servers, in the <head> section of a webpage can indeed impact performance negatively by blocking the rendering process until the script is fetched and executed. This can lead to slower page load times and a poorer user experience, particularly on slower network connections.

Moving scripts to the bottom of the HTML document, just before the closing </body> tag, is a widely recommended practice for improving page load times. This allows the browser to render the page content first before fetching and executing scripts, leading to a faster perceived load time for users. Additionally, using the "defer" attribute for scripts can achieve a similar result by instructing the browser to defer script execution until after the document has been parsed, further enhancing performance.

Therefore, it would be beneficial for documentation to advise users to place scripts, such as the one mentioned (https://unpkg.com/htmx.org@1.9.11), before the closing </body> tag or to utilize the "defer" attribute to optimize web performance and enhance user experience. This recommendation aligns with best practices for web development and can contribute to faster page load times and improved overall performance.

**Comment by andryyy** [comment]
This sounds so AI

**Comment by niutech** [comment]
@andryyy AI or not, but the concern is valid.

**Comment by croxton** [comment]
'Best practice' for production use would be to host htmx locally instead of loading it from a CDN, and to use a script tag with the `defer` attribute in the <head> of the document so the script downloads in parallel with the html and is only executed once html parsing is complete.

For reference: https://flaviocopes.com/javascript-async-defer/

**Comment by niutech** [comment]
@croxton So please update the [docs](https://htmx.org/docs/) according to the best practice.

**Comment by croxton** [comment]
Would you feel comfortable making a PR? The docs are all in this repo. Here's the file in question with installation instructions:
https://github.com/bigskysoftware/htmx/blob/master/www/content/docs.md

For documentation PRs please target the `master` branch.

**Comment by alexpetros** [comment]
Closed for this reason: https://github.com/bigskysoftware/htmx/pull/2488#issuecomment-2077699637

**Comment by niutech** [comment]
@alexpetros  I don't get your reason. Could you elaborate exactly which `hx-` functionality doesn't work with `defer`? Here is a [simple demo with `defer`](https://jsbin.com/silahikizi/edit?html,output) which works just fine.

**Comment by alexpetros** [comment]
> This sounds so AI

oh my god I had the same thought

**Comment by croxton** [comment]
> For that reason, I don't necessarily object to adding a note below the installation instructions about defer though, in the same place we suggest that you not load htmx from a CDN.

I agree. A note on this page is all that's required:
https://github.com/bigskysoftware/htmx/blob/master/www/content/docs.md
