### ISSUE TITLE
Debug extension unpkg link broken

### ISSUE THREAD

**Issue by verheyenkoen** [bigskysoftware/htmx#2477]
On the [debug extension docs page](https://htmx.org/extensions/debug/), the link to the unpkg.com CDN is broken: 

```html
<script src="https://unpkg.com/htmx.org@1.9.11/dist/ext/debug.js"></script>
```

Following this links returns a 520 error from CloudFlare. The unpkg CDN URL's for other HTMX extensions works fine though.

I also found another unpkg CDN link on the [github README for the debug extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/debug/README.md), but that also returns this error:

```html
<script src="https://unpkg.com/htmx-ext-debug@2.0.0/debug.js"></script>
```

NOTE: I'm not talking about getting this loaded as a script which can cause other problems. Purely loading these URL's in the browser or via CURL already doesn't work.

**Comment by storeman** [comment]
It's not just the debug extension, the main package doesn't work either:
https://unpkg.com/htmx.org/dist/

**Comment by verheyenkoen** [comment]
That may not be the right URL. The ones no the [Installing page](https://htmx.org/docs/#installing) do work.

**Comment by verheyenkoen** [comment]
Checked again and the CDN does serve the debug extension now, so must have been a temporary issue.
