### ISSUE TITLE
makeTagRegExp not ES5 and IE11 compatible

### ISSUE THREAD

**Issue by Shel-M** [bigskysoftware/htmx#2479]
Utility function makeTagRegExp(tag, global = false) is not valid ES5. 

Function utilizes default parameters and template literals, both of which are invalid in IE11 and throw console errors on Edge in IE mode on script load. 

Under certain scenarios with embedded browser windows in older applications (a daily unfortunate use for my org), this type of error causes a full pop up error message.

![image](https://github.com/bigskysoftware/htmx/assets/46656642/32fbf0c5-2b5c-4885-abb3-7646c04cf136)

**Comment by Telroshan** [comment]
Hey, fixed IE 11 incompatibilies in 1.9.12, it should work properly now.
Let me know!

**Comment by Shel-M** [comment]
That release seems to have fixed it! Thanks much!
