### ISSUE TITLE
afterOnLoad not triggered

### ISSUE THREAD

**Issue by lazymood** [bigskysoftware/htmx#248]
Hi, I'm facing this issue on a form with these attributes:

`<form
				  hx-post="/Roles/Edit/3" 
				  hx-target="closest .card" 
				  hx-select=".card" 
				  hx-swap="outerHTML" 
				  method="post" 
				  action="/Roles/Edit/3">` 

`afterOnLoad` is never fired, though the `htmx.logAll()` logs the event as expected. 
The issue seems to be related with the `hx-target` attribute (event is fired by removing it).
Using htmx v. 1.0.0
Any suggestion?

**Comment by 1cg** [comment]
How are you listening for the afterOnLoad event?  I suspect you are listening for it on the document, but it is being fired on an element no longer in the document.

**Comment by lazymood** [comment]
I was trying to get a custom extension - triggered by the afterOnLoad event - that had access to both the source element (the form) and the target element (the card), but afterOnLoad doesn't. I solved by using the afterSettle event: it exposes the `evt.detail.elt` and the `evt.detail.requestConfig.elt` elements.
Thank you

**Comment by 1cg** [comment]
I believe that these issues are resolved in the last few releases of htmx.  We tightened the trigger logic up quite a bit.
