### ISSUE TITLE
Having a custom event in "hx-trigger" never triggers htmx

### ISSUE THREAD

**Issue by zilti** [bigskysoftware/htmx#249]
As the title says, having a custom event in `hx-trigger` never causes the trigger.

In my example we have an input component, and I even added hyperscript to check if the event really does get triggered:
```html
<input id="profile-filter-tags"
  type="text"
  hx=get="/someurl"
  hx-target="#searchResultContainer"
  hx-swap="outerHTML"
  hx-trigger="myevent"
  _="on myevent call alert('myevent triggered!')">
```

On triggering the `myevent` event, I will get an alert box saying "myevent triggered!", but the htmx request will never get triggered.

**Comment by 1cg** [comment]
All good?

**Comment by kagenami** [comment]
I popped in to say that I am having the exact same issue. For some reason, custom triggers are not firing.

**Comment by 1cg** [comment]
@zilti closed this issue, @kagenami can you post some code so I can see what's happening?

**Comment by zilti** [comment]
Yes, all good for me. I incorrectly translated an intercooler attribute to htmx, causing an error (visible in the browser's js console).
