### ISSUE TITLE
Checkbox behavior is not compatible with ASP.NET MVC/Razor

### ISSUE THREAD

**Issue by mqudsi** [bigskysoftware/htmx#25]
ASP.NET's (and ASP.NET Core's) model binder for boolean parameters [only supports (case-insensitive) "true" and "false" string values](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.booleanconverter?view=netcore-3.1). 

For the fragment

```html
<label><input hx-get="/Foo" type="checkbox" name="bar" /> Click me!</label>
```

when checked, htmx makes a request to either `/Foo` or `/Foo?bar=on` depending on the checked state. I'm presuming *some* framework takes `on`/`off` for checkbox parameters, but I haven't come across it (rails, maybe, seeing as the docs mention it in a few places?).

In order of preference, is there
* some value that is supported by both whatever backend you have in mind and ASP.NET's default boolean model binder that could be used instead of `foo=on` (basically, can we switch to using `true` instead of `on` because whatever supports `on` also supports `true`?)
* some way to globally alter the value that is used for checkboxes when present (and perhaps when absent as well, e.g. always sending a value whether it's `foo=false` or `foo=true` instead of alternating between sending a value and not sending a value)

**Comment by chg20** [comment]
This is the value being returned by the .value property for the checkbox.  My understanding is that typically checkboxes have a value attribute, and that value is included if the checkbox is checked and excluded if it is not.  It appears that if no value is set for the checkbox, "on" is the default.  This isn't htmx specific as far as I know.

**Comment by NealWebb** [comment]
@mqudsi Review [here](https://www.learnrazorpages.com/razor-pages/forms/checkboxes) for more details on how the model binder works with respect to checkboxes.  This is written from the standpoint of a Razor Pages project but applies to MVC as well.  Below is a snippet that works just fine.

```
<form hx-get="/">
    <input type="hidden" name="handler" value="foo" />
    <div>
        <label>Test 1</label>
        <input asp-for="Test1" /> <!-- Tag helper automatically sets the value to true -->
        <!-- The tag helper will automatically generate a hidden input with a value of false -->
    </div>
    <div>
        <label>Test 2</label>
        @Html.CheckBoxFor(m => m.Test2)
        <!-- The HTML helper does the same work as the tag helper -->
    </div>
    <div>
        <label>Test 3</label>
        <input type="checkbox" data-val="true" id="Test3" name="Test3" value="true" @Model.Test3 : "checked" ? "" />
        <input type="hidden" value="false" name="Test3" />
        <!-- Here we create the hidden input and set the values manually -->
    </div>
    <button type="submit">Send</button>
</form>
```

**Comment by mqudsi** [comment]
Yup, *mea culpa*. Thanks!
