### ISSUE TITLE
The "multiple" attribute is not handled correctly

### ISSUE THREAD

**Issue by ojensen5115** [bigskysoftware/htmx#250]
In order for HTMX to recognize a `<select>` as having the multiple attribute, it must be given in the form `<select name="whatever" multiple="something">`. If instead it takes the more common form `<select name="whatever" multiple>`, it does not get recognized and sends only the first selected value.

**Comment by ojensen5115** [comment]
I've submitted a PR to fix the issue:
https://github.com/bigskysoftware/htmx/pull/246

**Comment by 1cg** [comment]
Hi oliver, I believe this is fixed in `dev`, but I like your fix better.  I will pull it in today.

**Comment by 1cg** [comment]
pulled in the fix, thanks!
