### ISSUE TITLE
Integrate WebSocket Support in HTMX for Real-Time Web Application Development

### ISSUE THREAD

**Issue by YagilItzhak** [bigskysoftware/htmx#2511]
WebSockets provide a persistent, low-latency connection that can receive and send messages to and from a server in real time. This is essential for applications that require instant data updates like real-time analytics, chats, and more...
Integrating WebSockets directly into HTMX would simplify the development of such applications by allowing developers to use HTMX's declarative API to manage WebSocket connections and data updates.

Here is an example of how I see it:
```html
<div hx-sock="/live_distance">
    The connection is yet to be established
</div>
```

If you like it, I would love to help in adding this feature!

**Comment by Telroshan** [comment]
Hey, you might want to look into the existing [websocket extension](https://htmx.org/extensions/web-sockets/)

**Comment by YagilItzhak** [comment]
> Hey, you might want to look into the existing [websockets extension](https://htmx.org/extensions/web-sockets/)

Oh, thanks 😂.
