### ISSUE TITLE
HX-Location should respect Hx-Push-Url when false

### ISSUE THREAD

**Issue by francis-chiss** [bigskysoftware/htmx#2527]
I have a scenario where I want to use the HX-Location response header to refresh a section of a page using the "target" property (like in the documentation).

However, I do not want the URL to be pushed into the browser history. I thought using Hx-Push-Url=false would work, but it didn't. 

Modifying htmx.js locally like this near the pushUrlIntoHistory call :

                if (hasHeader(xhr, /HX-Location:/i)) {
                    saveCurrentPageToHistory();
                    var redirectPath = xhr.getResponseHeader("HX-Location");
                    var swapSpec;
                    if (redirectPath.indexOf("{") === 0) {
                        swapSpec = parseJSON(redirectPath);
                        // what's the best way to throw an error if the user didn't include this
                        redirectPath = swapSpec['path'];
                        delete swapSpec['path'];
                    }
                    ajaxHelper('GET', redirectPath, swapSpec).then(function () {
                        // NEW CODE HERE!!! //
                        if (xhr.getResponseHeader("HX-Push-Url") !== "false") {
                            pushUrlIntoHistory(redirectPath);
                        }
                    });
                    return;
                }

...did exactly what I wanted. 

What do you think about this? Or am I missing something?

Thanks! Love the breath of fresh air that is HTMX!

**Comment by Telroshan** [comment]
Hey, it seems to me that if you're not interested in changing the URL, which is what `HX-Location` is for after all, you might either:
- Use the [`HX-Trigger` response header](https://htmx.org/headers/hx-trigger/) to trigger a request on your client along your initial request's response, which will allow you to just fire a standard htmx request and use a `hx-target` as you'd usually do, without changing the page's URL
- Or use OOB swap (see [hx-swap-oob](https://htmx.org/attributes/hx-swap-oob/) to directy swap your partial content in, and avoid an extra round-trip to the server if you already know what you want to swap in there

**Comment by francis-chiss** [comment]
Thanks for the quick feedback!

I was doing a POST to save something to the backend and I was trying to trigger (no pun intended!) a refresh of a list of those things. Doh, what was I thinking! HX-Trigger with an event named 'refresh-things' was exactly what I needed 

All I had to do was to add `hx-trigger="refresh-things from:body"` on the div hosting the list and voilà.

Thank you so much!
