### ISSUE TITLE
Unable to understand why this works with html&js but not with htmx

### ISSUE THREAD

**Issue by kharabela** [bigskysoftware/htmx#2530]
JS code:
 let form=document.querySelector('form#AccountDetailsForm') returns null.Js is able to evaluate div that are parent to form element but not the form

//this is my button
 <button id="accountnav"
        hx-get="/account"
        **hx-target="#tab-contents"**
        @click="$store.tabs.current = 'Account Details'"
        hx-on::before-request="alert('Making a request')"
        hx-on::after-request="" 
        class="flex justify-start items-center space-x-2 hover:text-white focus:dark:bg-indigo-600 focus:text-white hover:bg-gray-700 text-gray-400 rounded px-3 py-2  w-full md:w-52">
          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
         </svg>
          <p class="text-base leading-4">Account</p>
        </button>

<div **id="tab-contents"** role="tabpanel" hx-get="/account" hx-trigger="load"></div>

// this loads my form as below
<div id="tab-contents" role="tabpanel" hx-get="/account" hx-trigger="load" class="">

<form id="AccountDetailsForm" 
class="w-full transition-all duration-300 bg-white p-4 rounded-lg shadow-md border-l-4 border-blue-600 m-1" 
method="post" 
enctype="multipart/form-data" zgotmplz="">

    <div class="flex flex-wrap -mx-3 mb-2">
        <div class="w-full md:w-4/5 px-3 mb-6 md:mb-0">
            <label class="tracking-wide text-gray-700 text-xs font-bold block mb-2" for="AccountFirstName">
                <span class="text-sm font-bold text-red-800 w-5">*</span>
                First Name
            </label>
            <input class="appearance-none block w-full text-gray-700 border rounded py-2 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="AccountFirstName" type="text" oninput="this.value = this.value.replace(/[0-9.]/g, '');" onkeyup="validateAccountFirstName()" onfocusout="validateAccountFirstName()" maxlength="50" placeholder="Jane" value="Mak">
            <p id="ErrAccountFirstName" class="text-xs italic"></p>
        </div>
    </div> 
    <div class="flex justify-between">
        <button id="AccountSubmit" name="Save" type="submit" class="px-4 py-2 text-sm font-medium text-white bg-blue-700 rounded-md hover:bg-blue-900 focus:outline-none focus:ring focus:border-blue-300">
            Save &amp; Next
        </button>
    </div>
</form>
</div>

**Comment by Telroshan** [comment]
Hey, I'm sorry but I'm afraid I don't understand neither the issue nor the question.
Could you explain in more details what exactly is not working with htmx that is working in "html&js"?
Could you provide maybe a more complete example code?
For ex there are `AccountDetailsForm`, `tab-contents`, what is the situation exactly? What is the link between the various code snippets? There is no `hx-` attribute in your form code, nor is there a form element altogether, so I'm very confused about the whole situation and must admit I don't even know what's supposed to happen nor what you're doing in here.

Without more context for ex, something like
> let form=document.querySelector('form#AccountDetailsForm') returns null.

sounds false? If your form element exists in the DOM, this is valid JS (see [this JSFiddle](https://jsfiddle.net/7fy8bukh/)) so I don't think I understand here either.

Let me know!

**Comment by kharabela** [comment]
@Telroshan it was very difficult for me to setup the exact replication.After hours this came to rescue
<div id="tab-contents" 
role="tabpanel" 
hx-get="/account" 
hx-trigger="load" 
hx-on:htmx-after-on-load="console.log(document.querySelector('form#AccountDetailsForm'))"></div>
</div>

System was not able to find form , I was unable to understand why.Figured out my code was not able to retrieve it from live dom.As the html renders the form after slight delay.
