### ISSUE TITLE
[2.0.0-beta3] Form file input submission differs from `v1`

### ISSUE THREAD

**Issue by heikkilamarko** [bigskysoftware/htmx#2555]
When submitting a form containing a file input element using version `2.0.0-beta3` of htmx, the form sends a payload when no file is selected. This does not occur with htmx version `1.9.12`.

```html
<input type="file" multiple name="attachments" form="task-new-form" class="form-control form-control-sm" />
```

## `v2.0.0-beta3`

<img width="1346" alt="Screenshot 2024-05-19 at 9 30 31" src="https://github.com/bigskysoftware/htmx/assets/3757314/ae5dcee4-4ecc-4985-a1ce-928ed4790d02">
<img width="1344" alt="Screenshot 2024-05-19 at 9 31 48" src="https://github.com/bigskysoftware/htmx/assets/3757314/0e771a81-8d07-45b1-8da4-bafe43856c8e">

## `v1.9.12`

<img width="1349" alt="Screenshot 2024-05-19 at 9 27 06" src="https://github.com/bigskysoftware/htmx/assets/3757314/7307af9e-08b4-47b9-814a-d504fbe4aa42">

**Comment by heikkilamarko** [comment]
Not sure if this is incorrect behavior, but it behaves differently between `v1` and `v2`.

**Comment by 1cg** [comment]
should be fixed w/ https://github.com/bigskysoftware/htmx/commit/1e07206ed28ad4065a9a878823661478975eac36
