### ISSUE TITLE
[Bug] HTTP Redirect 303 with Hx-Push-Url response header, does not push the url

### ISSUE THREAD

**Issue by SKFrozenCloud** [bigskysoftware/htmx#2563]
If you redirect a request with the http code 303 and set the response header Hx-Push-Url to some url, the url will not be pushed.

**Comment by marcelfolaron** [comment]
Can confirm this issue, also tried 302 redirects. Went ahead and tried all different permutations of 

```
$headers["hx-replace-url"] = $url;
$headers["hx-push-url"] = $url;
$headers["hx-refresh"] = true;
$headers["hx-location"] = $url;
```
None of them seem to be processed when the response is a redirect response. 
It works fine on regular 200 responses

**Comment by marcelfolaron** [comment]
Dug a little deeper and `xhr.onload = function() {}` will follow redirects until it hits a 200 during that process it will lose the original response headers. Seems 302s will always be handled by the browser and can't be intercepted via xhr. 

I'll see how I can deal with this on the server side.

**Comment by Telroshan** [comment]
Hey, indeed the browser handles the 302 redirects internally and we can't do anything about that unfortunately.
See #2052 and #2879 for more discussions on that matter
