### ISSUE TITLE
Setting to handle error response same as success

### ISSUE THREAD

**Issue by mozey** [bigskysoftware/htmx#2564]
When the response status is >= 400, the **htmx:responseError** event must be used, see [this comment](https://www.reddit.com/r/htmx/comments/11ifjid/comment/l5gvtu9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

Wouldn't it make sense to have a setting where htmx will still process the response as usual even for error responses?

For example, say I make a requests like this
```html
<button hx-get="/contact/123" hx-trigger="click">Load contact</button>
```

And the response from the server, with **status code 404**, is this
```html
<p id="err" hx-swap-oob="true" class="error">Contact 123 not found</p>
```

I would like htmx to still process hx-swap-oob the same as **status code 200**

[Also posted here](https://www.reddit.com/r/htmx/comments/1czkye7/setting_to_handle_error_response_same_as_success/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by Telroshan** [comment]
Hey, you might want to look into the [response-targets extension](https://htmx.org/extensions/response-targets/), which could suit your needs here

**Comment by mozey** [comment]
@Telroshan Thanks for the link, I've actually already written my own version of `hx-target-error`, and this extension could work for me. It also has other features that might be useful.

I don't understand why the Hypermedia API reponse must be handled differently if the status code is not 2**?

Maybe there is a way to do this?
```js
Events.addListener(HtmxUtils.name, htmxResponseError, (e: Event) => {
  // Handle event same as success code
  htmx.handle(e)
})
```

**Comment by Telroshan** [comment]
There was discussion to [add a similar feature to the lib's core](https://github.com/bigskysoftware/htmx/pull/1620) but it didn't make it through.

However, please note htmx 2 will come with a [`responseHandling`](https://github.com/bigskysoftware/htmx/blob/dev/src/htmx.js#L264) config property that will allow you to swap errors by default (opt-in). (_It seems we have forgotten to add documentation for this feature yet, so bear with me for the link to the source code directly_)

**Comment by silmeth** [comment]
The main page of the docs also has a section on [Modifying swapping behavior with events](https://htmx.org/docs/#modifying_swapping_behavior_with_events) where it’s recommended to use the `htmx::beforeSwap` event, setting `evt.detail.shouldSwap = true;` to make it it processed normally. You can also which status codes should be treated this way.

(Myself, I’d still prefer to be able to declare any response should be handled directly in the triggering element with an attribute than writing a snippet of custom JS, though – but adding a simple even handler isn’t too bad)

**Comment by mozey** [comment]
@silmeth Thanks for the tip, to **display errors by default**, I'm setting `shouldSwap` as per the docs
```js
addEventListener("htmx:beforeSwap", (e) => {
  if (event.detail.xhr.status >= 400) {
    e.detail.shouldSwap = true
  }
})
```

To **override where the error is displayed**, I can set `hx-target-error` from the response-targets extension
