### ISSUE TITLE
Extension Point: Are extensions able to manipulate arguments used by other HTMX nodes?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#257]
This is either a question or a request -- I'm not sure yet :)  Is it possible for an extension to change/update arguments used by other htmx attributes?  If so, then I'd like to figure out how, and then update the docs accordingly.  If not, then I'd like to figure out what it would take to make this possible.

My example use case is rebuilding a custom `hx-boost` feature as an extension.  For example, a custom version might boost links when only the left mouse button is clicked (or the ctrl-click is not present).  I'm not proposing that we rewrite `hx-bost` as an extension, but I think this is a good litmus test for tasks that extensions *should* be able to perform.

**Comment by bencroker** [comment]
Let's call it a question for now, although I'll leave it to @1cg to answer ;)

**Comment by benpate** [comment]
Now that #298 has been merged, the answer to this question is "yes."  Just listen to the `htmx:beforeProcessNode` event and make the changes you want to make.
