### ISSUE TITLE
hx-include specificity issues

### ISSUE THREAD

**Issue by nickyoung87** [bigskysoftware/htmx#2572]
Ok so maybe I just understand this wrong but I am having a bit of an issue with trying to reuse some html in a template and only send the specific data I want to my HTMX post request. 

Basically the issue is this:
- I am trying to send only these specific inputs to the HTMX post
- The django endpoint is getting the data but it is always the last item (if there are multiple items)
- Django is getting only the last item because I am using `request.POST.get()` as opposed to `.getlist()` because I only need one value
- I would expect that only the inputs with the name would be sent over and not all the inputs on the page
- Even refining it down to use `hx-include` and the very specific class names it still sends my endpoint all of the input data on the page (for those fields with the same name at least)
- I am sure that people will say to do this a different way, and I get that, but  Ireally just want to understand if I am misunderstanding how `hx-include` should work

So maybe I am wrong but this seems like a "sort of" issue on the htmx side since I would expect it to only send the 4 inputs I have specified and not all 12 on the page. Am I wrong about this?

Here is a snippet of code to look at. It's a little bit clunky because I was trying various things to get this working and this is where it's at now.

```
<div class="form-block service-files service-files-{{ service.id }}">
                            <div id="service_{{ service.id }}_filelist">
                                <p>Files</p>
                            </div>
                            <div>
                                <strong>File Upload</strong>
                                <a href="#"
                                   @click="showModal = true"
                                   class="button secondary files-button"
                                   hx-post="{% url "media_library:modal" %}"
                                   hx-target="#modal"
                                   hx-swap="innerHTML"
                                   id="files-button-{{ service.id }}"
                                   hx-include=".object-type-{{ service.id }}, .service-id-{{ service.id }}, .target-{{ service.id }}, .swap-{{ service.id }}"
                                   data-service-id="{{ service.id }}">Media Library</a>
                                <input type="hidden"
                                       name="object_type"
                                       value="orders"
                                       class="object-type-{{ service.id }}"
                                       data-service-id="{{ service.id }}" />
                                <input type="hidden"
                                       name="service_id"
                                       value="{{ service.id }}"
                                       class="service-id-{{ service.id }}"
                                       data-service-id="{{ service.id }}" />
                                <input type="hidden"
                                       name="target"
                                       value="#service_{{ service.id }}_filelist"
                                       class="target-{{ service.id }}"
                                       data-service-id="{{ service.id }}" />
                                <input type="hidden"
                                       name="swap"
                                       value="beforeend"
                                       class="swap-{{ service.id }}"
                                       data-service-id="{{ service.id }}" />
                            </div>
                        </div>
```

**Comment by Telroshan** [comment]
Hey, one behavior your should be aware of is the following:
https://github.com/bigskysoftware/htmx/blob/4bc7c9710e99369a8c659f9b865e75866fd7a446/src/htmx.js#L2609-L2612

So as you're making a `POST` request here, if the snippet you provided is embedded inside a form, the whole form gets included.

As for `hx-include`, it allows you to **add** values to your payload, but not replace the ones that are already included by default.

Looking at your snippet here, if reorganizing your layout (so that your link is not a child of your parent form anymore) is not an option, it could be that the easiest way to solve this would be using a `GET` request instead of a `POST`.
If I may ask, why use a `POST` request here as you seem to be fetching a partial view (a modal), using hidden input values (thus simple strings key/value pairs)?
It looks like your selected files would be inserted under the `service_ID_filelist` element, and that your form would itself do the `POST` request and actually upload those files, unless I'm mistaken.

**Comment by nickyoung87** [comment]
Yeah there is a lot going on with this whole thing that makes it real complicated. The basic flow is that it sends an HTMX request to the modal so the modal can do all the file uploading and handling and then it just returns the IDs of the files that were uploaded as hidden inputs to the form to be processed so the files can be attached to the item. 

The behavior you showed me above with the `GET` actually made the difference. I simply was able to convert it to a `GET` request and it now seems to be working great. Thank you for that tip and I will never forget it now!

**Comment by nickyoung87** [comment]
I know I closed this already, but I have been thinking about it and I am curious. Why is there a difference specifically between the GET and POST request for this?

**Comment by Telroshan** [comment]
Looked at the history by curiosity, this evolved over time but was present almost from the very beginning
- At first, the closest form would [always be included](https://github.com/bigskysoftware/htmx/commit/04964d9e39d4a0945ae8720b33828c3769a4048b#diff-f14ff7f8c91a6f76e7688c45ca01d600e8928769b268caa71cf09b8f12661f3dR372) - _damn htmx was still named "kutty" at this point_
- Then it was [limited to non-GET requests only](https://github.com/bigskysoftware/htmx/commit/a3c9cf6b6a3fe05b8207e703bd6ff16fd51e34f2#diff-c7d06af83d22e155470d44a366cc1ba76cd5dc9da3405fc9e54a237174736b6aR974)
- Then order was simply [inverted to preserve values order](https://github.com/bigskysoftware/htmx/commit/b2890e3cf1cd7e4950b9a8f65e4adba25563a756), by including first the form's values then the input's own value

I can't speak for @1cg here as I wasn't there at the time, but I imagine this to be an arbitrary decision relative to native HTML elements _(and how to extend them while keeping the same philosophy)_, where links can do GET requests on their own while POST requests are done through forms, which then inevitably include their form data. Or maybe is it related to the fact that GET requests use URL params by default while POST use a request body?

**Comment by nickyoung87** [comment]
Interesting. Thanks for the thoughts on the subject. It definitely threw me off guard that it behaved differently, but now that I know the difference it won't happen to me again :)
