### ISSUE TITLE
Question: Idiomatic way to "select" a tab in parent document

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#258]
**How do I implement "tabs" with htmx so that labels are highlighted when the content is loaded?**

I'm building an htmx starter project for some middle-schoolers.  Here is a part of the main page (index.html)

```html
<div class="tabs">
	<a hx-get="tab-a.html" hx-target="#tab-content">Tab A</a>
	<a hx-get="tab-b.html" hx-target="#tab-content">Tab B</a>
</div>
<div id="tab-content"></div>
```

This nicely loads content from the remote files `tab-a.html` and `tab-b.html` and swaps it into `div#tab-content`.  However, I don't know of a straightforward way to automatically "select" those tabs, for instance, by adding a "selected" class to each anchor.  This seems like a basic feature that would be good to include, without requiring hyperscript or javascript hacks.

1) If this already exists, can you help me understand it and I'll add something to the docs.

2) If this doesn't exist, are there proposals on the table for handling this?  Or, can I try proposing something simple and declarative to solve this?

**Comment by benpate** [comment]
My first take (after thirty minutes of thinking) is be to add an `hx-selected` attribute that specifies a class to be added to a child element when it is clicked, and removed from all other elements in the tree.

I'm happy to make a PR for this, if it receives a blessing from on high.

**Example**

```html
<div class="tabs" hx-selected="highlight">
  <a hx-get="tab-a.html" hx-target="#tab-content">Tab A</a>
  <a hx-get="tab-b.html" hx-target="#tab-content">Tab B</a>
</div>
```
When "Tab A" is clicked, that DOM node receives `class="highlight"`.  When "Tab B" is clicked, the highlight is removed from tab a, and added to tab b.

An enhanced option for this would be to add the designated class to the clicked element *and all of its parents in the DOM tree*, which would facilitate tree navigation widgets, too.

**Comment by clarkevans** [comment]
This is an excellent idea. That said, one of the nice things about HTMX is that, at least at first glance, it seems to have a narrowly focused scope. This feature seems beyond the scope of client/server interaction. Is something like this more hyperscript feature?

**Comment by benpate** [comment]
Excellent point.  I do agree with keeping things focused.  Perhaps it's better to frame this as requirements for an extension?

Even with hyperscript, it is better, but not great.  I think the website lists the solution as: ` _="on click take .active from .tab for event.target"`

**Comment by 1cg** [comment]
The htmx way to do this is to include the tabs in the area replaced.

If you want to get a bit fancier and target only the content area, you can add some hyperscript or use `takeClass` from the javascript API: https://htmx.org/api/#takeClass 

```html
  <div onClick="htmx.takeClass(this, "activeOrWhatever")" ...>...</div>
```

**Comment by benpate** [comment]
Yes.  Just found this too.  Here's an extension that does the same.  It looks like this was way easier than I expected it to be :)

```
htmx.defineExtension("selected", {
	onEvent: function(name, evt) {
		if (name == "htmx:afterOnLoad") {
			htmx.takeClass(evt.target, "selected")
		}
	}
})
```

**Comment by clarkevans** [comment]
Ben -- sometimes idioms are just as valuable as the features; it'd be great if there were documentation /w working examples of common usage patterns (e.g. this one, pagination, etc.)

**Comment by benpate** [comment]
@clarkevans - Agreed

@1cg - would you be open to a PR that includes this extension along with documentation on different ways to accomplish tabs?

**Comment by 1cg** [comment]
Sure, I works for me.

**Comment by benpate** [comment]
I'm closing this because the PR has been merged.
