### ISSUE TITLE
Multiple HX-Trigger in Headers not firing events. Single event works

### ISSUE THREAD

**Issue by jrbenriquez** [bigskysoftware/htmx#2588]
Hi there,

I can get a single event to trigger via a response header

i.e.
```
HX-Trigger: event1
```
OR
```
HX-Trigger: event2
```

but when I pass in comma separated values as per the docs:
[HX-Trigger Headers](https://htmx.org/headers/hx-trigger/)

```
HX-Trigger: event1, event2
```

I don't get any events firing after receiving the response. Can confirm that I can trigger the events from the browser's console via

```
htmx.trigger(htmx.find('body'),'event1')
htmx.trigger(htmx.find('body'),'event2')
```

I am on HTMX 1.9.0, is this expected behavior? Thanks!

**Comment by samfurr** [comment]
I am able to reproduce on 1.9.0, but appears to be fixed in the latest version (1.9.12).

**Comment by samfurr** [comment]
support was added for this in 1.9.4: https://github.com/bigskysoftware/htmx/pull/1479

**Comment by jrbenriquez** [comment]
Ah cool, Thanks! Will close
