### ISSUE TITLE
Extension Point: init function

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#259]
Would it be valuable to have an `init()` function for extensions?  This might help in cases where there's some global setup that needs to occur.  It makes sense to me to pass in a few arguments, such as the element where the extension is defined.

**Use Case**
To create a "modal dialog" extension, I'd like to be able to create a DOM node at the bottom of the document where modal content is loaded.  This might also include a modal backdrop DIV, which is common for most modal dialog designs.  

```html
<button hx-ext="uikit-modal" hx-get="modal.html">Open Modal</button>
```

**Comment by benpate** [comment]
With `htmx:beforeProcessNode` I think this request may be moot.  At the very least, it should be on the back burner until after 1.1 and we can see if it's even needed at all.

**Comment by 1cg** [comment]
closing until needed by a real world example...
