### ISSUE TITLE
HX-Trigger header not working in certain cases

### ISSUE THREAD

**Issue by IvovdBruggen** [bigskysoftware/htmx#2598]
I have a div with hx-trigger="updateDocumentsTable from:body", however, when I do an api request somewhere. That being with fetch, it does a request that has a HX-Trigger header. This however does not trigger the div. So now I have to manually htmx.trigger the element. Is this because I am using fetch?

**Comment by Telroshan** [comment]
Hello, if you're doing the request yourself then indeed, no htmx header will work. The reason for that is that the headers do not trigger anything on their own ; htmx parses the response headers of the requests it makes itself, but if you do a request on your own, "outside" htmx's scope, htmx will basically know nothing about it.
You might want to look into [htmx.ajax](https://htmx.org/api/#ajax) to trigger requests from your JS while relying on htmx's behaviors
Hope this helps!

**Comment by IvovdBruggen** [comment]
I thought that was the case but couldn't find it. Thanks! I can work with that
