### ISSUE TITLE
Ergonomics when always serving full-page responses

### ISSUE THREAD

**Issue by mqudsi** [bigskysoftware/htmx#26]
One of the differences between htmx/intercooler and unpoly is that unpoly by default assumes that the backend is serving full pages in responses rather than page fragments. As I am using htmx to enhance a site that should otherwise be perfectly functional without JS, the backend always serves full pages and never partial templates. 

Additionally, I'm not sure what your typical sites look like, but I find that I almost never want to swap the element that is being clicked but rather some other element (this is also made easier by the fact that the entire page is served up by the backend, so things like buttons that have text that needs to be changed depending on the context are usually swapped out altogether with the element that is being affected by simply swapping a parent of the button and the results). As a result, all my htmx usages end up extremely verbose and redundant (especially because of #23 and #24), e.g. to simply swap a single element when a checkbox is altered:

```html
<label><input type="checkbox" name="hideIncomplete" hx-get="/Registrations" hx-push="true" hx-target=".registrations" hx-swap="outerHTML" hx-select=".registrations" /> Hide incomplete registrations</label>
```

I wonder if there's a configuration option that could be added or else an alternate syntax that could be used that would bundle all this in one to reduce the boilerplate (and chance for error).

**Comment by chg20** [comment]
Is the fact that most of the attributes can be placed on parents useful?  e.g.

``` 
hx-push="true" hx-target=".registrations" hx-swap="outerHTML" hx-select=".registrations" 
```

Could all be placed on a parent div surrounding the check boxes, if that's common.

You can also set the default swap mechanism to something other than innerHTML:

https://htmx.org/docs#config

**Comment by chg20** [comment]
I should also mention that you can place the hx-target="this" on the `.registrations` element rather than calling it out by a selector.

**Comment by chg20** [comment]
What do you think @mqudsi ?

**Comment by chg20** [comment]
I'm warming up to the idea that in the absence of an explicit target and swap, `hx-select` should define the target as the same item and the swap as `outerHTML`.

**Comment by mqudsi** [comment]
I wasn't aware that `htmx` attributes are inherited, that does indeed simplify a lot of things (although I prefer to be explicit in case of composing elements so that there is no unexpected behavior). The `hx-target="this"` feature is also great because it eliminates an entire class of typo/copy-and-paste/refactoring issues, thank you for bringing it to my attention.

I actually agree with your minimalistic approach and concur that simpler is better, but my guiding principle is that most developers/users operate on a combination of intuition and muscle memory. A feature that brings convenience should never clash with the user's ability to have a strong mental model of what is going on. I think in general you can either try (and usually fail) to achieve "intuitiveness" by handling individual "stories" on a one-by-one basis but can oftentimes get superior results by simply picking the right primitives.

**Comment by johndwells** [comment]
The differing  _assumptions_ behind unpoly vs htmx are really interesting. For me, I'm sort of in the Unpoly camp, e.g. I'd much rather only render full page responses on the server, and let the frontend JS pick and choose what to swap/inject. So in an ideal scenario, I'd at least be able to configure htmx to operate the way I'm architecting my app.

I'm not sure the parent/inheritance is clear to me (aside from it not being documented to great detail)...

What if you were to expose a configuration to set the default target & select? `this` could remain as a magic keyword, otherwise it's a selector, so you could set it to `#container`,  `.cart` or simply `body`.

Also - `hx-boost` uses `body` as the default. For me, this supports the view that the default should be `body`. :)

**Comment by jreviews** [comment]
You can use https://htmx.org/attributes/hx-select/ to let the front-end choose what to swap.

**Comment by johndwells** [comment]
@jreviews Oh wait - and does it indeed allow for multiple selects? If so I totally missed that (and therefore this is unneccessary https://github.com/bigskysoftware/htmx/issues/44)

**Comment by jreviews** [comment]
I haven't tested this, but it does say `or elements`

**Comment by johndwells** [comment]
@jreviews So yes when using `hx-select`, whatever element _or elements_ are selected in the response are swapped into `hx-target` (as dictated by whatever `hx-swap` may be). Everything else in the response is discarded. Not quite what I had in mind in #44 but still good to clarify.

**Comment by jreviews** [comment]
I am not currently using htmx, but you could try using the morphdom hx-ext https://htmx.org/extensions/morphdom-swap/ to swap the entire page with the response. It will only update modified elements, but I am not sure what the performance will be. Worth a try though

**Comment by RolandStuder** [comment]
Just to put a counter opinion on changing the default behavior. I just did some things with unpoly and I don't want to serve full page responses, I have an editor with many elements, serving a full page with all the editable elements makes for an expensive query. So where I mainly want to use htmx is where, I only want to replace specific things, like render a form for an element.

So I like really prefer the current default of expecting a fragment that will we swapped in.

**Comment by mqudsi** [comment]
@RolandStuder There is no request to change the default behavior or story of htmx to expect full page responses, merely to make it more easily usable for the cases where that is the case.

**Comment by johndwells** [comment]
Yeah, I have to admit that, especially as I read back though intercoolers
docs (I'd never used it before), the "fragment-first" approach seems
central to the spirit of htmx. And so, perhaps let it be a defining
difference from unpoly.

**Comment by chg20** [comment]
I came from a rails background, so the notion of splitting out partials and responding with them was very natural.

I do see @mqudsi's point here and, once I have some time, I'd like to take a look at what implementing improvements in this area would look like

**Comment by BoPeng** [comment]
I am not quire sure what this ticket is about but I am just writing to send a big kudos to `hx-select` since I simply convert my links from

```
          <a class="nav-link" href="/about">About</a>
```
```
          <a class="nav-link" href="#" hx-get="/about" hx-target="#page-content" hx-push-url="true"
            hx-select="#page-content">About</a>
```
to avoid the complete reload of my webpage, **without the need to change anything in the backend!**.

I cannot remember if this could be done in `intercooler.js` but I am really happy to use `htmx` now.

**Comment by 1cg** [comment]
closing out due to issue rot, happy to look at a new proposal in this area though
