### ISSUE TITLE
Is there a possible way make htmx to take another attribute from the named element other than the element value?

### ISSUE THREAD

**Issue by efsant0s** [bigskysoftware/htmx#2608]
I'm using the IMask.js library, which applies masks to the inputs. 

https://codepen.io/efsant0s/pen/GRaMxxX

It's possible to get element value (which has a mask, such as currency) and unmaskedValue (which is the original value).

The thing is, htmx get's the named inputs.value from the form to send it in the hx-post, and I wanted to make htmx to try to take the named input like: 
input.mask.unmaskedValue ?? input.value

Would that be possible ?

**Comment by Telroshan** [comment]
Hey, since this is a relatively specific behavior, I would suggest using the [htmx:configRequest](https://htmx.org/events/#htmx:configRequest) event for example, to manually adjust the payload before htmx sends its request (the linked doc includes an example of overriding a value, which could suit your usecase). From here, you could do your check and replace the input value as needed.

**Comment by efsant0s** [comment]
<button type="button" id="btnSave" class="btn btn-primary me-2" 
                    hx-swap="innerHTML transition:true"
                    hx-replace-url="false"
                    hx-push-url="false"
                    hx-include="#user-form"
                    hx-post="/api/company-admin/company-admin-users-save-user" 
                    hx-trigger='formSave' 
                    hx-target="#hx-upload-photo-response"
                _="     on htmx:configRequest  
                            repeat for key in Object.keys(event.detail.parameters)
                                set input to #user-form.querySelector(`[name='` + key + `']`)
                                if input != null and input.mask != null
                                    set event.detail.parameters[key] to input.mask.unmaskedValue
                                end
                            end
                        end">
                        </button>
