### ISSUE TITLE
`previous input` not work as expected.

### ISSUE THREAD

**Issue by zw963** [bigskysoftware/htmx#2610]
Plese check following example, there are two input element which has same name.

```html
<input type="hidden" value="WAnUI0ZhE8Gdab2pVgFPPDG-6Av7NuIdmXDlY_z08xQ" name="_csrf">
....
<label>
  <input type="hidden" name="university:marked" value="false" id="marked_unmark">
  <input type="checkbox" name="university:marked" value="true" id="marked" hx-put="/universities/812" hx-swap="none" hx-indicator="#spinner" hx-include="[name='_csrf'],previous input" class="">
  <span>标记</span>
</label>
```

The `previous input` not work in above include attribute, it not includes the hidden input elements which above it, 
and cause `university:marked set to false` is not available when user uncheck the checkbox.

It not work if i move hidden input after the checkbox input, and use `next input` too.

But, if use `#id` selector instead,  it work as expected as following code:

```html
<input type="hidden" value="WAnUI0ZhE8Gdab2pVgFPPDG-6Av7NuIdmXDlY_z08xQ" name="_csrf">
....
<label>
  <input type="hidden" name="university:marked" value="false" id="marked_unmark">
  <input type="checkbox" name="university:marked" value="true" id="marked" hx-put="/universities/812" hx-swap="none" hx-indicator="#spinner" hx-include="[name='_csrf'],input#marked_unmark" class="">
  <span>标记</span>
</label>
```

** Version

htmx 1.9.12
hyperscript 0.9.12

Thanks

**Comment by Telroshan** [comment]
Hey, unfortunately it's indeed a weakness of our extended selectors syntax at the moment. It's only handled if it's the only selector, i.e:
- `previous input` will work
- But `div, previous input` won't, and will simply result in a `document.querySelectorAll("div, previous input")`, which of course won't retrieve the element you're looking for

That's a weakness we'll have to fix in the future, and for now you may indeed use this ID workaround that you already found out!
