### ISSUE TITLE
[version 2.0.0-beta1] formData instead of parameters in htmx event

### ISSUE THREAD

**Issue by LucaPanofsky** [bigskysoftware/htmx#2616]
Hello, in the new beta there seems to be a breaking change in the way the event is handling parameters. 

In the current latest the htmx event has the property `parameters` that is a `JS object`. 
Now the htmx event seems to work with `formData`.

This behavior is not described here https://v2-0v2-0.htmx.org/migration-guide-htmx-1/ 

My question is, is that intended or not? If it is, there will be a way to preserve the current behavior?

**Comment by Telroshan** [comment]
Hey, we implemented the internal FormData change with a proxy object, so you should be able to use it just as you were before, as direct assignments (like an object's entries) will be handled by the proxy.
Let us know if it doesn't work as expected though!

_PS: Along the `parameters` and `unfilteredParameters` properties that use this proxy for retro-compatibility, please note we also added `formData` and `unfilteredFormData` that are the actual FormData object, i.e. not the proxy one._

**Comment by LucaPanofsky** [comment]
The main issue  is that now complex objects are parsed as [Object object], is there a way to restore the old behavior?

**Comment by Telroshan** [comment]
Sounds like an issue we'd want to fix indeed!
For now if you need the old behavior you may just not upgrade to htmx 2, though feel free to open a bugfix PR for this, it's definitely an issue that objects aren't serialized as they did before.

**Comment by Telroshan** [comment]
How did a request payload look like in the network tab with the 1.x version in this situation? Was the object rendered as a JSON string or was it handled otherwise?

**Comment by LucaPanofsky** [comment]
Parameters were constructed through `include-vals`, there I create some JS objects (no need to use include-vals, can hook into relevant events). 

Going to provide reproducible code in the following days

**Comment by LucaPanofsky** [comment]
**version 2 breaks**
![Schermata da 2024-06-18 22-44-13](https://github.com/bigskysoftware/htmx/assets/21056850/083c1c50-ad48-4dd8-a14b-74c919ae22d9)
![Schermata da 2024-06-18 22-46-41](https://github.com/bigskysoftware/htmx/assets/21056850/b14583d5-a554-4550-8d84-2cbf884db11f)

**version 1.x.x ok**
![Schermata da 2024-06-18 22-49-40](https://github.com/bigskysoftware/htmx/assets/21056850/f7521123-e831-4012-8353-0a1d70fc8c79)
![Schermata da 2024-06-18 22-49-23](https://github.com/bigskysoftware/htmx/assets/21056850/64e04838-4da5-4b54-b2fd-7a08534132f0)

**Comment by karolskolasinski** [comment]
where is my form data? It is not under formData or under parameters

![image](https://github.com/user-attachments/assets/ac41df11-e5a0-488a-8753-0e1379d0def8)
