### ISSUE TITLE
W3C Markup Validation `hx-` to `data-hx-`

### ISSUE THREAD

**Issue by smhmayboudi** [bigskysoftware/htmx#2622]
I would like to suggest to change `hx-` to `data-hx-`. What is a the main reason is to become more similar to [hyper media standards](https://validator.w3.org/). Many years ago, I remember I was very happy with [javascript unobtrusive](javascript unobtrusive).

**Comment by smhmayboudi** [comment]
if you like to submit a merge request, please ping me.

**Comment by GaelGirodon** [comment]
Isn't it already supported by default? It seems you can use both, depending on which you prefer.

Excerpt from the [documentation](https://htmx.org/docs/) (at the end of the _Introduction_ chapter, just before the title of the next chapter):

> It’s worth mentioning that, if you prefer, you can use the [data-](https://html.spec.whatwg.org/multipage/dom.html#attr-data-*) prefix when using htmx:
>
> ```html
> <a data-hx-post="/click">Click Me!</a>
> ```
