### ISSUE TITLE
How send checkbox values as array

### ISSUE THREAD

**Issue by devmitrandir** [bigskysoftware/htmx#2624]
How send checkbox values as array

```html
<form hx-get="/">
      <label><input type="checkbox" name="options" value="Option1"> Option 1</label>
      <label><input type="checkbox" name="options" value="Option2"> Option 2</label>
      <label><input type="checkbox" name="options" value="Option3"> Option 3</label>
      <label><input type="checkbox" name="options" value="Option4"> Option 4</label>
      <button type="submit">Submit</button>
</form>
```

Now request http://127.0.0.1:8008/?options=Option1&options=Option2

I need http://127.0.0.1:8008/?options=Option1,Option2

**Comment by Telroshan** [comment]
Hey, to get a non-standard encoding of values like the one you mentioned, you'll want to write your own logic.
You can listen for the [`htmx:configRequest`](https://htmx.org/events/#htmx:configRequest) event for example to override the request's payload before it's sent by htmx

**Comment by 1cg** [comment]
Yep, htmx tries to do the same thing HTML does, so if you want something different you'd need to write that logic yourself in `htmx:configRequest`

**Comment by higty** [comment]
Hi.

I just created json-higlabo extension that can handle value list of checkbox, object array that has some properties.
Please check below article.
https://www.codeproject.com/Articles/5388616/HTMX-custom-json-extension-that-handle-array-recor
