### ISSUE TITLE
Unminified install script from a book has incorrect hash

### ISSUE THREAD

**Issue by flopacero** [bigskysoftware/htmx#2627]
In a book unminified script tag to use htmx is
```html
<script src="https://unpkg.com/htmx.org@2.0.0/dist/htmx.js" integrity="sha384-n/Xh+GLLi0SMFPwtHQjT72aPG19QvKB8grnyRbYBNIdHWc2NkCrz65jlU7YrzO6qRp" crossorigin="anonymous"></script>
```
the `n/` part right next to `sha384-` in a hash is an error and should be removed. Otherwise hash validation fails. Without it everything is fine.

**Comment by flopacero** [comment]
Book link: https://htmx.org/docs/#via-a-cdn-e-g-unpkg-com

**Comment by 1cg** [comment]
thx, fixed
