### ISSUE TITLE
2.0.0 - Missing dist/htmx.d.ts

### ISSUE THREAD

**Issue by jacob-ebey** [bigskysoftware/htmx#2629]
`package.json` has the the types field defined as `dist/htmx.d.ts` but that file is not published to npm.

**Comment by 1cg** [comment]
Sorry, will be in the next release (early next week) @alexpetros is fixing!

**Comment by jacob-ebey** [comment]
Please re-open. Type issues still exist due to use of a ".js" MJS file being pointed to by a CJS package.json. You have two options:
- rename the `dist/htmx.esm.js` to `dist/htmx.esm.mjs` and update the main file accordingly
- or add `"type": "module"` to the package.json to ".js" means MJS.

**Comment by alexpetros** [comment]
I think I added `"type": "module"` to the `package.json` and it caused some issues a while back

**Comment by alexpetros** [comment]
Regardless, that is a separate issue, so please open a new one.
