### ISSUE TITLE
Website is too narrow on large screens

### ISSUE THREAD

**Issue by phillip-haydon** [bigskysoftware/htmx#2633]
Is it possible to adjust the width a bit...

![image](https://github.com/bigskysoftware/htmx/assets/895629/3f836deb-28eb-4fd6-8a72-8db57624df57)

The site is so narrow on a large display :(

![image](https://github.com/bigskysoftware/htmx/assets/895629/ea561e9f-6a0f-419d-bd58-2e4b10214793)

Increasing it makes it much easier to read. 

(just a suggestion, feel free to tell me to fuck off)

**Comment by 1cg** [comment]
fine by me, @pokonski you game?

**Comment by 1cg** [comment]
fixed by @pokonski w/ https://github.com/bigskysoftware/htmx/pull/2644
