### ISSUE TITLE
2.0.0 umd file missing?

### ISSUE THREAD

**Issue by it-can** [bigskysoftware/htmx#2635]
We now provide specific files in /dist for the various JavaScript module styles:
ESM Modules: /dist/htmx.esm.js
UMD Modules: /dist/htmx.umd.js
AMD Modules: /dist/htmx.amd.js
The /dist/htmx.js file continues to be browser-loadable

esm and amd are there but UMD is missing from the dist folder...

**Comment by 1cg** [comment]
sorry, docs error, should have been CJS, fixed!
