### ISSUE TITLE
htmx:invalidPath after migration to 2.0

### ISSUE THREAD

**Issue by TheLegs** [bigskysoftware/htmx#2642]
I have a tag set up like this:

`<div id="test123" class="log-viewer-box loading" hx-get="https://unpkg.com/htmx.org/README.md" hx-indicator="#log-test123-spinner"  hx-trigger="load" hx-target="this" hx-swap="scroll:bottom">
`

No matter what URL I put, it is working with 1.9.12, but as soon as I switch to 2.0.0 it shows `htmx:invalidPath` in the log with no further details.

I have tried both unminified and minified versions, specifically I have tried:

- https://unpkg.com/htmx.org@1.9.12/dist/htmx.js
- https://unpkg.com/htmx.org@1.9.12/dist/htmx.min.js
- https://unpkg.com/htmx.org@2.0.0/dist/htmx.js
- https://unpkg.com/htmx.org@2.0.0/dist/htmx.min.js

I have not configured any parameter such as self `htmx.config.selfRequestsOnly`, so it should be left to default `false`, but just to be on the safe side I have even tried to make it explicit with `<meta name="htmx-config" content='{"selfRequestsOnly":false}'>`, unfortunately with no change.

Workaround is to roll back to 1.9.12, which still works perfectly.

**Comment by alexadamski** [comment]
Yes same issue here

**Comment by alexadamski** [comment]
From the 2.0.0 Changelog:
htmx.config.selfRequestsOnly now defaults to true rather than false

**Comment by 1cg** [comment]
yep, we default to `selfRequestOnly` now, revert it with:

```html
<meta name="htmx-config" content='{"selfRequestsOnly":false}'> 
```
