### ISSUE TITLE
htmx.logAll is not a function

### ISSUE THREAD

**Issue by anentropic** [bigskysoftware/htmx#2659]
Using Vite...

I have:
```js
import htmx from 'htmx.org';
window.htmx = htmx;
```
in my `index.js`

at the bottom of my html I have:
```html
      <script>
        document.body.addEventListener('htmx:load', function (evt) {
          htmx.logAll();
        });
      </script>
```
and I get:
```
Uncaught TypeError: htmx.logAll is not a function
    at HTMLBodyElement.<anonymous> (...)
    at he (htmx__org.js?v=a64430c1:1658:21)
    at htmx__org.js?v=a64430c1:3038:11
```
so HTMX is initialised because the `htmx:load` event fired, and `window.htmx` is something, but apparently not a thing that has `logAll`

the docs here https://htmx.org/docs/#webpack say to do this `window.htmx = require('htmx.org');` in a separate file and then import that into `index.js`

but then I get `ReferenceError: require is not defined`

TBH I am lost in the confusing mess of JS build tools and module formats and just want some instructions that work

**Comment by anentropic** [comment]
so if I log what `htmx` is in the event handler...

when imported as `import htmx from 'htmx.org';` then:
![Screenshot 2024-06-21 at 14 22 39](https://github.com/bigskysoftware/htmx/assets/147840/5873ae37-66cb-4bc5-abe7-5c6a94f7f978)

as `import * as htmx from 'htmx.org';`:
![Screenshot 2024-06-21 at 14 23 49](https://github.com/bigskysoftware/htmx/assets/147840/3ac17e7b-402c-4317-8580-96f3c8cf7b6b)

as `import { htmx } from 'htmx.org';`:
`undefined`

if I just `import 'htmx.org';` then VS Code inteliisense will prompt me with `htmx.logAll()` as if it would work, but at runtime it gives `ReferenceError: htmx is not defined`

**Comment by anentropic** [comment]
ah..! here https://github.com/bigskysoftware/htmx/issues/2628

if I do this in `index.js`:
```js
import htmx from "htmx.org/dist/htmx.esm";
window.htmx = htmx;
```

then the body script works:
```html
      <script>
        document.body.addEventListener('htmx:load', function (evt) {
          htmx.logAll();
        });
      </script>
```

**Comment by Telroshan** [comment]
Hey, sorry for the inconvenience, as 1cg stated in the issue you linked
> entirely possible that those instructions are wrong now, unfortunately, since no one on the core team that I'm aware of uses webpack

We'll have to update those to match htmx 2's new setup!

Closing this issue in favor of #2628
