### ISSUE TITLE
Http response is not parsed correctly, if it contains multiple root elements, and one of them is a tr/td

### ISSUE THREAD

**Issue by K-Adam** [bigskysoftware/htmx#266]
I would like to use out of band swaps, with multiple elements. If one of the root elements in the http response is a table row, then it suddenly stops working. It usually fails silently, but if the `tr` is the first element, I get `htmx:swapError`.

Example html ( index.html ):

```html
<div>
  <table>
    <tbody>
      <tr id="row_1">
        <td>A1</td>
        <td>A2</td>
      </tr>
      <tr id="row_2">
        <td>B1</td>
        <td>B2</td>
      </tr>
      <tr id="row_3">
        <td id="td_c1">C1</td>
        <td>C2</td>
      </tr>
    </tbody>
  </table>
</div>

<p id="my_text">Test paragraph</p>


<button
  type="button"
  hx-get="example_working.html"
  hx-swap="none"
>
  Example working
</button>

<br/>

<button
  type="button"
  hx-get="example_bug1.html"
  hx-swap="none"
>
  Example bug 1
</button>

<br/>

<button
  type="button"
  hx-get="example_bug2.html"
  hx-swap="none"
>
  Example bug 2
</button>

<br/>

<button
  type="button"
  hx-get="example_bug3.html"
  hx-swap="none"
>
  Example bug 3
</button>
```

example_working.html:
```html
<tr id="row_2" hx-swap-oob="true">
    <td>col1</td>
    <td>col2</td>
</tr2>
```

example_bug1.html:
```html
<tr id="row_2" hx-swap-oob="true">
    <td>col1</td>
    <td>col2</td>
</tr>
<p id="my_text" hx-swap-oob="true">Test result</p>
```

example_bug2.html:
```html
<p id="my_text" hx-swap-oob="true">Test result</p>
<tr id="row_2" hx-swap-oob="true">
    <td>col1</td>
    <td>col2</td>
</tr>
```

example_bug3.html:
```html
<p id="my_text" hx-swap-oob="true">Test result</p>
<tr id="row_2" hx-swap-oob="true">
    <td>col1</td>
    <td>col2</td>
</tr>
<td id="td_c1" hx-swap-oob="true">col2</td>
```

**Comment by benpate** [comment]
I know there was some discussion re: this on discord, and that it's an issue with calculating <tr> parents correctly.  Just a thought, this might behave differently if you try <tbody> tags instead.  Would this workaround work for you?

```html
  <table>
    <tbody id="row_1">
      <tr>
        <td>A1</td>
        <td>A2</td>
      </tr>
  </tbody>
  <tbody id="row_2">
      <tr>
        <td>B1</td>
        <td>B2</td>
      </tr>
  </tbody>
  <tbody id="row_3>
      <tr>
        <td id="td_c1">C1</td>
        <td>C2</td>
      </tr>
    </tbody>
  </table>
```

Then swap in the whole tbody.

```html
<tbody id="row_2" hx-swap-oob="true">
<tr>
    <td>col1</td>
    <td>col2</td>
</tr>
</tbody>

<tbody id="td_c1" hx-swap-oob="true">
<tr><td>col2</td></tr>
</tbody>
```

I think HTML handles tbody tags differently, and they're able to stand on their own independently from a table, where tr tags often cannot.

**Comment by K-Adam** [comment]
@bencroker The suggested workaround in not really feasable. If I wrap each `tr` of my original table in a `tbody`, then the result would be a mess, and it would likely break the existing css definitions.

---

Since v1.0.2 is released, it is possible to swap non root elements as well, so a possible workaround is to wrap the response `tr` in a `tbody` and `table`, like this:

```html
<!-- example_workaround.html -->
<p id="my_text" hx-swap-oob="true">Test result</p>
<table>
    <tbody>
        <tr id="row_2" hx-swap-oob="true">
            <td>col1</td>
            <td>col2</td>
        </tr>
    </tbody>
</table>
```

It is not required to change the original table, only the http response.

@1cg It is reasonable to expect valid html as a result, and mixing `tr` with other html elements is not valid. This workaround works only, if I use `hx-swap="none"`, but the whole point of `oob` is to "piggy-back" additional updates on a request, so it may not be a solution for everyone. Even if you plan to fix the html parser, I recommend to note this limitation in the documentation, because others may run into this bug as well.

**Comment by 1cg** [comment]
This can be fixed by using the `htmx.config.useTemplateFragments` option for parsing responses (not IE11 compatible)
