### ISSUE TITLE
i got error :htmx:invalidPath for verifyPath 

### ISSUE THREAD

**Issue by cryp2one** [bigskysoftware/htmx#2669]
i got error :htmx:invalidPath for verifyPath when i use hx-get from my rest api with another site

**Comment by Telroshan** [comment]
Referencing #2546 as your comment here suggests that was the same issue, submitted a PR to fix the `selfRequestsOnly` doc

**Comment by Telroshan** [comment]
Closing this as the documentation was updated ; this error is now intended to happen by default, and you have to set `selfRequestsOnly` to true when dealing with external URLs to allow this

**Comment by IT-Cru** [comment]
I think it would be good to also add this as information to related extensions and adjust examples in their README.md files.

For example in client side templates extension all mustache examples are not working currently without switching **selfRequestOnly** to `false`.
https://github.com/bigskysoftware/htmx-extensions/blob/main/src/client-side-templates/README.md

**Comment by Telroshan** [comment]
Good catch @IT-Cru , if you feel like it, a PR would be welcome to fix that documentation!
