### ISSUE TITLE
Confused about detail.successful and detail.failed for htmx:afterRequest

### ISSUE THREAD

**Issue by JanRomero** [bigskysoftware/htmx#2671]
Idk maybe I’m reading the docs wrong, but shouldn’t these be the other way around?

[The docs say](https://htmx.org/events/#htmx:afterRequest):
> **detail.successful** - true if the response has a 20x status code or is marked `detail.isError = false` in the `htmx:beforeSwap` event, else false
> **detail.failed** - true if the response does not have a 20x status code or is marked `detail.isError = true` in the `htmx:beforeSwap` event, else false

Also, doesn’t `htmx:afterRequest` run before `htmx:beforeSwap`?

Here’s what the afterRequest event looks like for a 400 response in Firefox (Chrome is the same):
![failed successfully](https://github.com/bigskysoftware/htmx/assets/7873027/717eb9cd-3520-4214-abdc-a8556130ac6e)

Cheers!

**Comment by Telroshan** [comment]
Weird, I don't experience the same behavior, see [this JSFiddle](https://jsfiddle.net/nL68ws9o/) where it acts as you would expect...
![image](https://github.com/bigskysoftware/htmx/assets/19146183/4e38f944-b29a-4c74-bb4f-0b0df5808cfd)

The part of the code that's responsible to determine whether the request is an error or not relies on the htmx2-introduced `responseHandling` property ;
https://github.com/bigskysoftware/htmx/blob/6f83885de3e3881d262a6267fd55be69a18daa75/src/htmx.js#L264-L268

That's the default configuration, which sets `error` to `true` for any 4xx or 5xx code. Later on, this value is used to determine whether the request is successful, or a failure, as so :
https://github.com/bigskysoftware/htmx/blob/6f83885de3e3881d262a6267fd55be69a18daa75/src/htmx.js#L4606-L4608

Did you modify that property by any chance and maybe forgot to set `error` to true for the 400 code ?
Let me know!

**Comment by JanRomero** [comment]
@Telroshan Thank you for the quick response! You are correct of course. It’s a behaviour of the Response Targets extension and fixed by setting `htmx.config.responseTargetUnsetsError = false`:

https://jsfiddle.net/34wtxzh5/1/

Honestly I love HTMX but its weird defaults drive me nuts sometimes.

Thanks!

**Comment by schungx** [comment]
> @Telroshan Thank you for the quick response! You are correct of course. It’s a behaviour of the Response Targets extension and fixed by setting `htmx.config.responseTargetUnsetsError = false`:

Yup.  Tripped me up exactly the same way, but you found out before I can post an answer.
