### ISSUE TITLE
htmx:afterSwap is not fired in the extension.

### ISSUE THREAD

**Issue by mkgn** [bigskysoftware/htmx#2675]
I have a simple extension that controls the swap as below

    
    (function () {
        htmx.defineExtension('fcl-htmx-widget', {
            onEvent: function (name, evt) {
            
            console.log(name)

            if (name === "htmx:beforeSwap") {

                const isOurExt = evt.detail.elt.attributes.getNamedItem('hx-ext')?.value.includes('fcl-htmx-widget');
                if (!isOurExt) return;
                
                const widgetId = evt.detail.elt.attributes.getNamedItem('name')?.value;
                if (window.dashGrid){
                    const widgetOpts = JSON.parse(evt.detail.elt.attributes.getNamedItem('data-widget-opts')?.value || '{}')

                     //calling a gridstack js method to add a widget
                    window.dashGrid.addWidget({w: widgetOpts?.width || 6, h: widgetOpts?.height || 4, id: widgetId ,content: ''})

                    //retarget widget contents coming from server to go inside newly added widget above
                    evt.detail.target = htmx.find(`[gs-id=${widgetId}] .grid-stack-item-content`)

                    //ask htmx to process the newly added widget node
                    htmx.process(htmx.find(`[gs-id="${widgetId}"]`))
                }
                else                
                    evt.detail.shouldSwap = false;
            }
        
            if (name === "htmx:afterSwap") 
            {
                //need to do some further processing here
                const widgetScript = htmx.find(`#${widgetId}-widget`).attributes.getNamedItem('data-widget-script');
            }
        }
    });
    })();

So widget contents from server gets added properly. Now I expect it to fire afterSwap also because I have few more steps to perform with the newly swapped widget element (which I have asked htmx to process already) However it doesn't seem to fire the htmx:afterSwap at all. If I log all the events that gets fired below is the list as it appears in the console.

htmx:trigger
htmx:confirm
htmx:configRequest
htmx:validateUrl
htmx:beforeRequest
htmx:beforeSend
htmx:xhr:loadstart
htmx:xhr:progress
htmx:beforeOnLoad
htmx:beforeSwap <-- This works so I can do my work
htmx:afterRequest
htmx:afterOnLoad
htmx.min.js:1 [Violation] 'load' handler took 2352ms <-- also is this something i should be worried about?
htmx:xhr:loadend

Why is afterSwap not firing? And the event order is messed up?

**Comment by Telroshan** [comment]
> And the event order is messed up

The order seems correct to me looking at the codebase, which one(s) sound off to you?

As for the `afterSwap` not firing, could it be related to #2596 and #2420 ? Seems we have an issue where swapping a parent (`outerHTML`) won't trigger the `afterSwap` / `afterSettle` events
Let me know!

**Comment by mkgn** [comment]
As you said the event order seems to be fine. my bad. Since the afterSwap is not happening properly i used a global afterSwap() and got it done, but I guess this has to be looked into.
