### ISSUE TITLE
htmx.ajax lacks hx-indicator (and other?) capabilities

### ISSUE THREAD

**Issue by renannprado** [bigskysoftware/htmx#2686]
I'm building a fairly complicated screen (for someone that's a frontend newbie 😄) and I had to fallback to use a JSON API instead of our beloved HATEOAS.

Long story short: 

I'm using Alpine.js (to make the screen dynamic on the client side, it controls the whole page) and I submit a form using `fetch` native browser API.

Once the API returns 2xx, then I would like again to go back to "htmx mode" within my architecture, for this purpose I've used [`htmx.ajax`](https://htmx.org/api/#ajax).

Here's the pseudocode:

```typescript
const response = await fetch("post data");

if (response.status === 200) {
    htmx.ajax("GET", "/my-endpoint", "#my-panel")
}
```

The problem is that when I use `htmx.ajax`, I don't have the `hx-indicator` capability that I really like to use.
While I could of course use (more) js to make the indicator work as with htmx itself, I really would like this feature is exposed to the `htmx.ajax`.

Workaround (or actual solution?):

While trying to get this fixed, I thought of using the property `source` element of the `htmx.ajax` and indeed it takes into consideration the `hx-indicator` (and possibly other) attributes, therefore having the result I wanted.

But now then I leave a question here: is this the right thing to do? is there a better way to do it than creating an artificial/hidden element just for this purpose?

**Comment by Telroshan** [comment]
Hey,
> is this the right thing to do? 

Yep! Relevant parts of the code:
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/src/htmx.js#L3843-L3844

Then in `issueAjaxRequest`:
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/src/htmx.js#L4051-L4053

So what's happening is, if you don't define a `source` element yourself, htmx will use the `body` as a fallback. Many htmx attributes come into play in a request's flow, such as `hx-sync`, `hx-include`, `hx-request` and others (`hx-indicator` included). Unfortunately we don't have a way to override those purely with `htmx.ajax` as of today, and you'll have to configure them using attributes on an element.
Whether that element has to be artificial/hidden is up to you! I like to define these attributes on container elements with an ID in my case, so that when reading the HTML, it's clear that some htmx logic will be happening here (because of the configuration attributes) + I can quickly find where by searching for the element's ID across the codebase.
Or, when I'm doing a "little" request and only care about the indicator and no other request configuration property, I simply use the indicator element (or selector that resolves to that indicator element) itself as the `source`

Hope this helps!

**Comment by renannprado** [comment]
@Telroshan I see, makes sense. It would be really great to mention that in the documentation (i.e. that `htmx.ajax` respects `hx-*` attributes on the `source` element).

If nobody does it, I will send a PR to clarify this part in the next days. Thanks for the help!

There's one part that I kind of missed in the original post:

Would you have any suggestions on how to "trigger" the `hx-indicator` behavior _outside_ of `htmx.ajax`? As I mentioned, I do a `POST` directly via `fetch` and of course that doesn't trigger the `hx-indicator` nor the `hx-disabled-elt` (which I also need 😬).

Any hints on how to do that? (other than the besides mimicking outside of it)

**Comment by Telroshan** [comment]
> If nobody does it, I will send a PR to clarify this part in the next days

Sure, feel free to do so!

If you handle the request not using htmx, then you won't be able to use htmx' request workflow. You'll have to do those in JS yourself :
- You can manually make an indicator visible by putting the `htmx-request` (see [htmx.config.requestClass](https://htmx.org/reference/#config)) on it as it's how the default indicators style works
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/src/htmx.js#L4889-L4899
- As for `hx-disabled-elt`, you may simply toggle the `disable` attribute on the element

Though, if you only need to make a POST request here and process a response, please note that you could totally rely on `htmx.ajax` and simply define a [`handler`](https://htmx.org/api/#ajax) function property in your `htmx.ajax`'s context.
By specifying this property, you override the default response handling of htmx so you basically "disable" the initial behavior or swapping the response to whatever the target/method is.
This way, you may still enjoy htmx's other attributes and systems such as the indicator, disabled elt and so on, without the swapping part

**Comment by renannprado** [comment]
@Telroshan makes sense once again. I'll give it a try with the `htmx.ajax` approach. The catch is that I need to POST a JSON payload and not just `multipart/form-data` or `application/x-www-form-urlencoded`. But I suppose I can just create an extension to craft the JSON as I need in this case, right?

Since there's no documentation for what the `handler` takes as parameters, I dig a bit into the source code and it should be (correct me if I'm wrong):

![image](https://github.com/bigskysoftware/htmx/assets/2359543/135dea62-3b21-4861-b499-0e4bbe9625c7)

```js
handle(elt, HtmxResponseInfo)
```

Once again I can submit a PR for the docs when I have time.

**Comment by Telroshan** [comment]
Never tried it but you could even probably use the existing [json-enc extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/json-enc/README.md), and simply put this `hx-ext="json-enc"` attribute on your `source` element or any of its parents as well!

Yep that's it! source element as the first parameter and the response info object as the 2nd argument.
Many htmx events let you intercept and override this object before your handler gets called though (beforeRequest, configRequest events come to mind but I'm sure there are others, not mentioning extensions that can also do that), so I personnally tend to simply log the full object and see what's inside when I need it.
But basically for your request-outside-htmx processing, you'll probably only care about `responseInfo.xhr` that is a plain [XMLHTTPRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) reference

**Comment by renannprado** [comment]
Unfortunately it didn't work... I don't really understand why, so for now I parked the idea and went with adding the class manually via javascript and so on. But anyway, I learned something at least. Thanks a lot @Telroshan!
