### ISSUE TITLE
HTMX 2.0 release missing htmx.d.ts typescript definitions file

### ISSUE THREAD

**Issue by cseufert** [bigskysoftware/htmx#2687]
The typescript definitions seem to be lost when packaging the v2.0.0 release.

See: https://www.npmjs.com/package/htmx.org/v/2.0.0?activeTab=code

The file path is referenced by `package.json`.

**Comment by cseufert** [comment]
This could possible be because the output file is the /src path, not the /dist path
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/jsconfig.json#L7

**Comment by Telroshan** [comment]
Hey, this should be fixed by #2653 in the next release, let's follow up on this when next version gets released
