### ISSUE TITLE
Docs for beforeHistorySave event

### ISSUE THREAD

**Issue by limugob** [bigskysoftware/htmx#2688]
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/www/content/events.md?plain=1#L265-L268

The description of the beforeHistorySave and the historyRestore event is the same, but beforeHistorySave should have something like: 
 > This event is triggered before the content is saved in the history api.

https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/www/content/events.md?plain=1#L257-L260

**Comment by Telroshan** [comment]
Hey, good catch, especially as the events table already mentions
> triggered before content is saved to the history cache

This was probably an oversight at the time.
Feel free to open a PR against `master` to fix documentation!
