### ISSUE TITLE
Feature request: Client-side redirect

### ISSUE THREAD

**Issue by rschroll** [bigskysoftware/htmx#27]
I would like to propose that there should be a way to indicate within htmx that, after a successful request, another endpoint should be accessed for the new content.

I've been looking at switching an existing project, which uses jQuery to do HTML replacement, over to htmx.  This projects has users and groups in a many-to-many relationship, and has an endpoint to delete the association between a user and a group.  The user's profile page had a AJAX link to this endpoint that easily switched over to htmx.  The old jQuery code would trigger a refresh of that part of the page once the first request succeeded.  To model that with htmx, I changed to server to return a redirect to the fragment URL, instead of an empty response.  So far, this works great.

However, the group page also had code to hit this endpoint, which should then redirect to another fragment.  If I switched that page over, it would load the wrong fragment in when deleting a user from a group.  I can see a number of ways to fix this, but none is great:
- We could listen for events and trigger this refresh from JS.  But this is what I'd like to get away from.
- We could create two delete endpoints, differing only in where they redirect.  This seems needlessly duplicative.
- We could pass the redirect URL along with the initial request in one of several ways.  This seems better, but it still feels clunky.

Instead, I'd like to propose that htmx adds a way to indicate that a second request be fired off when the first succeeds.  This would allow us to return the delete endpoint to returning nothing, with the two pages indicating how to reload their fragment after the delete happens.  Some decisions would be needed:
1. What is the syntax for this option?
    - A new attribute like `hx-redirect` or `hx-success` (which suggests `hx-error`, too).
    - Multiple URLs in `hx-get` and friends.

    I think the latter could get too complex, but I don't have strong feelings here.
2. What verb should be used for the follow-up requests.  My gut feeling is that they should be GETs, acting like it would for 303 (and de-facto 302) responses.
3. When is this redirect triggered?
    - On any successful response for the primary request.
    - Only when the primary response is empty.
    - Only when the primary response is 204.
    - Only when the primary response is 30x.  (Can we convince the XHR to not follow these automatically?)

    I view this as taking the redirect decision away from the server, so it should happen on any success.  The other options would allow for more complex behavior, I guess.

I think #21 would provide another way to accomplish this goal.  However, that's attacking a larger problem (if I'm understanding it correctly).  It would also introduce more indirection to the behavior -- it wouldn't be obvious that one request triggers another.  Having the redirect on the same element as the original request would make the flow more obvious, at the cost of limiting the complexity of flows available.

If you would consider adding such a feature, I'd be happy to take a shot at a first prototype.

**Comment by chg20** [comment]
Could consulting the "X-HX-Current-URL" header on the delete help?

Or maybe looking at the "X-HX-Target" header?  That will be the id of the target element, if that is different on the two pages.

I am trying to keep the number of attributes to a minimum as a design goal, but I'm open to functionality.  In the chat we were discussing the way that dependencies worked in intercooler and were kicking around syntax like this:

<div hx-trigger="subscribe:/contacts/">
  ...
</div>

To indicate that this div should be refreshed whenever a mutating request occured against that path.

**Comment by rschroll** [comment]
The headers could certainly be used by the server to determine where the redirect goes.  What I don't like about this is, every time a new page access an API endpoint, that endpoint would have to be updated with a new redirect rule.  The benefit to having that redirect defined client-side is that the client code could be updated and rearranged at will, without the server needing to change.  This could conceivably let htmx be used with a third-party server that knows nothing about htmx.  (Admittedly, I don't have an example in mind.)

If the main worry is about an explosion of tags, this could be specified within the current endpoint tag.  For example, we could (ab)use the anchor portion of the url: `hx-post="/delete/object#/display/list"` would first POST to `/delete/object` and then GET (?) `/display/list`.

A trigger chain would be another solution, definitely.  My worry there is it may get rather complex pretty quickly.  This sort of redirect wouldn't solve as many use cases, but it feels a bit more contained.

Perhaps as a middle ground, elements could define an event that they trigger when they complete, and other elements could subscribe to such events.  Something like
```
<div hx-trigger="update-list" hx-get="/display/lilst">
    <button hx-post="/delete/object" hx-success-event="update-list"></button>
</div>
```
This would allow arbitrary connections, as with the subscription idea, but require a more explicit definition of how to make the connections.  It would require an additional attribute (or a complex syntax inside `hx-trigger`).  If you'd prefer to discuss this in #21, let me know.

**Comment by chg20** [comment]
Let's not move it over to #21 quite yet.

So you can accomplish what you have here:

```html
<div hx-trigger="update-list" hx-get="/display/lilst">
    <button hx-post="/delete/object"></button>
</div>
```

by using the `X-HX-Trigger` response header like so:

`X-HX-Trigger: update-list`

The event isn't in the HTML, but what I'm struggling with is: should it be?  Or should the HTML be subscribing to high level events that the server side emits?  And if the HTML is subscribing to these high level events, is it reasonable to ask that it be a parent of the element making the request?

This is what I see as the big advantage of resurrecting a more explicit `ic-deps` tag: you have an explicit mechanism for cross-DOM dependency triggers encoded in the HTML directly.

**Comment by chg20** [comment]
We want a request to issue here, so I really feel like this conceptually belongs on `hx-trigger`.

```html
  <div hx-trigger='depends:/foo/bar'>...</div>
```
and having it trigger on mutating requests to `/foo/bar` is what I currently like the best.  Not sure on the term though.  `depends`?  `subscribe`?

**Comment by rschroll** [comment]
On Thu, May 21, 2020 at 5:15 PM chg20 <notifications@github.com> wrote:

> So you can accomplish what you have here:
>
> <div hx-trigger="update-list" hx-get="/display/lilst">
>     <button hx-post="/delete/object"></button></div>
>
> by using the X-HX-Trigger response header like so:
>
> X-HX-Trigger: update-list
>
> Interesting -- I hadn't realized that this would work.  I was expecting
you'd have to add an event listener to document and then trigger the
appropriate elements from there.  This could solve the main issues I was
having with other solutions.  The various API endpoints could trigger an
event saying, "$X just happened", and it would be up to the various
elements on the page to subscribe to be refreshed at the appropriate
times.  It would require modification to the server, but that would be a
fixed change, which seems more reasonable than an update for every new use
of the endpoint.

> The event isn't in the HTML, but what I'm struggling with is: should it
> be? Or should the HTML be subscribing to high level events that the server
> side emits? And if the HTML is subscribing to these high level events, is
> it reasonable to ask that it be a parent of the element making the request?
>
I think my only complaint with the above now is that the action is not
obvious just from the HTML.  You have to know the server's reply headers to
trace what happens

> This is what I see as the big advantage of resurrecting a more explicit
> ic-deps tag: you have an explicit mechanism for cross-DOM dependency
> triggers encoded in the HTML directly.
>
Agreed.  My concern here is that the dependencies seems complex, both to
implement and to keep in your head.  But this is just based on a glance at
the intercooler docs, so I don't really know what I'm talking about.

As a concrete example, the app I'm looking at converting as urls like
`/assoc/{id}/delete` and `/assoc/{id}/update/{parameter}`.  (I won't
attempt to defend this structure, but that's what it is right now.)  We'd
like to trigger on URLs of the first pattern but not the second.  How easy
would this be to program though a dependency structure?

**Comment by chg20** [comment]
OK, I just pushed up an extension mechanism and mentioned using it on https://github.com/bigskysoftware/htmx/issues/21

I don't see a reason why an extension like I mention there couldn't support simple `*` matching to address your needs:

```html
<body hx-ext="path-deps">
  <div hx-trigger="path-deps" path-deps="/assoc/*/delete">...</div>
  <button hx-post="/assoc/22/delete">Post It!</button>
</body>
```

**Comment by rschroll** [comment]
Yep, it looks like I can implement any number of these solutions via the extension mechanism.  Thanks!
