### ISSUE TITLE
htmx 2.0.0 breaks <template> elements inside Web Components

### ISSUE THREAD

**Issue by luontola** [bigskysoftware/htmx#2702]
When a htmx response contains `<template>` elements inside a Web Component element, htmx 1.9.12 adds them to the DOM, but htmx 2.0.0 removes them. This breaks web components which use that method to receive data from the server.

## Example app

1. Save this file as `server.py`
```python
from flask import Flask

app = Flask(__name__)


@app.route("/")
def home():
    # Works with https://unpkg.com/htmx.org@1.9.12/dist/htmx.min.js
    # Doesn't work with https://unpkg.com/htmx.org@2.0.0/dist/htmx.min.js
    return """
<script src="https://unpkg.com/htmx.org@2.0.0/dist/htmx.min.js"></script>
<script type="module">
class HelloWorldElement extends HTMLElement {
  constructor() {
    super();
  }

  connectedCallback() {
    const template = this.querySelector("template");
    console.log("template:", template, template?.content.textContent)
  }
}
customElements.define('hello-world', HelloWorldElement);
</script>

<div hx-get="/lazy" hx-swap="outerHTML" hx-target="this" hx-trigger="load">
</div>

</div>
"""


@app.route("/lazy")
def lazy():
    return """
<hello-world>
<template>Lazy loaded content</template>
</hello-world>
"""

```

2. Run the app with the commands:

```
pip install Flask
flask --app server.py --debug run
```

3. Open the app at http://127.0.0.1:5000/

4. Open the JavaScript console and see what is printed there on page load

### Expected result

- The code prints `template: <template>​…​</template>​ Lazy loaded content`
- This is what happens on htmx 1.9.12

### Actual result

- The code prints `template: null undefined`
- This is what happens on htmx 2.0.0

**Comment by kubeden** [comment]
Hey, after some investigation, I found out the following function added to 2.0.0 which does not exist in 1.9.12:

```
      // oob swaps
      findAndSwapOobElements(fragment, settleInfo)
      forEach(findAll(fragment, 'template'), /** @param {HTMLTemplateElement} template */function(template) {
        findAndSwapOobElements(template.content, settleInfo)
        if (template.content.childElementCount === 0) {
        // Avoid polluting the DOM with empty templates that were only used to encapsulate oob swap
          template.remove()
        }
      })
```

You can see here that there is a comment _"// Avoid polluting the DOM with empty templates that were only used to encapsulate oob swap"_

Now, I tested your code and upon encapsulating the "Lazy loaded content" inside a **_\<p>_** tag, it is being correctly returned.

I am assuming the **_\<template>_** is considered empty if there is no tag inside.

A fix to this might be to instead of having a plaintext in your **_\<template/>_**, to instead have text inside a tag (p h2 etc.)

**Plaintext inside the template:**

<img width="545" alt="image" src="https://github.com/bigskysoftware/htmx/assets/40846846/dd275482-816e-4fa8-9bf2-1a68c4f17488">

<img width="440" alt="image" src="https://github.com/bigskysoftware/htmx/assets/40846846/26ec80cb-0643-4f30-ba03-a20a22c493b7">

**P tag inside the template:**

<img width="610" alt="image" src="https://github.com/bigskysoftware/htmx/assets/40846846/e71c4079-693a-4b6f-b626-3efc42a871dd">

<img width="435" alt="image" src="https://github.com/bigskysoftware/htmx/assets/40846846/ba5b74ef-9424-4e44-8bee-3a8116a6744c">

Otherwise the function might need to be deleted or change this line:

```
if (template.content.childElementCount === 0) {
```

To (or similar)... not sure about this, though. Someone from the core team should jump into the discussion.

```
if (template.content && template.content.textContent && template.content.textContent.trim().length > 0) {
```

**Comment by luontola** [comment]
Does htmx create some of its own templates and use them for oob swap? It seems dangerous to find and remove arbitrary template elements, instead of just those that htmx has created for a specific purpose. Maybe the oob swap templates could be tagged with a custom class or attribute for identification, and only delete those?

**Comment by kubeden** [comment]
Continuing the discussion with more investigation

The following function seems to be taking care of OOB elements:

**_findAndSwapOobElements(fragment, settleInfo)_**

```
function findAndSwapOobElements(fragment, settleInfo) {
    forEach(findAll(fragment, '[hx-swap-oob], [data-hx-swap-oob]'), function(oobElement) {
      if (htmx.config.allowNestedOobSwaps || oobElement.parentElement === null) {
        const oobValue = getAttributeValue(oobElement, 'hx-swap-oob')
        if (oobValue != null) {
          oobSwap(oobValue, oobElement, settleInfo)
        }
      } else {
        oobElement.removeAttribute('hx-swap-oob')
        oobElement.removeAttribute('data-hx-swap-oob')
      }
    })
  }
```

Now back to oob swaps again:

```
      // oob swaps
      findAndSwapOobElements(fragment, settleInfo)
      forEach(findAll(fragment, 'template'), /** @param {HTMLTemplateElement} template */function(template) {
        findAndSwapOobElements(template.content, settleInfo)
        if (template.content.childElementCount === 0) {
        // Avoid polluting the DOM with empty templates that were only used to encapsulate oob swap
          template.remove()
        }
      })

```

We are looping through each occurance of the fragment 'template' from the response of the findAll function ([see htmx official doc](https://htmx.org/api/#findAll)) so it seems htmx is indeed looping through all elements of some type:
<img width="700" alt="image" src="https://github.com/bigskysoftware/htmx/assets/40846846/8d391876-9ab3-4ecf-a1e8-cbca9ecaaaa0">


Maybe if the findAndSwapOobElements() is assigned to a variable to introduce a second check (if HTMX modified the template) before removing the OOB template, that would help?

```
forEach(findAll(fragment, 'template'), /** @param {HTMLTemplateElement} template */function(template) {
    let wasModified = findAndSwapOobElements(template.content, settleInfo)
    if (wasModified && template.content.childNodes.length === 0) {
      // Only remove if HTMX modified it and it's completely empty
      template.remove()
    }
  })
```

But then... I think this is starting a different discussion that maybe needs a new issue opened.

So it seems we are back to the initial workaround or "fix":

🚧 Workaround: don't leave plaintext inside \<template>
✅ Fix: check if there is at least one character before removing (not sure if that's a good practice... I need suggestions here); if someone approves this direction, I would be happy to open a pull request.

**Comment by kubeden** [comment]
Should I tag someone from the maintainers team? Or should I directly start PR to kickoff a discussion inside?

I'm new to this whole open source contributing thing. 🥲

**Comment by Telroshan** [comment]
Hello @kubeden, haven't had much time lately to investigate issues, a bugfix PR would be very welcome as per our [contribution guidelines](https://github.com/bigskysoftware/htmx/blob/master/CONTRIBUTING.md):
> Correspondingly, it is fine to directly PR bugfixes for behavior that htmx already guarantees, but please check if there's an issue first, and if you're not sure whether this is a bug, make an issue where we can hash it out..

So if you feel like it, sure go for it!
