### ISSUE TITLE
Docs for hx-post

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#271]
I am looking at this page: https://htmx.org/attributes/hx-post/

I am missing some docs: How can I send post data to the server?

**Comment by 1cg** [comment]
`hx-post` will include all the input data of an enclosing form, if any.

You can also use other attributes such as `hx-include`, `hx-params`, `hx-vars` and `hx-vals`, as described here:

https://htmx.org/docs/#parameters
