### ISSUE TITLE
Does new extension released with core?

### ISSUE THREAD

**Issue by godsarmy** [bigskysoftware/htmx#2724]
Hi

I am glad to know htmx 2.0.1 is released yesterday. But i did not see [extension](https://extensions.htmx.org/) new release. The latest version available is still 2.0.0. (e.g. https://unpkg.com/htmx-ext-ws@2.0.0/ws.js).

How is the extension release lifecycle in the future?

**Comment by Telroshan** [comment]
Extensions have their own version numbers now (if you look at sse, it's in 2.2.1 already), they are all in major version 2.x to match htmx but the following numbers are extension-specific.
Unless the htmx update breaks some extensions, there's no reason to update them as their code didn't change (as opposed to htmx 1 where extensions were sharing the same package as htmx itself, thus inherited its version number).
Hope this helps!

**Comment by godsarmy** [comment]
> Extensions have their own version numbers now (if you look at sse, it's in 2.2.1 already), they are all in major version 2.x to match htmx but the following numbers are extension-specific. Unless the htmx update breaks some extensions, there's no reason to update them as their code didn't change (as opposed to htmx 1 where extensions were sharing the same package as htmx itself, thus inherited its version number). Hope this helps!

awesome. Thank you for the explanation.
