### ISSUE TITLE
`'htmx.d.ts' is not a module`

### ISSUE THREAD

**Issue by Alexerson** [bigskysoftware/htmx#2733]
With htmx 2.0.1, I get the following error when trying to `import htmx from "htmx.org";`:

`File './node_modules/htmx.org/dist/htmx.d.ts' is not a module.ts(2306)`

I believe this is happening because the `htmx.d.ts` file should include `export default htmx;`.
Adding this line manually in the file fixes the issue. 

I will create a PR for this.

**Comment by renannprado** [comment]
I worked around this issue by adding the following snippet to my `tsconfig.json`:

```json
{
    "typeAcquisition": {
        "include": ["node_modules/htmx.org/dist/htmx.d.ts"],
        "enable": true
    }
}
```

**Comment by Alexerson** [comment]
I looked into this, and I’m not sure it’s fixing the issue though… 
Do you mind showing how you import the lib in your ts file?

**Comment by renannprado** [comment]
> I looked into this, and I’m not sure it’s fixing the issue though… Do you mind showing how you import the lib in your ts file? Also, are you on 2.0.0 or 2.0.1?

@Alexerson I edited my comment. It was actually not correct as the `typeAcquisition` property didn't fix it in the end (it was a lot of trial an error and I was mislead to believe that config fixed it).

I also added the relevant typescript snippet. I hope it helps.

**Comment by Alexerson** [comment]
Ah, thanks. But in that case, isn’t `htmxLib` just typed as `any` in your code?
My temporary solution is to manually copy the version of the .d.ts file I generate from the .esm file and manually add it in my project. I strongly believe that my PR is the proper fix though.

**Comment by renannprado** [comment]
> Ah, thanks. But in that case, isn’t `htmxLib` just typed as `any` in your code?

No it's not, because of the window declaration.

**Comment by alexpetros** [comment]
Fixed by: https://github.com/bigskysoftware/htmx/pull/2769
