### ISSUE TITLE
Add csrf token to ajax header

### ISSUE THREAD

**Issue by pmc2010** [bigskysoftware/htmx#276]
Hi - I'm using django and need to be able to add an X-CSRFToken header to the ajax calls for authentication.  Can this be done?

**Comment by 1cg** [comment]
A popular question lately.  :) 

This might be relevant:

https://twitter.com/cparlette/status/1340039019724496899

So something like:

<body hx-vals='{"csrf_token": "{{ csrf_token() }}"'>
  ...
</body>

Should work.  

I hope to have better django support ootb soon.

**Comment by danjac** [comment]
For reference: the above code won't work with Django. The X-CSRF-Token needs to be in the header.

You need to add this snippet somewhere in your template:

[  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
  </script>
](url)

**Comment by osadasami** [comment]
Two ways to configure Rails csrf tokens with HTMX

## 1

```js
document.body.addEventListener('htmx:configRequest', (event) => {
  event.detail.headers['X-CSRF-Token'] = document.getElementsByName('csrf-token')[0].content
})
```

## 2

```html
<body hx-vals='{"authenticity_token": "<%= form_authenticity_token %>"}'>
```
