### ISSUE TITLE
htmx.trigger() parameter detail works as css selector as default - should be documented.

### ISSUE THREAD

**Issue by hulsbo** [bigskysoftware/htmx#2764]
Hello, 

A value that is not a string, for any key inside the object of the third parameter detail for htmx.trigger(), becomes a id css selector. See example "someValue" below: 
```
  htmx.trigger("#tab2", "myEvent", {answer: someValue});

```
someValue (as opposed to "someValue") becomes here evaluated as #someValue in a css selector, sending the HTML element as an object in event.detail.

Further remarks:
- css custom selectors for htmx, such as "document", are also working here. 
- Stand-alone class selectors seems not to work ("." gives syntax error).

Is this feature intentional? If so, it should be documented.

**Comment by Telroshan** [comment]
Hey,

> A value that is not a string

I'm confused, what's the type of `valueTreatedAsAnIdForCssSelector` here then if not a string? (Or `someValue`? Do those two refer to the same value in this context btw? I'm asking as I don't see a `someValue` in the above example)

Glanced very quickly over the htmx code, I don't see any processing done to the properties of the third parameter, i.e. the `detail` object 🤔 
Would you mind providing a reproducible example on say a CodePen or a JSFiddle to better identify the issue? Thanks!

**Comment by hulsbo** [comment]
> Hey,
> 
> > A value that is not a string
> 
> I'm confused, what's the type of `valueTreatedAsAnIdForCssSelector` here then if not a string? (Or `someValue`? Do those two refer to the same value in this context btw? I'm asking as I don't see a `someValue` in the above example)
> 
> Glanced very quickly over the htmx code, I don't see any processing done to the properties of the third parameter, i.e. the `detail` object 🤔 Would you mind providing a reproducible example on say a CodePen or a JSFiddle to better identify the issue? Thanks!

Apologies, the issue post was inconsistant in the naming, you should read it as ´ valueTreatedAsAnIdForCssSelector = someValue´. See also latest edit. 

Nevertheless, I've tried to reproduce with codepen without results. Not sure I get htmx working correctly. Or that this was just a local bug in my own code. Next time I'll have an example ready up front.

**Comment by hulsbo** [comment]
Hello again, 

Now I have a working example, see .html file below:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.11/htmx.min.js"></script>
	<script>
		setTimeout(() => {
			htmx.trigger("#div1", "trigger", {id: div1});
		}, 100)
	
	</script>
</head>
<body>
    <div id="div1" hx-on-trigger="console.log(event.detail.id)"></div>
</body>
</html>
```

**Comment by Telroshan** [comment]
Thanks for the details, I see what's happening now.

Using `div1` like this, not surrounded with quotes, means using the `div1` variable, whatever its value is.
Browsers provide this handy shortcut where, using the ID of an element as a variable will resolve to the element itself.
You can observe that latter behavior on [this JSFiddle](https://jsfiddle.net/teyqbf4L/). Notice how there's no htmx involved at all here, purely the browser's native behavior.

So what's happening in your case, is that you're passing the `div1` element itself as the value of the `id` property of your detail object. Again, native browser behavior, doesn't actually have to do anything with htmx.

**Comment by hulsbo** [comment]
I see. I was not aware of that built-in browser feature, assuming it came from htmx therefore. Please excuse my ignorance.

Kind regards,
Oskar
