### ISSUE TITLE
Version `2.0.1` marked as `latest` in NPM

### ISSUE THREAD

**Issue by heyainsleymae** [bigskysoftware/htmx#2772]
The [htmx.org](https://www.htmx.org) homepage states:
> **NEWS:** htmx 2.0 has been released! It is not currently marked as [latest](https://docs.npmjs.com/cli/v10/commands/npm-dist-tag#purpose) in NPM so that people using the [1.x line](https://v1.htmx.org/) are not accidentally upgraded. We will mark 2.0 as `latest` at some point in 2025.

However, `2.0.1` is currently marked as `latest`, and `2.0.0` is marked as `next`, meaning that I unintentionally upgraded to `2.x` before rolling back to `1.9.12`. Have plans to mark `2.x` as `latest` in 2025 changed, or is this a mistake?

**Comment by 1cg** [comment]
Dammmit, that's a mistake on my part.  I have fixed the tags.
