### ISSUE TITLE
`<img loading="lazy">` in response does not work

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [bigskysoftware/htmx#2774]
`<img>` tags with `loading="lazy"` in an HTMX response are eagerly loaded even if they are offscreen. Tested with a large gallery of images on Firefox.

I've had this happen if an image's `src` is set in Javascript before `loading` is set.

**Comment by Telroshan** [comment]
As far as I know, htmx doesn't do any processing with the elements attributes except the [attributesToSettle](https://htmx.org/reference/#config), which do not include src nor loading by default though.

Could you provide a reproducible example such as a JSFiddle / Codepen?
If you feel like investigating, a bugfix PR would be very welcome!

**Comment by ColonelThirtyTwo** [comment]
@Telroshan Interesting. I'll try to look into it from my side.

I'd make a fiddle but I'm not sure how to configure an endpoint to return the HTML to test with - codepen asset uploading requires paying them and while JSFiddle has an echo endpoint, I don't know how to POST raw HTML to that via htmx.

**Comment by Telroshan** [comment]
You can use the demo script and mock endpoints using a `template` element with `url` attribute, like on [this JSFiddle](https://jsfiddle.net/sc3xwzpr/), hope this helps @ColonelThirtyTwo !

**Comment by ColonelThirtyTwo** [comment]
Didn't know about the demo script, that works. Here's a fiddle: https://jsfiddle.net/9s1hop52/

I think this is a Firefox bug... Chromium correctly defers the image loading.

**Comment by ColonelThirtyTwo** [comment]
Yeah, I mentioned that in my OP, though I wasn't aware that it was a Firefox specific issue. My JSFiddle above has `loading` before `src`, and it's still loading eagerly. It might be that the issue works differently for when loading the DOM from HTML (which I assume is what HTMX does) versus setting the attributes via JS (for things like React).

**Comment by Telroshan** [comment]
> Yeah, I mentioned that in my OP
> My JSFiddle above has loading before src

Oops, apologies for that, seems I really need to learn how to read 😭 

That's very weird indeed!
Htmx uses `DOMParser` internally to parse the HTML response, so your assumption is correct, htmx doesn't directly set the attributes.
If you feel like investigating, maybe you could setup a fiddle that uses DOMParser and no htmx at all, to see if by parsing the sample HTML of your previous fiddle and appending it to the DOM, you get the same behavior or not (thus to identify whether it's a pure htmx issue or a broader one)

**Comment by 1cg** [comment]
Closing as this sounds like a Firefox issue rather than an htmx issue
