### ISSUE TITLE
The request cannot be updated from htmx:configRequest if an async call is made.

### ISSUE THREAD

**Issue by tatejones** [bigskysoftware/htmx#2775]
The documentation states 
"htmx:configRequest
This event is triggered after htmx has collected parameters for inclusion in the request. It can be used to include or update the parameters that htmx will send:"

However, if the event contains an async call the htmx request just continues.  You cannot include or update the parameters in the request.  An example of async call would be obtaining token.

The template display the count and 5 seconds later the console has "htmx:configRequest done".

[jsfiddle](https://jsfiddle.net/tatebluedogcomau/5o4den1w/63/#&togetherjs=3S8z5aORGd)

```
<!-- load demo environment -->
<script src="https://demo.htmx.org"></script>

<script>
    document.body.addEventListener("htmx:load", function() {    
    console.log("loaded")
    htmx.trigger("#count", "count", { count: 1 })
  })
  
  document.body.addEventListener("htmx:configRequest", async function (event) {
    console.log("sleeping....")
    await new Promise((resolve) => setTimeout(resolve, 5000)) 
    console.log("htmx:configRequest done")
  })  
</script>

<div 
    id="count"
    hx-get="/counting" 
    hx-trigger="count from:body"
    hx-target="#result"
    hx-vals="js:{ count: event.detail.count }">
    Count
</div>
<output id="result"></output>

<template url="/counting"> 
  ${JSON.stringify(params)}
</template>
```

**Comment by Telroshan** [comment]
Hey, as far as I know, async event listeners are not supported anyway, even outside the htmx scope.

What you can do is use the `htmx:confirm` instead that provides a callback, to let you do any async processing before moving forward with the htmx request.
See the [async authentication](https://htmx.org/examples/async-auth/) example on the htmx website, which sounds similar to what you want to achieve here.

Hope this helps!

**Comment by tatejones** [comment]
thanks for that.  I though that might be the case.
