### ISSUE TITLE
"hx-delete" causes "Method Not Allowed  HTTP 405"

### ISSUE THREAD

**Issue by cardinal-II** [bigskysoftware/htmx#2777]
I'm using HTMX with Fat-Free Framework (PHP). After clicking a button to delete a contact, I get the error: "405
Method Not Allowed". In the browser console, the headers section says: `filename: /contacts`. But in the html file, the button fires to "/contacts/4".

`<button hx-delete="/contacts/{{ @contact.id }}">Delete Contact</button>`

In the browser inspector, you can see:
`<button hx-delete="/contacts/4" class="">Delete Contact</button>`

FFF's index.php:
`header('Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS');`

routes.ini:
`[routes]
GET /contacts/@contact_id/edit = WebPage->edit_contact_form

POST /contacts/@contact_id/edit = WebPage->edit_contact

DELETE /contacts/@contact_id = WebPage->delete_contact`

**Comment by Telroshan** [comment]
Weird, this looks like it could be an issue with how your backend is setup somehow.
A quick test on [this JSFiddle](https://jsfiddle.net/ouet9g3k/) gives the expected target URL on click. (It ofc results in a 404 error here as JSFiddle doesn't have that endpoint)
![image](https://github.com/user-attachments/assets/78b82163-d6fc-40da-8e75-c1123b91d3a1)

> In the browser console, the headers section says: filename: /contacts

What is this `filename` btw? What actual path do you see for the request in the network tab? (or maybe it's the same data, but with another name depending on which browser you use?)

Also, off the top of my head : FYI, the `DELETE` method uses URL params by default (like `GET`), could it be that you're carrying other values around which makes the actual targeted URL to be like `/contacts/4?whatever=values&you=have`, which would fail maybe an exact URL match expected by your backend? Just a random idea though, might be totally off the mark here.

**Comment by cardinal-II** [comment]
@Telroshan 
> > In the browser console, the headers section says: filename: /contacts

> What is this filename btw?

I suppose it should be '/contacts/4'. I'm not sure.

>What actual path do you see for the request in the network tab?

You can see the path if you test the website: [https://task-tracker-api.homedeco.kz](url)
Click "Edit" and then "Delete contact".

And this the html file:
```
<include href="layout.htm" />

<form action="/contacts/{{ @contact.id }}/edit" method="post">
	<fieldset>
		<legend>Contact Values</legend>
		<p>
			<label for="email">Email</label>
			<input name="email" id="email" type="text" placeholder="Email" value="{{ @contact.email }}">
		</p>
		<p>
			<label for="first_name">First Name</label>
			<input name="first_name" id="first_name" type="text" placeholder="First Name"
				   value="{{ @contact.first_name }}">
		</p>
		<p>
			<label for="last_name">Last Name</label>
			<input name="last_name" id="last_name" type="text" placeholder="Last Name"
				   value="{{ @contact.last_name }}">
		</p>
		<p>
			<label for="phone">Phone</label>
			<input name="phone" id="phone" type="text" placeholder="Phone" value="{{ @contact.phone }}">
		</p>
		<button>Save</button>
	</fieldset>
</form>

<button hx-delete="/contacts/{{ @contact.id }}">Delete Contact</button>

<p>
	<a href="/contacts/">Back</a>
</p>
```

**Comment by Telroshan** [comment]
Thanks for the link!
Well, when I click your delete button, I see not 1 but 2 requests!
![image](https://github.com/user-attachments/assets/59c52f81-a3ef-4f13-a894-f543f6a30ef1)

A request is correctly made to the first endpoint, `/contacts/4`, but it looks like your backend redirects back to the `/contacts` endpoint.

If by any chance what you're trying to do here is redirect your user to the contacts page after a successful deletion, you'll want to use the [`HX-Redirect`](https://htmx.org/reference/#response_headers) header, and not a standard HTTP redirect, which makes htmx follow the redirected URL and do the `DELETE` request towards it instead. (Note that the latter behavior isn't htmx specific)

Hope this helps!

**Comment by cardinal-II** [comment]
Thank you for not leaving me alone and for your help.
After hours of debugging, I eventually got the code to work correctly. Here's my solution.

The client html:
```html
<button 
	hx-delete="/contacts/{{ @contact.id }}"
	hx-target="body">
	Delete Contact
</button>
```

The back-end routes:
```
[routes]
GET /contacts/@contact_id/edit = WebPage->edit_contact_form
POST /contacts/@contact_id/edit = WebPage->edit_contact
DELETE /contacts/@contact_id = WebPage->delete_contact
GET /contacts = WebPage->contacts
```

The back-end controller:
```php
function delete_contact($f3){
	$contact_id = $f3->get('PARAMS.contact_id');
	$this->removeElementByFieldValue($this->contacts, 'id', $contact_id);
	header('HX-Redirect: /contacts', true); //<--- That's the needle!
	$f3->status(200);
	}
```

If you think there is no side effects in the solution, I am closing the issue.

**Comment by Telroshan** [comment]
I don't know this backend tech so I couldn't judge the syntax at all _(for ex I don't know what the `true` is about in the `header` function call)_, but this looks correct indeed!
Setting `HX-Redirect` is the right thing to do to redirect the client after an htmx request, and not redirect the _request_ itself.
