### ISSUE TITLE
Remove `internalEval()`

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#278]
Is there any reason for keeping the `internalEval()` function? It seems redundant and is triggering warnings in security scanners.
https://github.com/bigskysoftware/htmx/blob/062a70e3e9002bdcae5627e91a2f3fadc7b0551d/src/htmx.js#L247-L249

**Comment by 1cg** [comment]
We use it for testing.  I can look at where, exactly, and see if there are better ways to test it.

**Comment by bencroker** [comment]
Yes please. Ideally the library shouldn't contain an API function that is used purely for testing.

**Comment by 1cg** [comment]
Is there a better way to get access to internal methods?

**Comment by bencroker** [comment]
Not really, but my point is that `internalEval()` does nothing that a test can't already do by simply calling `eval()` itself. Having it inside the library triggers warnings in security scanners.

**Comment by 1cg** [comment]
I use the internalEval to grab symbols from inside the htmx implementation:

https://github.com/bigskysoftware/htmx/blob/165586b77752a2873cec67bc9561a471ca70e1f6/test/attributes/hx-push-url.js#L62

This lets me test internal stuff without exposing it directly.  In java or another sane language I'd use something like package protected methods for this, but this was the only way I could think to do it in javascript.  Is there another way to do so?

I do like being able to unit test internal functions, especially when they are in hard-to-get-to-via-browser-event places (like history)

**Comment by bencroker** [comment]
Ah, I see what you mean now by using it to test internal functions. I'm going to create a new issue for removing `eval` in general, thanks!
