### ISSUE TITLE
is offline editing or offline viewing within the scope of this project?

### ISSUE THREAD

**Issue by simkimsia** [bigskysoftware/htmx#279]
Sorry, if I ask about something that's entirely out  of scope. Recently came across this on the heavy recommendation of an experienced developer. It looks very interesting.

So asking out loud if offline editing or offline viewing (may be using service worker or indexed database) is part of this project

**Comment by 1cg** [comment]
Unfortunately offline editing is outside the scope of htmx.  It is focused on making network connectivity in plain HTML more rich, so a network is an important part of the equation.

Sorry about that!

**Comment by simkimsia** [comment]
No worries thanks for clarifying
