### ISSUE TITLE
Feature: Custom response handler

### ISSUE THREAD

**Issue by oko-x** [bigskysoftware/htmx#28]
Similar to htmx, we were using custom script that replaced JSON api call result in the HTML by data attributes. So it was not necessary to have HTML returned but it was possible to have bulk of the HTML in the place and just replace few values on request.

**Comment by chg20** [comment]
Hello, I am planning on making htmx pluggable in the entire request workflow.  Probably won't have time for a bit however.

**Comment by chg20** [comment]
You can now, in the `dev` branch, implement an extension to do this.  Check out www/extensions.md

I'm happy to work with you for your use case.
