### ISSUE TITLE
Extension: remove-me unexpected behavior

### ISSUE THREAD

**Issue by atmape** [bigskysoftware/htmx#281]
It was expected, that with the example below, that `<div remove-me="1s">` - tag should be removed after a 1sec period, but it didn't happen.

```
<!DOCTYPE html>
<html>
<head>
    <title>htmx test</title>
</head>
<body>
    <script src="https://unpkg.com/htmx.org@1.0.2"></script>
    <script src="https://unpkg.com/htmx.org@1.0.2/dist/ext/remove-me.js"></script>
    <div hx-ext="remove-me">
        <div remove-me="1s">To Be Removed...</div>
    </div> 
</body>
</html>
```

Over at the discord channel User `36864` figured out:

> Just testing this a bit, it seems to only work if you manually process the node after loading the page. Even processing the body node doesn't work, I'm having to manually find the div and call htmx.process() on it.
>  I managed to make it work by adding the extension to the body element instead of the parent div. On load, htmx only emits the processedNode event for the body node.
> This should only be necessary if you have something you want to remove on the initial load, rather than content that you load in through htmx.

As `36864` figured out, if you load the extension in the `<body>` - Tag everything works as expected:

```
<html>
<head>
    <title>htmx test</title>
</head>
<body hx-ext="remove-me">
    <script src="https://unpkg.com/htmx.org@1.0.2"></script>
    <script src="https://unpkg.com/htmx.org@1.0.2/dist/ext/remove-me.js"></script>
    <div remove-me="1s">To Be Removed...</div>
</body>
</html>
```

**Comment by iredmail** [comment]
Tried putting `hx-ext="remove-me` in `<body>` or `<div>`, neither works for me on macOS (Safari and Firefox).

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/commit/2944bf372c1292199c9ba81c6038bd8aec21efd0
