### ISSUE TITLE
Minor typo in docs for unminified version, read "2.02" missing a dot, should be "2.0.2"

### ISSUE THREAD

**Issue by mefernandez** [bigskysoftware/htmx#2812]
# Info

In https://htmx.org/docs/#via-a-cdn-e-g-unpkg-com there is a minor typo in the version, reads "2.02", should be "2.0.2", missing a dot.

It currently is:
```
<script src="https://unpkg.com/htmx.org@2.02/dist/htmx.js" integrity="sha384-yZq+5izaUBKcRgFbxgkRYwpHhHHCpp5nseXp0MEQ1A4MTWVMnqkmcuFez8x5qfxr" crossorigin="anonymous"></script>
```

Cheers,

Mariano.

**Comment by MichaelWest22** [comment]
Should be fixed now so this can be closed thanks :)
