### ISSUE TITLE
Change the version tags on npm

### ISSUE THREAD

**Issue by RTUnreal** [bigskysoftware/htmx#2818]
Currently the two versions `1.9.12` and `2.0.2` have the tags `latest` and `next` set on them.

But tools like Symfony's AssetMapper `importmap:update`/`importmap:outdated` look for the `latest` tag on npm when deciding which package version to compare to the currently installed package.

Changing the npm tags to i.e. `legacy` and `latest` might be better.

**Comment by Telroshan** [comment]
Hey, that's a temporary setup as we released htmx 2, which introduces breaking changes, and before that we were unfortunately not versioning the htmx import in the docs, thus people would get the `latest`, and if we set htmx 2 as latest now, this could break some setups.
See the warning on the website's homepage about this matter at https://htmx.org/
![image](https://github.com/user-attachments/assets/e21baebf-becb-4ae5-ac67-5db375d76d2d)

At some point, v2 will become latest

**Comment by RTUnreal** [comment]
oh, I missed that. Then I will wait, until version 2 is on `latest`, so my setup doesn't break
