### ISSUE TITLE
Is it possible to preserve selected elements with hx-boost?

### ISSUE THREAD

**Issue by danjac** [bigskysoftware/htmx#284]
Use case: I want to add Turbolinks behavior to my site by adding hx-boost to links and forms, preventing full server reloads. 

The problem is there is an element on the page that I don't want to replace: for example, it contains a video or audio that would be reset with replacing the whole "body" element.

In Turbolinks you just use the data-turbolinks-permanent attribute to the element and it will be preserved between page transitions.

Is there some way to achieve this with hx-boost?

**Comment by 1cg** [comment]
We don't currently have this functionality but we should.  :+1: 

Something like `hx-permanent`

**Comment by 1cg** [comment]
Does `data-turbolinks-permanent` require a stable ID?

**Comment by danjac** [comment]
@1cg yes. So something like this:

`<div id="something" data-turbolinks-permanent="true">`

**Comment by 1cg** [comment]
OK, that sounds pretty easy to implement.  I'll try to get to it soon.

**Comment by 1cg** [comment]
OK, I have a first pass in the `dev` branch, if you'd like to try it out.  There is a little dust in there right now as we work out HTTP prefetching, but all the tests pass so it shouldn't be a complete disaster.
