### ISSUE TITLE
Provide option on hx attributes for them not to be inherited

### ISSUE THREAD

**Issue by yaakovLowenstein** [bigskysoftware/htmx#2844]
I have a `<tr>` that I put `hx-swap="outerHTML"` on. This is now being inherited on everything inside the `<tr>`. However, all of my Htmx requests inside the `<tr>` I want to be `innerHTML`. Instead of needing to go specify `innerHTML` on all of those, it would be nicer if I could do something like `hx-swap="outerHTML inherit:false"`

**Comment by MichaelWest22** [comment]
https://htmx.org/attributes/hx-disinherit/

I think this is already implemented in the hx-disinherit attribute.  setting hx-disinherit="hx-swap" on the `<tr>` should override the inheritance.
