### ISSUE TITLE
htmx:invalidPath starting from 2.0.0 when trying to access an external url.

### ISSUE THREAD

**Issue by technologyconsulting** [bigskysoftware/htmx#2858]
when using hx-get="http://127.0.0.1:3000/data", which is external as the site is running from 127.0.0.1:5500, I get the following htmx:invalidPath after version 1.9.12.

I've tried to set "selfRequestsOnly" to 'false' using the below but it doesn't make a difference. I still get htmx:invalidPath.

`<script>
      document.addEventListener("DOMContentLoaded", function () {
        
        // Set selfRequestsOnly for all HTMX requests
        htmx.on("htmx:configRequest", function (event) {
          // Only allow requests to the same origin
          event.detail.selfRequestsOnly = false;
        });

      });
    </script>`

**Comment by Telroshan** [comment]
Hey, `selfRequestsOnly` is a configuration property, not an event property.

The `event.detail.selfRequestsOnly` that you're accessing here simply doesn't exist thus isn't ever used by htmx, which would explain why you don't see any difference.

See the [configuration reference](https://htmx.org/reference/#config) to learn more about how to configure htmx.
As it's a global config property btw, you shouldn't need to set it on each event, you can just define it once, globally, at the start (either via meta tag of JS directly).

So in your case you could simply do `htmx.config.selfRequestsOnly = false` at the start of your `DOMContentLoaded` handler

Hope this helps!

**Comment by technologyconsulting** [comment]
Ahh... I see. Ok, I added the following below and removed the script and contents.

`<meta name="htmx-config" content='{"selfRequestsOnly": false}' />`

Thanks for explaining it to me, I can now use 2.0.2.

**Comment by xCyborg** [comment]
> Ahh... I see. Ok, I added the following below and removed the script and contents.
> 
> `<meta name="htmx-config" content='{"selfRequestsOnly": false}' />`
> 
> Thanks for explaining it to me, I can now use 2.0.2.

That concluded hours of debugging and research, thanks.
