### ISSUE TITLE
Extension: path-deps extended to support explicit path refreshing

### ISSUE THREAD

**Issue by jvosloo** [bigskysoftware/htmx#286]
In intercooler.js we have an api method to explicitly trigger a refresh on an element or path: `Intercooler.refresh(eltOrPath)`
I would be useful to extend the htmx `path-deps` extension to support a similar explicit call to refresh dependent paths.

**Comment by jvosloo** [comment]
I will have a go at a pull request for this, using a custom event-based mechanism

**Comment by 1cg** [comment]
This has been accepted into `dev` thank you!
