### ISSUE TITLE
Changing id for hx-swap-oob doesn't work for tr inside template

### ISSUE THREAD

**Issue by adamritter** [bigskysoftware/htmx#2876]
Here's an example page:
  
    <script src="https://unpkg.com/htmx.org@2.0.2"></script>
    <button hx-get="/clicked.html" hx-swap="outerHTML">
        Click Me
      </button>
  
    <table>
      <tbody>
      <tr id="old">
        <td>old table</td>
        </tr>
      </tbody>
    </table>
  
    <span id="oldspan">old span</span>

clicked.html:
    
    <template>
      <tr id="new" hx-swap-oob="true: #old">
        <td>
            Table changed
          </td>
      </tr>
    </template>
  
    <span id="newspan" hx-swap-oob="outerHTML: #oldspan">span changed</span>

For the span both the content and the id changes, but for the tr only the content changes

**Comment by MichaelWest22** [comment]
```html
<template>
    <tr id="new" hx-swap-oob="outerHTML:#old">
      <td>
          Table changed
        </td>
    </tr>
  </template>
  
  <span id="newspan" hx-swap-oob="outerHTML:#oldspan">span changed</span>
```
This works as expected.  

hx-swap-oob can be set to the exact string "true" will work the same as outterHTML as the swap style.  But if you want to use a different swap style or add a colon and then a selector then you need to specify a valid swap style before the colon.  It was unable to find a true swap style so it defaulted back to innerHTML swap style and only swapped the contents and not the outer tr tag

**Comment by MichaelWest22** [comment]
hx-swap-oob="true" and hx-swap-oob="outherHTML" are the same and are both inline swaps.  The issue you were facing is that you tried to combine the special "true" value of hx-swap-oob with selectors and true is not a valid swap style.  to use selectors in a hx-swap-oob from the documentation you need to specify a valid swap style then a colon and then the selector.

The reason the special exception "true" is implemented for this attribute is that in html often you activate an attribute by setting it to the text string "true" and they wanted the default activating action to be a shorthand for doing the most obvious swap style of outerHTML.  But if you add a selector after the true it is no longer readable as activating the attribute

**Comment by adamritter** [comment]
I see, you are totally right, upon reading the documentation again, I see that true:#e1 is not a correct hx-swap-oob attribute value.

I guess I was confused because the implementation was still changing the innerHTML and not throwing any error in the console.
