### ISSUE TITLE
Document that HX-Trigger headers are ignored on 302s

### ISSUE THREAD

**Issue by boosh** [bigskysoftware/htmx#2879]
Please clearly document that `HX-Trigger` won't trigger events on endpoints that return redirects (#2052)

**Comment by MichaelWest22** [comment]
Added some documentation around this in a PR for review.

One thing I noticed when testing and reviewing the code for how htmx handles the headers is that we have a couple of duplications in the checking and handling of the HX-Retarget and HX-Reswap headers.  see https://github.com/bigskysoftware/htmx/compare/dev...MichaelWest22:htmx:duplicate-header-checks where I tested removing the duplicates and I checked carefully that the first header fetches were indeed not required.  No major perf gain removing them just makes the code more readable.

**Comment by MichaelWest22** [comment]
@boosh updated documentation is now live can you check and close the issue if your happy with it?

**Comment by boosh** [comment]
LGTM thanks
