### ISSUE TITLE
Space before comma leads to hx-trigger being ignored

### ISSUE THREAD

**Issue by npt** [bigskysoftware/htmx#2897]
With `hx-trigger="someCustomEvent from:body, load"`, the trigger on load works. Change it to `hx-trigger="someCustomEvent from:body , load"`, and the trigger on load no longer fires (and `htmx:syntax:error` is written to the console twice).

I would expect the extra whitespace to be ignored. (This came up when generating HTMX using a Jinja template, where I wanted to conditionally include the load trigger, so now my template is written in a more condensed style than I'd prefer.)

**Comment by Telroshan** [comment]
Indeed, that's a pretty annoying behavior...
If you'd like to investigate and submit a bugfix PR, feel free to do so!

**Comment by MichaelWest22** [comment]
@npt fix now in v2.0.3 so please retest and close if it is now resolved

**Comment by npt** [comment]
Seems resolved.
