### ISSUE TITLE
hx-trigger causes the page to refresh when manually triggering

### ISSUE THREAD

**Issue by npt** [bigskysoftware/htmx#2901]
Minimal example (`example1.html`):
```html
<!DOCTYPE html>
<html>
<head>
    <script src="htmx.js"></script>
</head>
<body>
<form hx-get="example2.html" hx-target="#target" hx-trigger="load">
    <button type="submit">Get</button>
</form>
<div id="target"></div>
</body>
</html>
```
When the button is pressed, a GET request is made for `example1.html`, and the page refreshes (changes in `example1.html` are reflected in the browser at this time), before the expected GET for `example2.html`. The URL in the address bar changes to `example1.html?` if it didn't already have the trailing `?`. The browser's network debugger shows the request for `example1.html` as having been initiated by the document, not JavaScript.

The contents of `example2.html` don't seem to matter, it can be empty or a line of text with no markup.

The expected behavior — pressing the button only requests `example2.html` — occurs if `hx-trigger="load"` is removed.

The same behavior occurs when using `hx-post` instead of `hx-get`.

**Comment by MichaelWest22** [comment]
the hx-trigger defines what actions should trigger the hx request for the form.  if you don't set hx-trigger on a form the default behavior is to override the default form `submit` process to convert it into a htmx ajax request instead.  But if you don't want the hx ajax request to trigger on the default submit event then you can change it to only fire on a custom event but it seems that if you do this then the default submit event will not be caught by htmx and it will just function as a non htmx form for most actions.  

You could try adding submit as an additional hx-trigger by adding "submit, " to the start of your trigger.

**Comment by npt** [comment]
That works, thanks!
