### ISSUE TITLE
hx-boosted form submit buttons omit their own name and value

### ISSUE THREAD

**Issue by robryk** [bigskysoftware/htmx#2908]
In plain HTML:

```
<form method="POST"><button name="foo" value="bar">submit</button></form>
```

causes the `foo=bar` value to be sent in the request. When I try to boost such a form:

```
<div hx-target="#stuff" hx-select="#stuff" hx-swap="outerHTML">
<form method="POST" hx-boost="true"><button name="foo" value="bar">submit</button></form>
</div>
```

the request made by htmx doesn't include the `foo=bar` pair. (I haven't checked whether `hx-{target,select,swap}` affect the behaviour, so am including them even though I doubt they matter.)

**Comment by MichaelWest22** [comment]
Did a quick test of both of those html examples and I was unable to reproduce with the current version of htmx 2.0.2 sorry. Both examples included foo=bar in the request made in my web app.

example of my network request from the browser
```bash
curl 'http://localhost:4321/' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'HX-Boosted: true' \
  -H 'HX-Current-URL: http://localhost:4321/' \
  -H 'HX-Request: true' \
  -H 'Origin: http://localhost:4321' \
  -H 'Referer: http://localhost:4321/' \
  --data-raw 'foo=bar'  
```

**Comment by robryk** [comment]
Reproducer:

```
<html>
<head>
<script src="https://unpkg.com/htmx.org@2.0.2" integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ" crossorigin="anonymous"></script>
</head>
<body>
<div id="stuff" hx-target="#stuff" hx-select="#stuff" hx-swap="outerHTML">
<table>
<form method="POST" action="/truncate" hx-boost="true">
<tr><td>
<button name="truncate" value="0">truncate</button>
</td>   </tr>
</form>
</table>
</div>
</body>
</html>
```

It seems that this happens when the form (apparently in contravention of what HTML5 allows) is placed between `<table>` and `<tr>`. It would be nice if forms so placed either didn't work at all with htmx, or worked fully.

**Comment by MichaelWest22** [comment]
Did a quick bit of debugging of this and found that htmx is trying to match standard html form behaviour and include the clicked button value in the parameters just like a normal form would.  But to do this it has to listen for the click and focusin events of buttons that bubble up into the form.  But it seems the browser is not bubbling up these events as expected when the HTML format is invalid like in your exact example and this is why it does not see which button was used to trigger the form. I don't think this is something that can be easily fixed.

**Comment by Telroshan** [comment]
Hey, indeed as per [`table`'s spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#technical_summary), a `form` is not an allowed child.

You'll probably want to use the `form` attribute of form elements (see [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#form) or [button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#form) documentations about their `form` attribute) and place your form outside the table.

>  It would be nice if forms so placed either didn't work at all with htmx, or worked fully.

While I understand the concern, it doesn't sound reasonable to me to add exceptions in the code to handle an invalid DOM layout (if we were to add it for this one, why wouldn't we handle a ton of other common invalid layouts?)

By using an invalid HTML layout, you're relying on whatever the browser will do with it, and the implementation may greatly vary between one another. I haven't tested this at all but I wouldn't be surprised if the behavior you're observing here on the browser you're using, was very different on others.

**Comment by robryk** [comment]
Assuming I'm an outlier in being confused by this issue (I didn't know that `<table>` should contain only table-type tags when I filed it) I would agree with you that trying to warn developers about the weirdness is not worth the fragility and complexity of any mechanism that would do so.
