### ISSUE TITLE
Possible to also swap javascript?

### ISSUE THREAD

**Issue by sandebert** [bigskysoftware/htmx#291]
I have a case where I would like the server to return html and a related javascript array that is used elsewhere in the page.

Simplified example showing what I'm trying to send back from the server:

```
<h1>You picked <em>fruits</em></h1>

<script type="text/javascript">
  var items = [
    {"id": 100, "name": "Apple"},
    {"id": 101, "name": "Orange"},
    {"id": 102, "name": "Banana"},
  ];
</script>
```

Everything updates just fine and all is well, but I just can't get `items` to update with the response from the server. 

Is this meant to work, and if so, where can I find the docs for this? If not - any hints for how to best solve it? Hack outside htmx?

**Comment by benpate** [comment]
Scripts can be run/updated.  I think you might be running in to a scoping problem on the variable.  I'm not sure where in the Javasript the original value is defined, but there's a good chance that it's not getting touched with the update.  Instead, try being explicit with the scope, like this:

### index.html
```html
<html>
<head>
    <script src="https://unpkg.com/htmx.org"></script>
<script>
  document.myData = "123"
</script>
</head>
<body>
    <div hx-get="do.html">Do</div>
</body>
</html>
```

### do.html
```html
Done!
<script>
    document.myData = "456"
    alert(myData)
</script>
```

**Comment by sandebert** [comment]
Thank you!
