### ISSUE TITLE
HTMX does not respond to events from elements appended to a form by HTMX

### ISSUE THREAD

**Issue by brackendawson** [bigskysoftware/htmx#2912]
I found this while making a form which has an array of options, I wanted to add more selectors to the form as the user wants to specify the option more times. I've found that events only work for the original form elements.

## Steps to recreate
This unit test:
```javascript
  it('handles events from appended form elements', function () {
    this.server.respondWith('GET', '/button', '<button id="new-button" class="pressy">Click me!</button>')
    this.server.respondWith('GET', '/test', 'Clicked!')

    var frm = make(`<form hx-get="/test" hx-trigger="click from:.pressy">
      <button id="get-button" hx-get="/button" hx-swap="afterend">Get the button I should click!</button>
    </form>`)

    var btn = frm.querySelector('#get-button')
    btn.click()
    this.server.respond()

    btn = frm.querySelector('#new-button')
    btn.click()
    this.server.respond()

    frm.innerHTML.should.equal('Clicked!')
  })
```

## Expected outcome
The form innerHTML will ultimately be replaced with "Clicked!"

## Actual outcome
Clicking the "Click me!" button has no effect.

## Debug
A version where the element was in the form to begin with works as you would expect:
```javascript
  it('handles events form original form elements', function () {
    this.server.respondWith('GET', '/test', 'Clicked!')

    var frm = make(`<form hx-get="/test" hx-trigger="click from:.pressy">
      <button id="get-button" hx-get="/button" hx-swap="afterend">Get the button I should click!</button>
      <button id="new-button" class="pressy">Click me!</button>
    </form>`)

    var btn = frm.querySelector('#new-button')
    btn.click()
    this.server.respond()

    frm.innerHTML.should.equal('Clicked!')
  })
```

**Comment by seanmorton** [comment]
I ran into something similar like this recently and https://htmx.org/api/#process may be your friend here, though I think you should also try adding `type=submit` to the new button to leverage htmx's default form triggers first.

**Comment by brackendawson** [comment]
I have tried using htmx.process on the bottom and the form, it didn't help.

I'm my real form it's actually a <select> and not a <button>, so it can't have a type=submit attribute. But I do want to submit the form every time the select is changed.

**Comment by Telroshan** [comment]
Hey, indeed hx-trigger is evaluated on load to bind event listeners but doesn't update automatically
As the [hx-trigger doc](https://htmx.org/attributes/hx-trigger/) states:
> The CSS selector is only evaluated once and is not re-evaluated when the page changes. If you need to detect dynamically added elements use an event filter, for example click[event.target.matches('input')]

You'll probably want to use that exact filtering trick with a `.pressy` selector instead of `input` in the example above.

Hope this helps!

**Comment by brackendawson** [comment]
Thank you @Telroshan, it is indeed already documented and that tip works.

For future travellers, the fixed example would be:
```javascript
  it('handles events from appended form elements', function () {
    this.server.respondWith('GET', '/button', '<button id="new-button" class="pressy">Click me!</button>')
    this.server.respondWith('GET', '/test', 'Clicked!')

    var frm = make(`<form hx-get="/test" hx-trigger="click[event.target.matches('.pressy')">
      <button id="get-button" hx-get="/button" hx-swap="afterend">Get the button I should click!</button>
    </form>`)

    var btn = frm.querySelector('#get-button')
    btn.click()
    this.server.respond()

    btn = frm.querySelector('#new-button')
    btn.click()
    this.server.respond()

    frm.innerHTML.should.equal('Clicked!')
  })
```

I found this line in the docs unclear without your help:
> The CSS selector is only evaluated once and is not re-evaluated when the page changes. If you need to detect dynamically added elements use an event filter, for example `click[event.target.matches('input')]`

Perhaps it could be modified to:
> The CSS selector is only evaluated once and is not re-evaluated when the page changes. If you need to detect dynamically added elements use an event filter, for example `hx-trigger="click[event.target.matches('<CSS selector>')]"`
Would you like me to open a PR for that?

**Comment by brackendawson** [comment]
This is working as designed.
