### ISSUE TITLE
Body does not contain  "..." Hyperlink to in-depth docs

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#292]
I try to see what happens if a nervous user is on a slow connection and hits the buttons several times. I use Devtools Slow-3G.

I get this message in the console:

```
htmx.org@1.0.2:1 Body does not contain 

<button hx-post=​"/​offer/​1/​add_offer_to_order" hx-target=​"#offer_1" hx-swap=​"outerHTML">​+​</button>​
```

My hint for your success: It would be very cool if the error message would contain a hyperlink or an error-message-number so that clueless developers like me can easily find a description of what this message means.

**Comment by 1cg** [comment]
That was a debugging statement that shouldn't have been in the release.  Sorry for the confusion!
