### ISSUE TITLE
support class selector for more flexablilty instead of ID only

### ISSUE THREAD

**Issue by hosamhamdy258** [bigskysoftware/htmx#2923]
hello,

consider this example and how to do it with HTMX but not with ID technique

HTML page contains this elements in form using HTMX get request 

```
<div>
    <p>random</p>
    <button class="disable_me" hx-swap-oob="outerHTML">Enabled</button>
</div>
<div>
    <p>random</p>
    <button class="disable_me" hx-swap-oob="outerHTML">Enabled</button>
</div>
```

the incoming response looks like 

`<button class="disable_me" disabled hx-swap-oob="outerHTML">Disabled</button>`

the desired result looks 

```
<div>
    <p>random</p>
    <button class="disable_me" disabled hx-swap-oob="outerHTML">Disabled</button>
</div>
<div>
    <p>random</p>
    <button class="disable_me" disabled hx-swap-oob="outerHTML">Disabled</button>
</div>
```

is that possible with HTMX ?

**Comment by MichaelWest22** [comment]
Yes it is simple to do with htmx and oob swaps.  There are no examples of this case in the documentation https://htmx.org/attributes/hx-swap-oob/ but it has:

`any valid hx-swap value, followed by a colon, followed by a CSS selector`

so for your case just use:
`<button class="disable_me" disabled hx-swap-oob="outerHTML:.disable_me">Disabled</button>`

**Comment by hosamhamdy258** [comment]
Thanks **@MichaelWest22** for help

I was reading docs from [https://htmx.org/docs/#oob_swaps]( https://htmx.org/docs/#oob_swaps)
they're different docs and didn't mention that option
i tested it it's **working** 
maybe they will update it on examples as it's tricky and very useful to stop bloating elements with IDs
