### ISSUE TITLE
if i want to add javascript based keyboard shortcut keys, is it correct to do it as extensions?

### ISSUE THREAD

**Issue by simkimsia** [bigskysoftware/htmx#294]
I read that to avoid polluting the core code, best to add feature requests as extensions.

If i want keyboard shortcut keys, is it correct to do it as extensions?

**Comment by r3sist** [comment]
(Subscribe - I am also interested in this topic.)

**Comment by 1cg** [comment]
you can respond to key events using the `hx-trigger`  attribute:

https://htmx.org/attributes/hx-trigger/

```html
  <div hx-get='/whatever' hx-trigger='keyup[ctrlKey&&textContent=="C"]'>
   ...
  <div>
```

if you want to implement a bunch of different keyboard shortcuts on, say, the `body` element, there isn't a great way to do this in htmx right now.  You'd probably want to add some listeners to the body element, maybe using the `htmx.on()` function:

https://htmx.org/api/#on

A better way to address this in pure htmx would be to support element from other elements with something like an `hx-src` attribute that let you listen to events on a different element:

```html
  <body>
     <span hx-src='body' hx-get='/whatever' hx-trigger='keyup[ctrlKey&&textContent=="C"]'></span>
     <span hx-src='body' hx-get='/somethingElse' hx-trigger='keyup[ctrlKey&&textContent=="X"]'></span>
   ...
  <body>
```

**Comment by simkimsia** [comment]
Thank you I'm going to try this with click as well

So in essence I will have tabbed views showing which can be toggled by clicks and by shortcut keys 

I see how well it works

**Comment by 1cg** [comment]
OK, I have implemented a new feature to address this use case in the `dev` branch.  You can now add a `from` keyword to trigger definitions.  This would like you implement a hot key for a tabbed UI like so:

```html
<div id="tab1" hx-get="/whatever" hx-trigger="click, keyup[ctrlKey&&textContent=="C"] from:body">Tab 1</div>
```
I hope to cut a release of htmx 1.1 next week with this functionality.
