### ISSUE TITLE
ws-send 

### ISSUE THREAD

**Issue by marxwood** [bigskysoftware/htmx#2947]
Just following the documentation to establish basic socket connection https://htmx.org/extensions/ws/

When `ws-send` is added to a `<form>` it comes with the error `TypeError: api.addTriggerHandler is not a function`.

Indeed when inspected through debugger the function does not exist exist on `api` object.

Is there another way of doing ws so the documentation should be updated? Or the bug should be fixed?

<img width="382" alt="image" src="https://github.com/user-attachments/assets/2b71eeb5-4d22-4632-ad31-cd7ce4f0ebcd">
<img width="708" alt="image" src="https://github.com/user-attachments/assets/42c62aa9-31b5-439c-b134-df9aee853db2">

**Comment by MichaelWest22** [comment]
It looks like you are trying to use the latest htmx 2.0.1 version of the web socket extension with the much older 1.7.0 version of htmx.  with htmx v2 the extensions were re-writen to support the newer version so you would either have to downgrade to an older web socket extension version or upgrade htmx to a newer version so the api functions that link them together will match.

**Comment by Telroshan** [comment]
Also note that the V1 documentation for web sockets is available at https://v1.htmx.org/extensions/web-sockets/ if you want to stick to htmx 1

**Comment by marxwood** [comment]
Thanks. The path I took was following the short tutorial from external resource. This is how I ended up with v1 instead of v2. Maybe the extension page should have this mentioned "use v2"...
