### ISSUE TITLE
Preserve scroll on swap content

### ISSUE THREAD

**Issue by gerbil** [bigskysoftware/htmx#2953]
I've tried both ```hx-swap="focus-scroll:true"``` and ```<meta name="htmx-config" content='{"defaultFocusScroll": true}'>```, but still got scroll back to top on every table body triggered refresh event.

Is there any way to preserve scroll for specific content part after swap?

**Comment by MichaelWest22** [comment]
Some things to check is that the element you want to retain its focus and scroll is one of the supported elements like an input and that you have it in focus and also it must have a id attached for the feature to work.

**Comment by gerbil** [comment]
It's a TD in TABLE; So generally ```hx-swap="show:#id:top"``` is working for static elements;
But for dynamic lists now i need:
- To get current 'infocus' element somehow (dynamically)
- To add this element ID into ```hx-swap``` somehow

**Comment by gerbil** [comment]
So the only possible option is `idiomorph' extension usage. Will try to stick with it.
