### ISSUE TITLE
Fix typo in URL to prevent broken link redirect

### ISSUE THREAD

**Issue by youssame** [bigskysoftware/htmx#2961]
There is a typo in the URL for Response Targets in the "Configuring Response Handling" section of the documentation. The current link
[Response Targets](https://htmx.org/extensions/reponse-targets) is incorrect. It should be:
https://htmx.org/extensions/response-targets.

I’ve already fixed it in PR #2960.

**Comment by Telroshan** [comment]
Closed by #2962, thanks!
