### ISSUE TITLE
Documentation for htmx:processedNode event

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#297]
There's an undocumented `htmx:processedNode` event.  Is this undocumented for a reason?  If this event is finalized, then let me know and I'll submit a PR with documentation.

**Comment by benpate** [comment]
Just to close the loop from another comment elsewhere.  I'm actually hoping that this event/name is NOT finalized, and it could be updated to `htmx:afterProcessNode` so that it will aligh with the PR listed above. :)

**Comment by 1cg** [comment]
The event is used in a few extensions, but I'd be OK with renaming it since it wasn't documented.
