### ISSUE TITLE
Offline docs?

### ISSUE THREAD

**Issue by lucasl84** [bigskysoftware/htmx#2974]
Hi there!

I was wondering if there's a way to get the HTMX documentation for offline browsing.

Thanks,
Lucas.

**Comment by Telroshan** [comment]
Hey,

I dont know how other lis generally handle this, but you can find our docs under `www` in this very repository.
For instructions to run the web version locally, see its [README](https://github.com/bigskysoftware/htmx/tree/master/www), you'll have to install Zola

Other than that, all of our documentation is made of markdown files (with sometimes additional zola-specific syntax), so even though it won't be as good-looking as the web version (as you don't get the little styling, although minor, applied to the website), it should still be totally readable!

Hope this helps

**Comment by lucasl84** [comment]
Thanks a lot! I will check it out. My bad for not checking the repo in first place!
