### ISSUE TITLE
How to work with mockjs or jquery.mockjax?

### ISSUE THREAD

**Issue by kitepad** [bigskysoftware/htmx#30]
In intercoolerjs, we can mock some url and test in single page.

How can do mock with htmx?

**Comment by chg20** [comment]
For my examples and testing I'm using sinon.js FakeServer:

https://sinonjs.org/releases/latest/fake-xhr-and-server/

Here is a sample test showing how I use it:

https://github.com/bigskysoftware/htmx/blob/master/test/attributes/hx-get.js

And the `makeServer()` helper is declared here:

https://github.com/bigskysoftware/htmx/blob/master/test/util/util.js

Note that for demos you probably want to set `server.autorespond` to `true`
