### ISSUE TITLE
Dynamic hx-target?

### ISSUE THREAD

**Issue by akashchopra** [bigskysoftware/htmx#302]
Is there a way of dynamically choosing the `hx-target` depending on whether the shift key was pressed when source element was clicked? Do I need to hook into one of the events and modify the target within the handler?

Thanks!

**Comment by 1cg** [comment]
Right now there is no way to do this, unfortunately.  

We should probably support a `javascript:` syntax in the target.

One thing you could do right now is nest two divs and have two different targets:

```html
<div hx-post="/whatever" trigger="click[shiftKey]" target="#targetOne">
  <div hx-post="/whatever" trigger="click[!shiftKey]" target="#targetTwo">
    ...
```
Not the cleanest code in the world, but it should work.

**Comment by akashchopra** [comment]
Thanks, that's a clever workaround. The code might not be the cleanest, but I think it is obvious what is going on, which is more important to me.

**Comment by 1cg** [comment]
OK, in that case I will close this and wait for a future feature request for a dynamic target...
