### ISSUE TITLE
Hey, I'm not sure to understand your usecase, but could the [`path-params`](https://htmx.org/extensions/path-params/) extension fit your needs here?

### ISSUE THREAD

**Issue by alphachart** [bigskysoftware/htmx#3023]
Hey, I'm not sure to understand your usecase, but could the [`path-params`](https://htmx.org/extensions/path-params/) extension fit your needs here?
Hope it helps!

_Originally posted by @Telroshan in https://github.com/bigskysoftware/htmx/discussions/2152#discussioncomment-8039729_

**Comment by Telroshan** [comment]
Looks like you missclicked at some point while checking out the referenced discussion ? 😄
