### ISSUE TITLE
on load does not work, but on click does

### ISSUE THREAD

**Issue by OmenApps** [bigskysoftware/htmx#303]
I'm working on integrating HTMX into a django project.

Here is an except from the template. It defines a select box which calls an endpoint, returning a div with an alert:

```
<form method="POST">
    <label class="form-label" for="order_notify">Order Notification Frequency</label>
    <select class="form-control" name="order_notify" id="order_notify" hx-post="/users/preferences/select_order_notification_freq/" hx-trigger="change" hx-target="#notification_response">
        <option value="NONE" selected>None</option>
        <option value="IMMEDIATE">Immediate</option>
    </select>
    {% csrf_token %}
</form>
<div id="notification_response"></div>
```

Here's what is returned. This works. It loads when I make a change to the select box, and when I click in the div, it disappears after 2 seconds:

```
return HttpResponse(
    ('<div _="on click wait 2s then remove me" class="alert alert-warning" role="alert">'
    '<strong>Success!</strong> Preferences were updated.'
    '</div>'),
    status=200,
    content_type="text/html"
)

```

If I change "click" to "load" - and nothing else - it does not work. The div gets loaded, and just never goes away. No errors in the console, just nothing at all:

```
return HttpResponse(
    ('<div _="on load wait 2s then remove me" class="alert alert-warning" role="alert">'
    '<strong>Success!</strong> Preferences were updated.'
    '</div>'),
    status=200,
    content_type="text/html"
)
```

Please let me know if you need more detail or if I'm misunderstanding how this should work.

**Comment by OmenApps** [comment]
Likewise, if I use the remove-me extension, it does not work as expected.

Added to the body:

```
<body hx-ext="remove-me">
...
```

The modified response to be loaded into the div:

```
return HttpResponse(
    ('<div  remove-me="2s" class="alert alert-success" role="alert">'
    '<strong>Success!</strong> Your preferences were updated.'
    '</div>'),
    status=200,
    content_type="text/html"
)
```

Nothing happens after the div is loaded.

**Comment by 1cg** [comment]
Yeah, the `load` "event" isn't really an event, it's a pseudo-event in htmx triggers unfortunately, so hyperscript isn't going to see that.

Something like this, however, should work:

```python
return HttpResponse(
    ('<div _="on htmx:processedNode wait 2s then remove me" class="alert alert-warning" role="alert">'
    '<strong>Success!</strong> Preferences were updated.'
    '</div>'),
    status=200,
    content_type="text/html"
)
```

Not sure what's up w/ the remove-me extension, that's tested and should be working.  I'll look into it.

**Comment by OmenApps** [comment]
Thank you for the reply @1cg. That makes sense, but I still couldn't get it working.

I had pulled the "on load" from the example on the HTMX docs:

`<div _="on load wait 5s then remove me">Here is a temporary message!</div>
`
But after your description it makes sense that that might not work for elements loaded after the page has completed loading.

[Here](https://preferences-with-swap.omenapps.repl.co/users/htmx_load_test/) is a demonstration using only elements already in the page (nothing loaded dynamically), attempting three different methods of removing the element automatically - none of which are successful executed. It also includes "on click", which works as expected.

It's probably something stupid I'm doing, but it seems like *one* of these three ought to have worked.


The code for that link is below, in case there is any issue accessing it:

```
<!doctype html>

<html lang="en">
    <head>
        <title>HTMX Test</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <script src="https://unpkg.com/htmx.org@1.0.2"></script>
        <script src="https://unpkg.com/hyperscript.org@0.0.2"></script>
    </head>

    <body>
        <h3>Testing removal on-load</h3>
        
        <div _="on click wait 2s then remove me" class="alert alert-success">
            <strong>Note!</strong> Click me, and I'll go away in 2 seconds.
        </div>

        <div _="on htmx:processedNode wait 2s then remove me" class="alert alert-warning">
            <strong>Note!</strong> This should go away soon (using on htmx:processedNode).
        </div>

        <div _="on load wait 2s then remove me" class="alert alert-danger">
            <strong>Note!</strong> This should go away soon (using on load).
        </div>

        <div hx-ext="remove-me" class="alert alert-info">
            <strong>Note!</strong> This should go away soon (using remove-me).
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
```

**Comment by 1cg** [comment]
This was a bug/feature shortcoming in hyperscript.  It has been fixed and will be in the next release (hyperscript 0.0.3/htmx 1.1.0)
