### ISSUE TITLE
hx-boost on body tag throws TypeError: path is null

### ISSUE THREAD

**Issue by garrappachc** [bigskysoftware/htmx#3039]
Setting `hx-boost="true"` on the `body` tag
![image](https://github.com/user-attachments/assets/d9623176-09a1-4046-b4ad-318980a16c6c)
causes this error to be thrown
![image](https://github.com/user-attachments/assets/5a13b367-3583-4e24-87b1-6fe399cf7321)
This happens only on v2.0.3, it doesn't happen in v2.0.2

This is the problematic code
![image](https://github.com/user-attachments/assets/1965cbea-599e-4e67-b1e7-edfb0848c853)

**Comment by MichaelWest22** [comment]
This has already been found here #2963 and a PR done to fix this is merged already ready for the next release

**Comment by garrappachc** [comment]
Ok, thanks!
