### ISSUE TITLE
Bad documentation link

### ISSUE THREAD

**Issue by damusix** [bigskysoftware/htmx#3041]
Hey guys, exploring your docs, I found a bad link on a page:

https://htmx.org/extensions/sse/ has a link to https://htmx.org/reference/hx-trigger.md, which gives a 404

**Comment by MichaelWest22** [comment]
Yeah looks like there are two hx-trigger links that need changing to https://htmx.org/attributes/hx-trigger.md in the sse documentation and also www/content/extensions/response-targets.md needs and update to https://htmx.org/attributes/hx-target.md which has the same issue.

**Comment by Telroshan** [comment]
Fixed in #3051
