### ISSUE TITLE
Provide "secure" version of htmx

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#305]
Following up from https://github.com/bigskysoftware/htmx/issues/278, I'd like to propose providing a "secure" version of htmx, up for discussion.

The issue with using `eval` and `Function()` in htmx is that they trigger warnings in security scanners. Also, any sites using a [Content Security Policy](https://content-security-policy.com/) will have to add `unsafe-eval` to the `script-src` directive, which is considered bad practice. A "secure" alternative version of htmx that excluded them would have limited functionality, but would be more secure. VueJS, for example, has a [runtime-only build that is fully CSP-compliant](https://vuejs.org/v2/guide/installation.html#CSP-environments). 

Obviously htmx has no build step, so the only way to address this is to remove the use of `eval` and `Function()`. Currently they appear to be used in the following places:

`hx-vars`:
https://github.com/bigskysoftware/htmx/blob/21ee3f1732eea2f4041ba2e6a463cbe93a8a4d87/src/htmx.js#L1806-L1810

Trigger conditionals:
https://github.com/bigskysoftware/htmx/blob/21ee3f1732eea2f4041ba2e6a463cbe93a8a4d87/src/htmx.js#L755-L757

`evalScript`:
https://github.com/bigskysoftware/htmx/blob/21ee3f1732eea2f4041ba2e6a463cbe93a8a4d87/src/htmx.js#L1215-L1223

For testing internal functions only:
https://github.com/bigskysoftware/htmx/blob/21ee3f1732eea2f4041ba2e6a463cbe93a8a4d87/src/htmx.js#L250-L252

**Comment by 1cg** [comment]
Is CSP statically enforced or dynamically enforced?

If it is dynamically enforced, we could add a configuration variable to htmx that allows you to disable all of these.  That would be the cleanest solution, IMO.

**Comment by bencroker** [comment]
I'll run a test and let you know.

**Comment by bencroker** [comment]
Good news is that it is dynamically enforced!!

This script, for example, does _not_ get blocked.

```js
var safe = true;
if (!safe) {
    eval('console.log()');
}
```

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/58f373d1e5a0d10b134d9c2f7cc4d49838a7bcc7

**Comment by bencroker** [comment]
Oh yessss!
