### ISSUE TITLE
Link to preload docs is broken

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#306]
https://github.com/bigskysoftware/htmx/blob/dev/CHANGELOG.md#110---2021-1-8

On above page the link to `preload` is broken: https://htmx.org/extensions/preload/

**Comment by 1cg** [comment]
Yep, that's in the `dev` branch, and hasn't been released yet.  :smile: 

You can see the actual docs here on the dev site: https://dev.htmx.org/extensions/preload/
