### ISSUE TITLE
Hx-trigger doesn't trigger on first reset DOM event, unless a delay is set

### ISSUE THREAD

**Issue by zachczx** [bigskysoftware/htmx#3062]
Hi, I'm using HTMX with hx-trigger="change, reset" with hx-post to post filter selections to my Go backend.

- Change for when checkboxes' value change
- Reset for when a reset button is clicked.

```
<!-- Sample --> 
<form id="filter-form" hx-target="#posts" hx-swap="outerHTML" hx-trigger="change, reset" hx-post="/filter">
	<input id="1" type="checkbox" name="number" value="1" />
	<label id="1-label" for="1">Label 1</label>
	<button id="reset-filter" type="reset">Clear</button>
</form>
```

Checkbox value change works as intended - triggers htmx swap. 

## Problem
Reset event triggers without hx-post of empty checkboxes value on first click of reset button. This first click comes with the typical htmx events, e.g. htmx:beforeSwap. It only works when reset button is clicked the second time. 

## Workaround
Behavior works as intended if I set a delay (any delay, 0.01s works). Seems like the reset event interferes with the change trigger. 

Is this intended behavior, i.e. if I want to listen to reset events, I need to add a delay? 

Thanks!

**Comment by Telroshan** [comment]
Hey, yep I would say it works as intended ; event listeners bound to standard events like this, run before the browser's logic does. This is to let you the opportunity to call `event.preventDefault()` on them.
If you were to call `event.preventDefault()` in a `reset` event listener, you'd see the form not resetting at all. As htmx binds standard event listeners, it indeed runs and builds its values set before the reset actually occurs.

To fix the issue, you'd have to use some delay/timeout anyway to first let the browser reset the form, then trigger the htmx request, whether it's hidden in an internal check in htmx, or explicity defined in your `hx-trigger` attribute.
So, your workaround is the way to go imho! A `hx-trigger="change, reset delay:1"` will fix this

**Comment by zachczx** [comment]
I see, thanks for the explanation! This would be a great thing to mention briefly (or link to your explanation in this PR), would definitely save some folks a bit of time figuring out why the reset event didn't work. Cheers!! :)

**Comment by Telroshan** [comment]
If you're interested, feel free to open a PR to clarify that @zachczx ! Documentation improvements are always welcome 😁

**Comment by zachczx** [comment]
> If you're interested, feel free to open a PR to clarify that @zachczx ! Documentation improvements are always welcome 😁 

Yup will do during the weekend!
