### ISSUE TITLE
Delay race condition while loading

### ISSUE THREAD

**Issue by garraflavatra** [bigskysoftware/htmx#3083]
According to the docs, the delay modifier works like this:

> wait the given amount of time (e.g. 1s) before issuing the request. If the event triggers again, the countdown is reset. 

I am using this to implement an auto-save form. Please see the below screen recording. The form has `hx-trigger="input changed delay:500ms"` and the red bar is the loading indicator. When text is typed while the request is in flight, it is happily overwritten with the new response (which contains the modifications up to the point where the request was issued), even though I'm using the delay modifier. So `delay` does not cancel a request. Is this desired behaviour of the `delay` modifier? 

https://github.com/user-attachments/assets/5cb8054e-594b-4215-89fe-98fec88ce2e8

Below is the workaround I'm trying to get to work. It's not working yet; it doesn't seem to abort the request.

```js
htmx.on('htmx:load', event => {
    event.detail.elt.querySelectorAll('input,textarea,select').forEach(input => {
        input.addEventListener('change', () => {
            htmx.trigger(input.closest('form'), 'htmx:abort');
        });
    });
});
```

**Comment by Telroshan** [comment]
Hey, the `delay` modifier lets you delay the moment where the htmx request should be fired. But indeed, once the request is fired, it's fired and `delay` doesn't have anything to do with it anymore.
I think your workaround could work with an `input` event listener instead of `change` (i.e. same event as your `hx-trigger` spec).
If I'm not mistaken, the `input` event is going to be fired for each keystroke (that modifies the value), but `change` will only fire when you focus out/blur the element, so it's likely not firing at all for a situation like the video you provided (where you type in but never leave the input)

**Comment by MichaelWest22** [comment]
I think the issue you need to solve is not to cancel the request but to not replace the input every time.  One way to solve this would be to just put the hx request on the input with the same `hx-trigger="input changed delay:500ms"` you have already but set the hx-swap to 'none' and this will allow you to update the backend with just the contents of this one input possibly via a dedicated backend endpoint for auto-save.  the input itself will then never be swapped out which I think is what is causing the reverts on save you are seeing in the video.  You could have a wrapping div or form above this input that has a 'change' trigger maybe that detects when the user exits the form and do a full save to the same or different endpoint which then replaces the form data with the 100% confirmed and validated version from the server.

It may also be possible to have two triggers on the input for `hx-trigger="change,input changed delay:500ms"` and then add an event listener or hx-on for the htmx:beforeSwap event that checks `evt.detail.requestConfig.triggeringEvent.type` and you can then set the swap type to none or cancel the swap in this event if its just a auto save input event type.

**Comment by garraflavatra** [comment]
Thanks for your quick replies! 💯 

I've implemented @MichaelWest22's first suggestion which works perfectly. I already had an API endpoint for this so the form uses that now. The reason I swapped the form is to display validation errors, but I've replaced them by using HX-Trigger to show a toast message. It also removes some backend complexity which is great too.
