### ISSUE TITLE
Default unpkg.com URL has stopped pointing to "latest" 

### ISSUE THREAD

**Issue by bittner** [bigskysoftware/htmx#3087]
It used to be possible to download the latest version of HTMX simply by cURL'ing https://unpkg.com/htmx.org/dist/htmx.min.js (or https://unpkg.com/htmx.org@latest/dist/htmx.min.js), which would redirect replacing the "latest" in the URL path by the current latest version number of HTMX.

That was very handy! I used that to automate checking for version updates in the CI pipelines of my Django projects.

Unfortunately, this seems to have stopped working after v1.9.12. The two URLs mentioned about still point to that version while the current latest version is already v2.0.4, at the time of this writing.

Was this change on purpose or is it a bug/mistake in the release automation?

**Comment by mailq** [comment]
The reason is clearly written in the NEWS block of the homepage: 2.x isn't the latest.

**Comment by bittner** [comment]
Okay, sorry, I didn't find anything in the README and didn't look further. My bad!

Thanks for the clarification! Love HTMX!
