### ISSUE TITLE
[Question/FR] Long Polling

### ISSUE THREAD

**Issue by ITwrx** [bigskysoftware/htmx#313]
I've so far resisted ajax so forgive my ignorance, but the htmx polling example seems to be `short polling`. Is there already a way to implement `long polling` with htmx? If not, could a `long polling` feature and example be added? I don't want to use SSE right now.

Also, it would be nice if the examples showed some basic info about the server side of things for stuff like long polling and SSE, so the way the technique works is clearer from the beginning. Sure, you can link to external resources, but they have their own, sometimes convoluted, examples and it is easier to understand if the server side example is in the context of the htmx frontend example. Even if it were just commented routes and what the response method(s) should return for the given example, that would be helpful. Or actual code written in any server side language of your choice. Either would show the whole request cycle for people who have never implemented the technique before. This may not be necessary for devs experienced in ajax, but many attracted to htmx might be ajax holdouts like me.

Thanks

**Comment by tomberek** [comment]
Fairly minimal example:
```
==> index.html <==
<!doctype html>
<html lang="en">
<head>
    <script src="https://unpkg.com/htmx.org@1.1.0"></script>
</head>
<body>
    <main>
        <div hx-sse="connect:/events/counter swap:message" hx-swap="innerHtml">...loading</div>
    </main>
</body>
</html>

==> main.go <==
package main

import (
        "log"
        "net/http"
        "strconv"
        "time"

        "github.com/alexandrevicenzi/go-sse"
)

func main() {
        s := sse.NewServer(nil)
        defer s.Shutdown()
        http.Handle("/events/", s)
        http.Handle("/", http.FileServer(http.Dir("./.")))
        go func() {
                counter := 0
                for {
                        s.SendMessage("/events/counter", sse.SimpleMessage(strconv.Itoa(counter)))
                        counter += 1
                        time.Sleep(1 * time.Second)
                }
        }()
        log.Println("Listening at :3000")
        http.ListenAndServe(":3000", nil)
}
```

**Comment by 1cg** [comment]
I'd like to build up server side examples over time, but that is going to have to be a separate project, and far in the futre.

Thank you @tomberek for the basic SSE example!

@ITwrx if you'd like you can jump on discord for help:  https://htmx.org/discord

**Comment by ITwrx** [comment]
yes, thanks @tomberek but i specifically said i wasn't interested in SSE right now and there was a bit of an example for that in the docs already. It's just long polling that is conspicuously missing. Your example can only help people (maybe me if i go back to SSE method) and it's no skin off my nose either. :)

@1cg The timeline, for what i believe to be a staple method like long polling, is disappointing. Thanks for the offer of help, but i don't use discord. Also, i think if people had time to help people in private chat, then a short example would only save them time in the long run, but whatever. I also don't like to ask questions where the conversation/answer can't be read by others publicly with their browser. 

Thanks for letting me know your stance on the matter, as i had already started using httpx and at least i know now that fuller docs won't be forthcoming, and i can evaluate, going forward.

**Comment by tomberek** [comment]
For long-polling in particular, it's even simpler on the client side. This can be accommodated in HTMX with some header manipulation (Keep-Alive, perhaps) followed by a mechanism to repeat the request. I've been able to do this by either having the server reply with a snippet that has the repeated request inside of it in the form of DOM that HTMX would interpret, or by running the response through a template that would stamp the new request on top.

**Comment by ITwrx** [comment]
@tomberek thanks
