### ISSUE TITLE
path-deps not triggering when element removed

### ISSUE THREAD

**Issue by akashchopra** [bigskysoftware/htmx#323]
The path-deps extension is very useful, but I've come across a situation where it doesn't work as expected:

```
<div hx-ext="path-deps" hx-get="/new/content" hx-trigger="path-deps" path-deps="/foo/bar">Some content</div>
<p hx-delete="/foo/bar" hx-swap="outerHTML">Click to delete</p>
```

The `/foo/bar` endpoint returns empty content, so the paragraph is removed when I click on it. However, the `div` above is not updated, despite the path-dep. 

I can make it work by removing the `hx-swap` attribute (so that only the inner HTML is removed), but this workaround is not suitable in my real code.

Is this a bug, or have I misunderstood something about how path-deps or removing elements should work?

**Comment by jwmullally** [comment]
I think I ran into the same issue.

The path-deps trigger works OK for me here:
```html
<div hx-ext="path-deps">
  <div id="outercontainer">
    <button hx-post="/reflect" hx-target="this">Press</button>
  </div>  
  <div hx-get="/someurl" hx-trigger="path-deps" path-deps="/reflect" hx-target="this"></div>
</div>
```

But not here when the outer container is replaced during the POST request
```html
<div hx-ext="path-deps">
  <div id="outercontainer">
    <button hx-post="/reflect" hx-target="#outercontainer">Press</button>
  </div>  
  <div hx-get="/someurl" hx-trigger="path-deps" path-deps="/reflect" hx-target="this"></div>
</div>
```

Legendary software btw, thanks :)

**Comment by 1cg** [comment]
Hmm, interesting.  Would one of you be willing to create a test for this case in the `path-deps` test file?

https://github.com/bigskysoftware/htmx/blob/b46e8ab10f1e267bb635ee7afa4fc016229537d7/test/ext/path-deps.js#L160-L159

**Comment by 1cg** [comment]
Fixed with https://github.com/bigskysoftware/htmx/commit/506a4474b5cc03248079781bf010aa8e9968748c

Thank you for the test!
