### ISSUE TITLE
htmx can't be included into Stackoverflow examples

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#324]
I try to add htmx to add a [runnable html/js code snippet](https://stackoverflow.blog/2014/09/16/introducing-runnable-javascript-css-and-html-code-snippets/) to a question at Stackoverflow.

![add-htmx](https://user-images.githubusercontent.com/414336/104132892-5f04c700-5380-11eb-827b-1595add4f7e9.png)

But unfortunately this gets rejected:

![err](https://user-images.githubusercontent.com/414336/104132898-66c46b80-5380-11eb-9560-02b69b2fffda.png)

Is there a way to get htmx with a js/css extension?

**Comment by DenizAksimsek** [comment]
`https://unpkg.com/htmx.org@1.1.0/dist/htmx.min.js` should work

**Comment by guettli** [comment]
Thank you
