### ISSUE TITLE
Docs: List of event-names

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#326]
From: https://htmx.org/attributes/hx-trigger/

> An event name (e.g. "click" or "my-custom-event") ...

Please provide a list of event names, or a hyperlink to a list of event names.

The helps new comers like me. 

Thank you very much!

**Comment by tomberek** [comment]
It seems it can be any DOM event: https://developer.mozilla.org/en-US/docs/Web/Events

HTMX then defines some additional custom events: https://htmx.org/reference/#events

**Comment by 1cg** [comment]
Yep, any event will work, and we document the htmx specific ones.
