### ISSUE TITLE
Empty inputs are not being sent via POST, or `undefined` if explicitly sent

### ISSUE THREAD

**Issue by johndwells** [bigskysoftware/htmx#33]
I have a form that needs to POST an empty field value. In my context, an empty value denotes _removing_ a coupon code from a user's cart.

However when I make a simple HTML form, and bind htmx to it, if the coupon code field is empty then it is not included in the POST request.

I have tried using `hx-params="*"` on the form element, but this has no effect, still only non-empty fields are POSTed.

Interestingly, when I explicitly mentioned the input field in question, e.g. `hx-params="couponCode"`, while it did POST that form param, the value sent was `undefined`. I tried setting name and id attributes to `couponCode` but both yielded `undefined`...

Thanks for your help!

---

htmx version: 0.0.3

**Comment by chg20** [comment]
what sort of inputs are these?

**Comment by chg20** [comment]
if we can boil down a simple example I can get a test and fix in for 0.0.4 on monday

**Comment by johndwells** [comment]
Here is what I used to isolate & confirm my test (uses PHP to echo the params sent):

```
<html>
<head>
    <script src="https://unpkg.com/htmx.org@0.0.3"></script>
    <script>htmx.logAll();</script>
</head>
<body>
<div>
    <h1>Test</h1>
    <hr>
    <div id="container">
        <h2>POSTs:</h2>
        <?php
        var_dump($_POST);
        ?>
        <hr>
        <h3>Form</h3>
        <form method="post" hx-post="/htmx.php" hx-select="#container" hx-target="#container">
            <input type="text" name="variable" value="">
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
</body>
</html>
```

If you submit it with a value in the input, it shows up in the `$_POST` array; if not, then the `$_POST` array is empty.

Thanks for your help! :)

**Comment by chg20** [comment]
OK, added a regression test and fix in `dev`:

https://github.com/bigskysoftware/htmx/commit/468c405d02848bd185adceaa3bbcdd50f48c8262

This will go out on monday w/ the 0.0.4 release.  Thank you for catching it!

**Comment by akathartos** [comment]
This seems to also happen with empty select lists with multiple -attribute.
