### ISSUE TITLE
Scrolling modifiers not working with outerHTML

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#335]
Scrolling modifiers don't seem to bee working with `outerHTML`, likely because the target element is swapped out and therefore no longer available when `updateScrollState` is called:
https://github.com/bigskysoftware/htmx/blob/a7d8f444abdca72fdfb55b71410cfca995fa224b/src/htmx.js#L2150

Example:

```html
<div id="results" style="height: 400px;"></div>

<a hx-get="/" hx-target="#results" hx-swap="outerHTML show:top">Refresh results</a>
```

I wonder whether htmx could be changed to find the new target using the CSS selector?

**Comment by 1cg** [comment]
I think that we need to do some smart consultation of the `elts` collection of new elements to make this work properly.

We also fire the `afterSwap` etc. events too many times because the original target is in this collection, so I can fix this when I fix that.

**Comment by 1cg** [comment]
I tried to fix this with https://github.com/bigskysoftware/htmx/commit/0cae34d337579c13b803978cc05276ebf5446db2

This is hard to test, would you mind manually testing it ben?

**Comment by bencroker** [comment]
Tested locally and it's working, nice work!!
