### ISSUE TITLE
Trigger Filters on form not preventing submission

### ISSUE THREAD

**Issue by mryderie** [bigskysoftware/htmx#338]
I'm having trouble using a trigger filter with form submission. I would expect that the example below would block the form submission, but it does not (https://jsfiddle.net/k6j0czu5/).

```html
<form hx-post="/whatever" hx-trigger="submit[false]">
  <input type="text" name="foo">
  <button type="submit">Submit</button>
</form>
```

My particular use-case is that I want to do some custom validation and prevent form submission when my criteria are not satisfied, e.g.

```html
<form hx-post="/whatever" hx-trigger="submit[myCustomValidationFunc()]">
```

I'm new to HTMX, so I may not be approaching this problem in the best way. Any alternative suggestions welcome!

**Comment by tomberek** [comment]
One possibility is to set `<button type="button">` then use an `onclick` or similar with a custom event for the trigger.

It looks like the `submit[false]` doesn't trigger and hence the submit is not intercepted. Perhaps something like this, using `onSubmit="return false"` to intercept the normal submission?:
```
<form onSubmit="return false" hx-post="/whatever" hx-trigger="submit[myCustomValidationFunc()]" hx-target="#result">
  <input type="text" name="foo">
  <button type="submit">Submit</button>
</form>
<div id="result">
</div>
```

**Comment by 1cg** [comment]
I think I see the bug:

We cancel the event here:  https://github.com/bigskysoftware/htmx/blob/08d594ccf39c81f76a677ddb231974513f573ac7/src/htmx.js#L931

But the filter logic applies *before* that: https://github.com/bigskysoftware/htmx/blob/08d594ccf39c81f76a677ddb231974513f573ac7/src/htmx.js#L925

So we aren't cancelling the form submission event, and the event is therefore triggering a regular HTML form submission.  

I have made a change in dev that should fix this if you are willing to test that out:

https://github.com/bigskysoftware/htmx/commit/fa2fa8017ef07c0369be33ac08b5d2aa3410155b

**Comment by mryderie** [comment]
@1cg I've confirmed that this change fixes my issue. Thanks!
