### ISSUE TITLE
Post process JSON response?

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#344]
I am calling a third-party API where `hx-get` would return JSON objects such as

```
{
            'unread_count': 5,
 }
```
but my widget only needs the `5` part. It looks like I need something similar to `hx-select="unread_count"` but `hx-select` works only on HTML response. Is there any support for parsing and retrieving JSON results in HTMX?

**Comment by 1cg** [comment]
Would the client side templating extension be useful here?

https://htmx.org/extensions/client-side-templates/

**Comment by BoPeng** [comment]
Thanks. It looks like I need a template 

```
{{ unread_count }}
```
I am not sure how efficient it is to provide an template for such a simple case, but it looks like it should work.

**Comment by 1cg** [comment]
I would like to eventually support a `javascript:` prefix in `hx-swap` (as well as other attributes) to allow you to do these things inline without any need for additional libraries...

**Comment by BoPeng** [comment]
The extension needs

**Comment by BoPeng** [comment]
Some feedbacks,

```
        if (nunjucksTemplate) {
            var data = JSON.parse(text);
            var templateName = nunjucksTemplate.getAttribute('nunjucks-template');
            var template = htmx.find('#' + templateName);
            if (template) {
                return nunjucks.renderString(template.innerHTML, data);
            } else {
                return nunjucks.render(templateName, data);
            }
          }
```

`render` is used so the `numjacks-template` has to be a filename, whereas for this simple case I definitely want to use `renderString`.

**Comment by iredmail** [comment]
> I would like to eventually support a `javascript:` prefix in `hx-swap` (as well as other attributes) to allow you to do these things inline without any need for additional libraries...

The `hx-get/post/delete/put` are easy and cool, but not easy to handle the returned JSON object.
Is it better to support a `json:` prefix in `hx-swap` instead of `javascript:`? `json:` indicates its a JSON object, then we can use something like map to access the json object: `json:unread_count`, or `json["unread_count"]`.

Maybe implement simple `if` condition and `for` loop too? Something like the `v-for` in VueJS?

**Comment by Colir** [comment]
Hi !
no news on that feature without adding a client-side templating engines ?
Someting simple as "json:unread_count" ?

Thank you
