### ISSUE TITLE
Support for prefetch?

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#346]
I saw some mentioning of prefetch (e.g. [here](https://github.com/bigskysoftware/htmx/issues/130)) but cannot find anything from the htmx references for `hx-trigger` or `hx-swap`.

I have in my html page a few `hx-get` calls that replaces the `content` area of the page, mimicking a single-page application. What I would like to achieve is that when the page is load, some `hx-get` calls would be made with results cached when the user is reading the page, and then when `hx-trigger="click"` is actually triggered, the AJAX call would return instantly. A similar thing would be for pagination for which I would like the next page to be cached before the page number is clicked.

This looks to me would be something like

```
hx-get'/nextpage' hx-trigger='click prefetch'
```
but perhaps it is already implemented with some other method?

**Comment by 1cg** [comment]
You probably want to take a look at the relatively new preload extension by @benpate:

https://htmx.org/extensions/preload/

**Comment by BoPeng** [comment]
Well, as usual, whatever I have in mind others had and solved it already ... Thanks for pointing me to that extension.
