### ISSUE TITLE
Doesn't load open posts when returning back - Load More

### ISSUE THREAD

**Issue by thefubon** [bigskysoftware/htmx#347]
### Describe the bug
Hello, Load More stopped working for me.
Cond I load posts in the Blog section, and then I go inside the news. And I press go back in the browser, All open pages with load through load more are reset.

https://github.com/putyourlightson/craft-sprig/issues/92#issue-797045365

### Screenshots

https://www.youtube.com/watch?v=h81CdJ2YObs&feature=youtu.be

### Versions
- Plugin version: Sprig 1.3.2
- Craft version: 3.6.2

**Comment by 1cg** [comment]
@bencroker :point_up:

**Comment by bencroker** [comment]
Here is some reproducible code that assumes that page is loaded at the URL `/htmx` and uses Twig templating to get the `offset` from the query string.

```html
{% set offset = offset ?? 0 %}

<p>Title {{ offset }}</p>

<button hx-get="/htmx?offset={{ offset + 1 }}" hx-push-url="/htmx?offset={{ offset + 1 }}" hx-target="this" hx-swap="outerHTML">Load More</button>
```

After a few clicks of the button, using the browser's back button is inconsistent.

**Comment by thefubon** [comment]
I cannot understand how to add correctly to my code

`{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).section(section).limit(limit) %}
{% set entries = entryQuery.all() %}

{% for entry in entries %}
	<h3 class="uk-card-title uk-margin-small uk-text-bold"><a href="{{ entry.url }}">{{ entry.title }}</a></h3>
	<p class="uk-margin-small">{{ entry.leadIn|striptags|slice(0, 240) }}</p>	
{% endfor %}

{# do sprig.pushUrl('/blog?offset=' ~ offset) #}
{% if entryQuery.count() > offset + entries|length %}
  <button class="uk-button uk-button-default uk-button-large uk-border-rounded uk-align-center" sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">{{ 'Load More'|t }}</button>
{% endif %}
`

**Comment by 1cg** [comment]
Thanks ben.  I'm going to be looking at history this weekend.

**Comment by bencroker** [comment]
going to address the history issue in https://github.com/bigskysoftware/htmx/issues/368.
