### ISSUE TITLE
Unable to update dom when using hx-select and extension morphdom-swap

### ISSUE THREAD

**Issue by andyhorng** [bigskysoftware/htmx#348]
https://github.com/bigskysoftware/htmx/blob/6d65d078e782f25b16b039fe75881dd221d370e1/src/ext/morphdom-swap.js#L7

The fragment does not have outerHTML if it was selected by `hx-select`. `hx-select` will create a DocumentFragement and select matched nodes into it.

https://github.com/bigskysoftware/htmx/blob/6d65d078e782f25b16b039fe75881dd221d370e1/src/htmx.js#L596-L602

Is there any use case that needs to select multiple elements from the response into the target? In my works, there is no such case and I can not imagine the scenario. If it is not required, we can just select the first matched node and return it. No need to create a new DocumentFragement.

**Comment by 1cg** [comment]
I would like to keep hx-select working the way it is, but fix up the morphdom extension to handle DocumentFragments.  Does that sound reasonable?

Would you be interested in tackling that problem?

**Comment by andyhorng** [comment]
Sure, I will send a PR soon. Thanks!
