### ISSUE TITLE
Revealed event

### ISSUE THREAD

**Issue by rauwebieten** [bigskysoftware/htmx#351]
I'm playing around with the revealed event to lazy load elements on a homepage.

But is seems the revealed event is only triggered on scroll.
When the dom-element is in view from page load, the revealed event is not triggered.

I would like to see when the page loads, all elements which are visible, receive revealed events.
Is this possible?

**Comment by 1cg** [comment]
Hmmm, that's how it *should* work:

https://github.com/bigskysoftware/htmx/blob/3c3cd304ae98b061b0a9310709a7f0fd8c094795/src/htmx.js#L1239

we immediately `maybeReveal()` the element when we process the event on it.

**Comment by 1cg** [comment]
We have another bug that says it only works when it is visible initially:

https://github.com/bigskysoftware/htmx/issues/360

:thinking:

**Comment by 1cg** [comment]
Does the infinite scroll demo work for you:

https://htmx.org/examples/infinite-scroll/

**Comment by 1cg** [comment]
Closing due to lack of response.
