### ISSUE TITLE
Feature request: Easy way to handle returned JSON object

### ISSUE THREAD

**Issue by iredmail** [bigskysoftware/htmx#353]
`hx-get/post/delete/put` are easy and cool, but not easy to handle the returned JSON object. Although it's possible with the official `client-side-templates` extension, but writing many template files to handle returned JSON object is not cool.

Could htmx offer an easy way to access the json data directly in `hx-swap` (or other existing or new `hx-*`)?
If returned JSON is `{"_success": true, "_msg": "Account removed"}`, can we get the `_msg` with some syntax like `json["_msg"]` directly?

Also, maybe implement simple `if` condition and `for` loop too?

**Comment by BoPeng** [comment]
In #344 @1cg said

> I would like to eventually support a javascript: prefix in hx-swap (as well as other attributes) to allow you to do these things inline without any need for additional libraries...

**Comment by benpate** [comment]
If you have custom logic that you want to do with a JSON object, I'd suggest you try to [make your own extension](https://htmx.org/extensions/#defining).  They're remarkably easy to build and amazingly powerful -- something that really surprised me when I first got going making them.  

Take a look at the source for the [client-side-templates extension](https://github.com/bigskysoftware/htmx/blob/master/src/ext/client-side-templates.js) that you mentioned.  In <40 lines of code, it implements three separate templating libraries.  I'll bet your custom messaging could be implemented in 10. :)

**Comment by 1cg** [comment]
Yep, a custom extension would be my recommendation for this.  Or some hyperscript :)
