### ISSUE TITLE
Safari issue with srcset

### ISSUE THREAD

**Issue by philipboomy** [bigskysoftware/htmx#355]
Hi

Like I also wrote to Caleb from Livewire, thank you for this great tool.

I am wondering if you could look at this issue as its happening using your library too. Its most likely a Safari bug but I am trying to gather more info. https://github.com/livewire/livewire/issues/2466

**Comment by bencroker** [comment]
Safe to say this is a bug in Safari, which if it is, there's nothing that htmx can (or should?) do about it.
