### ISSUE TITLE
hx-trigger="revealed" only works on immediate load, not when scrolled into view

### ISSUE THREAD

**Issue by danjac** [bigskysoftware/htmx#360]
I have this snippet of code at the bottom of a page:

```
<div hx-get="?page={{ page_number_from_server }}"
     hx-trigger="revealed"
     hx-swap="outerHTML">
  <div class="flex justify-center">
    <img src="loader.svg"
         alt="Loading..."
         class="h-16 w-16">
  </div>
</div>
```

The idea is that this loads the next page of items when the user scrolls to the bottom of the page. The returned HTML includes the next page of items, and this snippet at the end, thus implementing infinite scroll triggered as the user scrolls down the page.

However, it appears this is only triggered if the element is visible at page load. It is not triggered at all when scrolled into view. This is confirmed using htmx.logAll(): no request is triggered or sent to the server.

Using htmx 1.1.0, issue appears on Firefox and Chrome.

**Comment by 1cg** [comment]
Does the infinite scroll demo work for you:

https://htmx.org/examples/infinite-scroll/

**Comment by danjac** [comment]
I think the issue was the hx-swap: it had to be "afterend" (following your example). Looks like it's working now, thanks.
