### ISSUE TITLE
hx-swap-oob requires target having an ID

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#363]
I have potentially multiple avatar in a page so the avatar is defined as
```
<div class="avatar">
</div>
```
without an `id`.

After the avatar is updated from a `hx-post="update_profile"` somewhere, the returned piece has

```
<div class="avatar" hx-swap-oob="true:.avatar">
</div>
```
which, according to the [doc on `hx-swap-oob`](https://htmx.org/attributes/hx-swap/), would update the first `avatar`, which would be the one on the header and I am ok with it. However, the code triggers

```
DOMException: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.
```

from what I believe by line 453 of this piece of code

https://github.com/bigskysoftware/htmx/blob/c26e3c10bbcee836ea0ba7b091525737ac6cfd00/src/htmx.js#L441-L454

despite the fact that the `oobElement` is found by class name so no id is required.

https://github.com/bigskysoftware/htmx/blob/c26e3c10bbcee836ea0ba7b091525737ac6cfd00/src/htmx.js#L470-L474

The code also appears to suggest that all matching elements will be replaced (which is even better for me), instead of "If a selector is given, the first element matching that selector will be swapped.".

Is this a bug?

**Comment by benpate** [comment]
[The documentation](https://htmx.org/attributes/hx-swap-oob/) says that only the first matching selector should be swapped.    So, it seems like this is not behaving the way it's supposed to.

However, in practice, I think you're best off having an id for any element that you want to `oob-swap`.  That will make your code much more explicit.

**Comment by BoPeng** [comment]
The document does not mention the target must have an ID, and it does not appear to be necessary as long as the target can be located. I did not study the source code in detail but it does not make much sense to find the elements by provided selector, then again by id.

Whether or not allowing the replacement of multiple targets would be a design decision. It would work fine for my conversation app with multiple avatars but maybe not such a good idea for other applications.

**Comment by benpate** [comment]
Yeah, there's "good, abstract design principles" and then there's "my specific requirements" -- they never seem to line up, do they? :)

Personally, I wish htmx used more IDs than selectors -- the same way that HTML usually uses IDs to target other nodes.  But since we're using selectors, it seems logical to me to follow through all the way and update ALL of the items that match.

@1cg -- How do you feel about allowing `oob-swap` to update multiple elements?  If you had a pull request that implemented it (with tests and documentation, of course) would you consider merging it in?

**Comment by BoPeng** [comment]
I am not at all an expert on JS (and that is why I love htmx), but

```
@@ -441,16 +441,17 @@ return (function () {
         function oobSwap(oobValue, oobElement, settleInfo) {
             var selector = "#" + oobElement.id;
             var swapStyle = "outerHTML";
+            var target = oobElement;
             if (oobValue === "true") {
                 // do nothing
             } else if (oobValue.indexOf(":") > 0) {
                 swapStyle = oobValue.substr(0, oobValue.indexOf(":"));
                 selector  = oobValue.substr(oobValue.indexOf(":") + 1, oobValue.length);
+                target = getDocument().querySelector(selector);
             } else {
                 swapStyle = oobValue;
             }

-            var target = getDocument().querySelector(selector);
             if (target) {
                 var fragment;
                 fragment = getDocument().createDocumentFragment();
```
appears to solve this particular bug, and in theory slightly more performant since `querySelector(selector)` is only called when needed.

**Comment by BoPeng** [comment]
I created a [PR](#367) but do not know how to test it. I assume that no documentation update is necessary since it does not change existing behavior (although it might actually allows swapping multiple targets by classname).

**Comment by bencroker** [comment]
Before looking at the PR, the docs say:
```any valid hx-swap value, followed by a colon, followed by a CSS selector```

So shouldn't your code use a colon as follows?
```<div class="avatar" hx-swap-oob="true:.avatar">```

**Comment by BoPeng** [comment]
Yes, I was. I will fix the original post.

**Comment by bencroker** [comment]
Thanks. I'm not that familiar with the OOB functions, therefore paging @1cg to look at https://github.com/bigskysoftware/htmx/pull/367.

**Comment by geoffrey-eisenbarth** [comment]
I see that this never got merged in (specifically, I'm hoping for support of multiple targets using a class). Is this on anyone else's radar?

**Comment by BoPeng** [comment]
My PR was wrong but the feature request was valid.

**Comment by bencroker** [comment]
Best to create a new issue for this, this issue has become stale and too long.
