### ISSUE TITLE
execute JS code of hx-get + hx-select

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#365]
I have a base html page with 

```
<header>
<div id="page-content">content</div>
<footer> 
```
that every page uses and I use
```
<a href="#" hx-get="/another_page" hx-target="#page-content" hx-push-url="true"
                hx-select="#page-content">
```
extensively so that `/another_page` can be loaded by itself in its entirety, or loaded partially to replace `#page-content` when it is loaded from another page.

I have noticed that, however, I cannot use this mechanism for pages that contain its own JS code since the JS code is not executed if the page is loaded by `hx-get`.

Is there anyway to specify some `JS` code to execute after `hx-get`?

**Comment by benpate** [comment]
This *should* work.  I remember making a test case for this a while back.  [Here's where it's called in the code](https://github.com/bigskysoftware/htmx/blob/47567bc2946c96afd082bdd46dd7ecedb308de0c/src/htmx.js#L1222)

It's *supposed* to work even if you don't include a `<script type="text/javascript">` -- however, you might try adding this additional attribute to see if it helps make it run.

Are you able to post a sample of the code that's not running?

**Comment by BoPeng** [comment]
The entire page is loaded by `hx-get`, but `hx-select` only picks the content element. Are you sure all `scripts` in the loaded page would be executed?  I actually consider **not re-loading css and executing JS an advantage of using `htmx` in this scenario** because the "structure" is already there, css loaded, common-JS executed, and only the `content` will be replaced by the `hx-get` + `hx-select` instructions. In this particular case the new page has additional `js` code in addition to the ones already loaded.

**Comment by BoPeng** [comment]
Ok, here is my example,

[test.txt](https://github.com/bigskysoftware/htmx/files/5974073/test.txt)
[new_content.txt](https://github.com/bigskysoftware/htmx/files/5974074/new_content.txt)

To test it, change extension to `.html`, run maybe `python -m http.server` to serve the files,

1. load `http://localhost/test.html`, 
 
![image](https://user-images.githubusercontent.com/9889312/107817475-cf19ba80-6d3b-11eb-820e-3c4af661b50d.png)

2. click load new page

![image](https://user-images.githubusercontent.com/9889312/107817514-e0fb5d80-6d3b-11eb-846e-a9b1bf0f5caf.png)

3. refresh to execute the JS code, only now will the `window.alert` be triggered. This is expected behavior but I was trying to get the JS code executed with `hx-get`.

**Comment by BoPeng** [comment]
Closing it because I think there is nothing to improve on the htmx side.

A simplest solution would be including new `<script>` inside `#page-content` although this is not always possible.
