### ISSUE TITLE
History Cache Bug?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#368]
[On Discord](https://discord.com/channels/725789699527933952/725789747212976259/809842173087842375) there was a report of htmx not handling history correctly when there's a cache miss.  In this case (not sure how frequent) it apparently calls the server again without including the standard `HX-` headers.  

This would be a problem if the server is looking for these headers in order to customize the return value.  For instance, it's a common practice to generate a page fragment if `HX-Request` is present, but generate a full page if this header value is missing.

I haven't tested or seen this behavior myself, but it would be good to test for (and fix!) this if it is happening.

**Comment by bencroker** [comment]
We have duplicate issues, so moving this to https://github.com/bigskysoftware/htmx/issues/370.

**Comment by thefubon** [comment]
I cannot understand how to add correctly to my code

```
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).section(section).limit(limit) %}
{% set entries = entryQuery.all() %}

{% for entry in entries %}
	<h3 class="uk-card-title uk-margin-small uk-text-bold"><a href="{{ entry.url }}">{{ entry.title }}</a></h3>
	<p class="uk-margin-small">{{ entry.leadIn|striptags|slice(0, 240) }}</p>	
{% endfor %}

{% if entryQuery.count() > offset + entries|length %}
  <button class="uk-button uk-button-default uk-button-large uk-border-rounded uk-align-center" sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">{{ 'Load More'|t }}</button>
{% endif %}
```

**Comment by bencroker** [comment]
@thefubon this is a closed issue in the htmx repo and you are posting Twig code.

**Comment by thefubon** [comment]
https://fubon.uk/blog

<img width="1602" alt="Снимок экрана 2021-02-24 в 22 22 42" src="https://user-images.githubusercontent.com/43171309/109054374-d901cd00-76ee-11eb-813d-1bf6d21e1fc4.png">
