### ISSUE TITLE
Refused to get unsafe header "X-HX-Trigger" and "X-HX-Push"

### ISSUE THREAD

**Issue by mushishi78** [bigskysoftware/htmx#37]
I'm getting this warning messages when using htmx. I think they're just saying that your using `getResponseHeader` to get headers that aren't there. I can workaround by setting these headers to `''` on my server, but feels like I should be able to opt in to this functionality.

According to this [article](https://trackjs.com/blog/refused-unsafe-header/) you can use `getAllResponseHeaders` to get the header without warning.

(Thanks for making this library, I'm excited to use it)

**Comment by chg20** [comment]
This is fixed in dev, I'm pushing out a new version on Monday.

Thanks!

**Comment by mushishi78** [comment]
Awesome 😄
