### ISSUE TITLE
Back button behavior not as expected

### ISSUE THREAD

**Issue by joncombe** [bigskysoftware/htmx#370]
I am seeing an issue where the back button is not working as expected (hoped?). 

I have attached a very simple HTML example. I have tried using the `hx-push-url="true"` and `hx-push-url="/my-url"` formats but the behavior appears to be the same. I am not using the `hx-history-elt` option at all.

I have a set of links all loading (`hx-get`) content into the same DOM element (`hx-target="#content"`). If I click the links in sequence: `/` > `/one` > `/two` > `/three` then click the back button, the software works as expected, i.e. the url bar and DOM content change correctly. If however I press back again, the url bar updates correctly but the content of the page changes to be just the content of the loaded element. 

My understanding is that the user should be able to click back 10 times (as specified in `htmx.config.historyCacheSize`) but here I can only click once successfully. I notice that when the error occurs, a fresh request is made to the server with the `HX-History-Restore-Request` header, possibly meaning this issue is a duplicate of https://github.com/bigskysoftware/htmx/issues/368#issue-807451777

[htmx back button example.zip](https://github.com/bigskysoftware/htmx/files/5979285/htmx.back.button.example.zip)

**Comment by bencroker** [comment]
The issue, as I see it, is that the back button is triggering a page refresh in certain cases, which sounds like what you are experiencing.

![ScreenFlow](https://user-images.githubusercontent.com/57572400/108066072-28952880-705f-11eb-9380-43684599ff54.gif)

**Comment by bencroker** [comment]
@1cg It looks like the history state is getting blown out when `restoreHistory` is called.

![ScreenFlow](https://user-images.githubusercontent.com/57572400/108068489-72334280-7062-11eb-8441-1416bbb7c73b.gif)

**Comment by 1cg** [comment]
thank you everyone, I will try to address this tonight

**Comment by bencroker** [comment]
Fixed in https://github.com/bigskysoftware/htmx/commit/d2b1e10719f1bba5872c74833190735a03ecdde4, thanks @1cg!

**Comment by thefubon** [comment]
I cannot understand how to add correctly to my code

```
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).section(section).limit(limit) %}
{% set entries = entryQuery.all() %}

{% for entry in entries %}
	<h3 class="uk-card-title uk-margin-small uk-text-bold"><a href="{{ entry.url }}">{{ entry.title }}</a></h3>
	<p class="uk-margin-small">{{ entry.leadIn|striptags|slice(0, 240) }}</p>	
{% endfor %}

{% if entryQuery.count() > offset + entries|length %}
  <button class="uk-button uk-button-default uk-button-large uk-border-rounded uk-align-center" sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">{{ 'Load More'|t }}</button>
{% endif %}
```

**Comment by bencroker** [comment]
@thefubon this is a closed issue in the htmx repo and you are posting Twig code.
