### ISSUE TITLE
Undo doesn't work after input swap

### ISSUE THREAD

**Issue by maratori** [bigskysoftware/htmx#372]
Undo doesn't work after `<input>` swap.

### Steps to reproduce

1. Open [inline-validation example](https://htmx.org/examples/inline-validation/)
2. Enter `abc@test.com` into email address input
3. Press <kbd>Tab</kbd>
   * onchange event will be emited
   * htmx will replace `<input>` element with new one
4. Press <kbd>Cmd+Z</kbd> (<kbd>Ctrl+Z</kbd> on Windows)

### Expected behavior

Email address input should receive focus and be empty.

### Actual behavior

Nothing happens.

### Note

Undo for other inputs in that example works as expected because they are not swapped.

**Comment by bencroker** [comment]
I'm sure you can see why this is not working, since the `input` element is completely swapped out. Not sure if there is any workaround for this. Have you tried the `morphdom-swap` extension (https://htmx.org/extensions/morphdom-swap/)? I'm not sure it will make a difference but might be worth a shot.

**Comment by maratori** [comment]
I've tried the `morphdom-swap` extension. Unfortunately it behaves the same way.

Also I've tried `hx-preserve`. It also doesn't help.

I'm not an expert in JS, but I thing following solution is possible.
If an `<input>` has `id`, htmx may not swap it. But instead just update attributes from response.

**Comment by bencroker** [comment]
Have you tried `hx-preserve`?
https://htmx.org/attributes/hx-preserve/

**Comment by maratori** [comment]
Yes, see my previous comment.

**Comment by bencroker** [comment]
Ah sorry, missed that somehow. Going to refer to @1cg for further thoughts.

**Comment by 1cg** [comment]
Unfortunately I don't think we have any access to the undo state in the browser.  This might be a situation where a two-way binding solution would be a better approach.
