### ISSUE TITLE
hx-trigger="from:..." cannot handle newly added DOM elements

### ISSUE THREAD

**Issue by srkunze** [bigskysoftware/htmx#376]
The solution I would think of might also solve #375  but they represent conceptually separate problems where you might have different ideal solutions for either one. Thus this new issue.

### Setup

Let's consider the HTML template

- for URL `/home/`
```
<div hx-trigger="load, htmx:afterSwap from:.create_form" hx-target="this" hx-get="{{ view.list_url }}"></div>

<div hx-trigger="load" hx-target="this" hx-get="{{ view.create_url }}"></div>
```

- for URL `/create/`
```
<form class="create_form" hx-post="{{ view.create_topic_url }}" hx-target="this" hx-swap="outerHTML">
    ....
</form>
```

### Problem

This results in the following error and thus not even loading the form from `/create/`.

![image](https://user-images.githubusercontent.com/1389648/108340936-703fbf80-71d9-11eb-8960-5d01be4bbd4d.png)

**Comment by bencroker** [comment]
Can you please provide some more information? Which exact version of htmx are you using and what exactly are you asking for help with?

**Comment by bencroker** [comment]
Does my suggestion at https://github.com/bigskysoftware/htmx/issues/375#issuecomment-782052769 help?

**Comment by 1cg** [comment]
Ah, it can't handle elements that don't already exist in the DOM.  Interesting.  I'll need to investigate how to handle this.

**Comment by srkunze** [comment]
@bencroker 

> Does my suggestion at [#375 (comment)](https://github.com/bigskysoftware/htmx/issues/375#issuecomment-782052769) help?

Does have `htmx:afterSettle` an impact on `load`? I gave it a try but the javascript error as shown in the console pops up again.

**Comment by srkunze** [comment]
> Ah, it can't handle elements that don't already exist in the DOM. Interesting. I'll need to investigate how to handle this.

Let me know if I can help here.

My initial suggestion would have been to attach the event handlers to the body/document like:

``` javascript
$(body).on('click', 'element selector', function() {....})
```

**Comment by 1cg** [comment]
I think the right thing is something like this:

```html
  <div hx-trigger="load, htmx:afterSwap from:body source:.create_form" hx-target="this" hx-get="{{ view.list_url }}"></div>
```

So you explicitly listen for the event on the body (which is the right thing if the element might not exist) and then you pass in a CSS selector to filter the source of those events.

We need something similar in hyperscript.  I like how explicit this is, vs just magically making it work by listening to all events on the body by default.

**Comment by srkunze** [comment]
> I like how explicit this is

I like your idea .

I didn't thought of it from a user's perspective but given your example it makes sense to have explicitly stated. This even gives room for other use-cases where `body` is not appropriate.

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/02d637785bd47e97be0aa43bcafe3b6bca331c24
