### ISSUE TITLE
Improve `saveToHistoryCache`

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#377]
I currently see 2 areas of improvement in `saveToHistoryCache`.

1. The _first_ value in `historyCache` to match the URL is selected to be spliced. I would think that this should be the _last_ value.
2. Rather than triggering an error event when `localStorage` fills up, we could remove the oldest cached value and then try again.

Would love to get your thoughts on this @1cg.

https://github.com/bigskysoftware/htmx/blob/11287d924b3eea3adb65b53c34c80c903480eda1/src/htmx.js#L1409-L1426

**Comment by 1cg** [comment]
A given URL should only appear in the cache once, so I don't think it matters first or last.

I have implemented the historyCache backoff, please review it for me.

**Comment by bencroker** [comment]
Made a small tweak in https://github.com/bigskysoftware/htmx/commit/8c018be61d87ced4c899a197c906ac734b3a35cc, otherwise looking good!
