### ISSUE TITLE
hx-push-url and forms with method="get" appending rather than replacing querystring params

### ISSUE THREAD

**Issue by j4mie** [bigskysoftware/htmx#383]
👋 I have one of those issues with might just be me doing it wrong, but if so I can't figure out how to do it right!

I have a page with a search form at the top, and a `<div>` further down the page into which I want to load the results. I started with the [Active Search example](https://htmx.org/examples/active-search/) but I wanted two things it didn't offer: bookmarkable URLs (ie I want the search params to be included in the URL) and progressive enhancement (ie I want it to work without JavaScript). So I now have a single URL for the search page (rather than a separate endpoint that just returns a fragment containing the results). I want the form submission to make the request via AJAX (which will return a full page), and then pluck out the `#results` div from the returned HTML and replace the `#results` div on the current page with it.

Where I ended up:

```
<form hx-boost="true" hx-target="#results" hx-select="#results" hx-push-url="true" action="">
    <input type="text" name="search" value="{{ request.GET.search }}" placeholder="Search" />
</form>
```

This _almost_ works, but here's the issue: if I search for `foo`, then everything is fine, the results appear correctly, the URL is `/?search=foo` and all is good. But if I then change the contents of the `search` input to `bar` and resubmit the form, I'd expect the URL to change to `/?search=bar`. Instead, it changes to `/?search=foo&search=bar`. Each time I perform a new search, the parameter gets _appended_ to the URL, rather than replacing the existing search.

I'd be happy to try to tackle this if it is indeed a bug, and if someone can point me in the right direction!

Thanks 🙂

**Comment by 1cg** [comment]
I think this can be fixed by putting the actual URL in the action attribute:

```html
<form hx-boost="true" hx-target="#results" hx-select="#results" hx-push-url="true" action="/search">
    <input type="text" name="search" value="{{ request.GET.search }}" placeholder="Search" />
</form>
```

What's happening right now is that the URL does include that query parameter, and htmx appends additional query parameters to it, without merging.  In general, a query parameter can appear more than once in a query string, so this behavior isn't crazy.

**Comment by j4mie** [comment]
Huh, that does indeed fix it, thanks. I've been writing `action=""` for as long as I've been writing HTML to mean "submit to the current URL" but I am [just now discovering](https://stackoverflow.com/questions/1131781/is-it-a-good-practice-to-use-an-empty-url-for-a-html-forms-action-attribute-a) that it's actually wrong to do that! I guess this is why 😆 

Thanks again!
