### ISSUE TITLE
shouldCancel with <a href="#" hx-get>

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#385]
https://github.com/bigskysoftware/htmx/blob/b8ffa5c6a5176ac452e5aeee2710a2456dcde8d1/dist/htmx.js#L922-L926

When I trace an error on my side, I notice that

```
elt.href.indexOf('#') !== 0
```

returns `True` with my `<a href="#" ...>` element because somehow the browser has changed the `href` to `href="http://url_of_this_page/#"`.  I am not sure if this is a browser thing (chrome, mac) or something wrong on my side but I would like to bring this issue to the attention of the developers.

**Comment by BoPeng** [comment]
According to [this stackoverflow question](https://stackoverflow.com/questions/1550901/how-to-get-raw-href-contents-in-javascript), 

```
elt.href
```
gets the "expanded" URL, and
```
elt.getAttribute("href")
```
gets the original value of the URL, which is `#`.

Since 
```
elt.href.indexOf('#') !== 0
```
will always be true, should not
```
elt.getAttribute("href").indexOf('#') == 0
```
be used here?

**Comment by 1cg** [comment]
Thank you for contributing this fix!
