### ISSUE TITLE
Could anyone share a working example of the "client-side-templates" with nunjucks template engine?

### ISSUE THREAD

**Issue by iredmail** [bigskysoftware/htmx#395]
Dear all,

I'm trying to use htmx in a new project, but the examples are quite confusing and seems not complete.
Could anyone share a full working example of the "client-side-templates" with nunjucks template engine?

I tried with some simple testing code, but failed. It simply prints JSON string on page instead of calling nunjucks to handle JSON and return rendered HTML.

index.html:
```
<html>
    <head>
        <title>HTMX</title>
    </head>
    <body>
        <div hx-ext="client-side-templates">
            <button hx-ext="debug"
                hx-get="https://jsonplaceholder.typicode.com/todos/1"
                hx-target="#todo"
                hx-swap="innerHTML"
                nunjucks-template="todo"
                >Get TODO item</button>

            <p id="todo"></p>
        </div>

        <script src="https://unpkg.com/htmx.org@1.2.1"></script>
        <script src="https://mozilla.github.io/nunjucks/files/nunjucks.min.js"></script>
    </body>
</html>
```

nunjuck template file: `views/todo`:
```
#{{ id }}: {{ title }}
```

**Comment by 1cg** [comment]
Hi There,

htmx is focused mainly on server side rendering, so I wouldn't recommend it if you are using client side rendering extensively.  

For your example `https://jsonplaceholder.typicode.com/todos/1` would return an HTML fragment, rather than JSON.

If you wish you can use the content type headers to switch between the two formats.

**Comment by iredmail** [comment]
> htmx is focused mainly on server side rendering, so I wouldn't recommend it if you are using client side rendering extensively.

Thanks for the remind. I know this, but want to use htmx for simpler ajax requests. Handling returned JSON data is required in some requests, so i have to give it a try for evaluation.

> For your example `https://jsonplaceholder.typicode.com/todos/1` would return an HTML fragment, rather than JSON.
> If you wish you can use the content type headers to switch between the two formats.

Check the http headers with `curl`, it returns `content-type: application/json`. So i'm not sure whether it's a htmx issue.

```
$ curl --head https://jsonplaceholder.typicode.com/todos/1
...
content-type: application/json; charset=utf-8
...
```
