### ISSUE TITLE
hx-post does not trigger submit event of form

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#396]
I have a form with a `textarea` that is edited by [`easymde.js`](https://github.com/Ionaru/easy-markdown-editor).  The idea is that the `textarea` is hidden and replaced by a bunch of codemirror stuff,

```
<form>
<hidden textarea>
<js-created codemirror editor>
<button type='submit'>submit</button>
</form>
```
The trick here is that the content of the `textarea` will be replaced by the content of the editor when the `submit` event of the `form` is triggered.

However, when the form is triggered by `hx-post`, the `form` element no longer emits a `submit` event (at least according to my `addEventListener` test code) so the `textarea` will always be empty when the form is submitted.

I think this should be fixed if confirmed.

**Comment by 1cg** [comment]
Hi Bo,

This sounds like a library conflict, where both easymde and htmx are fighting over the submit action.

Does easymde fire any events after it has updated the text area that you can catch with an `hx-trigger`?  That might be a good solution.

**Comment by BoPeng** [comment]
At

**Comment by BoPeng** [comment]
The `save` on `submit` behavior is from `codemirror` so I would say any online editing widgets based on CodeMirror would be affected by this issue.

https://github.com/codemirror/CodeMirror/blob/6e7aa65a8bfb64837ae9d082b674b2f5ee056d2c/src/edit/fromTextArea.js#L24-L25

**Comment by BoPeng** [comment]
replaced by #398
