### ISSUE TITLE
How to submit hx form on input change?

### ISSUE THREAD

**Issue by AucT** [bigskysoftware/htmx#404]
Hi. I'm trying to replace old jquery code.
My old code is doing ajax form submit on file choose. (without clicking button).

How to make your code https://htmx.org/examples/file-upload/ trigger form on change / click file chooser?

**Comment by mikaelho** [comment]
Adding a small `delay:100ms` in the hx-trigger value works for other input fields.

**Comment by 1cg** [comment]
You should be able to trigger the request with the standard `change` event.

**Comment by AucT** [comment]
can u provide working example in code? I need form with files to be submitted when i chose file.
