### ISSUE TITLE
Websocket communication over channels

### ISSUE THREAD

**Issue by sreyansjain** [bigskysoftware/htmx#406]
Hi,

Thank you for creating htmx. It mind bending and simple at the same time.
I am trying to use htmx with [Elixir Phoenix Framework](https://www.phoenixframework.org/). I am trying to use web sockets. Now phoenix web sockets use channels for communication.

Does htmx support channels over websockets. If yes, can you please share a code snippet.

If I were using javascript I would use the following code to connect using channels - 
```
import { Socket } from "phoenix"

let socket = new Socket("/socket", { params: { token: window.userToken } })
socket.connect()

let channel = socket.channel("task:list", {})
channel.join()
  .receive("ok", resp => { console.log("Joined successfully", resp) })
  .receive("error", resp => { console.log("Unable to join", resp) })
```

**Comment by 1cg** [comment]
It looks like the notion of channels is an elixer/phoenix-specific concept:

https://stackoverflow.com/questions/49474019/javascript-websocket-subscribe-to-channel

I don't know how'd we'd integrate this into htmx, without an extension of some sort...

**Comment by 1cg** [comment]
Going to close this out, since it is backend specific.  An enhancement for it would be a potential use case however.
