### ISSUE TITLE
How to handle POST request errors?

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#41]
When using `hx-post` I see in the console a POST request to the value, quickly followed by a GET request to the value, the result of which is returned. Is it possible to handle errors that are returned in the POST response? All I see in the console is a `302 Found` status and an empty body, even though my controller is returning a `200` with a body. Any insights into how this works would be much appreciated.

**Comment by rschroll** [comment]
If your server is returning an error code, htmx will trigger the responseError event (https://htmx.org/events/#responseError.htmx).  But it sounds like that isn't what's happening here.

You can turn on logging in htmx to see everything that's going on: https://htmx.org/docs/#events.  It can be a little overwhelming, but maybe that will illuminate things more.

**Comment by chg20** [comment]
hey ben, can you post the HTML for me to look at?  I don't know why a GET should be issued immediately after a POST, that sounds suspicious.

**Comment by bencroker** [comment]
Thanks @rschroll and @chg20, after further investivation it seems the server was returning a `302` status after all. Fixing the controller to return a `200` status code fixed it. The `responseError` event looks perfect for future use, cheers!
