### ISSUE TITLE
HX-Trigger-After-Swap does not work (but HX-Trigger works)

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#418]
In my web application I sent 

```
resp['HX-Trigger-After-Swap'] = 'cart-updated'
```
after an `add-to-cart` button is pressed and handled in the backend. The event is supposed to trigger another element with `hx-trigger="cart-updated from:body"` and update the display of carts.

It somehow did not work. I traced to the code and found that the `HX-Trigger-After-Swap` has been handled, the event has been dispatched, but does not bubble up to `body`.

Out of desperation I changed the code to
```
resp['HX-Trigger'] = 'cart-updated'
```
and everything worked. I do not know how to trace a dispatched event and cannot determine what has happened, so I am describing the issue here in case someone knows what might be going on (and could identify a bug or undocumented feature).

**Comment by 1cg** [comment]
I bet that the element was removed from the DOM and so the event was never percolating up.  That's a bug.

**Comment by BoPeng** [comment]
I used `HX-Trigger-After-Swap` because element, whatever it is, should not disappear after swap is done. Let me create a test case and see if this is the case.

**Comment by bioworkflows** [comment]
Yes, @1cg was correct. The problem was that the element was swapped out.

Here is an example using flask

```python
from flask import Flask
from flask import render_template
from flask import make_response

app = Flask(__name__)

@app.route('/')
def root():
    return render_template('main.html')

@app.route('/add_to_cart')
def added():
    resp = make_response(render_template('added.html'))
    #resp.headers.set('HX-Trigger-After-Swap', 'cart-updated')
    resp.headers.set('HX-Trigger', 'cart-updated')
    return resp
```

templates/main.html

```html
<!DOCTYPE html>
<html lang="en">
<body id='body'>

    <a href="#" hx-get="/add_to_cart" hx-swap='outerHTML'>
    add to cart
    </a>

</form>
</body>
  <script src="https://unpkg.com/htmx.org@1.2.1"></script>
  <script>
  document.getElementById("body").addEventListener("cart-updated",
    () => {
        alert('cart-updated');
    });

  </script>
</html>
```

templates/loaded.html
```html
added to cart
```

Run
```
flask run
```
and

1. If ```hx-swap='innerHTML'``` , both `HX-Trigger` and `HX-Trigger-After-Swap` works.
2. If ```hx-swap='outerHTML'```, `HX-Trigger` works and `HX-Trigger-After-Swap` does not.

Without reading the code I think `HX-Trigger-After-Swap` should be triggered from the element that has been swapped in, not the element that was swapped out.

**Comment by 1cg** [comment]
We now dispatch on the body if the element is no longer part of the DOM:

https://github.com/bigskysoftware/htmx/commit/1fca7dbb7035e20d9f6919a2ca775b4476b8efb8

**Comment by BoPeng** [comment]
A side effect would be the parents of `hx-target` will not get the signal if `hx-target` is swapped out. Something needs to be documented, I guess.
