### ISSUE TITLE
Docs about "Hacking" or "First PR" are missing

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#422]
it would be helpful, if you could provide some instruction how to create a first Pull Request.

1. How to set up the IDE
2. How to run the tests
3. How to submit the PR

This would help new comers to write great PRs (instead of just creating issues), which would help you :-)

**Comment by 1cg** [comment]
Agreed!  I hope to have some time soon now that hyperscript 0.1 is winding down...

**Comment by 1cg** [comment]
dup, we have included a hacking guide in the README.md
