### ISSUE TITLE
Let oob use innerHTML for source (and outerHTML for target)

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#423]
I want to use [hx-swap-oob](https://htmx.org/attributes/hx-swap-oob/) to replace a table row of the existing page "out of band".

HTML already in browser (target):
```
<table>
 <tr id="offer_1">....</tr>
 <tr id="offer_2">....</tr> (old)
 <tr id="offer_3">....</tr>
</table>
```

I want to add this new table row (source coming from server)
```
 <tr id="offer_2" class="some-new-css-class"> .... </tr> (new)
```

Up to now hx-swap-oob does take the outerHTML from the source.

I would like to take the innerHTML, because of one reason:

On the server I have a method to create the table row. This method should not know the fact that result of the method gets used in hx-swap-oob. 

I am willing to provide a pull request.

Up to now I am unsure about how solution should look like at the end.

Here is one of many options:
```
<table hx-swap-oob="innerHTML-source">
 <tr id="offer_2" class="some-new-css-class"> .... </tr> (new)
</table>
```

`innerHTML-source` tells htmx to ignore the <table> tag and take the innerHTML as source.

Would you accept a PR?

BTW, #422 would be nice, too (Docs about how to create a PR).

**Comment by 1cg** [comment]
I'm open to the idea.  Maybe use the https://htmx.org/attributes/hx-select/ attribute in conjunction w/ the oob-swap?  Or a `select:` modifier in `hx-oob-swap`?

I'm good w/ any pull request, just add tests :)

**Comment by adicco** [comment]
Hey @guettli, I was actually looking into this myself. Have you found anything else in the meantime?

**Comment by guettli** [comment]
@adicco sorry, I don't recall how I solved this. I know that there was an issue with sending `<tr>...</tr>` out-of-band.

But that was solved by carlson: https://github.com/bigskysoftware/htmx/issues/469

Maybe you get a better answer if you ask in the discord channel or at Stackoverflow.

**Comment by adicco** [comment]
Thanks for the quick reply @guettli 

In my case I am using a Bun/Elysia stack with JSX templating, and it would be neat to be able to do something like

```jsx
<div hx-swap-oob="outerHTML:#my-target-component" hx-swap-oob-source="innerHTML">
<MyComponent />
</div>
```

Because presently the ```<div>``` itself replaces the target's outerHTML. Of course I can get by by doing:

```jsx
<MyComponent hx-swap-oob="..." />
```

But it would be neat to separate this concerns and not have components define optional swap properties, and be unaware of whether they would be swapped or not.

**Comment by guettli** [comment]
@adicco I would ask at Stackoverflow or at Reddit.

**Comment by adicco** [comment]
Thanks, I think the [multi-swap extension](https://htmx.org/extensions/multi-swap/) might be what I'm looking for.

**Comment by guettli** [comment]
Great, then I will close the issue. Feel free to re-open if there is a good reason.

**Comment by guettli** [comment]
@adicco sound reasonable. But I am the wrong person to talk to.

**Comment by scrhartley** [comment]
Would this work as an swap-style extension?
```html
<div hx-swap-oob="oobReplace:#target">
<MyComponent />
</div>
```
```js
(function() {
  var api
  htmx.defineExtension('oob-replace', {
    init: function(apiRef) {
      api = apiRef
    },
    handleSwap: function(swapStyle, target, fragment, settleInfo) {
      if (swapStyle === 'oobReplace' && fragment.firstElementChild &&
        !(target instanceof Element && target.tagName === 'BODY') ) {
        var index = [...target.parentElement.children].indexOf(target)
        var selector = `find :scope > :nth-child(${index + 1})`
        api.oobSwap(`outerHTML:${selector}`, fragment.firstElementChild, settleInfo, target.parentElement)
        return true
      }
      return false
    }
  })
})()
```
(Remember you need `hx-ext="oob-replace"`)
