### ISSUE TITLE
Security issues w/ strict CSPs

### ISSUE THREAD

**Issue by apollo13** [bigskysoftware/htmx#428]
This is a follow up to a twitter thread (https://twitter.com/fapolloner/status/1372944536805195776). Initially I was wondering how well htmx & hyperscript play together with a strict CSP. Since CSP is often used to guard against coding mistakes (that then allow injection of html/js/css) it would be great if the htmx documentation had a section about how an attacker could use HTML injection capabilities to circumvent even a strict CSP by using hx and/or attributes maliciously.

The htmx org (@1cg I presume) also suggested:

> that being said, I would like to include an attribute for both libraries that says "don't execute/evaluate anything within this element" for security concerns like this.

Personally I am not convinced that this would be very useful; after all one does not know where a mistake in the code lies and putting such an attribute on the initial `<html>` tag would not be helpful either :D It might make sense in areas where the user can submit HTML, but that should be sanitized properly anyways due to the magnitude of attack vectors there.

Let's see where the discussion leads :)

**Comment by 1cg** [comment]
I would like to add a `.htmx-disabled` class that can be used to flag a part of the DOM for non-execution/processing.

This could be used around areas where 3rd party HTML is being injected to avoid issues if the HTML is not properly escaped.

**Comment by 1cg** [comment]
I have added support for an `hx-disable` attribute and documented security concerns here:

https://htmx.org/docs/#security

I am going to close this issue for now, but @apollo13 if you have further thoughts on ways that we can improve security while still keeping the essence of locality of behavior please continue this discussion.  Some things that pop into my mind is a security manager like the JVM, some sort of locking mode (???) for attributes, etc.
