### ISSUE TITLE
Can an extension replace serialization (e.g. with msgpack)?

### ISSUE THREAD

**Issue by pohlt** [bigskysoftware/htmx#432]
Instead of JSON, I would like to use msgpack as the wire protocol. Could this be changed with an HTMX extension?

**Comment by 1cg** [comment]
Unfortunately right now there isn't a good way to do that

I'd be happy to work with you to make it possible though.  Are you interested in putting together a pull request?

**Comment by pohlt** [comment]
Hmm, definitely yes, it's just that the amount of spare time I can dedicate to such tasks is very limited and unpredictable.

Let me first have a look at the current implementation of the de/serialization. I'll think about an approach and discuss it with you.

Btw, the HTMX team does a very good job in supporting and onboarding potential contributors! Very welcoming and friendly bunch of people here! Keep up this spirit! It's a breath of fresh air in these crazy times. 👍
________________________________

**Comment by 1cg** [comment]
Hi @pohlt have you had any time (or need) to think about this further?

**Comment by pohlt** [comment]
Sorry, no. I actually worked on the other topic of having callbacks for a dis/re/connect of the WebSocket connection. Not sure when I will have time for that, I'm afraid to say. 😞

**Comment by 1cg** [comment]
closing out for lost interest, please reopen if you'd like to pursue the idea in the future

thank you!
