### ISSUE TITLE
Extension to customize hx-confirm?

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/htmx#434]
`hx-confirm` is nice but `window.confirm` is a bit primitive. I am trying to write an extension for [`bootlox.confirm`](http://bootboxjs.com/documentation.html#bb-confirm) but not sure how to do it (e.g. which event to intercept and how to return `confirmed` status).  Any suggestion on how I should proceed?

Something like `htmx.config.confirmFunction` would also be possible though.

**Comment by BoPeng** [comment]
I think a solution to this problem could be generalized to solve #401 (trigger of JS-based form validation before `hx-post`). That is to say, `hx-confirm` could 

1. get user confirmation from `window.confirm` (default)
2. call a JS script function to get user confirmation (this ticket)
3. call a JS script to validate the form (#401)

basically a generalized way to determine if `hx-post` should be triggered.

**Comment by jreviews** [comment]
What if you re-define the confirm function?

```js
window.confirm = function(msg, callback) {
  // ...
 }
```

**Comment by BoPeng** [comment]
There are actually some [stackoverflow discussions on overriding `window.confirm`](https://stackoverflow.com/questions/12747904/js-override-confirm), so in theory it should work.  It also provides an ugly solution to #401, namely passing certain string to a customized `confirm` function to validate forms before `hx-post` is triggered.

But I suppose overriding a system function should be avoided if at all possible.

**Comment by 1cg** [comment]
I had an old example done in intercooler that used events for something like this:

https://intercoolerjs.org/examples/bootstrap_confirm.html

It can probably be ported to htmx pretty easily.  Might be worth looking at.

**Comment by BoPeng** [comment]
Thanks for the information, which actually help answer one of my old questions, namely how to trigger `hx-get` or `hx-post` from JS code (#339). I will adapt the example for my case.
