### ISSUE TITLE
Updating navigation bar without creating browser history entry

### ISSUE THREAD

**Issue by landlockedsurfer** [bigskysoftware/htmx#436]
Hi!
Does HTMX support (i.e. has some `hx-..` attribute or response header) to update the navigation bar without creating a new history entry?
`hx-push-url` updates the navigation bar, but also creates a new entry in the browser history.
Thanks in advance!

**Comment by 1cg** [comment]
Right now, no.  Can you give me a use case for this?

**Comment by landlockedsurfer** [comment]
An example could be a listing of products with a filter section. In case the filter changes one might not want to create a new entry in the page history but instead only update the navigation bar.
Another way to think of it is to connect pages hosting HTMX powered apps. I.e. on each page an HTMX powered app can trigger navigation bar updates without creating new browser history entries. Using the back browser's back button would bring the user to the previous page containing another HTMX powered app.
Hope this makes sense.

Anyways, thanks for all the work you put into HTMX! Great library, love using it and exploring all its features!

**Comment by jerivas** [comment]
This would be specially useful for pages that allow filtering results via GET. For example a user could perform three different searches: `?search=foo`, `?search=bar`, and `?search=baz`. The current implementation adds 3 items to the browser's history so the user has to go back 3 times to actually return to the previous page.

**Comment by checketts** [comment]
I also would like this feature. @jerivas use case is exactly what I'm doing. I have an active search to filters as the user types. Being able to avoid littering the browser history would be very nice.

In previous projects using Angular we would use the [replaceUrl](https://angular.io/api/router/NavigationBehaviorOptions#replaceUrl) options. (If you need inspiration)

**Comment by 1cg** [comment]
Would a response header `HX-Replace-URL` address your needs?

**Comment by checketts** [comment]
@1cg I might be in a position to try hacking on this for a PR this week. Did you have any work in progress code you would like me to consider?
