### ISSUE TITLE
Tracking and reloading asset bundles when performing boosted page transitions

### ISSUE THREAD

**Issue by nickjj** [bigskysoftware/htmx#437]
One thing that Turbolinks / Hotwire Turbo does is it keeps track of your CSS and JS bundles and if they change then the next time you transition between pages it will automatically do a full page reload so that the `<head>` of your page gets re-evaluated and in turn you get the new assets as part of that response. It does this through the `data-turbolinks-track="reload"` attribute which is included in their docs at https://github.com/turbolinks/turbolinks#reloading-when-assets-change. Hotwire Turbo does the same.

I'm curious if that behavior exists with htmx because I wasn't able to see it in the docs.

This is really important IMO because if you apply boosts to all of your links and a user is actively using your page you would want the next link they click to do a full page reload to pickup your new bundles if you happened to deploy a new version of your app that contains new CSS or JS. And in the cases where your bundles don't change it would boost like usual and only swap the body.

**Comment by 1cg** [comment]
In general, htmx is lower level and less magic than both turbolinks and hotwire.  You can mimic this behaviour by using the `HX-Refresh` header:

https://htmx.org/reference/#response_headers

But it will be up to you to do so via whatever backend you are using.  A common solution is to set a version cookie and check that and, if there is a new version, issue the header in a pre-request header.  Another solution I have seen is to warn the user that then need to refresh the page when there is a new version.

Hope that makes sense.
