### ISSUE TITLE
Search doesn't work on example pages

### ISSUE THREAD

**Issue by Bauke** [bigskysoftware/htmx#440]
For example, when you try to search on the [Click To Edit example] Algolia errors out with: `message: "Could not parse the incoming response as JSON, see err.more for details"`

[Click To Edit example]: https://htmx.org/examples/click-to-edit/

**Comment by 1cg** [comment]
Ah, the demo proxy must be breaking it on those pages.  

Update: fixed, thank you for pointing that out!
