### ISSUE TITLE
htmx:afterRequest not triggered in v1.3.3

### ISSUE THREAD

**Issue by billmn** [bigskysoftware/htmx#441]
Hi, I have some problems after upgrading to Sprig 1.5.0 that uses HTMX 1.3.3.

This code works fine before the upgrade:
```html
<form sprig s-method="post" s-action="contact-form/send" s-ext="progress">
    ...
</form>
```

```js
htmx.defineExtension('progress', {
    onEvent: (name, e) => {
        if (name == 'htmx:afterRequest') NProgress.done()
        if (name == 'htmx:beforeRequest') NProgress.start()
    }
})
```

When I submit the form, NProgress start correctly but it doesn't stop because seems that the `htmx:afterRequest` event was not triggered.

I have added a `console.log(name)` and these are the results:

**Before v1.3.3**
```
(4) htmx:validation:validate
htmx:configRequest
htmx:beforeRequest
(2) htmx:xhr:loadstart
htmx:xhr:progress
htmx:xhr:loadend
htmx:xhr:progress
htmx:beforeOnLoad
htmx:afterRequest        <-----
htmx:afterOnLoad
htmx:xhr:loadend
htmx:beforeProcessNode
htmx:afterProcessNode
htmx:load
```

**With v1.3.3**
```
(4) htmx:validation:validate
htmx:configRequest
htmx:beforeRequest
htmx:beforeSend
(2) htmx:xhr:loadstart
htmx:xhr:progress
htmx:xhr:loadend
htmx:xhr:progress
htmx:beforeOnLoad
htmx:xhr:loadend
htmx:beforeProcessNode
htmx:afterProcessNode
htmx:load
```

**Comment by 1cg** [comment]
Hi @billmn sorry about that!

Is the form by any chance targeting a parent element?

**Comment by 1cg** [comment]
I bet what is happening is it is an outerHTML swap.  Good guess?

**Comment by 1cg** [comment]
oops, didn't meant to close...

**Comment by billmn** [comment]
Hi @1cg,
I'm not sure on how Sprig works under the hood but I think yes, the form targeting a parent element.

This is the code to include a Sprig component:
```twig
{{ sprig('_components/contactForm') }}
```

This is the Sprig component:
```twig
<form sprig s-method="post" s-action="contact-form/send" s-ext="progress">
    ...
</form>
```

This is the HTML generated by Sprig:
```html
<div
    id="component-qckehn"
    class="sprig-component"
    hx-target="this"
    hx-include="#component-qckehn *"
    hx-trigger="refresh"
    hx-get="index.php?p=actions/sprig/components/render"
    hx-vals="..."
>
    <form sprig="" s-method="post" s-action="contact-form/send" s-ext="progress" hx-vals="..." hx-ext="progress">
        ...
    </form>
</div>
```

**Comment by billmn** [comment]
@1cg Can you reopen this issue please?

The problem was not resolved and the "afterRequest" event is no longer triggered.

PS: My workaround doesn't solve the problem because the "htmx:xhr:loadend" can be called multiple times.

**Comment by 1cg** [comment]
I am working on getting a complete solution for events when elements are removed from the DOM today.

**Comment by 1cg** [comment]
OK, I had to take some time off for work, but I am resuming work on this.  I have what I consider a pretty good solution:

If the element has been removed from the DOM, trigger the event on it as well as the first remaining ancestor in the DOM.  This should handle most situations.  Need to test extensively, but it should be in 1.4.

**Comment by 1cg** [comment]
@billmn Question for you.  Do you expect the DOM to be updated with the new content in the `afterRequest` event?

**Comment by billmn** [comment]
@1cg I don't have much knowledge of how HTMX works behind the scenes.

How did the `afterRequest` event behave in version 1.3.2 and earlier?

**Comment by 1cg** [comment]
earlier we dispatched the event on the element only, but that didn't bubble properly when the element was removed from the DOM

i have updated the code to snapshot the hierarchy before the swap and dispatch the even on the node, and then if the node is no longer in the DOM, on the closest parent pre-swap that is still in the DOM

ugly, but the right thing I think
