### ISSUE TITLE
Set cookie from htmx post?

### ISSUE THREAD

**Issue by traverseda** [bigskysoftware/htmx#446]
I'm working on a particularly finicky and annoying authentication system, which means that I need to do a big part of my authentication flow through ajax. HTMX is almost perfect for this, requiring only a few changes to our existing forms to do 90% of what we need. Well aside from a whole bunch of CSRF-related changes.

Unfortunately I can't figure out any way to take the cookie from the form I'm posting to (using htmx) and set it from the calling page. Is there any way to do that, or will I need to use more traditional ajax?

**Comment by 1cg** [comment]
Hi @traverseda this should work the "normal" way.  htmx is just creating a normal AJAX request, so setting cookies *should* work, so long as there aren't any security issues.

I did just merge a fix to allow for cross site requests to include cookie info.  Is this by chance a cross site request?

**Comment by traverseda** [comment]
Yes, sorry for the lack of detail I've worked with CORS stuff in the past but didn't realize how much the cross-origin cookie system had changed.

This is a cross-origin request. This is for some work on the [glauth-ui](https://github.com/sonicnkt/glauth-ui/issues) project and not my day job. For now I've set it up to use header based authentication but it would still be nice to get this working some time.

**Comment by 1cg** [comment]
I'd have to see the details to be sure, but it sounds like what you probably want to do is trigger an event on the client side using the `HX-Trigger` response header, and then set the cookie manually in javascript on the client side.

**Comment by tschuehly** [comment]
Hello, 

I am currently trying the same thing:

```
response.setHeader("HX-Redirect","/")
response.setHeader("Set-Cookie", "JWT=${resp.accessToken}; Secure; HttpOnly; SameSite=Strict;Max-Age=6000;")
```


```
<form action="/api/user/login" method="post">
    <label>Email:
        <input type="text" name="email" />
    </label>
    <label>Password:
        <input type="password" name="password" />
    </label>
    <button type="submit">Submit</button>
</form>
```

With a normal form submit it works fine, the cookie is set but if I use the same form with a hx-post 
```
<form>
    <label>Email:
        <input type="text" name="email" />
    </label>
    <label>Password:
        <input type="password" name="password" />
    </label>
    <button hx-post="/api/user/login" hx-target="#response" >Submit</button>
</form>
```

The correct response headers are returned but no cookie is set.
![image](https://user-images.githubusercontent.com/33346637/153254921-ec19b9ae-2f21-42ec-822b-d6ca3c505466.png)

It is not a cross origin request.

Thanks for your help
