### ISSUE TITLE
How to copy element content into another element with htmx/hyperscript.

### ISSUE THREAD

**Issue by tonyalaribe** [bigskysoftware/htmx#450]
I have a usecase where I want to copy an element from a template tag into another element. 

I tried 
```
_="on click 
          set #editUserRaw to #editUserRawTmpl.innerHTML then
          remove .hidden from #editUserSlideover" 
```

But get an error
Can only put directly into symbols, not references

          set #editUserRaw to #editUserRawTmpl.innerHTML then
                                                          ^^
                                                          
Am  I doing something wrong? Or does this feature not exist?

**Comment by tonyalaribe** [comment]
While I'm here, is it also expected behaviour that hyperscript statements `_=""` which are defined on elements which are swapped in from the server do not work.? Or is there a way to enable it?

**Comment by 1cg** [comment]
Hi Tony, I think this is an asymmetry between `put` and `set`.  This should work:

```
_="on click 
          put #editUserRawTmpl.innerHTML into #editUserRaw then
          remove .hidden from #editUserSlideover" 
```

set is for setting variables and properties (mainly) where put "puts" stuff into other stuff, like you want here :)

If you are adding HTML dynamically to the DOM (outside of htmx, which is handled automatically) you will need to call `_hyperscript.processNode()` on the new content.  Obviously not ideal, but hyperscript is still pretty young.

**Comment by tonyalaribe** [comment]
Thanks @1cg . I tried your suggestion and it works nicely. 

This is what my code looks like now:
![image](https://user-images.githubusercontent.com/6564482/115459652-98728b80-a227-11eb-9ebe-a52398b1016d.png)

Thanks.
