### ISSUE TITLE
Unable to get hx-trigger="revealed" to work on scroll

### ISSUE THREAD

**Issue by danjac** [bigskysoftware/htmx#453]
Version: htmx@1.3.3. Issue found on latest Firefox and Chrome.

I've been trying to get the hx-trigger="revealed" attribute to work when the element scrolls into view: it only appears to work with the elements loaded immediately.

I have this use case: a list of items each containing a thumbnail. Each thumbnail is generated on the fly on the server, so I want to show a placeholder to be lazily replaced by the thumbnail when the image scrolls into view.

The HTML looks like this:

`<img src="placeholder.png"  hx-trigger="revealed" hx-swap="outerHTML" hx-get="/path/to/thumbnail/">`

The HTML returned from the server looks like this:

`<img src="generated-thumb.png">`

The trigger works, but only for the first *n* images immediately visible in the viewport. As I scroll down, images that come into view are never triggered. The htmx debug extension shows no events being fired for these images. 

Is there something I'm doing wrong here?

**Comment by danjac** [comment]
This appears to be an issue with relying on scroll event rather than the modern IntersectionObserver (presumably because of some requirement to support IE11?). In my case, the scroll event was not triggered when moving down, so nothing happened.

It would be good to document this, and/or provide conditional support for browsers supporting the IntersectionObserver API.

**Comment by danjac** [comment]
For further reference: CSS has this -

```
html {
  overflow: hidden;
}
body {
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
}
```
This prevents the documentElement scroll event from firing when scrolling.

**Comment by 1cg** [comment]
we now support the synthetic `intersect` event, which uses intersection observer: https://htmx.org/docs/#special-events
