### ISSUE TITLE
Support scroll:windowTop and scroll:windowBottom on hx-swap

### ISSUE THREAD

**Issue by dkniffin** [bigskysoftware/htmx#456]
`hx-swap` supports scrolling modifiers to control the scroll behavior after content is swapped in. The two supported values are `show:top` and `scroll:top`, but neither of those seem to scroll to the top of the page. Instead they scroll to show the top of the element and scroll the element overflow to the top, respectively. I would like an option to scroll the viewport all the way to the top (or the bottom).

**Comment by thijskaspers** [comment]
Would be very nice addition indeed!

**Comment by ccchapman** [comment]
This would be useful to have more control over the scroll target: both the element and pixel offset.

In the meantime, the best approach I have found for the sticky position header is:

- `scroll-behavior: smooth;` ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior))
- and, `scroll-margin-top: 175px;` on the `hx-swap` element. ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top))

This has browser support limitations.

**Comment by CaptainPaella** [comment]
If i could specify a scroll 'target id' and scroll 'behaviour', it would be very nice.
`scroll: #someElement smooth`

**Comment by 1cg** [comment]
@CaptainPaella can you test out the version in the `dev` branch and see if it works for you?

Syntax is:
scroll:[optional css selector:](top|bottom)
show:[optional css selector:](top|bottom)

The show option also supports `window` as a valid value to show the top or bottom of the window.

Examples:

```
  <button ... hx-swap="show:#some-button:top">...</button>
  <button ... hx-swap="show:window:top">...</button>
```

**Comment by 1cg** [comment]
will close after some user testing (this stuff doesn't unit test well unfortunately :expressionless: )

**Comment by CaptainPaella** [comment]
Hi,
I tried to get it running locally yesterday, but i failed. 
When i followed the [Htmx Hacking guide](https://github.com/bigskysoftware/htmx/tree/dev#hacking-guide) i got stranded at the step 'npm install'. 
After running 'npm install' in the root, the following error get thrown on my Windows 10 Enterprise PC:

```
error code SELF_SIGNED_CERT_IN_CHAIN
8235 error errno SELF_SIGNED_CERT_IN_CHAIN
8236 error request to https://registry.npmjs.org/debug/-/debug-4.3.1.tgz failed, reason: self signed certificate in certificate chain
```

Will try to google for an solution later this weekend.

**Comment by kunambi** [comment]
> **Any Offset: Javascript Based**
> 
> const STICKY_OFFSET = 160;
> 
> document.addEventListener("htmx:after-swap", (event) => {
>   if (!(event.target instanceof HTMLElement)) {
>     return;
>   }
> 
>   window.scrollTo(0, event.target.offsetTop - STICKY_OFFSET);
> });

Just want to note that with htmx 4.0, the event to listen for is named `htmx:after:settle`.
