### ISSUE TITLE
Add timeout params in htmx.ajax()

### ISSUE THREAD

**Issue by superpikar** [bigskysoftware/htmx#457]
Me and my employer @keyurshah found htmx is very interesting. 

We decide to convert our web from unpoly to htmx. Everything goes well :thumbsup: 
But, now I have a problem with cancel/reject an AJAX request when it reaches a timeout. It seems the current `htmx.ajax()` doesn't have a timeout feature. 

following is my use case :
- call htmx.ajax('/verify-address'), with a timeout 10s
- when it hits the timeout, then it wil call htmx.ajax('/verify-address-timeout')

as a workaround, I use window.setTimeout(), but the problem is I don't have any idea on how to cancel/reject the previous request
```
const formData = htmx.values(formEl);
let verifySuccess = false;
htmx.ajax('GET', `/ajax/postiecustom/verify-address?${CommonHelper.objectToQueryString(formData)}`, '#modals-container')
    .then(() => {
       console.log('validation is shown!');
       verifySuccess = true;
    });

// if verify is not success after timeout (6s)
//    then reject the previous request
//    then request modal timeout
window.setTimeout(() => {
  if (!verifySuccess) {
    // TODO - have to find a way to cancel the previous modalContent
    htmx.ajax('GET', '/ajax/postiecustom/verify-address-timeout', '#modals-container')
    .then(() => {
       console.log('validation timeout is shown!');
    });
  }
}, 6000);
```

this would be handy if htmx.ajax() has timeout params in the future, 
```
htmx.ajax('GET', '/first-request', '#selector', { timeout: 6000 })
    .then(() => {
        console.log('validation is shown!');
    })
    .catch(() => {
        htmx.ajax('GET', '/timeout-request', '#selector')
            .then(() => {
                 console.log('validation timeout is shown!');
            });
    });
```

a similar approach has been implemented in unpoly https://unpoly.com/up.request 
```
up.request('/search', { 
   timeout: 6000, 
   params: { query: 'sunshine' } 
}).then(function(response) {
  console.log('The response text is %o', response.text)
}).catch(function() {
  console.error('The request failed')
})
```

**Comment by 1cg** [comment]
great feature request, I will investigate it.

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/a4a9d2d73372dc00de4d504e564fd5145f1bbda5 will be in the next release of htmx (1.5, probably later this week)
