### ISSUE TITLE
Better support for content negotiation

### ISSUE THREAD

**Issue by akashchopra** [bigskysoftware/htmx#460]
I love the fact that the `hx-headers` attribute makes it trivial to include extra headers in the request. What I want to achieve is to have something like:

`<div hx-get='/report' hx-headers='{"Accept", "application/pdf"}' hx-swap='None'>View as PDF</div>`  and have HTMX determine that the response is not HTML and allow the browser to handle it in the standard manner rather than trying to swap the content in.

I tried using `hx-boost` on a normal link, but that didn't work either - it still swapped the content in. Ideally something like `<a href='/report' hx-boost='true' hx-headers='{"Accept", "application/pdf"}' target='_blank'>View as PDF</a>` would load the PDF in a new tab.

I'm not sure if this issue falls outside of the intended scope of HTMX, or if there is already a way to do this that I haven't found. Thanks!

**Comment by 1cg** [comment]
Hi @akashchopra

Making this work with pure AJAX is a PITA, but you can use `HX-Redirect` to redirect a user to the URL that will download the PDF, and it will work like you want.
