### ISSUE TITLE
Scroll position after hx-push-url and back navigation is incorrect

### ISSUE THREAD

**Issue by gmzu** [bigskysoftware/htmx#461]
The documentation says
> the hx-push-url attribute allows you to "push" a new entry into the browser location bar, which creates a new history entry, allowing back-button and general history navigation. The possible values of this attribute are true, false or a custom string.
> 
> Here is an example:
> 
 ```
<div hx-get="/account" hx-push-url="true">
 Go to My Account
</div>
```
> This will cause htmx to snapshot the current DOM to localStorage and push the URL `/account' into the browser location bar.

The problem is that when you go back, the browser displays the DOM snapshot starting from the top.
This is extremely inconvenient if you are scrolling through a list.
Is there a way to avoid this, and view the snapshot from where it left off?

**Comment by gmzu** [comment]
A possible solution could be to use this hyperscript code on each element of the list that triggers an ajax request (for example a button)
```html
<button hx-get="..." _="on htmx:beforeRequest setAttribute('data-scroll', window.scrollY) end
	       on load get me.getAttribute('data-scroll') if it call window.scroll(0,it) then removeAttribute('data-scroll') end
	    "
></button>
```
On long lists, however, there can be an unpleasant delay in scrolling.
Better or simpler solutions?

**Comment by 1cg** [comment]
We try to scroll to the correct location on history restoration:

https://github.com/bigskysoftware/htmx/blob/f97f825052ac2ab76fc473fa1a7e88abcd043b7e/src/htmx.js#L1577

based on the scroll position at the time the snapshot was taken:

https://github.com/bigskysoftware/htmx/blob/f97f825052ac2ab76fc473fa1a7e88abcd043b7e/src/htmx.js#L1528

It sounds like that isn't working properly for you?

**Comment by gmzu** [comment]
In my case it doesn't work (tested on Chrome, Safari and Firefox).
I solved it using hyperscript code

**Comment by 1cg** [comment]
OK

By and large, going to the top of the replaced content is "good enough" and since you can solve the issue w/ hyperscript I'm going to close this out
