### ISSUE TITLE
Swapping raw text or JSON?

### ISSUE THREAD

**Issue by CrazyPython** [bigskysoftware/htmx#466]
Hi, `htmx-swap` seems to swap directly, without escaping. Some outputs have not been escaped from the server, such as raw text. How do I insert raw text with htmx? Alternatively, how can I insert a JSON value?

**Comment by 1cg** [comment]
Hi James,

htmx expects content from the server to be escaped for insertion into the DOM.  However, if you wish to implement your own swapping mechanism you can do so with a plugin.  There is a client side template extension here that can be used as a basis for whatever sort of swapping logic you'd like:

https://htmx.org/extensions/client-side-templates/
