### ISSUE TITLE
webpack build doesn't work when installed using "npm install"

### ISSUE THREAD

**Issue by dfrankow** [bigskysoftware/htmx#468]
I installed using `npm install htmx --save` and got `+ htmx@0.0.2`.

I use webpack (config too long to include here), and added an `entry` to webpack.config.js:

```
    htmx: './node_modules/htmx/htmx.js',
```

When I run webpack, I get this error:

```
ERROR in ./node_modules/htmx/htmx.js 1:0
Module parse failed: Unexpected character '#' (1:0)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> #!/usr/bin/env node
```

It doesn't like the shebang (#!) at the top. That's not a valid javascript comment character.

If I delete that line, then htmx.js works.

But, cli.js does not. Perhaps I should file a separate issue, but I'll put it below for now. I can see `fs` required in cli.js, but I don't know what it is.

```
ERROR in ./node_modules/htmx/cli.js 2:4-17
Module not found: Error: Can't resolve 'fs' in 'projectroot/node_modules/htmx'
resolve 'fs' in 'projectroot/node_modules/htmx'
  Parsed request is a module
  using description file: projectroot/node_modules/htmx/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      projectroot/node_modules/htmx/node_modules doesn't exist or is not a directory
      projectroot/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in projectroot/node_modules
        single file module
          using description file: projectroot/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              projectroot/node_modules/fs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              projectroot/node_modules/fs.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              projectroot/node_modules/fs.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              projectroot/node_modules/fs.wasm doesn't exist
        projectroot/node_modules/fs doesn't exist
 @ ./node_modules/htmx/htmx.js 52:2-18
```

If it helps, these are the node modules I have with `fs` in them:

```
$ ls -1 -d node_modules/fs*
node_modules/fs.realpath/
node_modules/fsevents/
```

I don't know much about how npm install works, but I think you have to declare a dependency on fs.

**Comment by dfrankow** [comment]
Sadly, I am also not an npm ninja. I'd search for this issue.

**Comment by 1cg** [comment]
I reached out in the discord to see if anyone knows how webpack works.

**Comment by guettli** [comment]
You downloaded this project: https://www.npmjs.com/package/htmx

You want: `https://www.npmjs.com/package/htmx`

**Comment by guettli** [comment]
@dfrankow please close the issue, if this solves your issue. Thank you for using htmx. If you like it, please spread the good news. Thank you.

**Comment by dfrankow** [comment]
This did solve my issue, thanks!

I submitted a PR with a doc change. Maybe I should wait until the PR is merged to close this issue?

**Comment by dfrankow** [comment]
Thanks!
