### ISSUE TITLE
Support `queue` modifier for `hx-trigger` to specify event queuing behavior

### ISSUE THREAD

**Issue by MKxDev** [bigskysoftware/htmx#470]
As a developer, I want to have some control over how multiple requests originating from the same element are handled. Specifically, I want to be able to override request queueing for some elements and let the last one win.

**Rationale:**
Assuming I have a search page with multiple facet filters, where each one triggers an AJAX request. When a user keeps selecting multiple filters before the previous requests complete, each new request appears to be queued and will execute in order, which leads to subpar user experience. Instead, in a case like this, I would like the last request to win and cancel all previous ones originating from the same element.

**Things to consider:**
- Does this need to happen on per-trigger (both element and event) basis or just the element?
- If some requests are parallelized, should we specify the number of parallel requests, independent of browser settings?

**Comment by 1cg** [comment]
Do you mind sharing your code a bit more so I can make sure I address your needs?  I want to make sure I don't add queueing and then it doesn't work for your use case.
