### ISSUE TITLE
Keyup doesn't get triggered from contenteditable divs

### ISSUE THREAD

**Issue by tonyalaribe** [bigskysoftware/htmx#471]
I'm trying to create a contenteditable div that sends it's content to an endpoint when ever the content changes, 
but I can't seem to figure this out.
1. The keyup event doesn't trigger the hx-patch request
2. When I switch to a load event, the hx-patch request is made, but without the content of the div. How can the contend of the div be sent along with the request? 

I control the endpoint, and can make it handle the div content in any form I can get it. Raw div content or as part of json. 

Do you have any ideas? Or is this a supported feature? I imagine I can do this with hyperscript, but hyperscript doesn't support `delay:5s` functionality, to catch the keyup events but only react to the last event in the last 5secs.

```
 <div
        class="border-0 block w-full focus:border-transparent outline-none"
        contenteditable
        placeholder="Add note..."
        oninput="if(this.innerHTML.trim()==='<br>')this.innerHTML=''"
        hx-patch="/d/tasks/{{.task.ID}}/description"
        hx-trigger="keyup changed delay:5s"
      >{{.task.Description}}</div>
```

**Comment by tonyalaribe** [comment]
I tried this with a text input, and it seems to work:
```  <input
    class="text-2xl font-bold col-span-7 text-gray-900 outline-none"
    name="title"
    hx-patch="/d/raw/tasks/{{.task.ID}}/title"
    hx-trigger="keyup changed delay:1s"
    value="{{.task.Title}}"
  />```
  
  The value is sent as a HTTP form request. But I still can't get this to work on a content editable div

**Comment by 1cg** [comment]
Looks like for content editable you want the `input` event:

https://stackoverflow.com/questions/1391278/contenteditable-change-events

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

**Comment by fantasticle** [comment]
I tried around the same thing until I wanted to write a github issue. But it seems like this is already discussed. Will there be any fix for <elem contenteditable="true"> in the future? I'm working with <input> fields now and style them via my CSS framework but I'd rather have everything packed into one htmx element. 

So far really enjoying htmx though!!

**Comment by rdehuyss** [comment]
Leaving a solution as this is the first google result I got:

```html
<span id="contact-search-input" contenteditable="true" style="display: inline-block; width: 100%"
                                  hx-get="/ui/contacts/search"
                                  hx-push-url="false"
                                  hx-trigger="input delay:500ms from:#contact-search-input"
                                  hx-vals="javascript: search:htmx.find('#contact-search-input').innerHTML"
                                  hx-target="#dropdown-menu-contacts-results"
                            ></span>
```

**Comment by perrelet** [comment]
Expanding upon @rdehuyss's solution, here's a couple of further ideas:

1. If you only want a single request, you can simply set `hx-trigger='blur'`.
2. `hx-vals` can be simplified to `hx-vals='js:{search: event.target.innerText}'` avoiding the need for an id.
