### ISSUE TITLE
Have a hx-function attribute that works with hx-trigger

### ISSUE THREAD

**Issue by tonyalaribe** [bigskysoftware/htmx#472]
The hx-trigger system is very powerful and expressive, with support for keybindings/shortcuts(which hyperscript doesn't support). I have had multiple usecases where I want to react to a hx-trigger with a javascript or hyperscript function. If this makes sense with you, I'm happy to look into it and make a pull request.

**Comment by 1cg** [comment]
Hi @tonyalaribe 

I think for this I would be more inclined to increase the expressivity of hyperscript.  

Back during the intercooler.js days, I had `ic-action`: https://intercoolerjs.org/attributes/ic-action.html

and hyperscript was designed to replace that and remove that functionality, which got very elaborate, from the core of htmx, so htmx could stay focused on extending HTML as a hypertext.

That being said, I'm willing to look at examples with you and think about if there is a feature here that stays within the "extending HTML as a hypertext" philosophical position of htmx.

**Comment by 1cg** [comment]
@tonyalaribe I'm going to close this out, but still interested in discussing with you, maybe on discord?  htmx.org/discord
