### ISSUE TITLE
[ Help Want] Can I replace XMLHttpRequest by fetch API?

### ISSUE THREAD

**Issue by kitepad** [bigskysoftware/htmx#473]
I like htmx ideas for my web app. Recently, I'm trying to find solution to develop desktop app with remote backend. I choose sciter (sciter.com) as my desktop app's UI engine.  But latest sciter drop xmlhttprequest instead by fetch api, so I cann't use htmx.
So I want know how to replace all xmlhttprequest usage in htmx? I think (sciter.js + htmx) is best solution for me if htmx can have a fetch api version.

**Comment by matthewblott** [comment]
XMLHttpRequest has a very legacy feel about it now. IE11 will be officially retired by Microsoft in June 2022.

https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/
