### ISSUE TITLE
Add feed for Announcements and Essays

### ISSUE THREAD

**Issue by benjaminoakes** [bigskysoftware/htmx#477]
I found the announcements and essays at https://htmx.org/talk/ and I would like to subscribe to them in a feed reader.  I do not see an RSS or Atom feed either in the HTML or in the GitHub repository.  It looks like you may be using Jekyll, so ideally, this is easy to add.

Thank you for HTMX.  It's a very interesting and refreshing take on web development.

**Comment by 1cg** [comment]
Hi @benjaminoakes 

I've installed an ATOM feed.  I'm using eleventy.js to generate the site.  (It's OK)

Hopefully this addresses your needs.

:beers:
