### ISSUE TITLE
HTTP Header X Prefix

### ISSUE THREAD

**Issue by jon49** [bigskysoftware/htmx#48]
Since you guys are still early on in the rewrite I thought it would be worth while for you to know that the `X` prefix on custom headers is deprecated. Just using `HX` is enough. Not a huge deal, just makes the headers a little cleaner.

See https://www.keycdn.com/support/custom-http-headers#naming-conventions

which references the RFC Spec:

https://tools.ietf.org/html/rfc6648

**Comment by chg20** [comment]
fixed by https://github.com/bigskysoftware/htmx/commit/d01025823eb7b4800b1a712c14b29c460ca378d0
