### ISSUE TITLE
Disable inheritance for a child element

### ISSUE THREAD

**Issue by TwiceII** [bigskysoftware/htmx#483]
I have a form with some "hx-" attributes on it, that I would like to prevent running for some links inside of it. 
I have global "hx-boost" activated on body, and would like all anchor links to work as expected by hx-boost, not with overriden logic in parent elements.
Is there an explicit way to turn-off inheritance for some elements?

**Comment by 1cg** [comment]
Can you give me some concrete examples?  That will help me formulate the right approach to your problem.

Thank you!

**Comment by mattburton** [comment]
Came here to see if this had been requested - the use case I just ran into was an editable grid type of scenario - table row has an `hx-delete` triggered by the delete key if it's in focus, with an `hx-confirm` set. One of the row cells contains a quantity field which updates server via `hx-put` whenever the value is changed. Without specifying `hx-confirm` on the quantity input the parent `hx-confirm` is used, and I'd like to avoid having a confirmation box pop up for the quantity update. While it would be great if there was an `hx-disable-inheritance` or similar that I could place on a parent element another option might be to support `hx-confirm="null"` or something along those lines to be able to cancel it out.

HTH - thanks!

Just wanted to say as well while I'm here, long time Intercooler user - first time around with HTMX - going very smoothly so far - great job!

**Comment by 1cg** [comment]
next release will support the `unset` value for attributes to "unset" them (taken from CSS):

https://github.com/bigskysoftware/htmx/blob/dev/src/htmx.js#L131

**Comment by mattburton** [comment]
Excellent - great choice with `unset` as well - will make it very clear what the intention is. Thanks for the quick turnaround - most appreciated!
