### ISSUE TITLE
HTML <title> is not restored with back button

### ISSUE THREAD

**Issue by danjac** [bigskysoftware/htmx#484]
When using hx-boost or hx-push-url it appears that the <title> is not restored to the original state.

For example a link might have:`

`<a hx-get="/next" hx-target="#content" hx-push-url="true">..</a>
`

The current title is "Current"

The HTML fragment returned from the server:
```

<div id="content">next page</div>
<title>Next</title>
```

When the user clicks on the link, the text "Next" is inserted into document.title.

However, when clicking the back button, after navigating back to the original page, the title remains as "Next" instead of "Current".

**Comment by 1cg** [comment]
Can you reproduce the issue in `test/manual`?

The code looks right for this.

**Comment by 1cg** [comment]
closing pending feedback

**Comment by domchristie** [comment]
I have also run into this issue.

If I'm understanding the code correctly, `restoreHistory` handles `<title>` restorations but does so by referencing `fragment.title`:

https://github.com/bigskysoftware/htmx/blob/7ce7b4878b328b3897d08eaaaaffa24d17881ab9/src/htmx.js#L3166

Cached history fragments do not contain the full document and so `fragment.title` is blank. However the `cached` record includes the title, and so can be correctly restored with `cached.title`.

I'd be happy to open a PR for this after approval.
