### ISSUE TITLE
Input array not send empty fields

### ISSUE THREAD

**Issue by hitaloramon** [bigskysoftware/htmx#487]
Hello, I have a form where it has additional multifield and I use the name of the input to transform it into an array and receive it in the backend with PHP, something like:

`<input type = "text" name="subject[]">`

It turns out that as I can have several of these and the fields are optional, HTMX only sends those that are filled, ignoring the fields that are empty and this ends up generating the server-side matrix in the wrong way. With JQuery Ajax works correctly, is there any way to resolve this?

https://www.php.net/manual/en/faq.html.php#faq.html.arrays

**Comment by hitaloramon** [comment]
@1cg can you help me with this problem?

**Comment by 1cg** [comment]
htmx does it the "normal" way: unchecked checkboxes are ignored.  Some frameworks such as rails work around this by including a hidden version of the input too, but I don't think we should support server-side specific needs.

**Comment by bluekeyes** [comment]
I'm also running in to this issue, which I believe impacts all input types (I'm using `type="text"`), not only checkboxes - I too have a list of optional fields and want to receive empty values when the form is submitted for the inputs that have empty values.

You can see the difference between native and htmx handling here: https://jsfiddle.net/sjzypx9e/

I've submitted #1144 to fix this, which does the right thing in my application.

**Comment by 1cg** [comment]
thank you for your contribution @bluekeyes !
