### ISSUE TITLE
how to handle 404, 500 from api and display custom error messages?

### ISSUE THREAD

**Issue by darcwader** [bigskysoftware/htmx#494]
```
  <button hx-post="/clicked" hx-swap="outerHTML">
    Click Me
  </button>
```

in the above snipped. i would like to handle by displaying an error message for error cases.

- incase of error saving the form. show error connecting to server.
- incase server sends 500 say error internal server error
- incase of timeout show timeout calling server.

i've tried sample to just show templates, i understand sending template for error for validation is the approach, but i am trying to handle cases when server is not accessible. or if url has changed.

i know i have to use https://htmx.org/events/#htmx:responseError . how do i use it?

**Comment by paxperscientiam** [comment]
Not sure about that property, but thing i do for situations where I do have control is to send the right partial and desired HTTP code for a given scenario.

```
try {
  if (new Service()-> response->sucess) {
    echo partialLoader("partial", $data);
  } 
} catch (Exception $e) {
   http_response_code(500);
   echo partialLoader("partial_500", []);
}
```

The above is PHP/pseudo. I hope it's clear enough!

**Comment by 1cg** [comment]
thank you @paxperscientiam !  That's the right thing!

**Comment by jeanmonet** [comment]
Here's a basic approach I went for (maybe can be improved?):

```html
<div id="errormessages">
</div>

<script>
   htmx.on("htmx:responseError", function(evt) {
     var errdiv = document.getElementById("errormessages");
     errdiv.innerHTML = `
        <div id="errormessagealert" class="container mt-3 mb-3 alert alert-danger" role="alert">
            <h4>Request Error: ` + evt.detail.xhr.status + `
                <span style="float:right;"><a onclick="errormessagealert_off()">Close [X]</a></span>
            </h4>
            <code>` + evt.detail.xhr.responseText + `</code>
        </div>`;
     errormessagealert_on();
   });

  function errormessagealert_on() {
    document.getElementById("errormessagealert").style.display = "block";
  }

  function errormessagealert_off() {
    document.getElementById("errormessagealert").style.display = "none";
  }
</script>

<style>
  #errormessagealert {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    -ms-transform: translate(-50%,-50%);
    display: none; /* Hidden by default */
    background-color: rgba(0,0,0,0.8); /* Black background with opacity */
    z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
  }
</style>

```

**Comment by 1cg** [comment]
that looks like an excellent idea to try out in an extension!

**Comment by siefca** [comment]
https://github.com/bigskysoftware/htmx/pull/1436

Good Night! :)

**Comment by siefca** [comment]
Updated the request with tests for `response-targets`. Tests are passing.
