### ISSUE TITLE
IE11 support violation: `Array.prototype.includes`

### ISSUE THREAD

**Issue by paxperscientiam** [bigskysoftware/htmx#495]
`Array.prototype.includes` is an ES6 feature that, according to caniuse.com, is not supported by IE11. 

This method is used here: https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1106

I'm working on a PR for integrating typechecking with typescript interpreted JSDoc comments; that's how I found the above issue.

EDIT: My assumption here is that the readme is accurate in that `htmx` is still meant to support IE11, right?

**Comment by 1cg** [comment]
yes, that's an error and we should fix it, thank you!

**Comment by 1cg** [comment]
fixed in dev, not a huge deal since it is in websocket code anyway, but thank you!
