### ISSUE TITLE
Docs: swap:1s

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#498]
https://htmx.org/attributes/hx-swap/

```
Timing: swap & settle
You can modify the amount of time that htmx will wait after receiving a response to swap the content by including a swap modifier:

  <!-- this will wait 1s before doing the swap after it is received -->
  <div hx-get="/example" hx-swap="innerHTML swap:1s">Get Some HTML & Append It</div>
```

I think the docs should be extended to answer this question:

Imagine the request to `/example` takes 3 seconds. Does htmx wait 1 second now, that the overall wait time is 4 seconds?

Or does htmx ensure that the waiting time is not less than 1 second?

My wish: if the user already waited 3 seconds, I don't want him to wait one additional second.

**Comment by 1cg** [comment]
Right now it will queue the next request and issue it immediately when the previous request finishes.
