### ISSUE TITLE
Add htmx to tags for this project.

### ISSUE THREAD

**Issue by wiverson** [bigskysoftware/htmx#502]
Would make it easier to find other project that already have the htmx label.

**Comment by guettli** [comment]
You mean the github label? Yes, sounds good.

**Comment by wiverson** [comment]
Yup.

This is the easiest GitHub issue I've ever posted, lol.

**Comment by 1cg** [comment]
lol what do I do?

**Comment by wiverson** [comment]
On home page for project on GitHub in the upper-right next to About you should see a gear. Click that and you should see a dialog "Edit repository details". Under topics add "htmx" and save changes.

Might as well add htmx and hyperscript to both the htmx and hyperscript repos while you're at it. :)

**Comment by 1cg** [comment]
I think I have accomplished this task :expressionless:
