### ISSUE TITLE
Docs: hx-trigger: How to trigger via JS?

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#505]
I am missing some docs on this page: https://htmx.org/attributes/hx-trigger/

How to trigger the htmx-request of an element via JavaScript?

I looked at [ajax()](https://htmx.org/api/#ajax) and [trigger()](https://htmx.org/api/#trigger)

ajax() needs an URL. That's not what I want, the URL is already in hx-get/hx-post.

trigger() needs an event-type. Hmm, is this needed?

**Comment by paxperscientiam** [comment]
Depends on what you're trying to do. There is a great extension included called hx-path-deps. Given some modifying request (POST, PUT), it could trigger related elements with hx-get attribute.

**Comment by OmenApps** [comment]
This is something I went digging for today and found what I needed in the discord search. Here's a contrived example that might be useful for the docs. Once the page is fully loaded (using jquery's document ready function), it triggers `#objectDetail` div with the `pageLoaded` event to load up the contents of "/initial-content/":

```html
<div id="objectDetail"
    hx-get="/initial-content/"
    hx-swap="innerHTML"
    hx-trigger="pageLoaded"
    placeholder="Loading..." />
</div>


<script>
    $(document).ready(function() {
        htmx.trigger("#objectDetail", "pageLoaded")
    });
</script>script>
```
