### ISSUE TITLE
Is there any listing of thirdparties?

### ISSUE THREAD

**Issue by idlesign** [bigskysoftware/htmx#510]
Hi,

I didn't find any page on site with a list of thirdparty projects making use of `htmx`.
It could be useful when one needs to find a ready solution for some web-framework for example.
Is there anything like that? 

I've just published https://github.com/idlesign/django-siteajax — a pluggable Django app using `htmx` on client side.
I know there are also https://github.com/nonZero/django-js-lib-htmx and https://github.com/adamchainz/django-htmx
Those could be added to such a list.

**Comment by 1cg** [comment]
we now have a section on server-side examples:

https://dev.htmx.org/server-examples/
