### ISSUE TITLE
Flag Attributes without including "true"

### ISSUE THREAD

**Issue by jon49** [bigskysoftware/htmx#52]
Attributes like `hx-boost` have to have `="true"` would it be possible to have them without a value? Not a huge deal. I just thought it would be a little cleaner. I imagine there is a reason to include the `true` value but I didn't see it in the issues.

Thanks everyone for the work on this. I'm excited to use this library on my next project!

**Comment by chg20** [comment]
that's a reasonable change, I'll try to get it in for the next release

**Comment by 1cg** [comment]
i investigated this and it turned out to be surprisingly hard, so I'm closing this out for now.
