### ISSUE TITLE
How to reconnect to SSE (Server Sent Events)

### ISSUE THREAD

**Issue by vlcinsky** [bigskysoftware/htmx#522]
Scenarios similar to #148 may occur - server is restarted or connection is temporarily lost and the page looses contact with a stream of events provided via SSE.

There are some clients (e.g. https://pypi.org/project/sseclient/) which handle lost connection properly.

It would be great to have such an option at htmx too (or some workaround handling the event of lost connection).

I have tested SSE with FastAPI and htmx at https://github.com/vlcinsky/fastapi-sse-htmx

**Comment by 1cg** [comment]
@benpate any thoughts on this one?

**Comment by benpate** [comment]
Yes. I think htmx can do more here. While SSE is *supposed* to reconnect automatically, we account for some edge cases in hyperscript, but now htmx. 

I'd love to pull this back to htmx. I'm super swamped right now (moving+renovations) and am not above begging for help. If you're interested/able to make a pull request, I'll help out with testing. If not, I'll put this on my backlog and make an update once things settle down.

**Comment by benpate** [comment]
Quick update -- the new SSE extension DOES add the same reconnect logic that we're using in hyperscript.  So this should be available when it gets released.  We're working on the best migration plan for SSE and WS right now and should have something to share very soon.
