### ISSUE TITLE
Does the element specified in hx-target need to be the parent element ?

### ISSUE THREAD

**Issue by Fyp89** [bigskysoftware/htmx#524]
Scenario A:

```
<div class="panel-body" id="manual-duplicates">
       <input hidden class="checkbox-player" hx-get="/ajax/duplicates/detect/?ids=1" hx-trigger="click" hx-target="#manual- 
                 duplicates" type="button" id="checkbox-tst" >
</div>

```
Scenario B:
```
<div class="panel-body" id="manual-duplicates">
       
</div>
```
some more elements...
```
<div>
<input hidden class="checkbox-player" hx-get="/ajax/duplicates/detect/?ids=1" hx-trigger="click" hx-target="#manual- 
                 duplicates" type="button" id="checkbox-tst" >
 </div>
```

Scenario A works and Scenario B doesn't.

I am assuming it is because the target element isn't a parent element . Just wanted to confirm if this is the case as the docs suggest otherwise.

> The hx-target attribute allows you to target a different element for swapping than the one issuing the AJAX request. The value of this attribute can be:
> 
> a CSS query selector of the element to target

**Comment by 1cg** [comment]
the target does not need to be a parent element.  I suspect the problem there is that the attribute value is broken over multiple lines.
