### ISSUE TITLE
Support Page Visibility API

### ISSUE THREAD

**Issue by adamchainz** [bigskysoftware/htmx#525]
I wanted to create an element that fetches whenever the tab comes into focus, as detectable with [the page visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). I tried:

```
hx-trigger="visibilitychange[visibilityState === 'visible'] from:document"
```

but this did not seem to work, since `document` is not a valid CSS selector.

Supporting `from:document` or similar might be all that's needed to support this API, but it strikes me as something that htmx could abstract a little.

It could be useful to have virtual events for "tab became visible" and "tab became hidden". Then the repetitive filter `[visibilityState === 'visible']` could be avoided, and the events could work when `allowEval` is `false`.

Also there could be event modifiers for tab visible / tab hidden, so we could specify "poll only while the tab is visible". Polling only while visible would even make a sensible default...

**Comment by 1cg** [comment]
seems like a great idea to me

could be a simple as adding a special case for `document` here:

https://github.com/bigskysoftware/htmx/blob/c7bde5ad2587a53c5be3369803232757e4fdbfb8/src/htmx.js#L292

are you interested in making this change?  I can show you how to write tests, etc. for it...

**Comment by 1cg** [comment]
I just added syntax for filtering polls:

https://github.com/bigskysoftware/htmx/commit/40ed7b08271149085b478e8f9935e9c33dafa3d4

And it looks like the `Document.hidden` API could be used for this:

https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden

With that, can I close this?

**Comment by adamchainz** [comment]
That doesn't quite allow making a request as soon as the tab gains focus, which would be useful for infrequently polled items.

Maybe the best solution is a little JS to fire custom events?

**Comment by 1cg** [comment]
OK, I set it up so you can listen `from:document` now, so you can listen for the `visibilitychange` event on it, that seems like it would let you specify pretty much what you want

https://github.com/bigskysoftware/htmx/commit/bbf2ae44125e1cc404d6108f043a175268df86da

**Comment by adamchainz** [comment]
I can confirm this is working now in 1.5.0, with the syntax: `hx-trigger="visibilitychange[document.visibilityState === 'visible'] from:document"` 🥳

**Comment by jedie** [comment]
This this should be added as a example in the docs, isn'it ?
