### ISSUE TITLE
I want to add some usage examples, but have a question

### ISSUE THREAD

**Issue by paxperscientiam** [bigskysoftware/htmx#530]
OK, so I'd like to add some usage examples for the awesome `htmx`. Lately, I've been working on how to structure an htmx project to handle a client without javascript.

I put together the following functional [example](https://github.com/paxperscientiam/htmx-examples/blob/master/http/fallbacks/form.html):
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <title>Document</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../../node_modules/basscss/css/basscss.min.css" type="text/css" media="screen" />
        <script type="text/javascript" src="../../node_modules/htmx.org/dist/htmx.min.js"></script>
    </head>
    <body>
        <h1>Form fallback example</h1>

        <form action="partials/date-nojs.html"
              method="GET"
              target="form-response"
              style="min-height: 128px" class="border"
              hx-target="#form-response"
              hx-get="partials/date.html">
            <button type="submit">get date</button>
        </form>
        <h2>output</h2>
        <div id="form-response">
        </div>
        <iframe frameborder="0" src="" name="form-response"></iframe>
    </body>
</html>
```

My question is this: is it a principle of htmx to **ignore** standard `<form/>` attributes? If so, that makes it easy to code with no-js fallback in mind. It certainly appears to be the case as the above does work.

**Comment by 1cg** [comment]
Yes, htmx will ignore the standard attributes on your form.

If you use `hx-boost` it will use those attributes as the default values, but you can override them as well.

Thank you for any docs you can contribute!
