### ISSUE TITLE
Docs: `rails-method` extension - link from docs gives a 404

### ISSUE THREAD

**Issue by keybits** [bigskysoftware/htmx#531]
Clicking the link for the `rails-method` extension on https://htmx.org/extensions/#reference currently gives a 404.

**Comment by 1cg** [comment]
thank you, that extension has been made obsolete in modern versions of rails so it has been removed.

I removed the entry in the table...

**Comment by dkniffin** [comment]
@1cg I know this is an old issue, but do you have a source for that being obsolete? I'm 99% sure it's still used. I'm running a Rails 7 app and I have definitely seen `_method` in my app.
