### ISSUE TITLE
event filters did not work with `every` trigger

### ISSUE THREAD

**Issue by strayge** [bigskysoftware/htmx#532]
In case filter specified after timeout
```html
<div hx-get="/rand" hx-trigger="every 3s[false]">
```
raised error after 1 second
```js
htmx.js:209 Uncaught TypeError: Cannot read property 'htmx-internal-data' of undefined
    at getInternalData (htmx.js:209)
    at issueAjaxRequest (htmx.js:2101)
    at htmx.js:926
```

With filter right after `every` keyword
```html
<div hx-get="/rand" hx-trigger="every[true] 3s">
```
trigger not work at all.

Same url with `click` trigger works as expected:
```html
<div hx-get="/rand" hx-trigger="click[true]">
```

**Comment by 1cg** [comment]
Fixed with https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden#Browser_compatibility

syntax is

`every 3s [true]`

not great, but it works.

**Comment by strayge** [comment]
@1cg it does not work for me.
```html
<div hx-get="/rand" hx-trigger="every 5s [false]">
```
still triggers every 5 second with js from [master](https://github.com/bigskysoftware/htmx/blob/5a65b6b36e19e9a54d3f51741a732bbe17dc736b/src/htmx.js)

**Comment by 1cg** [comment]
fix is in the dev branch

**Comment by strayge** [comment]
same behavior with [js from dev branch](https://github.com/bigskysoftware/htmx/blob/0eeb922a1edb5ed02c6954b2598755c4731b3c44/src/htmx.js)
```js
hx-trigger="every 5s [false]"
```
triggers every 5 secs

**Comment by 1cg** [comment]
I wasn't consuming white space after the `3s` should be fixed in dev now (with a manual test)

/// big sky software ///

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by strayge** [comment]
thx, now works
