### ISSUE TITLE
Option to add new url param to current ones

### ISSUE THREAD

**Issue by strayge** [bigskysoftware/htmx#533]
## Problem

I have page with some url params, like `/test?p1=123&p2=456`.

There is no easy option to call same url with additional param:
```
/test?p1=123&p2=456&call_param=789
```
or other endpoint with same params:
```
/test/new_endpoint?p1=123&p2=456
```

## Current attributes

With `hx-vals='{"call_param":789}'` I lose all current params,  
`hx-params="*"` change nothing at this case.

Am I missed something?

## Workaround

My current workaround very ugly:
```html
<div 
hx-get="#" 
hx-trigger="click" 
hx-vals='javascript:{...Object.fromEntries(new URL(window.location).searchParams),...{"call_param":789}}'>
```

**Comment by 1cg** [comment]
can you try

```html
<div 
hx-get="" 
hx-trigger="click" 
hx-vals='{"call_param":789}'>
```
That should pass through all the current parameters

**Comment by strayge** [comment]
@1cg empty `hx-get` works, thanks for suggestion.
