### ISSUE TITLE
HACKING.md would be great

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#537]
It would be great if there would be some docs about how to create a nice pull-request.

I am looking at the htmx/test directory and I have no clue.

I would like to extend hx-include (#536), and of course I would like to write a test for this change.

A file HACKING.md or somethind similar would be great.

Thank you for this great library!

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/commit/f341013264d2f906da16844b7ac58cfd4b342ff1
