### ISSUE TITLE
Unminified Sinon  on the examples pages

### ISSUE THREAD

**Issue by kirjs** [bigskysoftware/htmx#539]
For some reason there's a half megabyte unminified sinon library on the examples page, e.g.
https://htmx.org/examples/delete-row/

I couldn't find any use for it. 

It probably should be deleted, or at least a minified version should be used.

**Comment by 1cg** [comment]
We use sinon to mock out our server requests.  I can't find a good minimized version on the CDNs.  :expressionless: 

At some point I'd like to undo that dependency, because it's a huge library and we use only a small fraction of it, but not right now.

**Comment by gitslav** [comment]
@1cg  there are versions on the Cloudflare CDN:
https://cdnjs.com/libraries/sinon.js
