### ISSUE TITLE
Support for GraphQL

### ISSUE THREAD

**Issue by ravensnowbird** [bigskysoftware/htmx#540]
Hi Team, I would like to know if we can add support for Graphql something like "/graphql?query={}" in place of REST Url.

**Comment by 1cg** [comment]
What would this look like beyond what is already there?  You can use whatever sort of URL you'd like in an `hx-get` attribute, for example.

Can you give me more details on what you are looking for?

**Comment by 1cg** [comment]
closing out for now until more info is received.  Generally, htmx should support GraphQL-style URLs
