### ISSUE TITLE
Feature Policy: Skipping unsupported feature name

### ISSUE THREAD

**Issue by ljfreelancer88** [bigskysoftware/htmx#541]
Hi, using `hx-boost="true"` seems not working in YouTube Iframe. I have seen the following warning below in Firefox console. It's working fine in Chrome.
```
Feature Policy: Skipping unsupported feature name "passive".
Feature Policy: Skipping unsupported feature name "accelerometer".
Feature Policy: Skipping unsupported feature name "autoplay".
Feature Policy: Skipping unsupported feature name "clipboard-write".
Feature Policy: Skipping unsupported feature name "gyroscope". 
Feature Policy: Skipping unsupported feature name "picture-in-picture". 
```

**Comment by 1cg** [comment]
Can you give me more details on this?  A high level layout of the HTML?  htmx can't process content within iFrames due to security constraints, but I'd like to see what you are trying to do.

**Comment by 1cg** [comment]
closing pending more information
