### ISSUE TITLE
Exception at line 209: Cannot read property 'htmx-internal-data' of undefined

### ISSUE THREAD

**Issue by derteufelqwe** [bigskysoftware/htmx#542]
**Description**
Using the trigger `hx-trigger: 'every 1s` will crash htmx when the server takes longer than 1 seconds to return a response. Option `queue:none` doesn't change anything.
Tested on version 1.4.1 and 1.4.0

**How to reproduce the error**
Create a div like this
```
<div hx-get="the-url" hx-trigger="every 1s queue:none">
</div>
```
And make sure the webserver takes longer than 1s to return a response on url `the-url`.

**Expected behaviour**
HTMX waits until the server responds

**Actual behaviour**
HTMX crashes with the following exception
```
Uncaught TypeError: Cannot read property 'htmx-internal-data' of undefined
    at getInternalData (htmx.js:209)
    at issueAjaxRequest (htmx.js:2101)
    at htmx.js:926

getInternalData @ htmx.js:209
issueAjaxRequest @ htmx.js:2101
(anonymous) @ htmx.js:926
setTimeout (async)
processPolling @ htmx.js:924
(anonymous) @ htmx.js:1363
(anonymous) @ htmx.js:1334
forEach @ htmx.js:229
processVerbs @ htmx.js:1328
initNode @ htmx.js:1424
(anonymous) @ htmx.js:1446
forEach @ htmx.js:229
processNode @ htmx.js:1446
(anonymous) @ htmx.js:2557
```

**Comment by 1cg** [comment]
fixed (as a side effect) in https://github.com/bigskysoftware/htmx/commit/40ed7b08271149085b478e8f9935e9c33dafa3d4
