### ISSUE TITLE
Add OpenAPI support and operation chains

### ISSUE THREAD

**Issue by lorddaedra** [bigskysoftware/htmx#543]
I would like to use htmx with OpenAPI based backend server (for example, based on Django with DRF or FastAPI).

I can't change server-side code (for example, I don't own it or respect OpenAPI rules and would like to keep compatibility for other integrations), so, for example, I can't add any redirect headers or change return status codes on server side.

Can I still use htmx in this setup?.. 

Can you give example code, please?..

Task: Send DELETE request to /collection/123 on delete button click. On success (returned server status code == 200 or 204): redirect to <url> (some well-known url, stored on client-side in js const). On error: reload "messages" div (send get request to /messages and replace block html content). 
(It's okay for me to use JavaScript in combination with hx-delete="/collection/123" and do some event processing, I'm looking for some code examples. It can be long operation chain, started from htmx event. I would like to manage other htmx operations using js too. In current case: htmx delete -> listen some event (which one?) and run js code -> (on error) trigger element with hx-swap to reload errors block.)

P.S. I would like to find way to create MVPs of products with htmx and OpenAPI backends. I think in this case I can write less JS code and create MVP faster. But I do not need Hyperscript as JavaScript replacement for that case because of I would like to replace htmx to Vue.js later on next step, I just do not want to use Vue.js from start (because of KISS and time to market).

**Comment by 1cg** [comment]
Hi There,

This isn't a good place for issues like this because it requires familiarity with OpenAPI, which I don't have.  Can you jump on the discord and ask your question?  You'll be more likely to find someone familiar with your tech stack there.
