### ISSUE TITLE
Feature Request: hx-done and hx-error

### ISSUE THREAD

**Issue by kimsuarez** [bigskysoftware/htmx#547]
hx-indicator is great and all, but what it would actually way more useful (for self saving forms) is a hx-done and hx-error that adds a class htmx-done / htmx-error to the given element (and removes the opposite if it exists) when the request is done without fuzz.

**Comment by 1cg** [comment]
Can you flesh this out a bit more?

**Comment by kimsuarez** [comment]
Sure. It should just work like hx-indicator as in setting a css class on an element, just for a different event. hx-done would set class htmx-done when the request is done without errors and remove it after a given duration (the removing part is just a nice to have, it could be done with pure css if necessary, it would be necessary to remove the class before adding it again though). In the example of an auto-save form/input the input would become green and fade out after a specified duration. hx-error would set htmx-error when the request comes back with an error code. In the example example of an auto-save form/input the input would become red and stay red. hx-done should remove the class htmx-error, hx-error should remove the class htmx-done. (this is useful when hx-done and hx-error point to the same element) In the example of an auto-save form/input both hx-done and hx-error would point to the same element (the input itself). I have these auto-save inputs all over the place with an ungodly amount of supporting javascript. It would be the perfect use case to introduce htmx to the projects that use the auto-save features.

**Comment by markbaird** [comment]
Something like this that would allow us to toggle an error message display, without having to catch `htmx:responseError` events and handle them manually, is definitely needed.

**Comment by 1cg** [comment]
I would like to see this as an extension first, then we can consider pulling it into the core.
