### ISSUE TITLE
Add htmx.version

### ISSUE THREAD

**Issue by carltongibson** [bigskysoftware/htmx#548]
Hi. Thanks for the awesome library! 

For debugging it's very handy to be able to pop open the console and do a (in this case) `htmx.version` to see exactly what got loaded into the page. 

That doesn't currently work with `htmx` but it would be nice if it did.

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/3dbf6dba4cdb7b9a9f3e9542cb33c5f412052f76

**Comment by carltongibson** [comment]
Super. Thanks. 🥳
