### ISSUE TITLE
Multiple trigger options for HTMX?

### ISSUE THREAD

**Issue by irahorecka** [bigskysoftware/htmx#554]
I'm wondering if it's possible to enable multiple trigger options for HTMX (using v1.5.0). What I want to do is to trigger HTMX on either content change or page load. So far, if I include both trigger types in hx-trigger, only the first trigger is executed; so in the example below, HTMX is triggered only upon content change.

```html
<select name="area" id="area" hx-post="/api/area" hx-trigger="change load" hx-target="#neighborhood" class="block">
  <option>eby</option>
  <option>nby</option>
  <option>pen</option>
  <option>sfc</option>
  <option>scz</option>
  <option>sby</option>
</select>
```

**Comment by 1cg** [comment]
You can comma separate them: 

https://htmx.org/attributes/hx-trigger/
