### ISSUE TITLE
Docs: modern browsers build?

### ISSUE THREAD

**Issue by lkraav** [bigskysoftware/htmx#556]
Hi. If we have no need for IE11 compatibility, can we shed some payload and configure ES6 build easily? Could this be described directly in README?

https://github.com/bigskysoftware/htmx/issues?q=IE11 doesn't seem to reveal this discussed thus far.

**Comment by 1cg** [comment]
We haven't discussed this yet.  I expect to potentially drop IE support at some point in 2022 or later, if we do.
