### ISSUE TITLE
script repeated Xtimes

### ISSUE THREAD

**Issue by constantinjoly** [bigskysoftware/htmx#557]
Hello,
please be indulgent if my question is silly, but I'm not very comfortable with JS. 

I am doing some tests with HTMX, and I can see the script i use is repeated several times: In this case 3times at the fisrt load (correspond to the nbr of elements modified by the script), then 13times at each page change. (the 2 pages have the same content, 13 elements)

the number of repetitions seems to correspond to the number of elements in the body. I'm not sure how to interpret this message. I imagine this is normal, and I was wondering if it was better to wrap all body's elements in a div for example to avoid these repetitions?

I only use the attribute hx-boost in the demo.

```
changeColor = null;

init = () => {

  // exemple
    changeColor = () => {
        console.log('something');
        const elems = document.querySelectorAll('p');
        for (const elem of elems) {
          elem.style.color = 'red';
        }
      }; changeColor();     

      // other stuff..
}


htmx.on('htmx:load', (evt) => {
      init();      
});

htmx.on('htmx:beforeHistorySave', (evt) => {
    changeColor = null;
});

// htmx.logAll();
```

I did a little demo, if anyone wants to inform me about it, I thank him in advance.

https://angry-perlman-5aba34.netlify.app/

**Comment by 1cg** [comment]
Hi there,

If we swap new content into an element, we are going to call `htmx:load` for each element of content inserted into the element, which is why you are likely seeing the repetition.
