### ISSUE TITLE
External scripts are ignored when using hx-boost

### ISSUE THREAD

**Issue by xvello** [bigskysoftware/htmx#559]
Hello,

I am using `<body hx-boost="true">` for progressive enhancement of a server-side-rendered website. While it works great, I ran into an issue for a page that has progressive enhancement on a form. I defined JS functions in an inline script in the page, and use them as `onclick` callbacks works great.

To reduce the size of the pages, I moved these functions to a js file, linked via a `<script src="my.js"></script>`. While this works if you directly load the page, it fails to load if you start at the index page and navigate to it via boosted links. When it fails, reloading the page (bypassing the boost) makes it work. Moving the `script` element to the head didn't help either.

- Here is a reproduction case for this bug: [htmx-bug.zip](https://github.com/bigskysoftware/htmx/files/6874019/htmx-bug.zip). hx-boost does not work on `file://`, so I ran `python3 -m http.server` to serve it easily.
- Here is the website's [main template](https://github.com/xvello/letsblockit/blob/main/data/pages/_layout.handlebars) enabling boost, and [the commit](https://github.com/xvello/letsblockit/commit/b1520c744f19905f0e4dd31f3eee54d8017c7ac1#diff-1e42ed68dae04a6c8d9f418f6c0902f4f61af94334866188c882329b23dd31a9) that tried moving the JS to an external file.

I would expect the external JS to be detected and imported when the page is swapped, using the browser's cache to avoid repeated downloads.

**Comment by xvello** [comment]
After checking the open issues a second time, it looks like this might be a duplicate of https://github.com/bigskysoftware/htmx/issues/379. Hopefully the reproduction case will be helpful to get to the bottom of it?

**Comment by 1cg** [comment]
Yes, this is a dup of #379 will comment over there.

**Comment by 1cg** [comment]
Fix ready for next release: 

https://github.com/bigskysoftware/htmx/commit/60a67179941b98132ac577abf1b42ea030231b65

**Comment by xvello** [comment]
Thank you so much @1cg, your work is very appreciated :bow:
