### ISSUE TITLE
Docs (at least) should refer to HTTP "methods", not "verbs"

### ISSUE THREAD

**Issue by MikeRalphson** [bigskysoftware/htmx#56]
The wikipedia article linked to https://en.wikipedia.org/wiki/HTTP_Verbs redirects to https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods and itself states:

> HTTP defines methods (sometimes referred to as verbs, but nowhere in the specification does it mention verb, nor is OPTIONS or HEAD a verb) ...

**Comment by chg20** [comment]
I like the informal "verb" and have always used it, when talking about the REST methods that htmx and intercooler provide.  Just the way I talk, I guess.
