### ISSUE TITLE
Are extensions included?

### ISSUE THREAD

**Issue by speg** [bigskysoftware/htmx#563]
Hi! 

Loving HTMX. Trying to use an extension. Everything in the docs says they are several "included." But... when I try the sample code:

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Preload</title>
</head>
<body hx-ext="preload">
    <h1>What Works</h2>
    <a href="/server/1" preload="mouseover">WILL BE requested using a standard XMLHttpRequest() and default options (below)</a>
    <button hx-get="/server/2" preload>WILL BE requested with additional htmx headers.</button>

    <h1>What WILL NOT WORK</h1>
    <a href="/server/3">WILL NOT be preloaded because it does not have an explicit "preload" attribute</a>
    <a hx-post="/server/4" preload>WILL NOT be preloaded because it is an HX-POST transaction.</a>
	 <script src="https://unpkg.com/htmx.org@1.5.0"></script>
</body>
</html>
```

Nothing happens. I looked through the source, and I don't any mention of "preload"...

```bash
curl -s https://unpkg.com/htmx.org@1.5.0/dist/htmx.min.js | grep preload || echo "No preload here."
No preload here.
```

I see the `ext` folder with in `https://unpkg.com/htmx.org@1.5.0/dist/` so now I'm thinking I need to include that file as well? That through me through a loop because the docs say:

> Htmx is a dependency-free javascript library.
...
Htmx includes some extensions 

I'm starting to feel like you you _do_ need to include the extensions... which makes perfect sense but wasn't obvious an hour ago when I started looking at this 🤦🏼‍♂️

**Comment by 1cg** [comment]
Sorry the docs aren't clear on this: yes, you do need to include the extension javascript to utilize each extension.
