### ISSUE TITLE
htmx.ajax() only working with lower case verb

### ISSUE THREAD

**Issue by renshul** [bigskysoftware/htmx#565]
`htmx.ajax('get', path, {
    source: reloader[0],
    target: target[0],
    values: filter
});`

When I use the above code with lowercase verb, the code works as expected. But when I use a capital verb ("GET"), the values parameter is not sent. 

I'm pretty sure the error occurs in the `issueAjaxRequest` function on line 2298. It checks specifically for 'get', I was using 'GET' since that's what the docs say.

**Comment by 1cg** [comment]
Ugh, sorry about that.  I've lowercased the verb internally so it doesn't matter.
