### ISSUE TITLE
xterm or hterm type example

### ISSUE THREAD

**Issue by cameronelliott** [bigskysoftware/htmx#567]
I love htmx, even though I am new and in-experienced at it. 
(probably doesn't hurt that I am a back-end Go developer either. Imaging the Internet if we all had 10gbps connections, would everybody be writing distributed applications??)

Sorry, stay on target.

QUESTION:
Which example should I focus on, to implement a scrolling-log type deal, where the browser is showing a remote log file line by line. (I got the server-side, but am new to Htmx)

Thanks

**Comment by 1cg** [comment]
Hi @cameronelliott 

For something like that, I would look at the infinite scroll example:

https://htmx.org/examples/infinite-scroll/

You probably want to combine that with "load polling" and a trigger delay:

https://htmx.org/docs/#load_polling

And then using the `scroll` or `show` option on `hx-swap`:

https://htmx.org/attributes/hx-swap/

Depending on how you lay the UI out.

**Comment by cameronelliott** [comment]
@1cg Just to ask, if you have by-chance, seen or heard of someone using something like
[xterm.js](https://xtermjs.org/) or [hterm](https://hterm.org/) with Htmx ???

Thank you for your quick and excellent prior answer.
Cameron
