### ISSUE TITLE
Want to add attributes to an element instead of 'htmx-request' class.

### ISSUE THREAD

**Issue by jakesco** [bigskysoftware/htmx#568]
I really like this project so far, but I'm running into a use case I'm not sure I can pull off with just HTMX.

I'm using the [pico.css](https://picocss.com/docs/#loading) framework which has built in loading indicators. The indicator is set by adding `aria-busy="true"` attribute to the desired element. I'm wondering if it's possible to get HTMX to set this attribute when it issues a request instead of adding the `htmx-request` class.

> I did see the `htmx.config.indicatorClass` and `htmx.config.requestClass` config settings but I need to set an attribute not a class unfortunately.

**Comment by 1cg** [comment]
Hi Jake,

The easiest way to do this would probably be with an extension:

https://htmx.org/extensions/#defining

```html
<script>
  htmx.defineExtension('pico-busy', {
    onEvent : function(name, evt) {
      var elt = evt.detail.elt;
      if(name === "htmx:beforeRequest") {
         elt.setAttribute("aria-busy", "true")
       } else if(name === "htmx:afterRequest" ) {
         elt.removeAttribute("aria-busy")
       }
    }
  })
</script>
<div hx-get="..."  hx-ext="pico-busy" ...>
   ...
</div>
```

**Comment by 1cg** [comment]
I haven't tested this at all, btw, it's just a guess.  :)

**Comment by jakesco** [comment]
Thank you! It's a good place to start, I'll look into implementing this.

**Comment by 1cg** [comment]
I am going to close this, please reopen (or jump on the discord: https://htmx.org/discord) if you need help

**Comment by plumber-craic** [comment]
+1 looking for the option to add attributes/classes to an existing element for loading, rather than revealing a new one. loading.css is the framework in my case. I'll try this extension approach to add my needed loading classes - thanks.
