### ISSUE TITLE
Feature request: select and swap multiple bits

### ISSUE THREAD

**Issue by halitcelik** [bigskysoftware/htmx#575]
With htmx we can easily specify hx-target, hx-select and hx-swap to select an element inside the response and replace the target with that element. 
But sometimes we need to update multiple parts in a page from a response. For example let's think of a `add_to_cart` example.  
In a products page we have products block, cart box on top left, proposed products block at the bottom. 
When the user adds an item in the cart, back-end (in my case Django) renders the new cart, proposed items block and the product that the user just added in the cart (with remove from cart button this time).
It would be very convenient if we had an option to specify selecting multiple elements from the response and swap the corresponding parts in the page. 
I was thinking of passing an object in `hx-select-multiple`  key being `hx-select`, value being `hx-swap` but writing a javascript object is not htmx way of doing things I suppose. 
What do you guys think about this?

**Comment by 1cg** [comment]
Would the https://htmx.org/attributes/hx-swap-oob/ attribute work for this?

**Comment by halitcelik** [comment]
Yes, I didn't know that this could be used for multiple targets. It's great. Thanks!
