### ISSUE TITLE
Title finder not working correctly

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#576]
The title finder, as well as the check for SVG tags, require tags that are closed immediately. Tags that have attributes are not being detected, the regexp and the `indexOf` functions need tweaking.

```html
<!-- This works: -->
<title>New title</title>
<svg><title>Image title</title></svg>

<!-- This doesn't work: -->
<title id="">New title</title>
<svg id=""><title>Image title</title></svg>

<!-- This also doesn't work: -->
<svg><title>Image title</title></svg>
<title>New title</title>
```

https://github.com/bigskysoftware/htmx/blob/0aa372d4470fedfade118d033fa219b7c3c3a644/src/htmx.js#L708-L718

**Comment by bencroker** [comment]
Well here's my crack at implementing your version with a regexp.

```js
var contentWithSvgsRemoved = content.replace('/<svg[^>]*>[\s\S]*?<\/svg>/gim', '');
var title = contentWithSvgsRemoved.match('/<title[^>]*>([\s\S]*?)<\/title>/im');

if (title) { 
    return title[1]; 
}
```

**Comment by 1cg** [comment]
how's about this hack?

![image](https://user-images.githubusercontent.com/469183/132065256-f156ad97-b50d-4f4b-831b-fb79ce7f2c05.png)

**Comment by bencroker** [comment]
Looks quite hacky, still looks for an exact match of `<title>` and would still fail in this case:

```html
<svg id=""><title>New title</title></svg>
<title id="">New title</title>
```

I dislike the idea of matching against `<title` and `<svg` because it doesn't rule out `<titlex>` and `<svgx>` tags.

**Comment by bencroker** [comment]
Ok, so this version does rule out `<titlex>` and `<svgx>` tags.

```js
function findTitle(content) { 
    var contentWithSvgsRemoved = content.replace('/<svg([\s][^>]*>|>)([\s\S]*?)<\/svg>/gim', '');
    var result = contentWithSvgsRemoved.match('/<title([\s][^>]*>|>)([\s\S]*?)<\/title>/im');

    if (result) { 
        return result[2]; 
    }
}
```

**Comment by 1cg** [comment]
Good points.  I'm good w/ this, if you want to make the change.

**Comment by bencroker** [comment]
Yup, I'll write and test and implement, thanks for taking a look.

**Comment by bencroker** [comment]
Added tests in https://github.com/bigskysoftware/htmx/commit/21ec1094ec831c5d4833d9280f75fa005f4fb7d4 and implemented in https://github.com/bigskysoftware/htmx/commit/a76f9f37aa6bb771c7e827ad8f70855e13316661. 

@1cg Would you manually spin up a 1.5.1 test directory or do you use an automated process to do this?

**Comment by 1cg** [comment]
Tests verified and I've created a `1.5.1` directory for testing.  Shooting for a release this week.

Thank you @bencroker!
