### ISSUE TITLE
hx-push-url does not include GET parameters

### ISSUE THREAD

**Issue by mqudsi** [bigskysoftware/htmx#58]
The documentation for `hx-push-url` starts with 

> If you want a given element to push its request URL into the browser navigation bar

and this is both the expected behavior and semantically correct when the intended result of the operation is that after the htmx trigger completes, the contents of the current page will be diffed/swapped/manipulated to match the contents of the requested url, but without actually triggering a page load (e.g. purely progressive enhancement).

However, it seems that in reality it is the value of `hx-verb` that gets pushed to the history/navbar and not the url of the request, as demonstrated by the following:

index.html:
```html
<script src="https://unpkg.com/htmx.org@0.0.4/dist/htmx.min.js"></script>

<div>
	This text is not in the div.
</div>

<div id="target">
	click me
</div>

<input type="checkbox" name="param1" value="foo" hx-get="./contents.html" hx-push-url="true" hx-target="#target" hx-swap="innerHTML" hx-select=".swap" />
```

contents.html:
```html
<div class="swap">this file contains only the contents of the div</div>
```

This (correctly) triggers an XHR to `/contents.html?param1=foo` but the location pushed to the history API is `/contents.html` rather than the true request URL.

**Comment by chg20** [comment]
Yep, looks like a bug.  `GET`s should push the full query URL.

**Comment by aiibe** [comment]
Some kind of hack but you can set the server response header `X-HX-Push` to a new url along with the request query params manually. Not ideal but works.

**Comment by chg20** [comment]
Fixed w/ https://github.com/bigskysoftware/htmx/commit/a65c37ec4f586ebf6406416f3158419f21c1a7c6
