### ISSUE TITLE
oob response creates exception when parentNode is null

### ISSUE THREAD

**Issue by nerdoc** [bigskysoftware/htmx#582]
I can't tell you exactly how I got this error, but it seems to be possible to fix it anyhow.
I am using djhtmx (a django wrapper for htmx), and there an `input` element which gets a response using hx-post into a hx-target (which is a div with id 2 levels up).

The swapping works, however, I always get an `htmx:swapError` in the console and a `Uncaught TypeError: parentNode is null`.
I narrowed it down to the function `swapOuterHTML` which calls `insertNodesBefore(parentElt(target), target, fragment, settleInfo);`

This is that function:
```javascript
 function parentElt(elt) {
    return elt.parentElement;
 }
```
in some cases, `target` is `div#hx-7ba416615e6049af91d9d762d7195fac.htmx-swapping` - and then it's parentElement is returned as `null` - whyever. In that case, `insertNodesBefore` throws the error.

Any Idea why that happens?
the parent class here is
```html
<div id="hx-7ba416615e6049af91d9d762d7195fac" hx-post="/__htmx/foo/render" hx-trigger="render" hx-headers="..." hx-swap="outerHTML" class="htmx-swapping htmx-settling">
...
</div>
```

**Comment by 1cg** [comment]
Can you debug and see how we are getting into a situation where the parent node of the div is null?  Seems like a strange situation (mabye we are trying to swap in content on a node that has been removed from the DOM?)

**Comment by nerdoc** [comment]
Ah, I think I saw how this came together. I had an hx-trigger on both the *input field* **and** the* button*. So it fired twice (normal form submit), and this seemed to trigger a race condition in the backend.
I think this is not really a fault of htmx, even if the race condition occurred in the htmx code.

But as that may be a common error, It could be worth looking at it more deeply - if not, please feel free to close this issuse, as it's done for at least me (the OP).

**Comment by 1cg** [comment]
OK, will close out for now.  Thank you.
