### ISSUE TITLE
Aborting XHR causes "Uncaught (in promise)" error

### ISSUE THREAD

**Issue by hdogan** [bigskysoftware/htmx#585]
Steps to reproduce:

Save `xhr` variable in `beforeSend` event than call `xhr.abort()` at somewhere else.

```js
let xhr;

htmx.on('htmx:beforeSend', function(evt) {
    xhr = evt.detail.xhr;
});

htmx.on('#my-button', 'click', function (evt) {
    xhr.abort();
});
```

**Comment by hdogan** [comment]
Another related issue is https://github.com/bigskysoftware/htmx/issues/551

All `maybeCall(reject)` calls probably cause this error (`onabort`, `onerror` and `ontimeout` handlers).

`issueAjaxRequest` returned value (promise) is only used by `htmx.ajax` (internal `ajaxHelper` method), which is JS API only.

I don't know how to check uncaught/undefined promise states (I'm not a JS guy), `if (func)` check is probably not enough in `maybeCall` method to make sure it exists/defined/catched.

The first (and stupid) solution I thought that, we may add `usePromise` parameter on `issueAjaxRequest` to check if it should call `maybeCall` on resolve/reject promise states (and maybe also only return promise if it's truthy, since nowhere else uses that promise). Than pass that parameter only in `ajaxHelper` method.

**Comment by 1cg** [comment]
fixed in next release

**Comment by hdogan** [comment]
Just added 2 comments to commit.
