### ISSUE TITLE
Adding a key trigger to <a> consumes all page events

### ISSUE THREAD

**Issue by mikemissing** [bigskysoftware/htmx#588]
Goes without saying I love the project, keep up the good work!

## Setup

I have a page where pagination is performed with `<a href="#" hx-post ... >next page</a>` and `<a href="#" ...>prev page</a>` links. For easier navigation I want to allow pagination using the arrow keys too. I achieve this by attaching a `<a hx-trigger="click, keydown[key=='ArrowLeft'] from:body" ...>` trigger to the `<a>` elements appropriately.

## Issue
When keys are pressend on the page, the `shouldCancel(e)` function always returns true for all but specified triggers so the `e.preventDefault()` is called thus rendering the page unresponsive to anything but the specified key triggers. This means the user cannot fill in forms etc. Even CTRL+R to refresh the page is not working (obviously).

I am opening the issue as I am not sure if this is a bug or I am missing something obvious.

Reference code that does this which is a mistery to me; I can see _why_ it's returning true due to `(elt.tagName === "A" && elt.href && (elt.getAttribute('href') === '#'` but I do not know why it _should_ return true ...
```
function shouldCancel(elt) {
    return elt.tagName === "FORM" ||
        (matches(elt, 'input[type="submit"], button') && closest(elt, 'form') !== null) ||
        (elt.tagName === "A" && elt.href && (elt.getAttribute('href') === '#' ||
            elt.getAttribute('href').indexOf("#") !== 0));
}
```

**Comment by 1cg** [comment]
Good catch.  We are cancelling all events for forms and anchors, without considering the event that is triggering them.  That's definitely a bug.  I will try to fix it in the next release.
