### ISSUE TITLE
Idiomatic way of handling HTTP errors

### ISSUE THREAD

**Issue by roobie** [bigskysoftware/htmx#59]
I am wondering what the idiomatic way is to handle request errors. From what I've been able to gather by searching the reference and this repository, I need to write JS to listen on the `responseError.htmx` event and in some way present feedback to the user. I'm thinking there must be a way for the server response to be rendered even if it is a 500?

For example, I have this button:
```
  <div></div>
  <button hx-post="/clicked" hx-swap="outerHTML">
    Click Me
  </button>
```
And the server responds with something along the lines of:
```
Status 500
Body: 
  <div class="error">Sorry, it failed. Try again</div>
  <button hx-post="/clicked" hx-swap="outerHTML">
    Click Me
  </button>
```
From experimenting, it seems that `htmx` does not replace the content in this case. Or perhaps I'm doing things wrong? :)

**Comment by agraddy** [comment]
Looks like we were thinking about how to handle errors at the same time. I've posted my proposed solution here: https://github.com/bigskysoftware/htmx/issues/60

**Comment by roobie** [comment]
@agraddy your issue is much better formulated, so I'm closing this one. Thanks for letting me know!
