### ISSUE TITLE
hx-boost behaviour with files

### ISSUE THREAD

**Issue by Tim-Wils** [bigskysoftware/htmx#593]
Hi, I have a question (and maybe a bug) related to hx-boost="true" set on a container div on a page and the behaviour of ajaxing files.

```
<div hx-boost="true" hx-target="#page">
    <a href="/contact">Contact</a>
    <a href="disclaimer.pdf">Disclaimer</a>

    <div id="#page">
        There's content here
    </div>
</div>
```

When clicking on /contact it's working like a charm, but clicking on the pdf-file or a doc-file behaves in a weird way. The contents of the pdf are loaded in the target:
<img src="https://user-images.githubusercontent.com/90032/133571666-cc7f6579-2f9d-42fa-bd4d-c561ace85340.jpg" width="200">

Is there something I'm missing here, like an attribute hx-boost-skip="files,images". 
Or shouldn't files be loaded with ajax at all?

Tim

**Comment by 1cg** [comment]
Hi Tim,

Unfortunately files can't be downloaded via AJAX, so you need that anchor tag to be "unboosted":

```html
<div hx-boost="true" hx-target="#page">
    <a href="/contact">Contact</a>
    <a hx-boost="false" href="disclaimer.pdf">Disclaimer</a>

    <div id="#page">
        There's content here
    </div>
</div>
```

**Comment by Tim-Wils** [comment]
Thanks for the clarification!
Unfortunately it's not a solution for rich-content that's loaded in the page. 
I think there should definitely also be a check if there's a target="_blank" on the anchor to skip the ajax-call.

For someone whose having for the same problem, a friend of mine came up with a nice workaround, but I hope this will be given more thought in the future:

```
window.addEventListener('htmx:beforeProcessNode', (e) => {
	// Do extra checks for <a> elements
	if(e.detail.elt.tagName == "A"){
		// Don't use AJAX for target="_blank" urls
		if(e.detail.elt.target == "_blank") {
			e.detail.elt.setAttribute('hx-boost', 'false');
		}
		// Don't use AJAX for links to files (URLs including a . in the last segment)
		else if(e.detail.elt.href.split('/').pop().indexOf('.') > -1) {
			e.detail.elt.setAttribute('hx-boost', 'false');
		}
	}
});
```

**Comment by 1cg** [comment]
I am going to mark this closed by https://github.com/bigskysoftware/htmx/commit/ee2ed10cfa1324778b7dbd96d238b121fd7b6b3e 

but @edgar-tamm-uptime I agree we should have some docs on dealing with files when boosting elements.  May I ask you to create a PR for that?
