### ISSUE TITLE
Check if element exists in `trigger` function

### ISSUE THREAD

**Issue by davidhellmann** [bigskysoftware/htmx#604]
Maybe stupid question but didn't found something in the htmx docs.
When I have something like this:

```js
<script>
  htmx.trigger('#cartBubble', 'refresh');
</script>
```
All is well as long as the element is present somewhere but if not it throws an error.

When I do it this way:

```js
<script>
  var cartBubble = document.getElementById('cartBubble');
  if (cartBubble) {
    htmx.trigger('#cartBubble', 'refresh');
  }
</script>
```
it's fine. Is this the way to go or should htmx itself check if the element exists and if not it skips his actions?

**Comment by bencroker** [comment]
So would you expect `htmx.trigger('#cartBubble', 'refresh')` to do nothing if no element with ID `#cartBubble` exists? If you're not sure that it exists then a simple check can be done, as you've shown.
```js
  if (htmx.find('#cartBubble')) {
    htmx.trigger('#cartBubble', 'refresh');
  }
```

**Comment by davidhellmann** [comment]
Yes that's what I'm searching for. Try it tomorrow. Thanks!!

**Comment by 1cg** [comment]
I would prefer that `trigger` fail fast is the element in question isn't in the DOM, so I think the right code is what Ben has offered.
