### ISSUE TITLE
Use parent <form> enctype if hx-encoding is not defined?

### ISSUE THREAD

**Issue by gnat** [bigskysoftware/htmx#605]
Currently using both of these for file upload forms so htmx sends the proper encoding, so I can keep compatibility between HTMX and normal form POST (transitional period to HTMX).

`<form ... enctype="multipart/form-data" hx-encoding="multipart/form-data" ... >`

Not the end of the world but would be nice to see: If `hx-encoding` is not defined, to use the existing `enctype` from the parent `<form>` as a fallback.

Thoughts? And thanks for the mindblowing library.

**Comment by 1cg** [comment]
yep, we should respect that

fixed in dev, hope to have a new release this coming weekend

**Comment by gnat** [comment]
Wow, cheers @1cg  for the crazy fast consideration / turnaround! :exploding_head:

**Comment by CaptainPaella** [comment]
Short question:

Was dit issue resolved in htmx v1.6.1 ?
Because this issue still present in my app which uses v1.6.1.

After a few hours of debugging some strange server error i discovered that htmx changed the "enctype" before sending the form. 

Anyways, i really like this library :)
