### ISSUE TITLE
Feature Request: hx-error-target

### ISSUE THREAD

**Issue by jgirardet** [bigskysoftware/htmx#607]
I see some issues here  about dealing with error but I did not find this proposal.
The situation is what I asked here : https://stackoverflow.com/questions/69364278/handle-errors-with-htmx
The idea is : if requests succeeds you want a target, but if it fails maybe you want  another. so we could have :
```
hx-error-target
hx-error-swap
others ?
```

**Comment by 1cg** [comment]
hi there,

in the next release we are expanding the functionality available in the `htmx:beforeSwap` event to allow for custom handling of response codes, including doing retargeting and overriding swap behavior:

https://dev.htmx.org/docs/#modifying_swapping_behavior_with_events
