### ISSUE TITLE
https://htmx.org/examples/bulk-update/ broken

### ISSUE THREAD

**Issue by jaens** [bigskysoftware/htmx#61]
Activate/Deactivate buttons do nothing.

**Comment by agraddy** [comment]
When I select the checkmarks in the table below the buttons and then press one of the buttons, it works for me. Were you selecting any checkmarks?

I wonder if moving the buttons beneath the table might make the needed interaction more obvious.

**Comment by chg20** [comment]
Thank you @agraddy for the suggestion, I have implemented this as well as added some language to clarify
