### ISSUE TITLE
What's the correct way to preserve listeners on swapped elements?

### ISSUE THREAD

**Issue by rsyring** [bigskysoftware/htmx#614]
I have a form with some jQuery listeners to help with validation:

```js
$(document).ready(function() {
    var $inputs = $('#resource-link-url,#resource-link-upload');
    $inputs.on('change', function () {
        // snip
    });
});
```

But, I swap out the entire form with htmx including the two `$inputs` above.  So the jQuery code above no longer fires when the new inputs are loaded by htmx.  

What's the best way to handle this issue?  I thought about using htmx's load event to setup the listeners again.  But, wouldn't the load event get called for any htmx load?  I only need it to happen for a particular form, not every htmx swap on the page.

**Comment by rsyring** [comment]
I missed that `onLoad` gave a target.  I was able to solve it with:

```js
function init_resource_link_listeners() {
    let $inputs = $('#resource-link-url,#resource-link-upload');
    $inputs.on('change', function () {
       // snip
    });
}

htmx.onLoad(function(target) {
    let $target = $(target)

    if( $target.is('body') || $target.is('section.resource-links') ) {
        init_resource_link_listeners()
    }
});
```

Is there a better way?  If the above seems reasonable, please feel free to close the issue.

**Comment by 1cg** [comment]
Hey,

You are close.  What you want to do is run the selector against the new content that comes in, rather than globally:

 ```js
htmx.onLoad(function(target) {
    let $inputs = $(target).find('#resource-link-url,#resource-link-upload');
    $inputs.on('change', function () {
       // snip
    });
});
```
So now if any content comes in with those elements in it, they'll be wired up properly, but you won't get multiple initializations of them since you are only looking in new content.

Documented here: 

https://htmx.org/docs/#3rd-party
