### ISSUE TITLE
Discussion for SSE extension syntax

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#618]
We're moving SSE support into an extension ([so it was decreed](https://twitter.com/htmx_org/status/1448416208244461573) by @1cg).  This thread is to collect suggestions/feedback on the syntax that we use in the new code.  I'm just getting started now, so please let me know if I'm missing anything, or if there's something we should add.  Now is the time :)

I think we should keep it as close to the existing syntax as possible, which should make it easier to migrate to the new code.  Here's my first pass:

```html

<div hx-ext="sse" sse-url="/my-first-event-source" sse-swap="message">
    INDIVIDUAL SUBSCRIPTION: I will be swapped whenever an unnamed message is received
</div>

<div hx-ext="sse" sse-url="/my-second-event-source" sse-swap="event1">
    INDIVIDUAL SUBSCRIPTION: I will be swapped whenever a message named "event1" is received
</div>

<div hx-ext="sse" sse-url="/my-third-event-source">
    SHARED SUBSCRIPTION:
    Nothing will happen to THIS div, but its children will listen to messages instead.

    <div hx-ext="sse" sse-swap="message">
        I will be swapped whenever an unnamed message is received
    </div>

    <div hx-ext="sse" sse-swap="event1">
        I will be swapped whenever a message named "event1" is received
    </div>

</div>


```

**Comment by 1cg** [comment]
for configuration options, I don't mind if extensions add their own to the standard object, so long as it is documented clearly

for events, I like triggering a real event, so long as it is backwards compatible

**Comment by benpate** [comment]
OK.  I've just posted more changes to https://github.com/benpate/htmx/tree/pr-sse-extension

1. New Extension architecture that passes a private variable to an `init()` function.  This will require more testing from @1cg and @dz4k before it gets merged.  
2. Manual connection retries in case the browser barfs on us (address #522)
3. One small change from the original behavior: settle options such as settle delay are not working.  If it's important to keep this feature then I'm going to need help to make it work correctly.

Please take a look and let me know how this looks to you, and how I can make it better.
