### ISSUE TITLE
History cache after manual reload incorrect

### ISSUE THREAD

**Issue by bascott** [bigskysoftware/htmx#620]
Version: 1.6.0

Minimal example setup:
- ```hx-boost``` on ```body```
- Full page renders of routes include the below inserted into ```body```.
- Available paths:
  - "/": ```<a href="/test">Test</a>```
  - "/test": ```This is a test.```

Steps to reproduce:
1. Navigate to "/".
2. Click link to navigate to "/test".
3. Refresh.
4. Press browser back.

Expected result: ```<a href="/test">Test</a>``` inserted into ```body```

Actual result: ```This is a test.``` inserted into ```body```

I also noticed that ```htmx-history-cache``` cached ```This is a test.``` under the path ```/``` instead of under ```/test```. From a cursory glance at the source, I think it's getting the path to save from ```location.pathname``` during the callback to ```window.onpopstate```.

**Comment by 1cg** [comment]
Thank you!  I found the bug (man, the history API is truly miserable :expressionless: ) and will include a fix in the next release.

**Comment by 1cg** [comment]
Fixed in the next release.  You can grab the current source from the `dev` branch if you want to test.
