### ISSUE TITLE
Question: How do you send a redirect or push state from websocket.

### ISSUE THREAD

**Issue by edelvalle** [bigskysoftware/htmx#629]
Websocket connection allows for sending pure HTML. 

How do you send headers like "HX-Push" or "HX-Redirect" to execute those commands?

**Comment by 1cg** [comment]
Agreed.  We should look at this as a potential feature (or enhancement) when websockets are pulled out, but it's beyond the scope of htmx right now.

**Comment by krystofbe** [comment]
had the same problem and wrote a pretty simple extension that expects a JSON payload with a `HEADERS` object that contains a `HX-Redirect` entry:

```
window.htmx.defineExtension("ws-redirect", {
  init: function () {
    window.htmx.createWebSocket = function (url) {
      const socket = new WebSocket(url);

      socket.addEventListener("message", (event) => {
        const data = JSON.parse(event.data);
        const headers = data["HEADERS"];
        if (headers) {
          const redirect = headers["HX-Redirect"];
          if (redirect) {
            window.location = redirect;
          }
        }
      });
      return socket;
    };
  },
});
```

html usage is something like this:

```
 <button hx-ext="ws,ws-redirect" ws-connect="/ws/tasks/" ...
```
