### ISSUE TITLE
discussion / feature request: target every element matching selector in `hx-select-oob`

### ISSUE THREAD

**Issue by msladecek** [bigskysoftware/htmx#634]
Hi, I recently started exploring htmx and I could use some advice on a feature I'd like to implement.

I am looking for a way to target multiple page elements with a single `hx-swap-oob` selector.

I have an page with this structure

```
- Item 1 [activate]
  tags
      - A:off
      - B:off
- Item 2 [activate]
  tags
      - C:off
      - B:off
- Item 3 [activate]
  tags
      - D:off
      - B:off
```

when I click `[activate]` on "Item 1" I want to also indicate the associated tags are active on the other items like this:

```
- Item 1 [deactivate]
  tags
      - A:on
      - B:on
- Item 2 [activate]
  tags
      - C:off
      - B:on
- Item 3 [activate]
  tags
      - D:off
      - B:on
```

I hoped I would be able to achieve this with `hx-swap-oob` ie. ship in the response from `items/1/activate`
 the new version of "Item 1" as normal, and in addition to that a new version of all affected tags using the out-of-band swap.

something like:
```
<div>(item 1 content)</div>
<div hx-swap-oob="true:.tag-A-cls">(tag A content)</div>
<div hx-swap-oob="true:.tag-B-cls">(tag B content)</div>
```

But when used like this the `hx-swap-oob` only updates the `B` tag on "Item 2" and not on "Item 3".
Indeed, this is [the documented behavior](https://htmx.org/attributes/hx-swap-oob/) (emphasis mine):

> If a selector is given, **the first element matching that selector** will be swapped. If not, the element with an ID matching the new content will be swapped.

Is there any way I can override `hx-swap-oob` to hit all matching targets?

The [docs](https://htmx.org/examples/update-other-content/) also discuss other ways of updating, I went through them and I don't think any of them fit this use case:
1. Solution 1: Expand the Target
   - This would mean reloading all of the items on the list, I have other data linked to each item which isn't exactly fast to recompute, so the whole operation would be slow
2. Solution 2: Out of Band Responses
   - Using a generalized selector which matches multiple elements doesn't work as discussed above
   - I would have to have a unique id on each item-tag, and the server would have to compute a full list possibly affected item-tags and ship it as out-of-band swaps (this is the solution I'm leaning towards the most)
3. Solution 3: Triggering Events
   - Each tag would have an event based trigger eg. `<div hx-get=/tags/B hx-trigger="reload-tag-B from:body">...</div>` and the item activation endpoint would return list of affected tags to be reloaded in the `HX-Trigger` header: `HX-Trigger: {"reload-tag-A": null, "reload-tag-B": null}`
   - After "Item" activation/deactivation, all elements of the related tags would reload themselves by with separate http requests to the server
   - I tried this approach and unfortunately it causes a somewhat unpleasant rolling update of the interface as the reloading responses are coming in
4. Solution 4: Solution 4: Using the Path Dependencies Extension
   - I haven't played with this, but I think it would suffer from all the drawbacks of Solution 3
5. Hyperscript
    - Add a hyperscript `on click` handler to the tag element which will take care of updating its peers based on a css selector
    - I would like to avoid this as it leads to fragmentation of the logic between server/client

For this use case, I think it would be ideal if the out-of-band swap could target all elements matching the css selector.
It would allow me to drive the content of the page from the server without overfetching.

Are there any other approaches that could work for this?
Any advice would be much appreaciated.

**Comment by 1cg** [comment]
It seems like if a selector returns multiple elements, each element should be swapped.  Can you create a pull request with tests?

**Comment by 1cg** [comment]
fixed, thank you!
