### ISSUE TITLE
HTTP 204 responses lead to an error message in the console

### ISSUE THREAD

**Issue by salberin** [bigskysoftware/htmx#635]
My server responds to a DELETE action with a 204 response. This triggers an error response in the console and no action in my userinterface. The error message is the following:
`htmx.org@1.6.0:1 Response Status Error Code 204 from /api/wifinetworks/16/`

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/e67e5ba41b4de7286adf3b6a6bceb1c0ae94c88b
