### ISSUE TITLE
Feature Request: Add `delete` mode to hx-swap and hx-swap-oob

### ISSUE THREAD

**Issue by ajusa** [bigskysoftware/htmx#645]
This mode would just attempt to delete the element that matches, rather than swapping it. Use cases (that I can think of anyway)

1. Removing references to an element after hitting a delete button in a modal. For example , if there is a list of elements that you can browse, after hitting delete one of them it should be possible to just delete the element in that list.
2. Having an updated list of users for a chat application. When a user leaves, we want to delete them from the list rather than generating the entire list and swapping that (could be expensive with 100s of users).

I did take a stab at implementing it in https://github.com/ajusa/htmx/commit/890b0c1834e7bcbab33d45e4968db05790936d3f but ~~wasn't quite able to get it to work~~ it works fine, my local test just wasn't correct. 
PR: #646

**Comment by 1cg** [comment]
merged and fixed, thx
