### ISSUE TITLE
Question: Does HTMX work within shadow dom?

### ISSUE THREAD

**Issue by OnurGumus** [bigskysoftware/htmx#647]
Can we use htmx to update things when it is executed in a web component and in a shadow dom? does it resolve the id's correctly?

**Comment by 1cg** [comment]
I have no idea.  We use the standard DOM APIs (e.g. `querySelectorAll`) so if those penetrate the shadow dom then yes...

**Comment by OnurGumus** [comment]
if you do document.querySelector it won't work. Based on the current element one needs to 
element.getRootNode().querySelector.

**Comment by p-baum** [comment]
Maybe this was prematurely closed.   hx-target isn't working for me from within a web-component in the shadow dom.  I imagine a fix would be fairly trivial.  If not found then check shadow root else fail.

**Comment by 1cg** [comment]
definitely willing to l look at a pull request!

**Comment by OnurGumus** [comment]
> Maybe this was prematurely closed. hx-target isn't working for me from within a web-component in the shadow dom. I imagine a fix would be fairly trivial. If not found then check shadow root else fail.

nope, same id can exist in both, so better check shadow doms hierarchically upwards

**Comment by p-baum** [comment]
I tried this code in the final else block of `querySelectorAllExt`

```
        let n = elt
        let elts = null
        while (true) {
            elts = n.querySelectorAll(selector)
            if (elts.length > 0 || n === window.top.document) return elts
            n = n.getRootNode()
        }
```

(I'm no javascript expert)

It doesnt solve the error:
```
htmx:afterRequest htmx.js:1756:17
    logError http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1756
    triggerEvent http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1773
    triggerErrorEvent http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1737
    onabort http://192.168.0.3:3000/static/htmx.js?t=1644487607884:2765
    (Async: EventHandlerNonNull)
    issueAjaxRequest http://192.168.0.3:3000/static/htmx.js?t=1644487607884:2763
    eventListener http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1257
    (Async: EventListener.handleEvent)
    addEventListener http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1269
    forEach http://192.168.0.3:3000/static/htmx.js?t=1644487607884:258
    addEventListener http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1190
    processVerbs http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1589
    processVerbs http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1558
    forEach http://192.168.0.3:3000/static/htmx.js?t=1644487607884:258
    processVerbs http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1552
    initNode http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1679
    processNode http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1709
    forEach http://192.168.0.3:3000/static/htmx.js?t=1644487607884:258
    processNode http://192.168.0.3:3000/static/htmx.js?t=1644487607884:1708
    <anonymous> http://192.168.0.3:3000/static/htmx.js?t=1644487607884:3141
    ready http://192.168.0.3:3000/static/htmx.js?t=1644487607884:3090
    <anonymous> http://192.168.0.3:3000/static/htmx.js?t=1644487607884:3137
    <anonymous> http://192.168.0.3:3000/static/htmx.js?t=1644487607884:3153
    <anonymous> http://192.168.0.3:3000/static/htmx.js?t=1644487607884:10
    <anonymous> http://192.168.0.3:3000/static/htmx.js?t=1644487607884:12
```

There are no meaningful error messages and I cannot understand the codebase.  I'm out.

Could we open this issue again please?

**Comment by OnurGumus** [comment]
I made a working prototype. 
You also need to alter processNodes to scan though shadowRoot and also use htmx.process(element) to kick start the process after shadow dom created.
