### ISSUE TITLE
hx-ext only works on <body> tag

### ISSUE THREAD

**Issue by poundifdef** [bigskysoftware/htmx#650]
Hello! I am only able to use extensions when I add them to the `<body>` tag. When I try to use them from a regular `<div>`, then the extension does not function (as if it is not present at all).

Here is an example reproducing the issue: 

```
<html>
    <head>
        <script src="https://unpkg.com/htmx.org@1.6.0"></script>
        <script src="https://unpkg.com/htmx.org@1.6.0/dist/ext/debug.js"></script>
        <script src="https://unpkg.com/htmx.org@1.6.0/dist/ext/class-tools.js"></script>
        <style>
            .bolded {
                font-weight: bold;
            }
        </style>
    </head>

    <body>
        <div hx-ext="class-tools, debug">
            <div classes="toggle bolded:1s">This should be bold and toggled</div>
        </div>
    </body>
</html>
```

However, the following _does_ work:

```
    <body hx-ext="class-tools, debug">
        <div>
            <div classes="toggle bolded:1s">This should be bold and toggled</div>
        </div>
    </body>
```

It seems like this was also reported in issue #281 

Any ideas on how to use extensions in a more localized way?

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/commit/2944bf372c1292199c9ba81c6038bd8aec21efd0
