### ISSUE TITLE
SSE trigger variety

### ISSUE THREAD

**Issue by tomberek** [bigskysoftware/htmx#66]
Currently an SSE event can only trigger a new GET request. This works when the SSE is use to notify the frontend of available data, but often the SSE event itself can contain what is needed. Other targets, swapping, and indicator behaviors with SSE would be wonderful. For example:
```
<div hx-trigger="sse:thing" hx-swap="innerHTML">Waiting for callback</div>
```

**Comment by tomberek** [comment]
or
```
<ol hx-trigger="sse:streamingListOfStuff" hx-swap="beforeend">Loading list...</ol>

**Comment by chg20** [comment]
hey tom,

Yes, that's how the websockets work, so SSE should support that mode as well.

Maybe something like:

```html
<ol hx-sse="swap on eventName" hx-swap="beforeend">Loading list...</ol>
```

**Comment by tomberek** [comment]
Implemented
