### ISSUE TITLE
How to prevent another htmx click if it's still in 1 card?

### ISSUE THREAD

**Issue by fikryrmdhna** [bigskysoftware/htmx#662]
![image](https://user-images.githubusercontent.com/58467587/142107790-6ded6ca5-15ca-4830-8551-92f2bcc01930.png)

I have a product detail card where the whole card can be clicked and then a details popup will appear and it is triggered by htmx. Then on the card there is a **Pesan Ulang** button which triggered by htmx.

Currently, when I click **Pesan Ulang**, the htmx to display the details popup is also triggered.

My question is, how I do that when I click **Pesan Ulang**, only htmx for **Pesan Ulang** is triggered, not product detail popup?

I've tried to handle it with javascript but it's still triggered. Is there a way in htmx to handle this?

<div class="order-list-detail-container">
    
    <div class="order-container order-detail-@order.getOrderId()">
        
        <div class="date-container">
            <span style="display: inline-block; width: 33%" class="date">@formatDateTime(order.getCreatedAt()) WIB</span>
            @if(order.getStatus().toString().equals("PENDING_PAYMENT")) {
                <div class="pay-due-container jsbc" style="width: 33%; justify-content: flex-start;">
                    <svg style="margin-right: 5px;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#cb4645" class="bi bi-clock"
                        viewBox="0 0 16 16">
                        <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                    </svg>
                    <span class="pay-due" data-date="@formatDateTime(order.getCreatedAt())"></span>
                </div>
            } else {
                <div style="width: 33%;"></div>
            }
            @if(order.getStatus().toString().equals("PENDING_PAYMENT")) {
                <button style="width: 33%; text-align: right;" class="cancel-transaction"
                hx-get="/account/order-cancellation" 
                hx-vars="'ordhis-orderId': '@encHashid(order.getOrderId())'"
                hx-trigger="click"
                hx-target="#order-cancel-form-reason"                            
                >Batalkan Transaksi</button>
            } else {
                <div style="width: 33%;"></div>
            }
        </div>

        
        <div class="order-info-container" style="border-bottom: 1px solid gainsboro; margin-bottom: 5px;">
                <div class="order-info with-margin-right" style="width: 33%">
                    <div class="label">Nomor Pesanan</div>
                    <div class="value no-order-value" style="color: #cb4645;">@if(order.getFormattedBusinessId().isEmpty()){-}else{@order.getFormattedBusinessId()}</div>
                </div>
                <div class="order-info" style="width: 33%">
                    <div class="label">Status</div>
                    <div class="value" style="color: #cb4645;">-</div>
                </div>
            <div class="order-info-grand-total" style="width: 33%; text-align: right;">
                <div class="label">Total Belanja</div>
                <div class="value">Rp @fbd(order.getPaymentAmount())</div>
            </div>
        </div>

        <div class="products-list">
            <div class="product-container">
                @with(OrderHistoryLine line = order.getLine()) {
                    <div class="product-inner-container">
                        <img class="product-image" src="@if(!isNull(line.getImageId())){/product-imgs/@encHashid(line.getImageId())}else{/static/comingsoon.png}" alt="lenovo" />
                        <div class="product-info-container">
                            <div class="product-name">@line.getName()</div>
                            <div class="product-catalog-code">@line.getMpn()</div>
                            <div class="product-detail-info">
                                <div class="product-price">Rp @fbd(line.getUnitPricePreTax())</div>
                                <div class="product-metadata">
                                    <span class="product-qty">@line.getQuantity() Produk</span>
                                    <div class="product-weight">(@line.getWeightKg() kg)</div>
                                </div>
                            </div>
                        </div>    
                    </div>
                }
                @if(order.isEligibleToDoPayment()) {
                    @if(!isNull(order.getMidtransTransactionId())) {
                            <button class="pay-transaction pay-midtrans"
                                hx-get="/checkout/mt-payment?checkout-transactionId=@order.getMidtransTransactionId()&mtToken=@order.getMidtransToken()123&partial=true" 
                                hx-trigger="click"
                                hx-target="#mtpay"
                                >Cara Pembayaran</button>
                    } else {
                        <a href="/order/@order.getOrderId()/payment-manual-bank-transfer">
                            <button class="pay-transaction">Cara Pembayaran</button>
                        </a>
                    }

                }
            </div>    
        </div>
    </div>

    
    <div class="order-action-outer-container jsbc">
        <div class="order-action-container">
            <button class="peek-order-detail">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                </svg>
                <span>Lihat detail pesanan</span>
            </button>
            <button class="hidden order-detail-trigger-@order.getOrderId()" 
            hx-get="/account/order-detail" 
            hx-vars="'popup': true, 'modalDialogId': 'order-detail-modal', 'modalBodyScroll': true, 'maxWidth': '750px', 'ordhis-orderId': '@encHashid(order.getOrderId())'"
            hx-trigger="click"
            hx-target="#orderDetailModal">
            Ubah
            </button>
        </div>
        @if(order.isEligibleToReorder()) {
            <div class="order-action-container">
                </button>
                    <button 
                        id="orderReorder"
                        style="padding: 5px 10px; border: 1px solid #cb4645; background-color: #cb4645; color: white; border-radius: 4px;">
                        Pesan Ulang
                    </button>
                <button class="hidden" 
                id="orderReorderHandler"
                hx-post="/account/reorder-order" 
                hx-trigger="click" 
                hx-vars="'ordhis-orderId': '@encHashid(order.getOrderId())'">Ubah</button>
            </div>
        }

    </div>

</div>

**Javascript**
```
<script>
    $(".order-detail-@order.getOrderId()").each(function() {
        $(this).on("click.div", function() {
            $('.order-detail-trigger-@order.getOrderId()').trigger('click.button');
        })
    });

   $("#orderReorder").on("click", function() {
      $(this).siblings().click();
   });
</script>
```

**Comment by 1cg** [comment]
Sorry this has taken so long to respond to.

If I understand you have two different elements that are being triggered by `click` but one is nested in the other, so when you click the inner object, both trigger.

The solution here would be to use the event filter on triggers and check the `event.target` in the outer element, and ensure it isn't the inner element.
