### ISSUE TITLE
Back/history broken for more than 1 click in `1.6.0`

### ISSUE THREAD

**Issue by thekashifmalik** [bigskysoftware/htmx#666]
The back button works as expected on version `1.5.0` but on `1.6.0` it only works once for a given full page refresh, i.e. if you load a page and navigate using htmx links twice, the back button will only take you back one step.

**Comment by 1cg** [comment]
Thank you, I am able to reproduce locally.

I will get it fixed for the next release.

**Comment by 1cg** [comment]
Actually, I take that back.  I am not able to reproduce locally.

Can you install this debugging code and let me know what you see:

```js
        htmx.on("htmx:beforeHistorySave", function(evt){
            console.log("Saving history : ", evt.detail);
            console.log("History Cache Before:", JSON.parse(localStorage.getItem("htmx-history-cache")))
            setTimeout(function () {
                console.log("History Cache After:", JSON.parse(localStorage.getItem("htmx-history-cache")))
            }, 10);
        })
```

This should print out when every history snapshot is taken and give you a before/after view of the history cache.

**Comment by hirasso** [comment]
Hi @1cg ,

while investigating HTMX for possible adoption, it seems to me that indeed something is odd with the cache/ajax. If you go to https://htmx.org/ and navigate around within the main nav (class: `navigation-items`, docs, references, examples, ...), the browser *sometimes* fully refreshes the page. Regarding to the documentation on `hx-boost`, this should not happen, right?

**Comment by dalito** [comment]
@hirasso - Boost is activated only on some of the pages: In the code of "examples" you find the comment `<!-- don't boost on demo pages, sinon hijacks everything :/ -->`

**Comment by hirasso** [comment]
@dalito thank you for the explanation! Are you referring to https://sinonjs.org ?
