### ISSUE TITLE
How to best send all values of `this` element

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#67]
I have a use-case in which I want `hx-get` to refresh the contents of a parent `div`.

```html
<div hx-target="this">
    <input hx-get="/reresh" type="text" name="name1" value="value1">
    <input hx-get="/reresh" type="text" name="name2" value="value2">
    <input hx-get="/reresh" type="text" name="name3" value="value3">
</div>
```

When any of the 3 input fields are changed, I would like all 3 field values to be sent in the request. I was hoping that putting `hx-params="*"` on the `div` element would achieve this, but it does not seem to work that way.

```html
<div hx-params="*" hx-target="this">
    <input hx-get="/refresh" type="text" name="name1" value="value1">
    <input hx-get="/refresh" type="text" name="name2" value="value2">
    <input hx-get="/refresh" type="text" name="name3" value="value3">
</div>
```

So I am currently solving this as follows, which does work (but feels a bit icky).

```html
<div id="random-id" hx-include="#random-id *" hx-target="this">
    <input hx-get="/refresh" type="text" name="name1" value="value1">
    <input hx-get="/refresh" type="text" name="name2" value="value2">
    <input hx-get="/refresh" type="text" name="name3" value="value3">
</div>
```

I know that if I was to use a `form` and `hx-post` then it would automatically send all input field values, but wondering if there is a better way for to achieve this with `hx-get`? I'm also aware that I could write an extension that listens for the `configRequest.htmx` event and adds all the values and I may well end up doing that, just wanted to ask first.

**Comment by chg20** [comment]
```
<div id="random-id" hx-include="#random-id *" hx-target="this">
    <input hx-get="/refresh" type="text" name="name1" value="value1">
    <input hx-get="/refresh" type="text" name="name2" value="value2">
    <input hx-get="/refresh" type="text" name="name3" value="value3">
</div>
```

I think this can maybe be simplified to:

```
<div hx-get="/refresh" hx-trigger="change" hx-include="input[type='text']" hx-target="this">
    <input type="text" name="name1" value="value1">
    <input type="text" name="name2" value="value2">
    <input type="text" name="name3" value="value3">
</div>
```

The "change" event should bubble up to the parent and then we include the values of all the text inputs...

Not sure if that will work, but it should!  Hey, it's 0.0.4!

**Comment by bencroker** [comment]
That does work, to my surprise! So the `trigger` is essentially applied to all descendant elements, very cool.

For my specific use-case, I want to be able to trigger a refresh only for specific input fields, but to send the values of all of the fields, so adding a `trigger` to the `div` won't work.

```html
<div id="random-id" hx-include="#random-id *" hx-target="this">
    <input hx-get="/refresh" type="text" name="name1" value="value1">
    <input type="text" name="name2" value="value2">
    <input hx-get="/refresh" type="text" name="name3" value="value3">
</div>
```

The above code works, so I guess I'll either stick with it or write an extension. Thanks for the prompt response and I'm still astounded by how much hmtx allows us to do!!
