### ISSUE TITLE
hx-post with body example?

### ISSUE THREAD

**Issue by aaronvaswani** [bigskysoftware/htmx#68]
Hey, really like htmx so far! It's great what you have done with it!
I was wondering if you could help me with a POST request example? I have a server that I send a JSON to and it returns a response. For some reason I cannot seem to get this working on my end.

Would you be able to provide an example?

**Comment by chg20** [comment]
Hi @aaronvaswani probably better to ask in the gitter room:

https://gitter.im/intercooler-js/Lobby
