### ISSUE TITLE
difference within documentation and example

### ISSUE THREAD

**Issue by DNWEIJ** [bigskysoftware/htmx#694]
From the documentation part  TRIGGER MODIFIERS
<start copy of document>
You can use these attributes to implement many common UX patterns, such as Active Search:

   <input type="text" name="q"
          hx-get="/trigger_delay"
          hx-trigger="keyup changed delay:500ms"
          hx-target="#search-results"
          placeholder="Search..."/>
    <div id="search-results"></div>
This input will issue a request 500 milliseconds after a key up event if the input has been changed and inserts the results into the div with the id search-results.

**_Multiple triggers can be specified in the hx-trigger attribute, separated by commas._**
<end copy of document>

The example show hx-trigger with spaces, the document (line in bold/italic) states "...sperated by commas." 

There can only be one truth :-)

**Comment by 1cg** [comment]
in the example, the `changed` word is a modifer of the `keyup` event, not a `change` event.  A bit confusing, but the docs are correct.  :)
