### ISSUE TITLE
active-search example: Case-insensitive

### ISSUE THREAD

**Issue by guettli** [bigskysoftware/htmx#715]
Hi,

it would be great, if the active-search example would be case-insensitive.

https://htmx.org/examples/active-search/

I type "venus" and get no result. This is confusing.

**Comment by gmso** [comment]
Hi @guettli,

Following up on this issue, I went ahead and implemented the changes on this active search page's code. I've just created the pull request #741. Feel free to check it out when you have the chance, thanks!

**Comment by guettli** [comment]
Thank you very much. Your PR looks good to me.

**Comment by gmso** [comment]
No problem! Happy to contribute 😃
