### ISSUE TITLE
htmx event listeners set on elements inside shadow DOM return right away

### ISSUE THREAD

**Issue by gotcha** [bigskysoftware/htmx#718]
```
var eventListener = function (evt) {
    if (!bodyContains(elt)) {
        eltToListenOn.removeEventListener(triggerSpec.trigger, eventListener);
        return;
    }
```
If I understand properly the code above, this checks if a node is part of body to avoid to run event listener if it is not the case anymore.

However, if elements from inside a shadow DOM are processed with code like

```
htmx.process(elt.shadowRoot)
```

`bodyContains(elt)` at the begin of eventListener always returns `false` because `elt` is part of shadow DOM.

I propose the following fix to take care of shadow DOM nodes.

```         
function bodyContains(elt) {
    if (elt.getRootNode() instanceof ShadowRoot) {
        return getDocument().body.contains(elt.getRootNode().host);
    } else {
        return getDocument().body.contains(elt);
    }
}
```

Opinions ?

**Comment by 1cg** [comment]
Thank you for the change.  Can you write a test that exercises this functionality?

**Comment by gotcha** [comment]
@cg Tests are why I started the CI PR. I'll do my best to add one.
