### ISSUE TITLE
htmx fails on apostrophe in text

### ISSUE THREAD

**Issue by WillyWilson1** [bigskysoftware/htmx#725]
I have code which puts text into a div. 

When I use any text that has an apostrophe I get this error:

htmx.org@1.3.3:1 htmx:swapError
ut @ htmx.org@1.3.3:1
htmx.org@1.3.3:1 DOMException: Failed to execute 'querySelector' on 'Element': 'DIV[id='stat~1~9dRC2~isn't']' is not a valid selector.

Are there any workarounds for this?

WW

**Comment by benpate** [comment]
Query selectors get passed straight to Javascript, so this would likely fail in Javascript, too.  Try making a selector that will work in regular JS, and it should work in htmx.

If you can't remove the apostrophe in your selector, I'd try either `DIV[id=stat19dRC2~isn't]` or `DIV[id='stat19dRC2~isn\'t']` as a starting point.

**Comment by 1cg** [comment]
yep, we just pass this through to the query selector API, so I would change the ids to not include apostraphes as it is obviously problematic w/ the standard DOM APIs
