### ISSUE TITLE
Feature request: easy way to handle JSON response

### ISSUE THREAD

**Issue by iredmail** [bigskysoftware/htmx#726]
Dear developers,

I understand that HTMX is mainly used for server-side rendering, but it's quite normal that our API server returns JSON, for example, a simple JSON reply to indicate succeeded or failed operation:
```
{
    "_success": true
}

{
    "_success": false,
    "_msg": "invalid credentials"
}
```

With current HTMX, it simply inserts the returned JSON text in place (e.g. with `hx-target` set to `innerHTML`). Is there any way to check JSON field value (e.g. `_success`) first, then action based on its value?

**Comment by gmso** [comment]
Hi iredmail,

have you tried the [client-side-templates extension](https://htmx.org/extensions/client-side-templates/)?

I believe using that extension, if your backend returns some JSON response, you can then use one of the supported templating libraries (moustache, handlebars or nunjucks) to render HTML depending on the JSON response you've received. Htmx should then be able to swap that newly rendered HTML into the DOM

**Comment by iredmail** [comment]
Involving a client-side-template extension seems a little "heavy" for such simple job. :(
Since __simple__ JSON handling is quite normal, might be better make it a builtin feature.

**Comment by gmso** [comment]
I understand. I think problem is that htmx is HTML-centric. So it is thought out to exchange HTML with the server, not JSON. I have heard the author of htmx say that he wants to keep the core functionality close to that idea, so unfortunately I don't see JSON parsing becoming a core feature any time soon. His idea (as far as I understand) is to be able to extend the core functionality using extensions, like the one I mentioned on my first comment.

That aside, if you receive JSON as a response and want to render some HTML with it, you need a templating solution at some point. Even if you don't use htmx at all for that and simply use vanilla JS with DOM manipulation, you still need to process that JSON (in your case, check the value of `_success`) and create or modify some DOM nodes afterwards.

I had not personally used the templating libraries before, but they seem to be relatively lightweight. Following the example [found here](https://htmx.org/extensions/client-side-templates/), I wrote [a short example on CodePen, using htmx, the extension and nunjucks.](https://codepen.io/gmso/pen/wvrPjbj) In that case I am checking that the id field in the JSON response is 1, and rendering two different things accordingly. If you change the fetched post number in the `hx-get` parameter (from `https://jsonplaceholder.typicode.com/todos/1` to `https://jsonplaceholder.typicode.com/todos/2` for example), you will see how the rendered content changes. That could be a solution you can use, checking for `_success` in your case.

Maybe there's another solution that I don't know, like hooking up to htmx's internal events and intercepting the JSON response, but that is probably more complicated and convoluted than using the extension.

**Comment by iredmail** [comment]
Dear @gmso ,

Thank you very much for the explanation. I will try the extension. :)

**Comment by gmso** [comment]
No problem, happy to help! 😃

**Comment by mariusGundersen** [comment]
I've just published an extension called [htmx-json](https://github.com/mariusGundersen/htmx-json) for converting json into html. Unlike the template extension it does not require everything to be in a template, and it updates only the stuff that need to change, so the html is a lot more stable.
