### ISSUE TITLE
Accessibility implications?

### ISSUE THREAD

**Issue by mgifford** [bigskysoftware/htmx#731]
Before jumping in on something like this it would be good to know that accessibility issues have been thought through and that we're just just making it harder to make our sites accessible. 

Do we need to rethink, "links go somewhere and buttons do things in the page?" That's just a basic example.

**Comment by Indribell** [comment]
Your always going to have accessibility issues the moment you start with any Web 2.0 features. 

Source: Used to work for a handicap organization and normally they have strict guidelines what to expect of websites. Unfortunately, a lot of features that are common in todays websites make them handicap unfriendly.

Most of the feature that HTMX offers can be circumvented to keep handicap friendly. Like ensuring that buttons have hx-get, hx-post. The moment you start putting hx-get/... on div or other non-standard elements, your entering a different territory and need to supply alternative text to ensure accessibility. 

For instance such that a blind person can see that a DIV is actually a clickable link. Like adding alt text or hiding a hidden span, that is readable by screen readers.

> <span class="sr-only">Open page X</span>

https://www.voorhoede.nl/en/blog/improving-accessibility-for-the-blind-8-guidelines/

You can make websites in basic HTML that are also badly accessible but a good accessibility website always takes more time. And discipline as a lot of websites may start with good accessibility but as developers change, things get forgotten / time pressure, etc and one of the first thing to go is accessibility.  And even a lot of government websites sin on this.

So no, accessibility does not prevent you from using HTMX or any JS framework. All that matters is how much focus you have on providing those help/hints for people.

**Comment by benpate** [comment]
Accessibility takes extra work -- even if you're only writing plain HTML.  Yes, "Web 2.0" makes it harder, but I'd say htmx (applied thoughtfully) makes this easier to manage than using something else.  

You can style buttons to look like anything, so if you're aiming for good accessibility, then perhaps everything interactive on a page should be a button (or some ARIA equivalent).  There are already well-researched guidelines on accessibility - it's just a matter of building to the guidelines.

I've been doing some experiments on making accessible widgets with htmx/hyperscript. They're still pretty new and raw, but [this tabs component](https://benpate.github.io/hyperscript-widgets/tabs.html) came out pretty well.  It follows all of the W3C guidelines on accessible tabs.  Hopefully more will come, and we'll have a clearer story to tell with htmx/hyperscript and accessibility.

**Comment by 1cg** [comment]
@Indribell I am going to do a progressive enhancement/accessibility section in the docs this weekend.  Would you mind reviewing it when I have done so?
