### ISSUE TITLE
json-enc extension does not update Content-Type

### ISSUE THREAD

**Issue by aimichal** [bigskysoftware/htmx#74]
I'm having trouble using the json-enc extension, because it appears to not update the Content-Type header. It is always `application/x-www-form-urlencoded; charset=UTF-8`, even though I've confirmed with console.log that I'm reaching the code in the extension that is calling `xhr.setRequestHeader("Content-Type", "application/json");`.

After some digging around, I found a kind of plot twist. Turns out, the parameter `charset` isn't allowed for mime type `application/x-www-form-urlencoded`. (For example, see discussion at [here](https://stackoverflow.com/questions/16819502/application-x-www-form-urlencoded-and-charset-utf-8) and [here](https://stackoverflow.com/questions/19694503/ajax-setrequestheader-content-type-application-x-www-form-urlencoded-and-ch).) Accordingly, this code in htmx.js:

```js
if (verb !== 'get') {
    headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8';
    ...
```

should become

```js
if (verb !== 'get') {
    headers['Content-Type'] = 'application/x-www-form-urlencoded';
    ...
```

For whatever reason, after this change, the extension `json-enc` does update the `Content-Type` header -- hurray! (I confirmed this in FF 76.0.1 and Chrome 83.0.4103.6 on Mac.)

Unfortunately, the header value is actually appended to:

```
Content-Type: application/x-www-form-urlencoded, application/json
```

And that's because the `setRequestHeader("Content-Type", ...)` is called twice, and behavior for `setRequestHeader` is [documented](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader) to be:

> If this method is called several times with the same header, the values are merged into one single request header.
>
> Each time you call setRequestHeader() after the first time you call it, the specified text is appended to the end of the existing header's content.

😬 

So... it looks like setting the Content-Type header should be done once for the XMLHttpRequest instance.

One idea is to somehow allow extensions to modify the `headers` map, and call this code once immediately before the xhr.send() call:

```js
// request headers
for (var header in headers) {
    if (headers.hasOwnProperty(header)) {
        if (headers[header] !== null) xhr.setRequestHeader(header, headers[header]);
    }
}
```

What do you think?

**Comment by chg20** [comment]
Fixed in dev: https://github.com/bigskysoftware/htmx/pull/92

**Comment by Master-Y0da** [comment]
This is setting content type application/json to all of my request...even if I set hx-encode to multipart formdata is sending data as json, such a problem :/
