### ISSUE TITLE
Please add alt attribute to the image in Lazy Loading example

### ISSUE THREAD

**Issue by rbri** [bigskysoftware/htmx#742]
Htmx looks really great - nice to see there are some folks around with a passion for simple and effective solutions.

Have just started to test your samples using wetator (www.wetator.org) because the ideas of both seems to match.
The first tests are really promising (https://wetator.org/files/htmx/run_report.xsl.html).

But for testing the Lazy Loading demo i need a chance to  detect the image availability. It will be great if you can add an alt (or an title) attribute to the image.

**Comment by 1cg** [comment]
:) thank you your work on this!

I have pushed a change up that I hope satisfies your requirements, please let me know if not.

**Comment by rbri** [comment]
Is the page already updated? The demo seems not to start....

**Comment by 1cg** [comment]
ugh, sorry about that

should be fixed!

**Comment by rbri** [comment]
:-D works fine now, will update my wetator test samples soon. Thanks
