### ISSUE TITLE
/migration-guide/ URL not referenced. Outdated url?

### ISSUE THREAD

**Issue by gmso** [bigskysoftware/htmx#747]
Hi,

looking at the source code for the htmx website, I realized that there is one route which is not linked throughout the site: https://htmx.org/migration-guide/. This route corresponds to this file: [migration-guide.md](https://github.com/bigskysoftware/htmx/blob/master/www/migration-guide.md)

Is this intentional? Was a previous link to this route removed? Is the information on this url outdated, or why is this page not linked anywhere? 

If it is old or not valid anymore, should it be removed? So as not to be reachable anymore?

**Comment by 1cg** [comment]
thank you for pointing this out!
