### ISSUE TITLE
Preserve element even if it's not in the new swap

### ISSUE THREAD

**Issue by wbobeirne** [bigskysoftware/htmx#748]
I'm trying to use `hx-preserve` on a fixed position element that is added via Javascript so that it persists across pageloads. It seems to me though that `hx-preserve` only works if the incoming swap has that element too. Is there any good way to keep the element around regardless of if it's in the new swap or not?

**Comment by 1cg** [comment]
If the element (as identified by ID) isn't in the new content, we don't know where to place it in the new content.  Or am I misunderstanding?

**Comment by wbobeirne** [comment]
My use-case is for the instance where you `hx-boost` the entire body, but have some JS that adds elements to the page. I had assumed that `hx-preserve` would keep those elements in the body at the top level, but they get removed since they're not in the DOM of the AJAX request.
