### ISSUE TITLE
How to import HTMX variable?

### ISSUE THREAD

**Issue by GitRon** [bigskysoftware/htmx#755]
Hi guys!

I am using HTMX attributes on some dynamically generated DOM elements. HTMX is not working, as stated in the docs under third-party-packages unless you call htmx.process().

When I tried to call this, I get - correctly - the error:

> Uncaught ReferenceError: htmx is not defined

Any idea how I can import this htmx variable? No idea how the example in the docs can work.

Thx!

**Comment by 1cg** [comment]
the htmx symbol should be available just by loading the library

how are you loading the library?

**Comment by GitRon** [comment]
Hi @1cg - sorry for not posting an update! I solved it at SO with

> window.htmx = require('htmx.org');

I put this line in my custom JS file which I bundle like all third-party packages. When adding the variable to `window` I make it available in my templates. That did the trick!

I am using webpack in a django context in combination with django-webpack-loader.

It took me in total ages to figure this out, maybe an update on the docs might help? 😇

**Comment by 1cg** [comment]
That's a good idea.  Do you want to create a pull request on this?  The main documentation can be found in `/www/docs.md`

**Comment by GitRon** [comment]
Hi @1cg please have a look at my PR https://github.com/bigskysoftware/htmx/pull/775
