### ISSUE TITLE
hx-indicator should support "this" (like hx-target)

### ISSUE THREAD

**Issue by bitc** [bigskysoftware/htmx#757]
References:

  - https://htmx.org/attributes/hx-target/
  - https://htmx.org/attributes/hx-indicator/

These are similar attributes, both target an element, but `hx-target` has additional power, it allows the "this" value.

I think it makes sense for `hx-indicator` to also support the same "this" syntax. And while we're at it, it should also support "closest" and "find".

I think this change will make htmx more internally consistent, easier to learn and use, and more powerful.

Thank you

**Comment by 1cg** [comment]
thank you for pointing this out, fixed
