### ISSUE TITLE
BUG: OOB Swaps Confused By Other Content

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#761]
I've been working on a bug with @xtlc related to swapping two pieces of content into a page: 1) additional content into a <TBODY>, and 2) an optional OOB swap to display an error message.  The example code below works great if the server returns either one of these two HTML fragments, but breaks hard if both are included in the page response.

Here's the index.html file that sets up a table and has a button at the bottom to load more content...
```html
<!DOCTYPE html>
<html>
<head>
	<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body>

<div id="form-errors"></div>

<table class="table table-striped table-hover">
	<thead class="thead-dark">
		<tr>
			<td>Heading</td>
			<td>Heading</td>
			<td>Heading</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>data...</td>
			<td>data...</td>
			<td>data...</td>
			<td></td>
		</tr>
	</tbody>
	<tbody id="newProduct"></tbody>
</table>

<button class="btn btn-success btn-sm"
	hx-swap="outerHTML"
	hx-get="tables-2.html"
	hx-target="#newProduct">
	Click Me
</button>  

</body>
</html>
```

And here's the second file (linked above as "tables-2.html")

```html
<tbody>
	<tr> 
		<td>FIELD</td>
		<td>FIELD</td>
		<td>FIELD</td>
		<td class="text-end">
			<button class="btn btn-success btn-sm editbutton">ADD RECORD</button>
		</td>
	</tr>
</tbody>

<div id="form-errors"  hx-swap-oob="true">
	<p class="text-danger">If this OOB swap is included, then the TBODY above will break</p>  
</div>
```

As I mentioned above, if either of these two top-level elements (the `tbody` or the `div`) is returned, then the page works fine.  But if BOTH are returned, then it breaks the page layout.

**Comment by 1cg** [comment]
once again, table swapping rears its ugly head.

Solution is to htmx.config.useTemplateFragments	to true, sacrificing IE11 compatibility.
