### ISSUE TITLE
oob-swap not being handled properly

### ISSUE THREAD

**Issue by iustin94** [bigskysoftware/htmx#762]
This is pretty much the same issue as  https://github.com/bigskysoftware/htmx/issues/469:
I am using HTMX version 1.6.1 with django.

The following HTTP response that is being processed results in a different result when processed by HTMX.

    <tr>...</tr> 
    <div hx-swap-oob="true">...</div>

After HTMX processes the table row, the tr is being stripped from it entirely and what is being used for the swap are the internal contents of the table row.

And from  this I get the same error response as the above mentioned issue:
![image](https://user-images.githubusercontent.com/13846875/149117817-ce485806-7675-4d88-a04a-1722893a2635.png)

**Comment by 1cg** [comment]
I believe this is an issue when using oob swaps with top level table elements using the default content processing mechanism.

You can fix this by setting htmx.config.useTemplateFragments to true, which will sacrifice IE11 compatibility

https://htmx.org/docs/#config
