### ISSUE TITLE
Scoping Parameters

### ISSUE THREAD

**Issue by tola** [bigskysoftware/htmx#766]
This is my table template. If I have 3 data items then I have three rows.
`                <td>
                
                   <span id="b<%#Eval("Code")%>">

                </span>

                    <input type="hidden" id="booktoken" name="token" value="<%#Eval("Token")%>">
                      <a href="#" hx-post="/GetBookInfo"  
                      hx-target="#b<%#Eval("Code")%>" 
                      hx-params="token"  
                      hx-trigger="click"> <%#Eval("Code")%></a>

                </td> `

 htmx will work as expect if there is only one row. However, if there are more rows, htmx will send all the params (3 param in this case) when only a single link is clicked.
![image](https://user-images.githubusercontent.com/205426/149489248-b119fc53-8719-4676-bcb3-cadb2983a3fa.png)

My work-around is to wrap a TD tag between the FORM tag like this:

                <form>
                <td>
                
                   <span id="b<%#Eval("Code")%>">

                </span>

                    <input type="hidden" id="booktoken" name="token" value="<%#Eval("Token")%>">
                      <a href="#" hx-post="/GetBookInfo"  
                      hx-target="#b<%#Eval("Code")%>" 
                      hx-params="token"  
                      hx-trigger="click"> <%#Eval("Code")%></a>

                </td>  
                </form> 

I have read about hx-params here  [https://htmx.org/docs/#parameters](https://htmx.org/docs/#parameters) and here [https://htmx.org/attributes/hx-params/](https://htmx.org/attributes/hx-params/) to try to find how to make hx-params limit to get only parameter that's belong to current TD. In other words, how do I limit the hx-param scope to current elelemnt or parent element only? 

Is there any scoping parameter feature similar to scoping variable by [@hype](https://github.com/bigskysoftware/_hyperscript) as mentioned here [https://hyperscript.org/docs/#variables_and_scope](https://hyperscript.org/docs/#variables_and_scope)

Is there away to make hx-params target the element by ID or read value assignment directly? Something like this:

- hx-params="p1:elementId,p2:elementId2"
- or the parameters and the value should be specified like this:
 hx-params="p1:value1, p2:value2"

**Comment by 1cg** [comment]
You can use hx-vals to accomplish this:

https://htmx.org/attributes/hx-vals/
