### ISSUE TITLE
hx-select doesn't work with "unset"

### ISSUE THREAD

**Issue by Alireza-Farahani** [bigskysoftware/htmx#768]
`hx-select` is inherited and according to htmx docs, we should be able to make children opt out of it by setting `hx-select="unset"`. It doesn't work in my code:

```html
<form id="np-report-form"
          hx-target="#np-dynamic-content"
          hx-select="#np-dynamic-content"
          hx-swap="outerHTML"
          hx-push-url="true">
      <select id="np-reports" onchange="enableSubmit();"
              hx-target="#np-report-options"
              hx-select="unset"  {# Doesn't work. Nor hx-select="" #}
              hx-trigger="change"
              hx-swap="innerHTML"
              hx-push-url="false">
        <option value="1" hx-get="{% url 'report1-link' %}">
          report1
        </option>
    <button type="submit" class="disabled">Submit</button>
</form>
```
Without hx-select on `<select>` and hx-* stuff from `<form>`, htmx request on `<select> works well, but introducing hx-select on `<form>` makes htmx on `<select> corrupted. (the AJAX is sent as normal) 

Htmx have a test case [here](https://github.com/angusholder/htmx/blob/d6a22d72e76fcceabe76e92917e6ed986dd32465/test/attributes/hx-select.js#L51) that tests `hx-select=""` removes parent's hx-select. It's confusing and in my case didn't work, too.

**Comment by 1cg** [comment]
Hi there.  I think that the functionality does work properly.  I added a regression test here:

https://github.com/bigskysoftware/htmx/issues/768

and it passes.  I see you are adding an `hx-get` to an option, and I wonder if that will work correctly.  IIRC, options don't trigger events and so can't support `hx-get`.
