### ISSUE TITLE
VS Code Extension Request

### ISSUE THREAD

**Issue by atwilliams88dev** [bigskysoftware/htmx#776]
I would like to work on a VS Code extension for HTMX. What do y'all think? Would you find this useful? - I'm hoping to provide code completion and suggestions for attributes.

**Comment by benpate** [comment]
Yes. This is an excellent idea!

**Comment by atwilliams88dev** [comment]
great, this is the only information I have found on contributing. 

## contributing
please write code, including tests, in ES5 for IE 11 compatibility
please include test cases in /test and docs in /www
if you are adding a feature, consider doing it as an extension instead to keep the core htmx code tidy
development pull requests should be against the dev branch, docs fixes can be made directly against master
No time? Then become a sponsor. 

Is there a more formal procedure? A vs code plugin could be in a different repo. I'm new to contributing to this codebase and I don't want to step on anyones toes.

**Comment by benpate** [comment]
Fortunately, I've found that nobody around here has toes :) Definitely see if there's any prior work that you can hook into, or coordinate with, but everyone on this project is really open. I'm sure they'll welcome the enhancement.

There is a fantastic [hyperscript extension](https://marketplace.visualstudio.com/items?itemName=dz4k.vscode-hyperscript-org) by @dz4k - that might be one place to start.

**Comment by 1cg** [comment]
no toes here

I would do it as a separate project and then jump on the discord if you want to recruit help:

https://htmx.org/discord

closing, as you have our blessing and godspeed!
