### ISSUE TITLE
Page jump on focus after swap

### ISSUE THREAD

**Issue by jreviews** [bigskysoftware/htmx#781]
Posting this as a follow up to a Discord discussion so it doesn't get lost. 

When htmx focuses an element after swap it will scroll to that element even if the user had already scrolled away from it. One case in point is a long form where validation is performed on input changes. The issue can be reproduced with the example below where you select an option from the list, then scroll down to make other changes or submit, but the page jumps up to the select that was changed to focus it.

```html
<form hx-post="" hx-trigger="submit, change">

        <select id="select">
            <option value="">Select</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select>
        <p>Scroll down to submit</p>
        <div style="height: 800px;"></div> 

        <button id="button" type="submit">Submit</button>

</form>
```

The problem takes place here:

https://github.com/bigskysoftware/htmx/blob/f1cef92e528871993df1a5569b30bb94c99ec847/src/htmx.js#L2569

The focus method includes an option to prevent scrolling which could be use to avoid such cases.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focus_with_focusoption

Even though it says it's not supported in Safari, I tested it and it works. On Safari mobile the focus is lost regardless so the issue doesn't happen there.

**Comment by jreviews** [comment]
@1cg Would you consider a PR that changes the default behavior to `focus({preventScroll:true})`? Or would you rather make this configurable and if so, maybe using a global config value `htmx.config.focusScroll`?

**Comment by 1cg** [comment]
Seems like a good option for hx-swap: https://htmx.org/attributes/hx-swap/

focus:true

or some such?

**Comment by jreviews** [comment]
Maybe the modifier should be `scroll:focus` to enable the scrolling when re-focusing an input after swap? Not sure if that conflicts with other scroll modifiers. I still think re-focusing the input is the right thing to do, but now scrolling to it if it makes the page jump all over the place.

**Comment by David-Guillot** [comment]
Hi @jreviews , may this issue be closed?

**Comment by jreviews** [comment]
Yes @David-Guillot. Closing now. Thanks.
