### ISSUE TITLE
Can we get a reference to the triggering DOM element in polling (hx:poll:trigger) events?

### ISSUE THREAD

**Issue by cb109** [bigskysoftware/htmx#792]
Example:

```html
<input
  id="checkbox-autorefresh"
  type="checkbox"
  name="autorefresh"
  hx-get="/page/refresh"
  hx-trigger="
    change[target.checked],
    every 60s [htmx.find('#checkbox-autorefresh').checked]
  "
  hx-target="#page-content"
>
```
In my example above I have a checkbox that I want to trigger AJAX requests to refresh a part of the page. This should happen based on two events:
  - Either when the checkbox is checked, which would trigger a `change` Event to which we add a conditional `[target.checked]` which essentially checks if `event.target.checked`, since that Event will have this kind of information.
  - Every 60s, but again only if the checkbox is checked. The conditional is the same mechanic, but since the `hx:poll:trigger` type Event we have here has no reference to the triggering element (the checkbox input), we need to search the DOM using `htmx.find()` to get a reference to it, so we can see if it is `.checked`.

I found that a bit unintuitive and now we have two wildly different ways to test if the element has a certain state. I would find it helpful to let the `hx:poll:trigger` Event carry some reference to the element that triggered it, while that may not be under `event.target.value`, maybe as `detail.elt`? There's already some `detail.triggerSpec` payload, so something similar maybe?

The hx-trigger could then look like:

```html
<input
  hx-trigger="
    change[target.checked],
    every 60s [detail.elt.checked]
  "
>
  ```

The relevant function is [processPolling()](https://github.com/bigskysoftware/htmx/blob/2ab84352b88c0d8304e34e172a7243efe4f9b73f/src/htmx.js#L966-L976) from what I understand, where we do have an element reference `elt`, it's just not passed down to the created CustomEvent.

Thank you for this library!

**Comment by 1cg** [comment]
great idea, implemented and will be part of the 1.7 release (mid feb)

:beers:

**Comment by cb109** [comment]
Awesome, thank you :)

**Comment by carltongibson** [comment]
For anyone following along, this was merged as `detail.target` so you'd use `detail.target.checked` in the example here.
