### ISSUE TITLE
Can't make anchor tag trigger ajax request.

### ISSUE THREAD

**Issue by iustin94** [bigskysoftware/htmx#793]
Hi, I'm trying to get an anchor tag to create an hx-get request to update a partial view in my page. It seems however that an anchor tag will always end up triggering a normal request and update the whole viewport.

In my case, I have this anchor tag which issues a get request to the backend and I want it to swap the response with the contends of a div#generator element. What happens instead is that the whole viewport is being redirected to the contents of the response, as a normal hyperlink would do. I also tried switching the href with an hx-get, however that made the link unclickable. 

Is there something wrong in the way that I am trying it or is this expected behavior with HTMX? 
The HTMX version that I'm using is 1.6.1

![image](https://user-images.githubusercontent.com/13846875/152377464-ac944c47-92ec-4660-af92-268d364db44c.png)

**Comment by russellfeeed** [comment]
Try `hx-trigger="load"`
Works for me
