### ISSUE TITLE
[Question] How can I abort a request?

### ISSUE THREAD

**Issue by bobbyarcher** [bigskysoftware/htmx#796]
Similar question to [this](https://github.com/bigskysoftware/htmx/issues/340), but I tried the solutions suggested there to no avail. Apologies if I'm missing something obvious.

I have some dynamically created form fields which I'm using to set parameters for a hx-get request in htmx:configRequest:

`document.body.addEventListener('htmx:configRequest', function(evt) {
    // setting parameters here with evt.detail.parameters["key"] = value;
})`

While looping through my inputs, if any of them are empty, I want to abort the request, and alert the user. I've tried calling

`evt.detail.xhr.abort();`

but I just get the error "Uncaught TypeError: evt.detail.xhr is undefined"

**Comment by jreviews** [comment]
This should probably be in [discussions](https://github.com/bigskysoftware/htmx/discussions) and not posted as an issue. You can use `evt.preventDefault()` to cancel the request before it starts.

**Comment by 1cg** [comment]
In the upcoming release (1.7, mid feb) you will be able to send an `htmx:abort` event to an element to abort a request it is making.
