### ISSUE TITLE
Discourage use of unpkg.com

### ISSUE THREAD

**Issue by adamchainz** [bigskysoftware/htmx#800]
There are many reasons to avoid CDN's, as summarized [in this post](https://blog.wesleyac.com/posts/why-not-javascript-cdn). I'd like to update the htmx docs to:

1. only recommend unpkg.com for development/testing use
2. always recommend the subresource integrity and crossorigin=anonymous attributes, rather than as a "hey maybe you'd like to use them"
3. provide a direct download link to `htmx.min.js` to make it easy for self-hosting

What do you think?

**Comment by 1cg** [comment]
I'm good w/ that.  Please propose a PR.
