### ISSUE TITLE
Add time interval unit for minutes

### ISSUE THREAD

**Issue by mhadam** [bigskysoftware/htmx#807]
Correct me if I'm wrong, but time intervals are only defined in seconds (seems like you can put e.g. 1m, but it's interpreted as 1s).

It'd be nice to specify `every 2m` rather than `every 120s`.

**Comment by David-Guillot** [comment]
Hi @mhadam ,

You're right, htmx currently supports only `ms` and `s` for delays. See [the code](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L112-L123). It would be quite easy to add minutes support, so if you're willing to contribute and if @1cg is okay with it, feel free to do it 😉 . @1cg , would it be okay to you, or would you consider it too much sugar?

**Comment by 1cg** [comment]
added 'm' modifier for minutes
