### ISSUE TITLE
Scripts only loaded once between HTMX/Ajax requests

### ISSUE THREAD

**Issue by nfplee** [bigskysoftware/htmx#813]
I'd like to use this library but I can't get my head around executing scripts. The problem I have is once a script is loaded in the browser it is never loaded/executed again if you navigate from and back to the same page between HTMX requests. 

I currently use require JS which caches scripts from executing twice but I believe if I execute a script with type="module" (which I plan to convert to one day) the same happens.

For example say I have the following within my page `<script>require(['my-lib'])</script>` or `<script src="my-lib.js" type="module"></script>` where 'my-lib.js' looks like:

```
document.querySelector('.el').addEventListener('click', e => ...);
```

Then it will work the first time the page is executed but it won't for subsequent requests to the same page.

I did think about changing my script to:

```
document.addEventListener('click', e => {
    if (e.target.classList.contains('.el')) {
        ...
    }
});
```

However now this script will always be loaded and there may be pages when the event listener executes when I don't want it to.

I was wondering if anyone else has ran into the same problem and could share how they got around it or whether there's a feature in this library I've missed.

**Comment by WayneLambert** [comment]
Hi @nfplee ,

I use something like this in one of my projects to load a date picker using the Flatpickr library.

The way you handle this is through using the`htmx.onLoad` callback function. It works like this...

Imagine a button which makes an HTMX request to the server to return an HTML snippet which includes the HTML required for a date field.

```html
<button type="button"
        hx-target="#basic-info"
        hx-swap="this"
        hx-get="{% url 'hx_my_view' %}"
>
</button>
```

Make sure that your initial page contains the intialisation script within it before the closing `</body>` tag.

When you click on the button, that will call the `initialiseFlatpickr` function passing through the event as a possible argument for potential later use.

The JavaScript function needs to do whatever is required to initialise it. As an example, in terms of initialising a Flatpickr datepicker object, the function might start out as the snippet below. It will only fire when the full page is loaded.

```js
// Initialises a Flatpickr object for dates/times handling

(function initialiseFlatpickr(evt) {
    HSCore.components.HSFlatpickr.init('.js-flatpickr')
})()
```

You simply add the `htmx.onLoad` callback before the function and now the function will be called both on a new GET request to the page and also an AJAX request using HTMX. So the function now looks like:

```js
// Initialises a Flatpickr object for dates/times handling

htmx.onLoad(function initialiseFlatpickr(evt) {
    HSCore.components.HSFlatpickr.init('.js-flatpickr')
})()
```

Check out the [third party integration section of the docs](https://htmx.org/docs/#3rd-party).

**Comment by 1cg** [comment]
Thank you @WayneLambert that's exactly the right answer!  :beers:

**Comment by vkgautham** [comment]
@WayneLambert `htmx:onLoad` will fire for every node inserted into DOM and would result in multiple initialisations. A better approach is to use the `htmx:afterSettle` event listener as detailed here:
https://github.com/bigskysoftware/htmx/discussions/1158#discussioncomment-7365830
