### ISSUE TITLE
Some links ignored in 1.6.1. Works well in 1.6.0

### ISSUE THREAD

**Issue by mauricioarangoosorio** [bigskysoftware/htmx#817]
I upgraded to 1.6.1. Now htmx is ignoring some links (they behave as it htmx were not present). When I downgrade to 1.6.0 everything works again as expected. 

I created a [minisite](https://mauricioarangoosorio.github.io/issues/issue/index.html) to show the problem. Notice that clicks on the homepage link are ignored by htmx. But all the other clicks do work as expected. 

Cannot figure out why, but it is likely a big oversight on my end.

**Comment by aymericderbois** [comment]
Hi,

I have just tested your example, and on my side when I click on the link "Home", a request is correctly made by htmx. I just tried with Firefox and Chrome.

**Comment by mauricioarangoosorio** [comment]
Hi, yes, thank you for checking. 

The issue is that starting with HTMX 1.6.1 if a link has a targe="_self" attribute, HTMX ignores the link, so it is treated as a normal html element and the page navigates to the new content. 
I removed the target='_self' from the links and that's why it is working now. I'm not sure if this behavior was changed on HTMX 1.7. 

This is not an issue when one is creating a new project. But some text editors do add the target to links created on them. And it would be a pain in the neck to add HTMX to older projects that have lots of anchors with this attribute. I'm really hoping they modified it 1.7.

**Comment by David-Guillot** [comment]
Hi there,

It seems you @mauricioarangoosorio  opened PR #818 about this, and it's merged, but some wild back-merging seems to have occurred just before 1.7.0 release, and we don't know what's the status about this issue, as I don't even see either your commit in new `master` nor anything about it in the changerlog. @1cg could you tell us what happened here?

**Comment by David-Guillot** [comment]
Note: the behavior was changed by this commit: https://github.com/bigskysoftware/htmx/commit/ee2ed10cfa1324778b7dbd96d238b121fd7b6b3e

**Comment by 1cg** [comment]
fixed, thank you @David-Guillot for finding the issue
