### ISSUE TITLE
HX-Boosted Anchor Targets and History

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [bigskysoftware/htmx#827]
Not sure how to best recreate this, but it seems there's an issue with using `hx-boost` to targets on other pages, which perhaps involves something around https://github.com/bigskysoftware/htmx/blob/master/dist/htmx.js#L2577

Here's what seems to be happening on my machine:
1) Have a `/home/` page with a link to `/services/#speeches` that is HX-Boosted
2) Clicking on the link adds #speeches to the URL bar (`/home/#speeches`), then navigates to `/services/#speeches`
3) Clicking the browser Back button scrolls up the `/services/` page to the location of the initial link on the `/home` page and changes the URL to `/home/#speeches`, but the content of the page is still the `/services/` page.

**Comment by reedspool** [comment]
Maybe useful for debugging this: Are you serving those pages, accessing them with HTTP? Or are you accessing them locally? That is, does the URL start with `http(s)://` or `file://`?

**Comment by geoffrey-eisenbarth** [comment]
@reedspool I'm serving them (either Django dev server or nginx), I've never used true local (`file://`) in dev. I can PM you a link to a hosted dev version of the site if you have time to look into it (but no worries if not).

**Comment by geoffrey-eisenbarth** [comment]
I've figured out the cause of the issue, it has to primary causes:

The first cause has to do with setting `location.hash` (https://github.com/bigskysoftware/htmx/blob/master/dist/htmx.js#L2897) At this point, `location` is still referring to the initial page (the one containing a link to another page + anchor), and `responseInfo.pathInfo.anchor` is referring to an anchor on a separate page. To use the URLs of my initial comment, the result is that `location` is `/home/` and `responseInfo.pathInfo.path` is `/services/#speeches`, so therefore `responseInfo.pathInfo.anchor` is `#speeches` and as a result, we get `location = '/home/#services'` (which likely does not exist) instead of `location = '/services/#speeches'` (intended behavior).

The second cause has to do with the definition of `pathToPush` (https://github.com/bigskysoftware/htmx/blob/master/dist/htmx.js#L2920). The definition of this value is a bit convoluted, consisting of 

```
var pathToPush = pushedUrl || getPushUrl(elt) || getResponseURL(xhr) || responseInfo.pathInfo.finalPath || responseInfo.pathInfo.path;
```

I understand the importance of the initial `pushedUrl || getPushUrl(elt)`, but I'm unsure why: 
1) `getResponseUrl(xhr)` is preferred over just using `responseInfo`?
2) Why `pathInfo.finalPath` (which doesn't seem to contain the anchor) is preferred over `pathInfo.path` (which does seem to contain the anchor)?

It seems to me (based on my limited testing) that:
1) `getResponseURL(xhr)` will not contain the anchor (and has precedence over those options that do)
2) `pathInfo.finalPath` does not contain the anchor (and has precedence)
3) `pathInfo.path` DOES contain the anchor, but almost never gets assigned to `pathToPush` due to the previous options in the OR chain.

One way to solve the problem (although possibly not the best solution)
1) In line L2896: check to see if `location.pathname` agrees with something like `getResponseUrl(xhr)` (although not sure if `xhr` is available there). This would check to see if you're "staying on the same page" or "going to another page."
2) In line L2920: set `pathToPush = pushedUrl || getPushUrl || responseInfo.pathInfo.path` 

Another solution would be:
1) Move the setting of `location.hash` (L2897) inside of the `doSettle` function after the call to `pushUrlIntoHistory`

I'm down to submit a PR to address this issue (which has been brought up by a few people in the Discord) but I'm hoping for a little more guidance on my solution since I'm not familiar with the meat and bones of the source code.

Thanks!

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/issues/827, going out w 1.8, probably this week

**Comment by 1cg** [comment]
er, https://github.com/bigskysoftware/htmx/commit/7e7a5b43619d7b0cca27bde36302f1fc2aba17f6
