### ISSUE TITLE
How to pass submit type name to Django view on request.POST or hx-post

### ISSUE THREAD

**Issue by haradhansharma** [bigskysoftware/htmx#845]
Hi

My form has multi-button for different operations.  Some of the buttons are within the `form` tag, some are outside of `form`.  To control each operation separately I have to pass the name attr. of submit type. It is either button or input type. Using basic HTML can pass easily but when trying to use hx-post it is not passing the name. Is there any way in Htmx to pass the name to control separately?

**Comment by haradhansharma** [comment]
finally, I am doing with the `hx-vals `and form id is `hs-post`

**Comment by David-Guillot** [comment]
Hi there,

Have you checked out the value of HTTP headers named `HX-Trigger` and `HX-Trigger-Name`? If the element that triggers has `id` or `name` attribute, you should see them on server-side through these :wink: 

If it's not the case, please post here a minimal example.

**Comment by 1cg** [comment]
you can probably put an `hx-vals` tag on the button to add additional context, or take @David-Guillot 's suggestion of looking at the headers

either one should work
