### ISSUE TITLE
should_cancel takes 2 parameters, only supplied 1 by ws.js (htmx 1.7.0)

### ISSUE THREAD

**Issue by KenWhitesell** [bigskysoftware/htmx#846]
This is throwing an error at line 1198 when the event is a form submission.

Working with the uncompressed htmx.js file, [line 1196](https://github.com/bigskysoftware/htmx/blob/b4c83ca811109c4bf62e45a29f3ee3813f1491e2/dist/htmx.js#L1196) has the  definition of shouldCancel, taking two parameters, evt and elt.

The ws.js extension calls shouldCancel at [line 204](https://github.com/bigskysoftware/htmx/blob/b4c83ca811109c4bf62e45a29f3ee3813f1491e2/dist/ext/ws.js#L204), passing only one parameter.

**Comment by benpate** [comment]
Thank you for reporting this.  I believe I fixed this in another bugfix.
