### ISSUE TITLE
Behavior change in extension in v 1.7 with nested attributes.

### ISSUE THREAD

**Issue by marcus-at-localhost** [bigskysoftware/htmx#847]
I've built an extension that adds a custom hx-trigger attribute to a `form[hx-post]` tag. Inside the form tag is a `<a hx-get="/remote" hx-trigger="load">Click</a>` tag, that loads a document on loading the main page with the form (some sort of lazy loading).

In version 1.7 the extension throws an error, because at some point, the extensions evaluates all elements inside the form and chokes on a text node (I believe right before the `hx-get="/remote"` gets swapped out).

Here is a screenshot and a working example: https://codesandbox.io/s/sad-tereshkova-d97itq - I stripped it down to illustrate my case.

![image](https://user-images.githubusercontent.com/1337223/155892551-78896a9d-a63e-49a0-ae76-1faf80328df0.png)

If I change the nested `hx-swap="innerHTML"` to `hx-swap="outerHTML"` it works. 

I thought `hx-disinherit` could help here, but it doesn't do anything.

For now, I helped myself with checking the node type (commented out in the example), but it was quite unexpected when I updated the htmx library. Not sure if I did something wrong in how I wrote the extension, or if there is a bug somewhere.

Thanks for looking into it!

**Comment by 1cg** [comment]
we may trigger events on text nodes (e.g. top level text content added to the DOM) so that's something to check for.  If you expect a form here I'd look for it explicity.
