### ISSUE TITLE
Data-tables and pagination support

### ISSUE THREAD

**Issue by wilberninsiima** [bigskysoftware/htmx#850]
I have been using the Data-tables library for paginating data rendered on the page.
I recently integrated HTMX into my system for partial content loading. However, there is a problem in incorporating HTMX and data tables library.
Your response is welcome

**Comment by GitRon** [comment]
Actually, I have the same issue. I am using HTMX to avoid custom JS/jQuery -  but I cannot tell my partial to make the html table to a jquery datatable without some really mean piece of JS-code. Is there a way to add a callback or so, this would at least lessen the pain.

**Comment by benpate** [comment]
It sounds like you need to tell your javascript library that there's new content it should process.  I'm not familiar with Data-tables, but most JS libraries like this will scan everything when they first load, and will then have another function that you can call manually to "kick" it into processing new content.

Try adding an event listener for `htmx:afterSwap` and call the init code for your external javascript library in there.

**Comment by GitRon** [comment]
@benpate Works like a charm 👍

**Comment by 1cg** [comment]
thank you @benpate !

**Comment by jvanzyl** [comment]
@GitRon Might you still have a snippet of what you did?

**Comment by GitRon** [comment]
@jvanzyl Sure thing.

```jinja
{% block js %}
    <script type="text/javascript">
        document.body.addEventListener('htmx:afterSwap', () => {            
           // Do your JS thing, like casting a table etc.
        });
    </script>
{% endblock %}
```

Hope it helps.
