### ISSUE TITLE
ws.js doesn't update multiple divs

### ISSUE THREAD

**Issue by KenWhitesell** [bigskysoftware/htmx#857]
Situation: HTML being returned by server through websocket to HTMX containing two top-level divs with id attributes.
Example:
```
<div id="area-1">Area 1 text</div>
<div id="area-2">Area 2 text</div>

```
ws.js updates the first div, does not update the second.

It appears to me that the problem is caused in the area around line 160:
```
if (fragment.children.length) {
	for (var i = 0; i < fragment.children.length; i++) {
		api.oobSwap(api.getAttributeValue(fragment.children[i], "hx-swap-oob") || "true", fragment.children[i], settleInfo);
	}
}
```
The issue looks like something in the oobSwap function is deleting "fragment.children[i]". (If you look at fragment.children before and after the loop, you will see that the first element has been removed.) This is changing the size of the array, so after the first one has been processed (and deleted) and i is incremented, it is now equal to fragment.children.length and the loop exits.

I believe there are two possible solutions to this.
- Iterate backward through the fragment array. (Something like `for (var i = fragment.children.length - 1; i >= 0 ; i--)`)
- Copy the elements and process the copies.
What I tried:
```
fragments = Array.from(fragment.children);
for (const a_fragment of fragments) {
    api.oobSwap(api.getAttributeValue(a_fragment, "hx-swap-oob") || "true", a_fragment, settleInfo);
}
```

I didn't dig into oobSwap because I figured it works the way it does for other purposes within htmx, and so changes to that wouldn't be appropriate without a lot more testing.

**Comment by 1cg** [comment]
fixed thanks to @Renerick!
