### ISSUE TITLE
ws.js doesn't connect ws-send attributes in new elements

### ISSUE THREAD

**Issue by KenWhitesell** [bigskysoftware/htmx#859]
When "active" html elements (buttons, or anything with a "ws-send" attribute) are added via websocket, the triggering events are not connected to the websocket to send data.

This one doesn't appear to have a quick fix - at least I haven't found one yet. I tried adding a call to `processWebSocketSend` within the `socket.addEventListener('message', ...` function, but that ends up with multiple instances of the event listener getting registered, causing multiple `ws-sends` to happen.

To solve _my_ issue with this, I took the brute-force approach and removed all event listeners for elements with a "ws-send" attribute and then called the processWebSocketSend function on those same elements.

I'm sure this isn't the best way to handle it, but I couldn't come up with something better.

So now the end portion of my function looks like this:
```
...
api.settleImmediately(settleInfo.tasks);

ws_send_elements = Array.from(document.querySelectorAll("[ws-send]"));
ws_send_elements.forEach(element => {
    element.replaceWith(element.cloneNode(true));
});

forEach(queryAttributeOnThisOrChildren(elt, "ws-send"), function(child) {
    processWebSocketSend(elt, child);
});
```

**Comment by 1cg** [comment]
fixed thanks to @Renerick!
