### ISSUE TITLE
Move X-HTTP-Method-Override tunneling feature into an extension

### ISSUE THREAD

**Issue by Conal-Tuohy** [bigskysoftware/htmx#86]
In some places the htmx documentation claims to support other HTTP methods, but in fact only GET and POST are used. If an htmx client page attempts to use a different method (e.g. PUT or DELETE), htmx uses the POST method instead, and the actually desired method is sent in an HTTP header called `X-HTTP-Method-Override`.

It appears that the use of the header is designed as a 'hack' or workaround for a situation in which htmx is a front-end on a back-end service which uses one of these HTTP methods, but which is deployed behind a firewall which blocks those methods. The workaround allows these requests to tunnel through the firewall to another proxy which then changes the method and finally forwards the request to the back end service. 

The fact that this tunneling feature is a mandatory part of htmx's core makes it necessary to set up a proxy for any server software which uses methods other than GET and POST, even in circumstances where there's no reason for it. 

In order to make the tunneling feature optional, I believe the code should be removed from the htmx core, and re-packaged as an `http-method-override` extension (like the `json-enc` extension). That way anyone who actually needed to tunnel through an enterprise firewall could include the extension in an architecturally clean manner, but it would not interfere with the general case in which people just want to use HTTP in a normal way.

See also https://twitter.com/conal_tuohy/status/1265926740049715201 for background.

**Comment by cscortes** [comment]
This seem very reasonable to me.  I actually had to "hack" flask to get all my server side code to work with htmx samples that used "put". Include it only if you need it, in my "flask" cases I really didn't need it and it caused me extra work on the server side.  If it was an extension, then no additional server side code, and actually "less" code on the client side -- WIN/WIN!

**That might also be a great "guiding light" rule for extensions.  If a feature is not really needed by everyone or "fixes" something on some servers or cases, then maybe consider it an extension candidate.** 

Just my 2 cents, but I will take a look at the code and see how hard it might be to pull that feature out.

**Comment by chg20** [comment]
Fixed for next release
