### ISSUE TITLE
Source Maps Support

### ISSUE THREAD

**Issue by sharmando** [bigskysoftware/htmx#860]
Not urgent, but probably useful.

# Related Links
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

https://github.com/ryanseddon/source-map/wiki/Source-maps%3A-languages,-tools-and-other-info

**Comment by 1cg** [comment]
Since htmx is single file written in vanillajs, you can just include the non-minimized version to debug.

Is that good enough?

**Comment by 1cg** [comment]
Calling it good, we should probably do this for hyperscript though 😑
