### ISSUE TITLE
Further CSP issue: style-insertion

### ISSUE THREAD

**Issue by martin-lueders** [bigskysoftware/htmx#862]
I am currently trying to make my web page, using django and htmx, CSP compliant, and ran into the following problem:
Including the line 
```
<script src="{% static 'js/htmx.js' %}"></script>
```
in the base template, seems to insert the following into the HTML:
```
<style>                      .htmx-indicator{opacity:0;transition: opacity 200ms ease-in;}                      .htmx-request .htmx-indicator{opacity:1}                      .htmx-request.htmx-indicator{opacity:1}                    </style>
```
This, on the other hand leads to the issue:
```
htmx.js:3064 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-d7rFBVhb3n/Drrf+EpNWYdITkos3kQRFpB0oSOycXg4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```
The [google developers documentation](https://developers.google.com/web/fundamentals/security/csp#inline_code_is_considered_harmful) argues strongly against using inline styles. 

Is there any way to use htmx without the need of the 'unsafe-inline' settings for CSP?

(I am using the htmx.js from the git repository, commit 9e3d33f90d495b0415160462333e999fb10a12fa)

Thanks,
Martin

**Comment by lmcnearney** [comment]
You can set `htmx.config.includeIndicatorStyles` to `false` so it doesn't inject the inline styles and then add those styles manually to your site's CSS.

**Comment by Lueders-Martin** [comment]
Thanks. In a django environment, where would I have to put this setting?

**Comment by 1cg** [comment]
Thank you @lmcnearney that's exactly the right solution: turn off the auto-inclusion of styles

**Comment by TheJanzap** [comment]
There doesn't seem to be a good workaround for using both `.htmx-indicator` and CSP without inline-styles (besides just copying `.htmx-indicator` into a CSS source that is allowed per CSP, but that doesn't look like a clean solution to me).
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src) there are other ways to either safely use inline CSS or change CSS via JS. But they also seem like hacky workarounds in this case. So I guess the solution above is the best way to deal with this?
