### ISSUE TITLE
Running Safari with "Block all Cookies" breaks htmx

### ISSUE THREAD

**Issue by alfonsrv** [bigskysoftware/htmx#866]
Running Safari with setting "block all cookies" breaks htmx, due to "insecure operations" Safari is blocking.

Unfortunately since JavaScript and htmx basically runs, the default fallback (e.g. submitting a form the regular way) doesn't get executed instead.

![safari](https://user-images.githubusercontent.com/48770755/159880964-c8f1e763-b3d1-4f45-97b0-daa41ba0925f.png)

One of them seems to be related to `S(localStorage.getItem("htmx-history-cache"))` – tried both en-/disabling the history using `<meta name="htmx-config" content='{"historyEnabled":false, "refreshOnHistoryMiss": false}'>`, but that didn't change the behavior.

**Comment by David-Guillot** [comment]
Hi there,

Yes, "Block all cookies" feature also blocks `localStorage` (called "other data" on [this user guide](https://support.apple.com/guide/safari/manage-cookies-sfri11471/mac)). htmx should ensure `localStorage` is available. I'll open a PR about this right away.

**Comment by 1cg** [comment]
thank you @David-Guillot !
