### ISSUE TITLE
Onload script performance

### ISSUE THREAD

**Issue by oko-x** [bigskysoftware/htmx#87]
For a page with extensive DOM, the onload performance is not ideal. I understand it is needed for features like 'hx-boost' but for basic usage it is not needed. For capturing the click events global window listener could be sufficient.

To reproduce: Check Chrome Dev Tools main thread work for page with 4K+ DOM elements on load.

**Comment by turbopixel** [comment]
Same here. I have an HTML page with a table with 300 rows. There are two select fields per line. The page loads in 1.2 seconds. With htmx Firefox needs a total of 17 seconds to render the page.

**Comment by chg20** [comment]
OK, I have added a perf test for a large number of DOM elements:

        var str = stringRepeat("<div>", 30) + stringRepeat("<div><div><span><button hx-get='/test'> Test Get Button </button></span></div></div>\n", 3000) + stringRepeat("</div>", 30);


This creates 30 nested divs with 3000 internal double divs, with a span and then a button in it.

Right now this runs on my machine in 285ms-350ms.  I have a good machine (a recent system 76 laptop) but that isn't anywhere near 17 seconds.

I plan on addressing the full DOM scan but I also want to understand how this could be getting out to 17 seconds.  Seems like there may be an O(n^2) issue somewhere that my test isn't capturing?

**Comment by chg20** [comment]
Do the selects have a lot of values in them as well?  Can you post what the HTML looks like somewhere so I can inspect it?

**Comment by chg20** [comment]
I have a branch with a selector-based perf improvement.  I was able to improve the performance by about 3x, got a 3000-row set of nested divs and buttons down to 100ms from 300ms in firefox, and 400+ms in Chrome down to just over 100ms.

This is still nowhere near the numbers you guys are seeing though, and it does have an effect on the extensions mechanism.  I'm hesitant to go with this unless it really addresses the HTML you guys have.  

Could I ask you to post the HTML so I can run htmx against it and see what happens?

**Comment by chg20** [comment]
see change https://github.com/bigskysoftware/htmx/commit/b07ed32dc4fe7338c7ddabb4858a88f23ed30b0b

Improves load time by 3x on my synthetic test.  Could be a lot more if there are few selector matches in a large document.

**Comment by chg20** [comment]
OK, perf improvements are going out on Friday.  Still need to know if this is good enough for what you guys have, or if it is even possible to optimize for what you have.  Let me know.

**Comment by turbopixel** [comment]
Unfortunately I can't publish the HTML code because there is too much business information in the table.

Yes the one select box has about 1200 options. The other two selectboxes have only three and 20 options. (I know this is not optimal yet.)

The table has about 800 rows. The structure is as follows:
| text | text | text | select*20 options | select*1200 options | text | | text

Only two CSS files and the HTMX script are loaded in the HTML document. 

**Runtime with javascript:**

![grafik](https://user-images.githubusercontent.com/15839724/84988346-25e5da80-b142-11ea-9fd1-bcd788b8d712.png)

**Runtime without javascript**

![grafik](https://user-images.githubusercontent.com/15839724/84988396-38601400-b142-11ea-9677-eaff46cf7a9e.png)

(You can find the firefox runtime addon here: https://github.com/meetDeveloper/Quick-JS-Switcher)

**Comment by turbopixel** [comment]
I will try to make my table smaller and the selectboxes smaller as well.

Interestingly, the page only reloads quickly again when I remove the htmx.min.js. If I remove hx-* attributes from the selectbox, the loading time remains the same.

**Comment by chg20** [comment]
Can you try using the htmx file out of the dev branch and see if it improves performance?

https://raw.githubusercontent.com/bigskysoftware/htmx/dev/src/htmx.js

**Comment by chg20** [comment]
Yeah, it uses selectors now to pull out only items explicitly marked up.  If you have a ton of elements marked up w/ htmx there will still be issues though.

**Comment by cscortes** [comment]
I don't know if this helps, but I wrote a little flask file that creates a "fake" data version of the 800 rows, 20 select, 1200 select web page.  If it helps ill be happy to upload it or send it to whoever it interested.

**Comment by turbopixel** [comment]
Hey @chg20 
the version from https://github.com/bigskysoftware/htmx/issues/87#issuecomment-646024977 is better. My page load faster than before.

**Comment by chg20** [comment]
Ok it is using selectors so it is about as fast as possible now
