### ISSUE TITLE
add hx-trigger throttle

### ISSUE THREAD

**Issue by ssendev** [bigskysoftware/htmx#88]
Hi I implemented a volume control with `<input type="range" min="0" max="100" name="volume" hx-post="/volume" hx-trigger="input changed delay:200ms" hx-target="#display-none">`

It would be nice if `hx-trigger` accepted a `throttle:200ms` argument because like it is now the volume changes only when one stops moving and not while the volume is changed.

**Comment by chg20** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/1f6254109465009ef6cae3f1b948aac01dc0a7f1
