### ISSUE TITLE
hx-trigger with load after:n clause generates (maybe spurious) syntax errors

### ISSUE THREAD

**Issue by netaisllc** [bigskysoftware/htmx#881]
### Case

Using `hx-trigger="load after:100ms"` results in `htmx:syntax:errors` in the console, even though the code appears to execute correctly.

- Low priority

### Repro
To repro: access https://htmx.org/examples/tabs-hateoas/ (using Chrome, MacOS) and inspect the dev console.

### Investigation
Errors are thrown by `function getTriggerSpecs( elt )` here 

```
if ( tokens.length === initialLength ) {
   triggerErrorEvent( elt, "htmx:syntax:error", { token: tokens.shift() } );
}
```

### Other

I first saw this in my own code; as an htmx beginner this concerned me for awhile until I decided to checkout the example page.

Maybe this situation warrants a warning in lieu of an error? IDK.

**Comment by 1cg** [comment]
That actually is a syntax error, the correct syntax is `delay:100ms`  :)

I have fixed the example!
