### ISSUE TITLE
Document that you need to add an extra JavaScript file when using extensions

### ISSUE THREAD

**Issue by wimdeblauwe** [bigskysoftware/htmx#885]
It was not clear to me from the docs at https://htmx.org/docs/#extensions that you need an extra JS included when you want to use an extension (like SSE support). Also the https://htmx.org/extensions/server-sent-events/ page makes no mention of this.

I also noticed that htmx itself has a minified version (`htmx.min.js`), but the extensions do not have this (only `ext/sse.js` for example).

**Comment by wimdeblauwe** [comment]
The minification issue has a separate issue https://github.com/bigskysoftware/htmx/issues/1089

**Comment by 1cg** [comment]
@Renerick has fixed this for us!
