### ISSUE TITLE
Don't load all DB records after performing delete in HTMX

### ISSUE THREAD

**Issue by ljfreelancer88** [bigskysoftware/htmx#886]
I know, the title seem odd. But that's my concern when reading and watching tutorials using HTMX.

Watching this tutorial [https://www.youtube.com/watch?v=qk1gVbnaOAc](https://www.youtube.com/watch?v=qk1gVbnaOAc&list=PL-2EBeDYMIbRByZ8GXhcnQSuv2dog4JxY&index=4). He loads all the DB records & render it in a partial html after deleting an item. The problem here is, this is not good approach when you have a lot of records.

Given on the example below. Say, I want to delete the `Hope` record.
Is it possible to DELETE the record then HIDE the parent or closest `<li>` element of Delete button in htmx way?
No swapping element etc. Just do what I intented to do which is DELETE. Not DELETE then LOAD.

```html
<ul>
<li>Hope [Delete]</li>
<li>Faith [Delete]</li>
<li>Love [Delete]</li>
</ul>
```

**Comment by David-Guillot** [comment]
Hi there,

Is [this](https://htmx.org/examples/delete-row/) what you're looking for? It says:
> This request responds with empty content, indicating that the row should be replaced with nothing.

**Comment by ljfreelancer88** [comment]
Yes it is! Thank You.
