### ISSUE TITLE
How to trigger multiple requests on button click? 

### ISSUE THREAD

**Issue by rajasimon** [bigskysoftware/htmx#889]
I need to make a multiple requests in parallel when button clicked. 

```
<button>Click<button>

<div hx-get="/call1">
<div hx-get="/call2">
<div hx-get="/call3">

```

How do I do that using HTMX?

**Comment by David-Guillot** [comment]
Hi there,

I think [hx-trigger](https://htmx.org/attributes/hx-trigger/) 's `from:<Extended CSS selector>` modifier can help you 😉

**Comment by poly2it** [comment]
> Hi there,
> 
> I think [hx-trigger](https://htmx.org/attributes/hx-trigger/) 's `from:<Extended CSS selector>` modifier can help you 😉

???

The issue is that there should be a way to send multiple hx-get requests on one click.

**Comment by David-Guillot** [comment]
> > Hi there,
> > I think [hx-trigger](https://htmx.org/attributes/hx-trigger/) 's `from:<Extended CSS selector>` modifier can help you 😉
> 
> ???
> 
> The issue is that there should be a way to send multiple hx-get requests on one click.

And there is, thanks to the `from:` modifier. In the given example, if you set id="gogogo" on the button, you can set `hx-trigger="click from:#gogogo"` on each of the three divs, they will all trigger their own request, resulting in 3 separate requests from a single click.
