### ISSUE TITLE
add hx-swap ignore

### ISSUE THREAD

**Issue by ssendev** [bigskysoftware/htmx#89]
In #88 I also had the problem that the focus is lost (#75).

For now I worked around it with a target that has `display: none` which makes the changes invisible but adding a `hx-swap="ignore"` option could make implementing actions that don't change the html easier.

**Comment by chg20** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/4ef719e63a98ee53c7f6490ab3289fb1d0dd596c

**Comment by ribeiropaulor** [comment]
Hi!

hx-swap="none" does not appear on the docs: https://htmx.org/attributes/hx-swap/ . I can see that the pull request included the docs modification. It somehow got lost.
