### ISSUE TITLE
HTMX pass button value from selected list

### ISSUE THREAD

**Issue by smailt** [bigskysoftware/htmx#892]
I'm trying to make an application with Django using htmx. I have created a dropdown list as:

```
<select class="custom-select mb-4" name="fields" hx-get="{% url 'select_field' %}" hx-trigger="change" hx-target="#Wells">
            <option selected>Select a field</option>
            {% for Field in TFTFields %}
            <option ue="{{Field.Perimeter}}">{{Field.Perimeter}}</option>
            {% endfor %}
 </select>
```

Now I want to take the selected value from this list and pass it to a button to excite another function called "plotlybar", I did something like this:

```<button class="btn btn-primary" hx-get="{% url 'plotlybar' %}" hx-target="#plotlybar">Plot the bar Well **Serv</button>```

So now I didn't know how to pass this selected item? any hints or solutions?

All my best

**Comment by 1cg** [comment]
you want to use the `hx-include` attribute to include the select value in the button: 

https://htmx.org/attributes/hx-include/
