### ISSUE TITLE
Disabling checkbox sends empty request

### ISSUE THREAD

**Issue by PMunch** [bigskysoftware/htmx#894]
I was writing a small dashboard for my home automation system and decided to try out HTMX. The first interactive element I added was a checkbox (styled as a switch toggle by CSS). I added a `hx-post` attribute and a `name` property (the requirement on the latter wasn't obvious from the documentation, but that might just be because I skimmed over that part). Now when I click the checkbox it will send `autolights=on` whenever I enable the checkbox, but just an empty body whenever I disable it which is a bit confusing. Here is a minimal site to reproduce the issue:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>
  </head>
  <body>
    <div class="container">
      Automatic light dimming <input type="checkbox" role="switch" name="autolights" hx-post="/autolights" checked="">
    </div>
  </body>
</html>
```

Am I doing something wrong here or is this the expected behaviour?

EDIT: For completeness here is the small Nim server I used to test this minimal site:
```nim
import jester

routes:
  post "/autolights":
    echo request.body
    resp Http201, "Created"
  get "/":
    resp readFile "testpage.html"
```

**Comment by David-Guillot** [comment]
Hi @PMunch ,

You're doing it right 😜 . AFAIK this behavior is compliant with what happens when submitting a form with an `input type="checkbox"`. Here's what [the MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value) says about it:
> Note: If a checkbox is unchecked when its form is submitted, there is no value submitted to the server to represent its unchecked state (e.g. value=unchecked); the value is not submitted to the server at all. If you wanted to submit a default value for the checkbox when it is unchecked, you could include an [<input type="hidden">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden) inside the form with the same name and value, generated by JavaScript perhaps.

Should htmx be the one who generates this `input type="hidden"`? I don't see why, as it cannot assume how your server handles checkbox values (is it expecting `"on"`/`"off"`? or just defined/undefined?)

**Comment by 1cg** [comment]
yes, the behavior of checkboxes is very unintiutive, but htmx does behave in the standard manner here

**Comment by PMunch** [comment]
@David-Guillot totally forgot to respond, but this makes a lot more sense now. Is this something which is explained anywhere in the documentation? If not I think this should be kept open to track the issue of not explaining this clearly in the docs.

**Comment by raratiru** [comment]
@David-Guillot  Thank you!

```html
<input id="{{ obj.id }}"
                   type="checkbox"
                   name="{{ obj.id }}"
                   hx-get="/the/url/"
                   hx-include="[name='{{ obj.id }}']"/>
<input type="hidden" name="{{ obj.id }}" value="off"/>
```
The above jinja template produces:
* `/the/url/?21=on&21=off` when checked
* `/the/url/?21=off` when unchecked

**Comment by halldorrt** [comment]
Sorry to add to a closed issue, but I think this alternative solution might be helpful for people that come across this in the future.

I ran into the same issue and found [hx-vals](https://htmx.org/attributes/hx-vals/) in the docs. I used the code below to get my checkbox state in my request body.

```html
<input
	name="purchased"
	type="checkbox"
	if i.Purchased {
		hx-vals='{"purchased": "false"}'
		checked
	} else {
		hx-vals='{"purchased": "true"}'
	}
	hx-patch="/some-url"
/>
```

Hope this helps
