### ISSUE TITLE
Only the first part of my ws response is processed, is that normal?

### ISSUE THREAD

**Issue by Gys** [bigskysoftware/htmx#904]
My client html code is like this:

        <div hx-ext="ws" ws-connect="ws://localhost/xxxx">
                <div id="eventstatus" hx-select="#eventstatus">Checking...</div>
                <div id="meetings" hx-select="#meetings"></div>
        </div>

The htmx websocket connects correctly to the backend and receives this data:

        <div id="eventstatus">STATUS</div><div id="meetings">MEETINGS</div>

I assumed this would change both #eventstatus and #meetings. But it only changes the content of #eventstatus. The second div is ignored completely.

I also added logging on the client:

        htmx.onLoad(function (elt) {
            console.log("receiving data", elt)
        })

This also just shows the first div of the data, the #eventstatus part. The last part is not shown.

If I change the order of the divs in the data, I see the same pattern again. Then also only the first div is processed, being `<div id="meetings">MEETINGS</div>`.

I tried adding `hx-select="#meetings"` to the source code and `hx-swap-oob="true"` to the data, but that did not solve this.

So I wonder if this is intentional? Is the websocket connection not meant to process multiple data elements? Or am I missing something?

**Comment by KenWhitesell** [comment]
Is this the same as the problem reported at (https://github.com/bigskysoftware/htmx/issues/857)? If so, it looks like there's a fix in the works.

**Comment by Gys** [comment]
Indeed. Sorry that I missed that. Thank you!

**Comment by KenWhitesell** [comment]
(You may want to close this issue if it's no longer needed.)
