### ISSUE TITLE
Different target according to response?

### ISSUE THREAD

**Issue by ddahan** [bigskysoftware/htmx#905]
I'm building a simple Event subscription tool that basically looks like:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1933516/167683973-a7519eda-9c6a-4b75-ad39-4c5e3864eac0.png">

When I want to edit, then save a participation for a specific user, there are 2 different cases:
1. if the submit fails (eg: wrong information provided) -> the form must be displayed with errors in it:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1933516/167684092-5066a6e0-e15c-4124-ae22-76f5fd13afc6.png">

2. if the submit succeeds, it should like this:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1933516/167684190-21391c58-8a44-40d7-9709-e82a9a67eba2.png">

## My problem

As you probably noticed, the target to change information is not the same:
- In case 1 (submit failed and returns form + error forms), the `x-target` attribute should be the form itself
- In case 2 (submit suceeds), the `x-target` attribute should be at a higher level, since lots of data has changed.

How do you solve a use case like this with HTMX?
It seems there is no way to tell htmx "if my response is A, the target is X, if my response is B, the target is Y".

Thanks a lot.

**Comment by gone** [comment]
You can use the hx-retarget response header for this I think: https://htmx.org/reference/#response_headers

**Comment by gone** [comment]
Actually there was a good discussion on the discord around this - https://discord.com/channels/725789699527933952/864934037381971988/971824567637147698

The core was defining a dictionary on the view that mapped targets (given through hx-target request header) as the key and template/retargets as the value.
