### ISSUE TITLE
How to prevent logging errors on Firefox console?

### ISSUE THREAD

**Issue by tardigrde** [bigskysoftware/htmx#906]
We have a GET request which takes around 5-10 sec to execute, we call this with htmx. If we reload the page, the request is aborted and on load the request is sent again automatically. In this case we get the following errors:
![image](https://user-images.githubusercontent.com/32789141/167802800-9c868775-c00e-482e-93f5-82e8ec5be993.png)

This is a result of two reloads.

This is only logged in Firefox browser, and not chromium-based ones. Any idea why is this happening? 
Or how could we suppress  these logs? `.preventDefault()` did not work.

**Comment by 1cg** [comment]
unfortunately htmx is going to log any errors that the system throws and it sounds like Firefox is aggressive in throwing aborted errors on a refresh

you can set up your own logger by setting `htmx.logger` explicitly, but that would be a lot of work for what seems to me to be a minor issue.  Your call though, the extension point is there.
