### ISSUE TITLE
HX-Boost should respect native `enctype` attribute if present in a form tag

### ISSUE THREAD

**Issue by codepilotsf** [bigskysoftware/htmx#908]
When using `hx-boost`, a totally native HTML form tag like this should still work correctly:
`<form method="post" action="/upload" enctype="multipart/form-data">`

It is unexpected (and difficult to debug) behavior when the form refuses to submit multipart as expected because `hx-boost` converts it to an AJAX request which then requires an `hx-encoding` attribute rather than `enctype`. 

Proposed solution: HX-Boost currently converts native HTML in anchor tags and form tags to make an AJAX request instead. In addition to attributes such as `href`, `method`, `action`, HX-Boost should also respect `enctype`.

**Comment by 1cg** [comment]
Fixed, thanks for your help!

**Comment by codepilotsf** [comment]
Wow, thank you for publishing a fix in under an hour!!
