### ISSUE TITLE
HX-Trigger Response Headers not triggering on initial page load

### ISSUE THREAD

**Issue by not-rusty** [bigskysoftware/htmx#922]
I'm not sure if this behaviour is intended, but it is a bit confusing that the events listed in the json from hx-trigger header won't trigger on initial page load.

Any ideas?

**Comment by 1cg** [comment]
The initial load is not via htmx, but rather via your normal browser request mechanism, so we don't get a chance to process the headers unfortunately.  I don't see a good way around this.  Sorry about that.
