### ISSUE TITLE
hx-trigger triggers only once and then shows errors in console

### ISSUE THREAD

**Issue by COMR4D3B451L** [bigskysoftware/htmx#923]
My code: 
`<input type="search" id="search" name="search"
                             hx-post="/patientsearch/"
                             hx-trigger="keyup delay:500ms, search"
                             hx-target="#result-text"
                             hx-swap="outerHTML"
                             hx-indicator=".htmx-indicator"/>
<span id="result-text" name="result-text" class="dark:text-rose-100"></span>`

Console error:
`htmx:targetError
pt @ htmx.org@1.7.0:1
$ @ htmx.org@1.7.0:1
J @ htmx.org@1.7.0:1
Z @ htmx.org@1.7.0:1
(anonymous) @ htmx.org@1.7.0:1
setTimeout (async)
i @ htmx.org@1.7.0:1`

**Comment by David-Guillot** [comment]
Hi @COMR4D3B451L ,

Are you sure that the call to `POST /patient search/` does return an HTML fragment which root element has `id="result-text"`? Since you're swapping on `outerHTML`... The error clearly states an error about target, not trigger 😉

**Comment by COMR4D3B451L** [comment]
Hi @David-Guillot ,
Yes it returns a string for the search result. and it always works the first time. But when I try to change the search form it does not return anything, it shows the error above instead.

**Comment by David-Guillot** [comment]
Have you tried removing `hx-swap=""outerHTML`? The default is to swap innerHTML and that may solve your problem...

**Comment by COMR4D3B451L** [comment]
@David-Guillot You are a legend, it worked now. Thank you very much for the help!

**Comment by 0mercjh** [comment]
> Have you tried removing `hx-swap="outerHTML"`? The default is to swap innerHTML and that may solve your problem...

bro you are a lifesaver............😭
