### ISSUE TITLE
hx-params="*" not working for hx-get

### ISSUE THREAD

**Issue by itamar-nabriski-healthy** [bigskysoftware/htmx#925]
I don't seem to be able to include the `hx-params` in an `hx-get` request per the docs:
https://htmx.org/attributes/hx-params/

Here is a minimal example:
```
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <script
      src="https://unpkg.com/htmx.org@1.7.0"
      integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo"
      crossorigin="anonymous"
      defer
    ></script>
  </head>
  <body>
    <form>
      <input id="field" name="field" type="text" value="value" />
      <button hx-get="/some-request" hx-params="*">Button</button>
    </form>
  </body>
</html>
```
The input named ```field``` is not added as a query parameter to the get request even though it's part of the enclosing form.

**Comment by David-Guillot** [comment]
Hi @itamar-nabriski-healthy 🙂

What if you move the `hx-get` attribute to the `<form>` element, and make the button a `type="submit"` one? I think that way you wouldn't even need `hx-params`...

**Comment by itamar-nabriski-healthy** [comment]
Hi @David-Guillot,

Guess that would work but the real case scenario I need it for is a table with search, filters, sorting, paging etc. where I want each action to include the present state of the table. Thus, if I move to the next page I want the current sorting to be included in the request.
I did find a workaround for it using ```hx-include``` but I think the best way is with ```hx-params```.

Also, I wanted to report this as a bug as, unless I've missed something, the behaviour is not aligned with the docs.

**Comment by David-Guillot** [comment]
My understanding of `hx-include` and `hx-params` is that the former is used to bring some values from outside of the triggering element (in addition to values from within the element), while the latter is used to select values from within the element (in order to reduce what is sent to the server). This is why I recommended none of them with a smart `hx-get` placement, but with your real use case clearly `hx-include` is the way to go 👍 . I don't think there is a bug here, but maybe some unclear documentation...

**Comment by ant1fact** [comment]
> Hi [@itamar-nabriski-healthy](https://github.com/itamar-nabriski-healthy) 🙂
> 
> What if you move the `hx-get` attribute to the `<form>` element, and make the button a `type="submit"` one? I think that way you wouldn't even need `hx-params`...

I'm new to htmx and I am so grateful for this nearly 3-year-old comment :D
