### ISSUE TITLE
Make htmx Tags work in HTML coming in late via e.g. jQuery AJAX

### ISSUE THREAD

**Issue by cb109** [bigskysoftware/htmx#931]
## I'd like to use htmx on top of our AJAX based frontend

Our internal frontend is based on some initial page rendered by Django, but then most UI interactions will reload only parts of that page via jQuery AJAX requests (think a list of things on the left and a detail view on the right). This is a more traditional custom/hybrid setup: htmx would make a good replacement for it, but I am instead trying to introduce it **on top** to see some adoption and then see how it fits for us. 

### Problem & Workaround as visuals

![jquery_ajax_html_with_htmx](https://user-images.githubusercontent.com/6052590/170989418-edb90835-95c9-41e4-97dc-67a0ddd5972a.png)

### Problem

My problem with it is this:

- Initial page is loaded in the browser, htmx is initialized via a `<script>` tag.
- User interacts with the page, some part of it is updated via AJAX.
- The incoming partial HTML includes htmx-specific tags like `hx-get` and `hx-trigger`, but these **do nothing**.

I guess when htmx initializes it parses the current page for its own tags and handles attaching listeners and such, and for HTML coming in later it does not do so automagically (which is expected, no offense).

### Workaround 

My experimental workaround has been to "reinitialize" htmx whenever I update my page via jQuery AJAX requests (via the global [.ajaxStop()](https://api.jquery.com/ajaxStop/) that jQuery offers). However since there is nothing like a `htmx.init()` function, I resorted to removing and then adding again the original `<script src="htmx.js">` tag to force the browser to let htmx run its [init code](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3091-L3120) again.

### My Questions 

This seems rather brutal so I have the following questions:
- ~~Is this a valid method to reinitialize htmx, or are there things like **internal state being lost** that make this a bad idea?~~ See comment by @David-Guillot
- Is this "marrying existing AJAX" with htmx an okay idea in general, or **would you advice against it?** Just want to make sure I'm not being silly here.
- ~~If okay, could we have a **function to call** that sets up any new html on the page that may not be setup yet instead of force-reloading the script tag?~~ Use [htmx.process()](https://htmx.org/api/#process) instead of my wonky script workaround above :face_with_spiral_eyes: 

Thank you for your time :wave:

**Comment by David-Guillot** [comment]
Hi @cb109 ,

Thank you for explaining your problem so clearly :+1: . Would [htmx.process()](https://htmx.org/api/#process) meet your needs?

**Comment by cb109** [comment]
@David-Guillot Holy macaroni, no idea how I missed that. Yes, that would be what I was looking for, thank you!
