### ISSUE TITLE
Indicator styles are injected even if includeIndicatorStyles is set to false.

### ISSUE THREAD

**Issue by hotdoy** [bigskysoftware/htmx#950]
That's pretty much it. The other param in the screenshot (`scrollBehavior`) is properly applied.

![image](https://user-images.githubusercontent.com/11572524/176196597-67e85c93-4860-41ef-93c6-f175d5267020.png)

**Comment by Renerick** [comment]
"false" should not be quoted, it's parsed as string, not boolean false

**Comment by hotdoy** [comment]
This is totally true! Thanks. Work as expected. 😅
