### ISSUE TITLE
Suggest: split ajax module as extension to isolate htmx core with ajax implementation

### ISSUE THREAD

**Issue by kitepad** [bigskysoftware/htmx#952]
Currently, ajax module is part of htmx core, and implement by XMLHTTPRequest. But most core functions are about dom, and as we know, The Fetch API is a new and modern interface that allows you to make HTTP requests in the web browsers. So I suggest abstract an API layer in core, and api implementation layer as extension, default implementation is based on XMLHTTPRequest. Other implementations can be provided by extension contributor, such as Fetch API based implementation.

**Comment by 1cg** [comment]
interesting idea, but I'm going to stick w/ XMLHTTPRequest for now

may consider fetch for htmx 2.0 though
