### ISSUE TITLE
Boosted links do not include fragment

### ISSUE THREAD

**Issue by danieljsummers** [bigskysoftware/htmx#953]
When a boosted link with a fragment (anchor) is clicked, the content comes back, but the browser is only navigated to the page; it does not include the fragment nor jump to that part of the content.

An example can be seen at [this page](https://bitbadger.solutions/open-source/myweblog/rss.html); scroll to the bottom, and there is a link on the words "post documentation" that go to `writing.html#podcast-episodes`. If you click that link, you'll go to `writing.html`. When you click the back button, the URL changes to the prior page; however, the content does not, yet the fragment appears, and the page scrolls to it. (Following this example, the URL ended with `rss.html#podcast-episodes`, but displayed the content from `writing.html`.)

_This example should be good for a while; I have no plans to change those URLs._

**Comment by 1cg** [comment]
I believe I have fixed this with https://github.com/bigskysoftware/htmx/issues/827

**Comment by 1cg** [comment]
er, https://github.com/bigskysoftware/htmx/commit/7e7a5b43619d7b0cca27bde36302f1fc2aba17f6
