### ISSUE TITLE
How to prevent action when the default option is selected in a <select>

### ISSUE THREAD

**Issue by simondrabble** [bigskysoftware/htmx#955]
I have a select element with several options, the top-most of which is default and merely serves to instruct the user what to do ("Select an option..."). This option has no value attribute and I would like to somehow be able to disable the hx-get associated with the select when it is chosen. Is there a simple way to do this? While it can be filtered out on the server, this presupposes that it is possible to do so, which may not be the case for a variety of reasons.

**Comment by David-Guillot** [comment]
Hi @simondrabble ,

I can't test it right now, but have you tried `disabled ` attribute on the option element?

**Comment by David-Guillot** [comment]
Ah never mind, `disabled` makes it impossible to have this option selected in the first place.

Another thought on your issue: if your form is a regular form (no htmx involved), there is no client-side mechanism that would prevent a user from submit the form with this no-value option selected. I'm not sure htmx should have such responsibility.

**Comment by simondrabble** [comment]
Well.. maybe, but the whole point of javascript solutions is enhanced functionality, so I would expect to be able to check for and prevent an undesirable situation. Otherwise, sure, I can do without HTMX - because checking for an empty value is something that can be done inside an onsubmit/ onchange handler pretty easily.

**Comment by simondrabble** [comment]
@1cg do you have an example of such? Not super familiar with filter expressions in HTMX.

**Comment by 1cg** [comment]
https://codepen.io/1cg/pen/zYLobwX
