### ISSUE TITLE
No spinner on subsequent requests.

### ISSUE THREAD

**Issue by amanrawat121** [bigskysoftware/htmx#967]
Hi everyone. Is it possible to achieve a spinner on every xhr request I make to the server. Because I get a spinner only on first requests. all  requests made after getting result doesn't show any spinner

**Comment by David-Guillot** [comment]
Hi there,

Do you want the same spinner for all requests, whatever the trigger element? Or a specific spinner for every trigger element? [hx-indicator](https://htmx.org/attributes/hx-indicator/) should work any case:
* If same spinner for all requests, you can set `hx-indicator` on a common parent element of all trigger elements
* If trigger-specific spinner, you must set `hx-indicator` on every element holding `hx-get`, `hx-post` or `hx-delete` attributes

**Comment by amanrawat121** [comment]
I wanted to say when I make first XHR Request, It show spinner only for that request, once I get response and I make request again, it doesn't show the spinner. The previous results stay there and are directly swapped with new results. 
What I wanted was if results are there and if I make request again, those results must disappear and there should be a spinner again.

**Comment by David-Guillot** [comment]
Maybe your spinner is part of the element that gets swapped, and the response doesn't hold this same element?

If my question doesn't make sense, please show us some code (the element that triggers the request, the skeleton of the one that gets replaced, and the XHR response) 😉

**Comment by amanrawat121** [comment]
Yes! U r right. The spinner is the part of swapped elements. Could you please tell me what to do in that case...

**Comment by David-Guillot** [comment]
No offense taken :wink: 

There is no absolute solution to this situation, it all depends on what you want to achieve on a design point of view. Probably it's better to move your spinner out of the swapped elements, maybe with a container, like

```html
<div>
  <div id="spinner"></div>
  <div id="htmx-target"></div>
</div>
```

What do you think?

**Comment by amanrawat121** [comment]
I guess u r right. I already implemented that and it's working pretty fine as of now. I'll just close this issue. Thankyou so much for your help..
