### ISSUE TITLE
Missing value of submit button when sending data with ws-send

### ISSUE THREAD

**Issue by medihack** [bigskysoftware/htmx#971]
### Discussed in https://github.com/bigskysoftware/htmx/discussions/970

When adding `hx-ext="ws"` (as recommended in the [documentation](https://htmx.org/extensions/web-sockets/)) to a surrounding `div` of a form, then buttons in the form won't be tracked, and the value of a clicked button is not included in the sent data.

A full description (and example) of why this happens can be found in the discussion above.

I guess the documentation should be updated or the initialization should be changed to also include sub-elements (like forms).

**Comment by alexpetros** [comment]
Resolved by #1559
