### ISSUE TITLE
hx-boost not working when submitting form programmatically

### ISSUE THREAD

**Issue by oliverhanappi** [bigskysoftware/htmx#975]
I expected that programmatically submitting a form using JavaScript will trigger the `hx-boost` functionality, however it does not.

```html
<form action="" method="get" hx-boost="true">
  Value: <input type="text" name="value" value="Test 1">
  <button type="submit" id="submit-button">Regular Submit (working)</button>
  <button type="button" onclick="this.form.submit()">form.submit() (not working)</button>
  <button type="button" onclick="this.form.requestSubmit()">form.requestSubmit() (working)</button>
  <button type="button" onclick="document.getElementById('submit-button').click()">Submit by Click (working)</button>
</form>
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) the `HTMLFormElement.submit()` function does not raise the `submit` event, which is probably the root cause.

I do not know if this can be workarounded, but maybe the documention could be at least adopted to include an advice to use `.requestSubmit()` instead.

**Comment by 1cg** [comment]
i agree that this is confusing, but I think it's beyond the scope of the htmx docs

**Comment by kg-currenxie** [comment]
Beyond the scope? I think it's highly relevant if people have these questions and having issues integrating htmx.

With your argument, you could say that this is also beyond the scope of the docs:
> Note that some elements cannot unfortunately be preserved properly, such as <input type="text"> (focus and caret position are lost), iframes or certain types of videos. To tackle some of these cases we recommend the [morphdom extension](https://htmx.org/extensions/morphdom-swap/), which does a more elaborate DOM reconciliation.
