### ISSUE TITLE
ignoring bootstrap table

### ISSUE THREAD

**Issue by abrorbekuz** [bigskysoftware/htmx#978]
when i use hx-get request its not handling html elements from bootstrap table
i know the problem, its because bootstrap table recreates whole thing but can we improve that ?

if u respond, its appreciated, pls

**Comment by abrorbekuz** [comment]
also thanks for project, its the best 

> thumbs up

**Comment by 1cg** [comment]
Do you need to call `htmx.process()` on the table after it is created?
