### ISSUE TITLE
The alpine-morph extension does not work

### ISSUE THREAD

**Issue by bmihelac** [bigskysoftware/htmx#985]
Hello everyone,

It looks like [alpine-morph](https://htmx.org/extensions/alpine-morph/) extension is not working.

Example from documentation states that Alpine x-data states should be preserved, but it just swaps whole fragment.

Here is modified example, minimal test case that works on jsfiddle:

https://jsfiddle.net/kp2c1er0/36/

I have tried different versions of AlpineJS and htmx but did not notice any difference.

**Comment by rudiv** [comment]
You need to import the morph extension, also target the actual element that is being replaced (rather than the outer, otherwise you will get some weird effects).

https://jsfiddle.net/owgea4j2/

**Comment by bmihelac** [comment]
@rudiv Thanks. 

This works prefect. I have added 2 pull requests to extend documentation with your remarks.
