### ISSUE TITLE
Custom event filter not working, SyntaxError: missing ) in parenthetical

### ISSUE THREAD

**Issue by Guilouf** [bigskysoftware/htmx#989]
I  have a list of item in a container, which has a trigger to be refreshed every 2 seconds. But, when a boostrap5 modal is opened from one the fetched item, i want to interrupt the polling. 

```html
<div
          hx-get="/item-list"
          hx-trigger="load, every 2s [show.bs.modal from:body]">
</div>
```

The event `show.bs.modal from:body` is working sandalone, but i can't get it to work as a conditional for the polling event, as it raises a syntax error:
```
SyntaxError: missing ) in parenthetical
    s https://unpkg.com/htmx.org@1.8.0:1
    Zt https://unpkg.com/htmx.org@1.8.0:1
    Ie https://unpkg.com/htmx.org@1.8.0:1
    Me https://unpkg.com/htmx.org@1.8.0:1
    dt https://unpkg.com/htmx.org@1.8.0:1
    vt https://unpkg.com/htmx.org@1.8.0:1
    G https://unpkg.com/htmx.org@1.8.0:1
    vt https://unpkg.com/htmx.org@1.8.0:1
    <anonymous> https://unpkg.com/htmx.org@1.8.0:1
    dr https://unpkg.com/htmx.org@1.8.0:1
    <anonymous> https://unpkg.com/htmx.org@1.8.0:1
    <anonymous> https://unpkg.com/htmx.org@1.8.0:1
    <anonymous> https://unpkg.com/htmx.org@1.8.0:1
    <anonymous> https://unpkg.com/htmx.org@1.8.0:1
```

I'm not sure if it's a bug or some misunderstanding from myself.

**Comment by 1cg** [comment]
what are you trying to do her?

```
load, every 2s [show.bs.modal from:body]
```
isn't a valid trigger description: the square brackets define a filter expression, which should return a true or false.  I *think* what you want is something like htis:

```
load, show.bs.modal from:body, every 2s
```
